### ISSUE TITLE
Structured query for postal code doesn't work

### ISSUE THREAD

**Issue by ixtensa** [GIScience/openrouteservice#1003]
#### Here's what I did
I send a structured query like this: https://api.openrouteservice.org/geocode/search/structured?postalcode=39261&country=de&api_key=...

---
#### Here's what I got
Regardless of postal code the coordinates 9.687096, 50.970097 are returned.
It is always the same, as if no postal code is provided.

---
#### Here's what I was expecting
Return the coordinates related to the postal code.

---
#### Here's what I think could be improved
Searching for postal codes should work.

**Comment by rabidllama** [comment]
Hi, 
the geocoder that we use is Pelias, and there is a known problem with postal codes in Germany as the data simply isn't available in the datasets that Pelias uses (the main one being Whos On First). You can see and example on their page for doing this query and it comes up with the same results:

https://pelias.github.io/compare/#/v1/search/structured?postalcode=39261&country=de&debug=1

It could be a case that in the future they will use a different dataset for postcodes, so if/when they do that would also be implemented in our instance of Pelias.
