### ISSUE TITLE
Hgv subprofile access restrictions resolved only when vehicle parameters set

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#1006]
HGV subprofile-specific access restrictions are not resolved unless `options.profile_params.restrictions` are set. As an [example](https://classic-maps.openrouteservice.org/directions?n1=49.388714&n2=8.712137&n3=15&a=49.390851,8.703232,49.381563,8.719969&b=4a&c=0&k1=en-US&k2=km) consider [Saupfercheckweg](https://www.openstreetmap.org/way/174376622) tagged with `bus=yes` and `hgv=no`.

**Comment by koebi** [comment]
Is that in any way related to #816 ?

**Comment by aoles** [comment]
Yes, that's the other issue I've mentioned in the meeting.
