### ISSUE TITLE
exist location was not found in openroutemap

### ISSUE THREAD

**Issue by srhinow** [GIScience/openrouteservice#1012]
With https://nominatim.openstreetmap.org/ui/search.html?q=Germany%2C++16945+Buckow%2C+Ringstra%C3%9Fe+19+ locations was found, but with openroutemap not. 
With the same search-String 'Germany,  16945 Buckow, Ringstraße 19 ' also with different search-string like 'Buckow, Ringstraße 19 ' not.

**Comment by takb** [comment]
We've been experiencing some trouble with our geocoder instance recently, but I could find said address by searching for "buckow ringstrasse 19" https://bit.ly/3hUBvnj

Were you using the our current client version at https://maps.openrouteservice.org ? 

Please let us know if the problem persists.
