### ISSUE TITLE
migrate from springfox-swagger to springdoc-openapi

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#1027]
Currenlty swagger 2 is still used as API specs.
OpenAPI specs have been out for some time an are the go to standard nowadays.

It might be possible to integrate the custom keys used to define parameter dependencies in a more openapi spec native way (to be investigated).

Should be tackled together with [ors-website's capability to render openapi](https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-website/-/issues/106).

**Comment by MichaelsJP** [comment]
This would be great. Could also give us additional abilities in the direction of auto-generated API clients: https://github.com/OpenAPITools/openapi-generator.

**Comment by TheGreatRefrigerator** [comment]
- [ ] parameter dependencies, possible native now?
- [x] extra/custom parameter attributes `x-valid-when` etc. possible?
- [ ] use [3.1 features](https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0)? summary attribute & new json schema multi type lists

**Comment by MichaelsJP** [comment]
>  parameter dependencies, possible native now?


Regarding that one, is this what we're looking for?
https://json-schema.org/understanding-json-schema/reference/conditionals.html

It's also listed [here](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---OpenAPI-3.1). Just search for `dependentSchemas` and `dependentRequired`

**Comment by MichaelsJP** [comment]
I'ts not visible that springdoc-openapi will integrate these parameters. For the short-term we should use `x-` to add dependencies. For the medium, longterm, we can think of a class overwrite that adds the functionality, as e.g., the [openapi-generator](https://github.com/OpenAPITools/openapi-generator/pull/13442) supports at least the `dependentRequired` tag for the client generation.
