### ISSUE TITLE
Add more spring-boot configurations

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#1028]
The [spring configuration](https://github.com/GIScience/openrouteservice/blob/master/openrouteservice/src/main/resources/application.properties) right now only sets the port and disables whitelabeled errors (?)

It should be checked which settings are applicable for ors, that might help improve

**Comment by MichaelsJP** [comment]
> and disables whitelabeled errors

Since we're an API and not a web service with a webpage, we shouldn't throw an `Whitelabel Error Page`.  This should be good.

**Comment by MichaelsJP** [comment]
A few things that we could consider optimizing in the `application.properties`:
- Cache settings (maybe we can benefit from that) https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.cache
- Jackson configuration https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.json
- for kafka https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.integration
- tomcat settings: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.server.server.tomcat.accept-count
- ~Devtools settings such as livereload: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.devtools~
