### ISSUE TITLE
Cannot running with Docker on Windows

### ISSUE THREAD

**Issue by AnhTuan-AiT** [GIScience/openrouteservice#1041]
I'm trying to host <b>openrouteservice</b> backend locally on my laptop. I cloned this repository and ran the command following the installation instructions in this section: [https://github.com/GIScience/openrouteservice#installation](https://github.com/GIScience/openrouteservice#installation), but it doesn't work. I also tried to build <b>openrouteservice</b> image as instructed [here](https://giscience.github.io/openrouteservice/installation/Advanced-Docker-Setup.html), but the result is the same. Both cases give the following output:

```
### openrouteservice configuration ###
ors-config.json exists in ors-conf folder. Copy config to /ors-core/openrouteservice/src/main/resources/ors-config.json
### Package openrouteservice and deploy to Tomcat ###
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
66486 [ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.heigit.ors:openrouteservice:6.6.1: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.3.5.RELEASE from/to HeiGIT main (https://repo.heigit.org/artifactory/main): Connect to repo.heigit.org:443 [repo.heigit.org/129.206.7.121] failed: Connection refused (Connection refused) and 'parent.relativePath' points at wrong local POM @ line 64, column 13
 @
66504 [ERROR] The build could not read 1 project -> [Help 1]
66507 [ERROR]
66507 [ERROR]   The project org.heigit.ors:openrouteservice:6.6.1 (/ors-core/openrouteservice/pom.xml) has 1 error
66510 [ERROR]     Non-resolvable parent POM for org.heigit.ors:openrouteservice:6.6.1: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.3.5.RELEASE from/to HeiGIT main (https://repo.heigit.org/artifactory/main): Connect to repo.heigit.org:443 [repo.heigit.org/129.206.7.121] failed: Connection refused (Connection refused) and 'parent.relativePath' points at wrong local POM @ line 64, column 13 -> [Help 2]
66513 [ERROR]
66516 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
66518 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
66519 [ERROR]
66519 [ERROR] For more information about the errors and possible solutions, please read the following articles:
66520 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
66521 [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
```
So, I want to know if there is something wrong with openrouteservice images, or due to some other cause, how to fix it and how to know when running successfully with docker (e.g. new directory, file is created,...)

**Comment by koebi** [comment]
Hey,

it doesn't look like this is an issue on site of the openrouteservice.
You're trying to access a resource that is present, but your connection gets refused.
This might be an issue with a possible proxy, some windows firewall problem or something else.

Please check what is causing the issue and report back if it turns out to be related to our artifactory.

**Comment by ghost** [comment]
Same problem here. Any solutions so far?

**Comment by joker234** [comment]
> Same problem here. Any solutions so far?

Do you have any timestamp for us, when the issue occurred? This would help us to identify if there is/was an issue on our side. Is the issue still occurring at this time?

**Comment by ghost** [comment]
Sorry it's the first time I use that image :(

**Comment by ghost** [comment]
Problem solved on my side. I had to add my companies root certificate. So it was a environment-specific problem on my side. Sorry.

**Comment by joker234** [comment]
Okay good to know. Thanks for the feedback :+1: 

**If anyone every stumbles upon this issue**, please check if https://repo.heigit.org is accessible, if not, try again a few minutes later. If you want to open an issue, include the time and date (including timezone) when you performed the request/build.
