### ISSUE TITLE
deprecated 'cobblestone:flattened' used as surface value for wheelchair

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#1059]
#### Here's what I got

The default value for the minimum `surface_type` option is `cobblestone:flattened`.
According to the [osm wiki](https://wiki.openstreetmap.org/wiki/Key:surface) this value should not be used.

---
#### Here's what I think could be improved

`sett` or another sensible value for surface should be used as default minimum surface type.
`cobblestone:flattened` still exists in osm data and should maybe still be considered when creating  a wheelchair route

---
#### ask Forum topic
https://ask.openrouteservice.org/t/wheelchair-direction-problem/3142

#### related links and discussions
- https://github.com/streetcomplete/StreetComplete/issues/728
- https://translate.google.de/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fforum.openstreetmap.org%2Fviewtopic.php%3Fpid%3D648522%23p648522&edit-text=&act=url
- https://taginfo.openstreetmap.org/keys/surface#values (search for cobblestone:flattened vs sett)

**Comment by koebi** [comment]
In the `WheelchairTypesEncoder`, all three of `sett`, `unhewn_cobblestone` and `cobblestone:flattened` use the same value:
https://github.com/GIScience/openrouteservice/blob/a462aea7745e8d171f170bf303d979e29dc11e93/openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/WheelchairTypesEncoder.java#L68-L70

As [from the wiki](https://wiki.openstreetmap.org/wiki/Key:surface) it looks like unhewn cobblestone is the inferior surface type, so I'd set the default to unhewn cobblestone as to not confuse the user.

It may be a case that there actually should be different values for `sett`, `unhewn_cobblestone` and `cobblestone:flattened`, but that'd require feedback from a wheelchair user.

**Comment by TheGreatRefrigerator** [comment]
i would prefer `sett` over `unhewn_cobblestones` as a default, as it is more common (215 421 : 9 311
: 5 362 for flattened) and looking at the picture would be a less bumpy ride than unhewn_cobblestones.
wdyt?

**Comment by koebi** [comment]
Yeah, sounds good to me :)
