### ISSUE TITLE
Enable population data for isochrones

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/openrouteservice#106]

**Comment by MichaelsJP** [comment]
https://github.com/GIScience/openrouteservice/commit/a1f445b1454ff8c4e91543c9dfab8c39dc6a2f87

**Comment by MichaelsJP** [comment]
`http://localhost:8082/openrouteservice-4.4.0/isochrones?locations=8.67255110065730,49.40585904466701&profile=driving-car&range=60&attributes=pop_area`

try this query if you want to test it. But attribution must be set in the app.config before.
