### ISSUE TITLE
Ability to avoid specific surfaces|waytypes

### ISSUE THREAD

**Issue by Kinas** [GIScience/openrouteservice#107]
For bikers it would be nice if we could add something to avoid additional features:

For example I want to go from Heidelberg to Stuttgart by bike. I can see that my route contains 4% unpaved ground but saying it in numbers would mean I have to go on 4.5 km on a unpaved ground which is not that nice. So I would like to avoid some surface types on my route even though that means my route will be longer!
Same with Waytypes and Steepness.

I think a checklist would be nice to be implemented in the front end. Or when you open the arrow (legend) it would be nice to click on one of the elements and they would be crossed out. See example below:

![avoidadditionalinforamtion](https://user-images.githubusercontent.com/15326489/35918431-1b3e4d10-0c12-11e8-84f6-f62ab375ab63.png)

**Comment by TimMcCauley** [comment]
Also see https://github.com/graphhopper/graphhopper/issues/655#issuecomment-369939126

**Comment by HendrikLeuschner** [comment]
What do you think we should do with this with regard to the minimization of the core graph? @TimMcCauley @aoles

**Comment by aoles** [comment]
I think we have already decided that because the `paved/unpaved` road classification is very unreliable we don't provide an option to filter on them.

**Comment by HendrikLeuschner** [comment]
This will not be integrated due to data quality/density issues. A route that is set to avoid unpaved should not have a single piece of unpaved and we cannot ensure this condition with OSM. At the same time, this does not integrate well with Core-ALT as a binary classification with no strong single-sided tendency is too much for the core.
