### ISSUE TITLE
Origin is not allowed by Access-Control-Allow-Origin for reverse geocode API

### ISSUE THREAD

**Issue by kf99916** [GIScience/openrouteservice#1076]
#### Here's what I did

https://api.openrouteservice.org/geocode/reverse?api_key={API_KEY}&point.lon=121.47145271301271&point.lat=24.927073120131514&boundary.circle.radius=50&size=1&lang=zh-TW

---
#### Here's what I got

Origin is not allowed by Access-Control-Allow-Origin. It also happens in play ground: https://openrouteservice.org/dev/#/api-docs/geocode/reverse/get

---
#### Here's what I was expecting

Get reverse geocode API response. But direction API works.

---

**Comment by TheGreatRefrigerator** [comment]
Hi @kf99916,

please check out https://ask.openrouteservice.org/t/error-with-r-package-ors-directions/3184/2 and test if that is a problem on the machine your working on, by sending a curl request from your command line.

If you still encounter the same problem please also provide the Headers of your request.

Best regards

**Comment by kf99916** [comment]
Hi @TheGreatRefrigerator ,

The issue still exists in [your API playground](https://openrouteservice.org/dev/#/api-docs/geocode/reverse/get) with my API key. But my API key can work on directions API. so I think it is not expired certificate issue.

Here is the API response:
![截圖 2021-10-19 下午6 43 05](https://user-images.githubusercontent.com/6695195/137894411-a23f1a70-cf03-45fd-9151-0bd8a08cd3b9.jpg)

the request header:
```
Accept: application/json, text/plain, */*
Origin: https://openrouteservice.org
Referer: https://openrouteservice.org/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
Cache-Control: no-cache
Pragma: no-cache
```

the api response:
![image](https://user-images.githubusercontent.com/6695195/137894632-5481fcfe-b4de-47b3-9099-77f09c6b04d0.jpeg)

**Comment by kf99916** [comment]
Hi @TheGreatRefrigerator ,
I found this is quota issue for my API key and thank you for your help.
