### ISSUE TITLE
Direction Service Routing Problem with Gotthardo

### ISSUE THREAD

**Issue by Cinci07** [GIScience/openrouteservice#1077]
Hello

There seems to be a problem with the calculation of the altitude when calculating a route through the Saint Gotthard tunnel. Inside the tunnel, values for altitude of up to 6000 metres are given, but outside the tunnel the values seem to be valid. 

Enclosed is the requested route as Python code:

*** 
import requests

body = {"coordinates":[[9.029192,46.195839],[8.303934,47.047776]],"elevation":"true"}

headers = {
    'Accept': 'application/json, application/geo+json, application/gpx+xml, img/png; charset=utf-8',
    'Authorization': ***************,
    'Content-Type': 'application/json; charset=utf-8'
}
call = requests.post('https://api.openrouteservice.org/v2/directions/driving-car/geojson', json=body, headers=headers)
*** 

Thanks in advance for checking

[ors__v2_directions_{profile}_geojson_post_1634735038586.txt](https://github.com/GIScience/openrouteservice/files/7381528/ors__v2_directions_.profile._geojson_post_1634735038586.txt)

**Comment by aoles** [comment]
Thanks for reporting this!

Weird indeed, not sure where the elevation of 6000 m could come from. We already had some similar problems in the past which have been addressed in https://github.com/GIScience/openrouteservice/pull/750. However, there seem to be a similar issue in graphhopper too, see below.

[openrouteservice maps](https://classic-maps.openrouteservice.org/directions?n1=46.601337&n2=8.844116&n3=11&a=46.527052,8.603937,46.672123,8.592768&b=0&c=0&k1=en-US&k2=km)

![image](https://user-images.githubusercontent.com/6545356/138104099-3e8aee96-caa0-40e1-a373-480962327713.png)

[Graphhopper maps](https://graphhopper.com/maps/?point=46.526952%2C8.605556&point=46.681125%2C8.59251&locale=en-us&elevation=true&profile=car&use_miles=false&layer=Omniscale)

![image](https://user-images.githubusercontent.com/6545356/138104348-af068679-ae18-4031-a2c1-637317ad374f.png)

**Comment by MichaelsJP** [comment]
Is this still relevant?

This could be connected to some elevation pre-processing in the backend. At some point, the elevation data from SRTM is “smoothed” and maybe it's generating a local anomaly.

**Comment by aoles** [comment]
The issue doesn't come up in GH anymore, however, it is still persistent in ORSv6 API. I would like to revisit once ORSv7 goes live, hence the label.

**Comment by aoles** [comment]
Unfortunately, the problem still persists in ORSv7.

**Comment by aoles** [comment]
As of ORSv8 the problem does not occur anymore 🎉
