### ISSUE TITLE
API returns 400 with empty body (on any request)

### ISSUE THREAD

**Issue by ghost** [GIScience/openrouteservice#1085]
#### Here's what I did
Create a new docker-image extending openrouteservice:latest to add my companies root cert.
docker-compose build
docker-compose up

---
#### Here's what I got
The container starts up all right and there are, besides some warnings at the beginning, only info logs. When trying to use the API (e.g. http://localhost:8080/ors/v2/directions/driving-car?start=8.681495,49.41461&end=8.687872,49.420318) I get a straight 400 response without any content (and Content-Type html/text). Seems like The request is not really processed at all.

Here's the stdout:
>xxx openrouteservice configuration xxx
>ors-config.json exists in ors-conf folder. Copy config to /ors-core/openrouteservice/src/main/resources/ors-config.json
>xxx Package openrouteservice and deploy to Tomcat xxx
>WARNING: An illegal reflective access operation has occurred
>WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
>WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
>WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
>WARNING: All illegal access operations will be denied in a future release
>NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
>18-Nov-2021 06:25:47.660 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.39
>18-Nov-2021 06:25:47.666 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Mar 14 2019 11:24:26 UTC
>18-Nov-2021 06:25:47.666 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.39.0
>18-Nov-2021 06:25:47.667 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
>18-Nov-2021 06:25:47.667 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.10.47-linuxkit
>18-Nov-2021 06:25:47.671 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
>18-Nov-2021 06:25:47.672 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-11
>18-Nov-2021 06:25:47.673 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.12+7
>18-Nov-2021 06:25:47.673 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
>18-Nov-2021 06:25:47.674 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
>18-Nov-2021 06:25:47.675 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
>18-Nov-2021 06:25:47.676 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
>18-Nov-2021 06:25:47.677 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
>18-Nov-2021 06:25:47.678 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
>18-Nov-2021 06:25:47.678 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
>18-Nov-2021 06:25:47.679 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
>18-Nov-2021 06:25:47.682 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
>18-Nov-2021 06:25:47.683 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:TargetSurvivorRatio=75
>18-Nov-2021 06:25:47.684 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:SurvivorRatio=64
>18-Nov-2021 06:25:47.685 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxTenuringThreshold=3
>18-Nov-2021 06:25:47.685 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseG1GC
>18-Nov-2021 06:25:47.686 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+ScavengeBeforeFullGC
>18-Nov-2021 06:25:47.686 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:ParallelGCThreads=4
>18-Nov-2021 06:25:47.687 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms1g
>18-Nov-2021 06:25:47.687 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx2g
>18-Nov-2021 06:25:47.689 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
>18-Nov-2021 06:25:47.690 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
>18-Nov-2021 06:25:47.690 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
>18-Nov-2021 06:25:47.691 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote
>18-Nov-2021 06:25:47.692 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.port=9001
>18-Nov-2021 06:25:47.692 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.rmi.port=9001
>18-Nov-2021 06:25:47.692 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
>18-Nov-2021 06:25:47.693 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.ssl=false
>18-Nov-2021 06:25:47.693 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.rmi.server.hostname=localhost
>18-Nov-2021 06:25:47.694 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
>18-Nov-2021 06:25:47.694 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
>18-Nov-2021 06:25:47.695 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
>18-Nov-2021 06:25:47.696 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
>18-Nov-2021 06:25:47.696 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib]
>18-Nov-2021 06:25:47.767 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
>18-Nov-2021 06:25:47.785 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
>18-Nov-2021 06:25:47.819 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
>18-Nov-2021 06:25:47.827 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
>18-Nov-2021 06:25:47.828 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 577 ms
>18-Nov-2021 06:25:47.900 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
>18-Nov-2021 06:25:47.901 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.39
>06:25:53.636 [localhost-startStop-1] INFO  org.heigit.ors.config.AppConfig - Default path of 'ors-config.json' used for configuration
>18-Nov-2021 06:25:47.935 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ors.war]
>06:25:53.647 [localhost-startStop-1] INFO  org.heigit.ors.config.AppConfig - Loading configuration from /usr/local/tomcat/webapps/ors/WEB-INF/classes/ors-config.json
>
> ...Spring ASCII...
> :: Spring Boot ::        (v2.3.5.RELEASE)
>
>18 Nov 06:25:54 INFO [ors.Application] - Starting Application v6.6.1 on a4d396998214 with PID 94 (/usr/local/tomcat/webapps/ors/WEB-INF/classes started by root in /ors-core)
>18 Nov 06:25:54 DEBUG [ors.Application] - Running with Spring Boot v2.3.5.RELEASE, Spring v5.2.10.RELEASE
>18 Nov 06:25:54 INFO [ors.Application] - No active profile set, falling back to default profiles: default
>18 Nov 06:25:57 INFO [ors.Application] - Started Application in 4.358 seconds (JVM running for 10.892)
><?xml version="1.0" ?>
><Configuration>
>  <Properties>
>    <Property name="filename">/var/log/ors/ors-logs.log</Property>
>  </Properties>
></Configuration>
>18 Nov 06:25:57 INFO [routing.RoutingProfileManager] -  Total - 1.00 GB, Free - 804.75 MB, Max: 2 GB, Used - 221.25 MB
>18 Nov 06:25:57 INFO [routing.RoutingProfileManager] -       
>18 Nov 06:25:57 INFO [routing.RoutingProfileManager] - ====> Initializing profiles from 'data/map/osm_file.pbf' (1 threads) ...
>18 Nov 06:25:57 INFO [routing.RoutingProfileManager] -                               
>18 Nov 06:25:57 INFO [routing.RoutingProfileManager] -                
>18 Nov 06:25:58 INFO [routing.RoutingProfile] - [1] Profiles: 'driving-car', location: 'data/graphs/car'.
>SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
>SLF4J: Defaulting to no-operation (NOP) logger implementation
>SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
>18-Nov-2021 06:25:57.807 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
>18-Nov-2021 06:25:57.889 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ors.war] has finished in [9,953] ms
>18-Nov-2021 06:25:57.895 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/ROOT]
>18-Nov-2021 06:25:57.966 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/ROOT] has finished in [71] ms
>18-Nov-2021 06:25:57.967 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/manager]
>18-Nov-2021 06:25:58.015 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/manager] has finished in [48] ms
>18-Nov-2021 06:25:58.015 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/examples]
>18-Nov-2021 06:25:58.249 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/examples] has finished in [234] ms
>18-Nov-2021 06:25:58.257 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/docs]
>18-Nov-2021 06:25:58.276 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/docs] has finished in [19] ms
>18-Nov-2021 06:25:58.284 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/host-manager]
>18-Nov-2021 06:25:58.314 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/host-manager] has finished in [30] ms
>18-Nov-2021 06:25:58.329 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
>18-Nov-2021 06:25:58.348 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
>18-Nov-2021 06:25:58.400 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 10572 ms`

Sorry I have no Idea where to start, since there is no hint in the logs.

Thank you in advance
Best Regards
CypRyan

**Comment by koebi** [comment]
Hey,

to me, this looks like the ors hasn't finshed building all profiles.
You can check `http://localhost:8080/ors/status` in your browser, it'll tell you whether the ors is ready or not.
Note, that depending on your used pbf file, it may take quite some time until the ors is ready.

Best regards

**Comment by ghost** [comment]
Hey, thank you for the fast response.
After waiting a bit I am one step closer.

For status I get: 
`{
  "engine": {
    "version": "6.6.1",
    "build_date": "2021-11-18T09:37:12Z"
  }
}`

For http://localhost:8080/ors/v2/directions/driving-car I get a nice 400 with content (error 2001).

But http://localhost:8080/ors/v2/directions/driving-car?start=8.681495,49.41461&end=8.687872,49.420318 results in a infinite wait until timeout. And this request does not show up in the access log.

Best regards

**Comment by koebi** [comment]
Hey,
status should also mention the services and profiles available - if it doesn't, then it's not ready.
Check `http://localhost:8080/ors/health` to see wheter it's ready or not.

Out of curiosity, what is the .pbf-file you're using? How big is it?

**Comment by ghost** [comment]
Hey, thank you for the hints. It's a 60GB file from here: https://ftp.fau.de/osm-planet/pbf/?C=M;O=D
Gonna wait some more time then :) Thank you!

**Comment by koebi** [comment]
Hey,
yes, for a 60GB file expect two or three days of build time and note that you'll probably need around 120GB of RAM for *one* profile.
Best regards
