### ISSUE TITLE
Error Code 2099  in /ors/v2/directions/driving-car API

### ISSUE THREAD

**Issue by darshan-rivulet** [GIScience/openrouteservice#1122]
#### Here's what I did
I have setup ORS backend service with docker 

I'm using direction API  **/ors/v2/directions/driving-car**

**Request Parameters :**
`{
  "coordinates": [
    [
      -121.82567676573,
      37.282215914330116
    ],
    [
      -121.81070536168951,
      37.305813913765206
    ]
  ],
  "radiuses": -1,
  "units": "mi"
}`

**Response:** 
`{
  "error": {
    "code": 2099,
    "message": null
  },
  "info": {
    "engine": {
      "version": "6.7.0",
      "build_date": "2022-01-24T14:01:08Z"
    },
    "timestamp": 1643632102738
  }
}`

---
#### Here's what I have already tried

I have already tried to swap the coordinates, even I have also tried to change **"maximum_distance": 900000,**  configuration in conf/ors-config.json file but this didn't help.

**Comment by koebi** [comment]
Hey,

your query runs perfectly on the public ors api.
This is thus not related to the ors source code, but most probably to your setup.
Please refer to [our help forum](https://ask.openrouteservice.org/) for advice.

Please check if you have done the following before posting a topic:
- didn't mix up latitude and longitude
- searched the forum for similar topics and there are none
- using the correct category
- described problems precisely and included full request URLs / bodies and responses in CODE FORMAT (```url/request body/response```) and screenshots where appropriate.
- api key is replaced by `xxx` or `api-key` as placeholder.

Best regards
