### ISSUE TITLE
iso maps leaked to metadata.query

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#1125]
#### Here's what I did

do an isochrone request with (prob. also without) population to the live API

---
#### Here's what I got

<img width="341" alt="grafik" src="https://user-images.githubusercontent.com/23240110/153041560-07403545-9aae-4b2c-b3fe-51f9774a9b84.png">

---
#### Here's what I was expecting

No internal objects leaked to response

---
#### Here's what I think could be improved
Don't leak internal objects to response

**Comment by koebi** [comment]
This was introduced in #1086 fixing #1067 and was subsequently fixed in #1117, but is not live yet.
