### ISSUE TITLE
Parameter profile is missing

### ISSUE THREAD

**Issue by indeOWS** [GIScience/openrouteservice#1129]
I am installing openrouteservice via docker in a Ubuntu Server 20.04 LTS according to the tutorial in [[1](https://github.com/GIScience/openrouteservice)] and [[2](https://giscience.github.io/openrouteservice/installation/Running-with-Docker)].  
After creating the container ors-app and tryng to make a request in the browser for : http://192.168.15.44:8081/ors/v2/directions, I am getting the following response for the request:

**{"error":{"code":2001,"message":"Parameter 'profile' is missing."},"info":{"engine":{"version":"6.7.0","build_date":"2022-02-19T21:03:28Z"},"timestamp":1645314330727}}**

I checked the ors-app container logs, but did not find any error through the logs. Any comment on this missing profile parameter will be very appreciated

**REPRODUCE THE ISSUE:**

1 - docker pull openrouteservice/openrouteservice
2 - mkdir -p conf elevation_cache graphs logs/ors logs/tomcat
docker run -dt -u "${UID}:${GID}" \
  --name ors-app \
  -p 8080:8080 \
  -v $PWD/graphs:/ors-core/data/graphs \
  -v $PWD/elevation_cache:/ors-core/data/elevation_cache \
  -v $PWD/conf:/ors-conf \  # will copy the container's ors-config.json to the host
  #-v $PWD/your_osm.pbf:/ors-core/data/osm_file.pbf \  # your local PBF file
  -e "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g" \
  -e "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost" \
  openrouteservice/openrouteservice:latest
3 - http://your_server_ip:8080/osr/v2/directions

**Comment by takb** [comment]
Requests to the directions endpoint need to be sent with a set of required parameters, one of which is `profile`. For details, see our API playground: https://openrouteservice.org/dev/#/api-docs/v2/directions/{profile}/get
