### ISSUE TITLE
Run application with embedded tomcat aka "java -jar"

### ISSUE THREAD

**Issue by mariodavid** [GIScience/openrouteservice#1131]
Hi,

I looked into your docker deployment and saw that during the container creation, the java build is also performed. This has the implication that at runtime there are a lot of dependencies (related security risk exposure), that are probably not needed in the container - like `mvn`.

Is there any specific reason why this was implemented like this?

After seeing that the application is built on top of Spring Boot and the embedded tomcat is also present I was thinking of simply doing a `java -jar -Dors_config=ors_config.json ors.war` in the container instead of having a complete tomcat installation with the tomcat manager app, JMX configuration, etc.

The remaining question would be did you see any downsides in using the embedded tomcat for running the application? Currently, there is only one issue I have with this, which is:

```
24 Feb. 12:17:15 ERROR [flagencoders.SpeedLimitHandler] - java.io.FileNotFoundException: /Users/mario/dev/projects/examples/openrouteservice/openrouteservice/target/file:/Users/mario/dev/projects/examples/openrouteservice/openrouteservice/target/ors.war!/WEB-INF/classes/resources/services/routing/speed_limits/car.json (No such file or directory)
```

Having not much expertise with openrouteservice, I'm not sure what implications that has on the production system.

Looking forward to hearing your opinion.

**Comment by TheGreatRefrigerator** [comment]
Hi @mariodavid,

we are aware of this but currently don't have resources to tackle this.
The specific reason would be, because it works right now 😅
Please also see https://github.com/GIScience/openrouteservice/issues/1025

There is a lot of room to improve the project structure and the deployment, feel free to comment on the existing issues related to that or even do a PR with suggested changes.

Best regrads

**Comment by MichaelsJP** [comment]
@mariodavid We have a new Dockerfile (ors >=6.8.2)  that excludes a lot of the build dependencies, such as `maven`. It's slim and only has a size of <300 MB. For the ors version 7.2.0 we're planning the spring-boot upgrade to 2.7.9 which includes the spring-boot native tomcat.

I'll close this issue now, but you are welcome to reopen if necessary.
