### ISSUE TITLE
Geocode search error - Failed to get a valid response from API

### ISSUE THREAD

**Issue by letsdig** [GIScience/openrouteservice#1135]
Geocode search error in official website aswell (https://openrouteservice.org/dev/#/api-docs/geocode/search/get)

Failed to get a valid response from API

"errors": [ 
"[index_not_found_exception] no such index [pelias], with { resource.type=\"index_or_alias\" & resource.id=\"pelias\" & index_uuid=\"_na_\" & index=\"pelias\" }" 
]

It only works with cities without any address
Error even with the default query "Namibian Brewery"

**Comment by koebi** [comment]
Hey,

yes, we're currently experiencing issues with our geocoder and are in the process of rebuilding the database. It'll be back up working within a few days.

EDIT: This issue will stay open until the matter is resolved, as it may be helpful for anybody else to see :)

**Comment by letsdig** [comment]
Thanks for the quick answer, hope it is going to be up asap, very much needed!

**Comment by Conway6288** [comment]
Any eta on this one?

**Comment by koebi** [comment]
Unfortunately not, but it should rather be a matter of days than weeks.

**Comment by koebi** [comment]
Hey, as by [this announcement](https://ask.openrouteservice.org/t/geocoding-working-again/3668), the geocoder is back up and running.

**Comment by letsdig** [comment]
Ok thank you!
