### ISSUE TITLE
Could not find routable point within a radius of 350.0 meters of specified coordinate

### ISSUE THREAD

**Issue by jessegpierce** [GIScience/openrouteservice#1137]
I've seen a couple of similar issues with the above error, but they turned out to be swapped coordinates. Here is my requested url:
[https://api.openrouteservice.org/v2/directions/driving-car?api_key=REDACTED&start=%20-103.6195867,48.2366192&end=%20-102.581440960,47.414588700&units=mi](url)

I also tried the directions map @ [https://classic-maps.openrouteservice.org/directions?n1=48.236619&n2=-103.619587&n3=18&a=48.236619,-103.619587,47.414589,-102.581441&b=0&c=0&k1=en-US&k2=km](url)
and they it showed the error there, too.

The location is perhaps 1100 meters away from a discernable road. Anyway to increase the threshold on the query?

**Comment by koebi** [comment]
Hey,

please refer questions like these to [our official forum](https://ask.openrouteservice.org/), where you would find answers [like these](https://ask.openrouteservice.org/t/point-not-within-a-radius-of-350-0-meters/1156/9) ;)

Also, you left your API key in the request - I've removed it, but you might want to delete and create a new one.

On to your problem:
If you switch to the POST request, you can use the `radiuses` parameter to increase the snapping distance.

I'm not quite sure whether this is the way to go here, though.
Either you're trying to route to a point in the middle of nowhere with no possible road. In that case, I think you should change your end point to something that is actually routeable.
Or you're trying to route to a point that has a road going there, which is just not in the OSM.
In that case that road should be entered into the OSM, changes will be reflected in around 2-3 weeks in the ORS.

Best regards,
Jakob

**Comment by jessegpierce** [comment]
Thank you for the reply and for removing my API key!
