### ISSUE TITLE
Profiling graph preprocessing

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/openrouteservice#114]
The idea here is to find bottlenecks in the graph computation. It might make sense to use this plugin: http://plugins.jetbrains.com/plugin/7115-visualvm-launcher

**Comment by HendrikLeuschner** [comment]
Will investigate this when we have finished our choices regarding CH-ALT-Core

**Comment by TimMcCauley** [comment]
fyi https://github.com/graphhopper/graphhopper/pull/1759

**Comment by HendrikLeuschner** [comment]
On hold until other RE questions resolved.
