### ISSUE TITLE
I built my own server, how do I configure the unique api_key?

### ISSUE THREAD

**Issue by falvees** [GIScience/openrouteservice#1153]

**Comment by MichaelsJP** [comment]
@falvees Hi, thx for using openrouteservice. Once you set up your own server you shouldn't need any api_key but just query the respective ip/url your instance is running at. To check run (replace {} with your details):

- local docker setup from our repo: curl http://0.0.0.0:8080/v2/ors/status
- local non-docker setup: curl http://127.0.0.1:8080/v2/ors/status
- setup with external access: curl http://{external IP}:8080/v2/ors/status

The api_key variable isn't part of ors but  in our infrastructure injected via third party tools between ors and external accesses.

If you feel for more discussion please head over to our support forum at https://ask.openrouteservice.org/.
Closing this now.
