### ISSUE TITLE
openrouteservice local  container  cannot load profile "driving-hgv"

### ISSUE THREAD

**Issue by vittorioz** [GIScience/openrouteservice#1158]
#### Here's what I did
I have built a container with docker-compose with  Albania map downloaded from Geofabrik (https://download.geofabrik.de/europe/albania.html)  and it works fine.
I'm trying to enable "driving-hgv"  profile but it doesn't work. 
For enabling it,  I added the XXX part of profile-XXX name  in the "active" list in the ors-config.json file (see attached file line 96 in the zip archive). I tried to add a different profile (hiking) and it works.
What am I missing?
Thank you in advance.

NOTES:
I'm working with an apple silicon Mac so I modified the  first line of the dockerfile in order to build everything from arm64v8/openjdk:11-jdk  instead of the original openjdk:11-jdk but I don't think is that the problem.
As mentioned here https://ask.openrouteservice.org/t/how-to-change-the-weighting-of-road-types-for-the-hgv-profile/3698 I changed line 53 with line 49 (see attached dockerfile in the zip archive)

[git_issue.zip](https://github.com/GIScience/openrouteservice/files/8573304/git_issue.zip)

**Comment by MichaelsJP** [comment]
@vittorioz Thanks for reporting, and thank you for your patience.
Please upgrade to our latest versions >= 6.8.2 where this is fixed as described in: [Running-with-Docker](https://giscience.github.io/openrouteservice/installation/Running-with-Docker.html).
You are welcome to report if the error persists.
