### ISSUE TITLE
Language parameter ignored

### ISSUE THREAD

**Issue by centiveo** [GIScience/openrouteservice#1159]
I try to get directions in 'nl'. On the status page 'nl' is in the list but when I add 'language=dutch' in the url the instructions are still in english. Also other languages ('de') are not working. Instructions are always in English. I'm running the latest build in Docker.

**Comment by koebi** [comment]
Hey,

could you give a bit more info about your request? You're stating you're adding `language=dutch` in the url.
That suggests you're using the [GET](https://openrouteservice.org/dev/#/api-docs/v2/directions/{profile}/get)-request, for which languages are not available.

To use them, you'd have to issue a [POST](https://openrouteservice.org/dev/#/api-docs/v2/directions/{profile}/post)-request.
In the post body, use `"language":"nl"` to request a language.

As you can verify in the playground linked, the language works on the public instance of the ors. This suggests that this is not a bug in the code, but rather a problem with your setup or request.
For this, please refer to our [help forum](ask.openrouteservice.org).
