### ISSUE TITLE
Postalcode is missing in reverse geocoding

### ISSUE THREAD

**Issue by bassmaster187** [GIScience/openrouteservice#1163]
#### Here's what I did
I don't know if this bug belongs to pelias or ORS so here we go:
https://api.openrouteservice.org/geocode/reverse?api_key=xxxx&point.lon=9.90026&point.lat=48.18184&size=1
https://pelias.github.io/compare/#/v1/reverse?layers=address&sources=osm&size=1&point.lat=48.18184&point.lon=9.90026

---
#### Here's what I got

[ors__geocode_reverse_get_1651836609717.txt](https://github.com/GIScience/openrouteservice/files/8639618/ors__geocode_reverse_get_1651836609717.txt)

---
#### Here's what I was expecting
I am expecting the postalcode: 88487

Nominatim and OpenStreetMap is returning the right postalcode so basically the data should be there:
https://nominatim.openstreetmap.org/reverse?format=xml&lat=48.18184&lon=9.90026&zoom=18&addressdetails=1

https://www.openstreetmap.org/search?whereami=1&query=48.18184%2C9.90026#map=18/48.18184/9.90026

**Comment by koebi** [comment]
Hey,

the geocode service is a pelias instance hosted by us.
This is not related to the ors, but rather to pelias, and [there](https://github.com/pelias/pelias/issues/789) [is](https://github.com/pelias/pelias/issues/111) a [lot](https://github.com/pelias/pelias/issues/777) of [discussion](https://github.com/pelias/pelias/issues/887) around this [issue](https://github.com/pelias/pelias/issues/889).

The gist of this, as I understood it, is that postal codes are hard (streets spanning multiple postal code areas, missing data, …) and they'd rather have missing information than wrong results:

Quote from the first link (issue 789):
> Because they [polygons representing postal codes] are of variable quality internationally we've decided not to include them in the point-in-polygon system at this stage.
> The tradeoff there is that we could assign postcodes to records which don't have it, but a large number of those would be incorrect.
> So if we did this we'd instead receieve bug reports about incorrect postcode instead of missing postcodes and it could hurt the project reputation as we would be providing a mix of accurate and inaccurate data.

I hope this clears it up a bit :)
Best regards

P.S.:
Here's [another issue discussion](https://github.com/pelias/pelias/issues/913) surrounding post codes, maybe also interesting :)
