### ISSUE TITLE
bridleway with bicycle=yes not used for bike routing

### ISSUE THREAD

**Issue by koebi** [GIScience/openrouteservice#1167]
This was brought up by [this question](https://ask.openrouteservice.org/t/bridleways-and-cycling-isochrones/3868) in the forum.

#### Here's what I did
Request a [bike route](https://maps.openrouteservice.org/#/directions/Jackson's%20Bridge,Manchester,England,United%20Kingdom/Jackson's%20Bridge,Manchester,England,United%20Kingdom/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,90,0,152,3,164,32,14,1,217,8,17,128,54,106,205,160,86,66,6,96,5,149,178,1,162,117,227,59,80,0,196,192,39,45,33,66,218,137,171,64,55,17,82,140,203,82,228,201,181,10,213,9,15,107,223,167,33,181,70,235,237,84,74,138,33,184,128,128,1,213,60,8,137,176,229,0,11,202,0,91,92,230,109,222,128,128,3,55,128,1,183,69,199,0,4,243,5,10,64,7,55,194,240,128,5,116,69,70,66,70,177,0,15,66,15,70,135,68,67,0,139,196,44,130,242,242,45,135,69,129,0,5,247,170,0,0) over a [way](https://www.openstreetmap.org/way/32405217) tagged with `highway=bridleway` and `bicycle=yes`.

Way has been modified 11 months ago, should be included in ors.

---
#### Here's what I got
The following route, which doesn't use the `highway=bridleway`.
![Screenshot 2022-05-12 at 09-21-42 ORS Maps](https://user-images.githubusercontent.com/4692974/168014524-aa9dc1cb-3613-44b3-bb8b-a9267fa2ab5d.png)

---
#### Here's what I was expecting
As I found out from #413, the legality of pedestrians and bikes on bridleways is heavily dependent on the country in question.
Here, however, an access tag `bicycle=yes` is explicitly set. Thus, I'd expect the route to go via the much shorter bridleway.

---
#### Here's what I think could be improved
Tag handling regarding `highway=bridleway` or `bicycle=yes` - no idea where the problem actually arises…

**Comment by aoles** [comment]
Apparently https://github.com/graphhopper/graphhopper/pull/2105 fixes this issue. I believe it could be fixed on the ORS side by incorporating those changes into `CommonBikeFlagEncoder`.
