### ISSUE TITLE
Lat Long order in search

### ISSUE THREAD

**Issue by IAmTheWebb** [GIScience/openrouteservice#1169]
I was testing the search functionality on https://maps.openrouteservice.org to see what inputs were all accepted.  When I enter the lon/lat co-ordinates for New York 40.714,-74.006 the maps shows Antartica, if I switch the order it shows New York.

Not sure if that is expected behaviour?

**Comment by aoles** [comment]
Yes, [lon/lat coords of NY are -74.006, 40.714](https://www.latlong.net/place/new-york-city-ny-usa-1848.html).
