### ISSUE TITLE
Missing dependencies in 6.4.3

### ISSUE THREAD

**Issue by dombourcier** [GIScience/openrouteservice#1175]
#### Here's what I did
Hello there. 
We are using ORS with docker in version release-6.4.3. It looks like you recently removed the ch.poole:ConditionalRestrictionParser:jar:0.2.3 from this repository https://repo.heigit.org/artifactory/main which makes things break.

---
#### Here's what I got
[ERROR] Failed to execute goal on project openrouteservice: Could not resolve dependencies for project org.heigit.ors:openrouteservice:war:6.4.3: The following artifacts could not be resolved: ch.poole:ConditionalRestrictionParser:jar:0.2.3, ch.poole:OpeningHoursParser:jar:0.16.1: Could not find artifact ch.poole:ConditionalRestrictionParser:jar:0.2.3 in HeiGIT main (https://repo.heigit.org/artifactory/main) -> [Help 1]

---
#### Here's what I was expecting
I guess I am not the only one using this version of open route service, and as long this version is available from the docker registry, related dependencies might be as well...
---
#### Here's what I think could be improved
I tried to upgrade to 6.6.1 which fix the dependency issue, but I ran into other configuration issue.

**Comment by netoferraz** [comment]
I'm unable to build successfully because I've gotted on this error
```
ors-app    | 167794 [ERROR] Failed to execute goal on project openrouteservice: Could not resolve dependencies for project org.heigit.ors:openrouteservice:war:6.6.1: The following artifacts could not be resolved: com.github.GIScience.graphhopper:graphhopper-core:jar:v0.13.18, com.github.GIScience.graphhopper:graphhopper-api:jar:v0.13.18: Could not find artifact com.github.GIScience.graphhopper:graphhopper-core:jar:v0.13.18 in HeiGIT main (https://repo.heigit.org/artifactory/main) -> [Help 1]
ors-app    | 167797 [ERROR] 
ors-app    | 167798 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
ors-app    | 167798 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
ors-app    | 167799 [ERROR] 
ors-app    | 167799 [ERROR] For more information about the errors and possible solutions, please read the following articles:
ors-app    | 167799 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
ors-app    | NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
```

**Comment by MichaelsJP** [comment]
@dombourcier  @netoferraz Thanks for reporting, and thank you for your patience.
Please upgrade to our latest versions >= 6.8.2 where this is fixed as described in: [Running-with-Docker](https://giscience.github.io/openrouteservice/installation/Running-with-Docker.html).
You are welcome to report if the error persists.
