### ISSUE TITLE
Include `waterway:lock_gate` in (pedestrian) routing

### ISSUE THREAD

**Issue by koebi** [GIScience/openrouteservice#1177]
This was reported [in the ask-forum](https://ask.openrouteservice.org/t/locks-and-weirs-which-double-as-footpaths-get-excluded-from-routing/3905/2).

#### Here's what I did
Request [this route](https://maps.openrouteservice.org/#/directions/Saxon%20Court,Benson,England,United%20Kingdom/Saxon%20Court,Benson,England,United%20Kingdom/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,90,1,24,3,164,48,128,217,8,29,128,78,0,56,2,96,25,142,170,5,96,5,129,246,1,163,100,202,228,218,114,104,77,147,81,28,216,6,226,42,76,85,70,116,219,145,161,208,131,102,28,248,8,166,206,128,6,26,229,155,183,161,196,15,16,16,0,58,167,129,17,54,28,160,1,121,64,11,107,144,141,43,55,160,64,1,155,192,0,219,162,224,130,5,66,163,224,3,187,32,132,3,89,32,3,154,88,131,251,162,7,163,67,162,33,131,133,226,230,64,120,121,230,195,162,192,128,2,251,85,0,0)

---
#### Here's what I got
The following route going around, although the lock is tagged with `foot:designated`
![Screenshot 2022-05-30 at 14-59-42 ORS Maps](https://user-images.githubusercontent.com/4692974/170997886-4e52fc5a-5a25-41b9-abd6-3bfe1b0a59a4.png)

---
#### Here's what I was expecting
The short route, since the lock is tagged as accessible by foot.

---
#### Here's what I think could be improved
According to @aoles this case might have to be added to [handleNonHighways](https://github.com/GIScience/openrouteservice/blob/7cba0a4d0c6a2ad259d4006b23f84bb7ff800848/openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/flagencoders/FootFlagEncoder.java#L293-L316) similar to some of the other scenarios such as ferries or public transport platforms.

If done so, it should also be added to [the backend documentation](https://github.com/GIScience/openrouteservice/blob/master/docs/documentation/Tag-Filtering.md#foot).

**Comment by aoles** [comment]
For the record: the problem with this particular example is that both way segments [82644748](https://www.openstreetmap.org/way/82644748) and [677222821](https://www.openstreetmap.org/way/677222821) which constitute the lock gate are not tagged as `highway`. In order to consider such ways for routing some additional logic based on OSM tags needs to be added to [handleNonHighways](https://github.com/GIScience/openrouteservice/blob/7cba0a4d0c6a2ad259d4006b23f84bb7ff800848/openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/flagencoders/FootFlagEncoder.java#L293-L316), probably sth along the lines:

```
        if (way.hasTag("waterway" = "lock_gate")) {
            String footTag = way.getTag(OSMTags.Keys.FOOT);
            if (intendedValues.contains(footTag))
                acceptPotentially = EncodingManager.Access.WAY;
        }
```

Fun fact: there is only a bunch of water locks open to pedestrians [worldwide](https://overpass-turbo.eu/s/1iTx). Note that in contrary to the above some of them are tagged as `highways`.

**Comment by koebi** [comment]
ToDo here:

- [x] check how routing behaves on `waterway=lock_gate` if tagged w/ `highway`
- [x] add unit test for `waterway=lock_gate; foot=yes/no`
- [x] add check as above
- [x] test and be happy :)

**Comment by koebi** [comment]
[This route](https://classic-maps.openrouteservice.org/directions?n1=57.098312&n2=-4.739251&n3=18&a=57.098876,-4.739866,57.097736,-4.739141&b=2&c=0&k1=de&k2=km) and [this route](https://classic-maps.openrouteservice.org/directions?n1=51.99644&n2=-2.157491&n3=18&a=51.995596,-2.157896,51.997301,-2.157193&b=2&c=0&k1=de&k2=km) both include `waterway=lock_gate`s that have a `highway=*`-tag.

I'd conclude that these edges tagged as `highway`s work as expected.

**Comment by aoles** [comment]
Great, thanks a lot @koebi for verifying that in the presence of `highway` tag the routing works as expected. I can additionally confirm, that as long as there is a highway tag present the routing works even in the absence of an explicit `foot` tag, as [here for example](https://classic-maps.openrouteservice.org/directions?n1=63.942524&n2=-20.817523&n3=18&a=63.942425,-20.817408,63.942449,-20.816838&b=2&c=0&k1=de&k2=km). For reference see also [other cases around the world](https://overpass-turbo.eu/s/1iXm).
