### ISSUE TITLE
 java.lang.Exception: ExtendedGraphStorage for avoid features was not found.

### ISSUE THREAD

**Issue by netproject0** [GIScience/openrouteservice#1182]
Hi,

Seems my Isochrone request `https://MYSERVER:8080/v2/isochrones/foot-walking` doesn't take into consideration `"options":{"avoid_features":["ferries"]}` parameter.
Also, i've this error in my log :
`04 Jun 00:11:59 ERROR [extensions.ORSEdgeFilterFactory] - java.lang.Exception: ExtendedGraphStorage for avoid features was not found.`

I use the "docker-compose" way. What could be wrong with my setup ?
Do i need to be more explicit ?
Many thank by advance for your help.

Best

**Comment by koebi** [comment]
Hey,

this issue was reported similarly in our forum, I think also by you.
[This is the response](https://ask.openrouteservice.org/t/isochrone-call-on-premise-server-avoid-features-ferries-issue/3940/2), linked here for completeness.

Best regards
