### ISSUE TITLE
Address `access=destination` restrictions through an edge filter

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#1184]
Apparently there have been attempts to address access restrictions tagged as `destination` through `DestinationDependentEdgeFilter`. Even though this code has been defunct, such approach could actually be a pretty neat alternative to a priority-based solution described in https://github.com/GIScience/openrouteservice/issues/705. The idea here would be to have a dedicated edge filter which allows routing over edges marked as `destination` only if they originate from the source or target points. AFAIU this is what the following method in `HeavyVehicleEdgeFilter` tries to achieve.

https://github.com/GIScience/openrouteservice/blob/cb4f5540ca953fd2542eed6d09b19ca5abd5dde3/openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/edgefilters/HeavyVehicleEdgeFilter.java#L110-L142 

One could try re-implementing and testing this approach in the existing `HeavyVehicleEdgeFilter`. If this works out, the solution could be easily integrated into other profiles, possibly as a boolean flag encoded directly on the edge rather than an additional extended storage.

**Comment by TheGreatRefrigerator** [comment]
This solution seems inferior to the one based on a penalized weighting. A potential problem with an edge filter is that it entirely disables routing over edges. As such it might be much more error prone. It would be fine if only single edges were marked with `access: destination`. Then such edges could be allowed for snapping but blocked for routing. However, such approach might fail in the following tho scenarios:
- A number of consecutive edges is tagged with `access: destination`. This can be the case e.g. when a single OSM way gets split into multiple edges in the routing graph.
- An edge tagged as `access: destination` is the only connection to a smaller subnetwork.

**Comment by aoles** [comment]
It has been decided not to follow up on this but rather implement the solution described in https://github.com/GIScience/openrouteservice/issues/705.
