### ISSUE TITLE
shortest route takes footways

### ISSUE THREAD

**Issue by joshinils** [GIScience/openrouteservice#1205]
#### Here's what I did
trying to generate a route around hauptbahnhof in berlin, which used this segment, in this direction:
https://maps.openrouteservice.org/#/directions/Invalidenstra%C3%9Fe,Berlin,Germany/Invalidenstra%C3%9Fe,Berlin,Germany/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,70,1,152,3,164,32,54,1,216,5,96,9,128,14,1,57,242,160,22,0,25,110,160,26,91,141,170,178,85,24,50,166,204,161,26,20,3,113,21,38,76,164,182,34,26,16,161,70,131,30,52,248,213,167,78,149,33,44,25,144,98,196,23,16,16,0,58,167,129,17,54,28,160,1,121,64,11,107,159,11,75,215,160,64,3,55,128,1,183,69,199,0,4,243,6,10,64,7,48,5,166,135,69,136,5,118,14,70,128,177,3,247,64,15,66,76,67,3,11,194,76,135,119,119,68,69,135,69,129,0,5,243,170,0

---
#### Here's what I got
a small segment (the one above) of a larger route takes me along a `highway=footway` which is even tagged as `footway=sidewalk`. 
cycling there is never permitted if not explicitly tagged so, in neither direction.
if i change the direction it routes along the road, which is to be expected

https://maps.openrouteservice.org/#/directions/Invalidenstra%C3%9Fe,Berlin,Germany/Rahel-Hirsch-Stra%C3%9Fe,Berlin,Germany/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,70,1,152,3,164,32,54,1,217,10,176,128,88,40,9,128,14,7,111,223,0,104,5,96,120,158,205,100,192,3,0,78,10,66,36,8,13,196,84,153,17,249,198,208,101,65,131,66,76,155,117,227,193,136,141,92,41,138,230,73,151,90,32,56,128,128,1,213,60,8,137,176,229,0,11,202,0,91,92,138,172,222,129,0,12,222,0,6,221,23,28,0,19,204,24,41,0,28,192,22,154,29,22,32,21,216,57,26,18,196,15,221,0,61,9,49,12,12,47,19,0,2,198,3,19,21,11,54,222,209,217,212,25,0,13,194,30,22,0,31,70,194,24,34,54,62,183,20,21,2,38,216,164,0,22,77,62,192,1,91,183,177,203,50,6,1,5,18,183,0,27,64,23,64,23,199,107,104,0,0
even routes me through the station, where cycling is also not permitted, all via footways.

i have to spam many avoid polygons to get a somewhat realistic route:
https://maps.openrouteservice.org/#/directions/Invalidenstra%C3%9Fe,Berlin,Germany/Rahel-Hirsch-Stra%C3%9Fe,Berlin,Germany/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,70,1,152,3,164,32,54,1,217,10,176,128,88,40,9,128,14,7,111,223,0,104,5,96,120,158,205,100,192,3,0,78,10,66,36,8,13,196,84,153,17,249,198,208,101,65,131,66,76,155,117,227,193,136,141,92,41,138,230,73,151,90,32,56,128,128,1,213,60,8,137,176,229,0,11,202,0,91,92,248,69,89,189,2,0,12,222,0,6,221,23,28,0,19,204,4,41,0,28,192,22,154,29,14,32,21,196,57,26,18,196,31,221,16,61,25,49,12,28,47,19,0,2,198,3,19,21,27,54,222,209,217,212,25,0,13,194,30,22,0,31,70,194,4,50,46,33,183,20,21,18,38,196,164,0,22,93,62,192,1,71,175,177,219,50,6,1,5,10,183,0,27,83,125,118,92,137,138,151,199,143,129,139,132,89,128,23,67,155,100,151,100,89,91,72,228,240,130,234,238,83,71,222,231,139,147,86,153,231,116,223,99,236,117,57,48,206,160,203,166,207,225,71,98,3,116,191,107,165,24,229,193,133,168,158,151,72,103,16,233,240,97,145,240,112,185,20,35,19,166,57,169,65,207,8,124,42,134,193,132,8,65,104,138,93,0,228,74,225,113,8,92,60,121,17,132,102,167,179,40,116,66,67,198,154,79,4,189,200,100,81,63,51,235,64,16,242,78,84,204,113,214,132,37,68,138,200,56,218,18,62,82,205,164,170,197,10,24,84,161,132,42,217,253,52,128,194,4,151,23,77,120,137,244,102,161,5,12,131,203,217,145,8,128,230,62,137,213,167,151,154,132,184,176,113,186,238,32,144,81,1,138,159,59,60,76,195,34,134,132,199,8,228,130,94,161,17,8,217,86,234,4,158,211,31,15,251,201,114,17,51,49,49,201,228,136,152,174,239,99,27,87,241,17,144,89,102,195,42,101,95,154,226,23,40,70,220,250,112,138,195,172,80,27,59,113,46,140,218,100,117,167,35,230,65,197,30,57,221,163,118,217,57,145,80,111,70,108,98,26,71,190,134,29,102,188,90,99,230,151,56,248,236,113,148,118,160,146,231,85,216,244,123,221,140,175,194,20,106,51,126,28,230,159,144,248,67,222,194,59,24,190,123,53,94,219,42,166,62,0,67,117,200,21,207,245,97,215,121,76,14,29,64,141,72,149,96,0,167,64,15,3,96,224,52,147,56,0,95,12,45,10,0,0

---
#### Here's what I was expecting
a route without footways neither inside nor outside.
a route without going the wrong way (https://www.openstreetmap.org/way/342098495 was taken as a shortcut until I forbid it with an avoid polygon)
a route without ever using bits of roads tagged with `bicycle=use_sidepath`, like https://www.openstreetmap.org/way/48859724.
---
#### Here's what I think could be improved
give a warning if taking footways by foot is intended, since getting off your bike and pushing is theoretically possible, but not wanted in this case (?).

give a setting that forces the engine not to ever use footways or roads tagged with `bicycle=use_sidepath`.
or just never use those

**Comment by takb** [comment]
Thank you for the report, (and sorry for the long time we took to answer,) but this behavior is basically intended. The bicycle profiles treat footways as traversible "pushing sections", since in some cases getting off the bike and pushing for a certain length of the way makes more sense than taking a longer detour, and this assessment is calculated by assigning pushing sections a lower priority in the priority weighting. Unfortunately, since this is a heuristic, you will always find cases where the assessment diverges from human common sense, and though the heuristic can surely be improved, the required manpower to perform in-depth analysis to do so is simply not available at the moment due to our prioritization of other topics. 

An API option to have the routing engine avoid pushing sections entirely is certainly possible, but again, not within our current priorities and manpower, at least for the foreseeable future. It would be surely appreciated if you were to program and contribute such a feature, though it would also take some time for us to evaluate and integrate your code. 

For a shorter term solution, you can always download and adjust our code and run your own instance.

**Comment by marq24** [comment]
also there is quite simple alternative by using 'fastest' option (instead of shortest)...
