### ISSUE TITLE
Geocode search error - Failed to get a valid response from API

### ISSUE THREAD

**Issue by kf99916** [GIScience/openrouteservice#1207]
#### Here's what I did

https://openrouteservice.org/dev/#/api-docs/geocode/search/get with the default query "Namibian Brewery"

---
#### Here's what I got

 "errors": [
"[index_not_found_exception] no such index [pelias], with { resource.type="index_or_alias" & resource.id="pelias" & index_uuid="na" & index="pelias" }"
]

---
#### Here's what I was expecting

Get correct results

---

**Comment by TheGreatRefrigerator** [comment]
See https://ask.openrouteservice.org/t/geocode-search-stopped-working-index-not-found-exception-no-such-index-pelias/3653/9
