### ISSUE TITLE
Autocomplete with house number 

### ISSUE THREAD

**Issue by Rickyc81** [GIScience/openrouteservice#1208]
It's seems the autocomplete work only with address without house number, correct?

Like
text = 'via Roma 100 Palermo' 

Thanks

**Comment by takb** [comment]
House numbers can be used in places where they are available in the underlying data. Our geocoder uses OSM and several additional databases, and if you did not find your example query it means it's not represented in any of our data sources.

Also, this is NOT the right place for questions like these, we have a forum for that: https://ask.openrouteservice.org/ Please refrain from opening issues for questions.

**Comment by Rickyc81** [comment]
Ok thanks so much.. but keep calm.. :)
