### ISSUE TITLE
Weird results (to slow driving) in Belgium

### ISSUE THREAD

**Issue by StevenGhyselbrecht** [GIScience/openrouteservice#1218]
#### Here's what I did
`{
    "coordinates": [[5.97715,50.664077],[6.02034,50.67909]],
    "language": "nl", "preference": "fastest",
    "attributes": ["avgspeed"]
}
`

---
#### Here's what I got
`{
    "routes": [
        {
            "summary": {
                "distance": 9428.0,
                "duration": 721.3
            },
            "segments": [
                {
                    "distance": 9428.0,
                    "duration": 721.3,
                    "steps": [
                        {
                            "distance": 2762.2,
                            "duration": 192.6,
                            "type": 11,
                            "instruction": "Richting noordwest op Rue Mitoyenne - Neutralstraße, N67",
                            "name": "Rue Mitoyenne - Neutralstraße, N67",
                            "way_points": [
                                0,
                                40
                            ]
                        },
                        {
                            "distance": 32.0,
                            "duration": 10.9,
                            "type": 7,
                            "instruction": "Ga de rotonde op en neem de 1e afslag richting N3",
                            "name": "N3",
                            "exit_number": 1,
                            "way_points": [
                                40,
                                44
                            ]
                        },
                        {
                            "distance": 2059.4,
                            "duration": 131.5,
                            "type": 5,
                            "instruction": "Keer om flauw rechts richting Lütticher Straße - Route Charlemagne, N3",
                            "name": "Lütticher Straße - Route Charlemagne, N3",
                            "way_points": [
                                44,
                                69
                            ]
                        },
                        {
                            "distance": 628.1,
                            "duration": 71.7,
                            "type": 7,
                            "instruction": "Ga de rotonde op en neem de 1e afslag richting Montzener Straße",
                            "name": "Montzener Straße",
                            "exit_number": 1,
                            "way_points": [
                                69,
                                91
                            ]
                        },
                        {
                            "distance": 3241.5,
                            "duration": 272.2,
                            "type": 12,
                            "instruction": "Keer om links richting Montzener Straße",
                            "name": "Montzener Straße",
                            "way_points": [
                                91,
                                194
                            ]
                        },
                        {
                            "distance": 704.8,
                            "duration": 42.3,
                            "type": 12,
                            "instruction": "Keer om links richting Schloss Straße",
                            "name": "Schloss Straße",
                            "way_points": [
                                194,
                                216
                            ]
                        },
                        {
                            "distance": 0.0,
                            "duration": 0.0,
                            "type": 10,
                            "instruction": "Aankomen op Schloss Straße, rechts",
                            "name": "-",
                            "way_points": [
                                216,
                                216
                            ]
                        }
                    ],
                    "avgspeed": 47.06
                }
            ],
            "bbox": [
                5.954765,
                50.664115,
                6.020218,
                50.69852
            ],
            "geometry": <skipped>,
            "way_points": [
                0,
                216
            ]
        }
    ],
    "bbox": [
        5.954765,
        50.664115,
        6.020218,
        50.69852
    ],
    "metadata": {
        "attribution": "openrouteservice.org, OpenStreetMap contributors",
        "service": "routing",
        "timestamp": 1664286119166,
        "query": {
            "coordinates": [
                [
                    5.97715,
                    50.664077
                ],
                [
                    6.02034,
                    50.67909
                ]
            ],
            "profile": "driving-car",
            "preference": "fastest",
            "format": "json",
            "language": "nl",
            "attributes": [
                "avgspeed"
            ]
        },
        "engine": {
            "version": "6.7.0",
            "build_date": "2022-09-21T07:58:08Z",
            "graph_date": "2022-09-27T13:41:46Z"
        }
    }
}`

---
#### Here's what I was expecting
avgspeed should be faster, probably because the defaultsetting of a "residential" street is 30. Where in Belgium the default is 50 km per hour. 

---

**Comment by StevenGhyselbrecht** [comment]
Already started with changes the car.json and testing the results.

**Comment by aoles** [comment]
Thanks for your feedback! Details on how road speed values are being determined can be found in section [Travel Speeds](https://giscience.github.io/openrouteservice/documentation/travel-speeds/Travel-Speeds.html#travel-speeds) of the openrouteservice backend documentation. In particular, as described there, the base speed in residential areas is reduced by an acceleration modifier or a residential penalty in an attempt to model real-life driving conditions. Therefore, the resulting average speed is in general expected to be below the legally allowed speed limit.
