### ISSUE TITLE
Walking profiles fail to route over ways tagged as `foot=yes` but `access=no`

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#1227]
> Seit dem letzten Update, Anfang November, sind bei der Routenerstellung über im Raum Görlitz (mind) zwei Fehler enthalten. Es werden zwei Fußwege auch für Fußgänger gesperr, so dass man auch als Fußgänger einen Umweg gehen müsste. Es handelt sich um den
> (Since the last update, beginning of november, routing around Görlitz contains (at least) two errors. Two footways are also blocked for pedestrians, so that you'd have to make a detour even as a pedestrian. Those are)
> 1. [Finkenweg in 02827 Görlitz](https://www.openstreetmap.org/way/237508769)
> 2. [Gibirgsdorfer Straße in 02829 Schöpstal, Brücke über den weißen Schöps](https://www.openstreetmap.org/way/154608214)

[Example illustrating the issue](https://maps.openrouteservice.org/#/directions/Finkenweg,G%C3%B6rlitz,SN,Deutschland/Finkenweg%2021a,G%C3%B6rlitz,SN,Deutschland/Hans-Beimler-Stra%C3%9Fe,G%C3%B6rlitz,SN,Deutschland/Girbigsdorfer%20Stra%C3%9Fe%2048,Markersdorf,SN,Deutschland/Girbigsdorfer%20Stra%C3%9Fe%2044,Markersdorf,SN,Deutschland/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,70,0,88,3,160,19,128,86,114,3,101,32,118,0,25,205,42,129,153,241,124,128,105,207,216,163,200,4,192,3,144,141,1,2,90,21,32,27,136,153,114,45,105,87,36,38,145,122,84,6,214,235,200,148,138,91,234,212,47,157,161,89,36,14,208,19,218,253,66,195,9,9,215,208,143,9,249,201,58,20,124,133,178,18,132,28,132,82,84,244,244,226,2,46,158,132,26,198,146,74,164,140,230,114,164,30,180,180,20,180,10,132,153,81,60,124,94,166,110,177,217,170,44,32,156,32,16,0,14,168,240,16,136,216,56,160,0,94,80,0,182,184,248,218,32,53,208,16,0,102,240,0,54,232,184,32,131,80,168,0,180,0,238,200,35,0,214,72,0,230,149,125,208,232,131,232,91,136,96,227,120,91,144,29,29,232,136,176,232,176,32,0,190,55,64,0)

![image](https://user-images.githubusercontent.com/6545356/201060204-48010bc7-2feb-4172-8607-06fe546d7310.png)

**Comment by koebi** [comment]
[This post](https://ask.openrouteservice.org/t/cannot-route-the-trail-which-has-no-sac-scale-tag-in-openstreetmap/4427/2) in the forum describes a similar problem, but might be resolved with the next data update.

**Comment by aoles** [comment]
Thanks @koebi ! I think the issue might be an actual bug rather than a data problem, that's why I originally labeled it as such. I suspect it might have been introduced in https://github.com/GIScience/openrouteservice/pull/1185. I will have a look into it.

**Comment by koebi** [comment]
Can confirm that #1242 will fix this.
