### ISSUE TITLE
openrouteservice is not suggesting the shortest route

### ISSUE THREAD

**Issue by Loki-Afro** [GIScience/openrouteservice#1229]
#### Here's what I did

https://maps.openrouteservice.org/#/directions/K%201366,Falkenstein%2FHarz,ST,Germany/Alte%20Reihe,Falkenstein%2FHarz,ST,Germany/Alte%20Reihe,Falkenstein%2FHarz,ST,Germany/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,70,124,3,160,25,128,38,1,57,201,32,54,0,88,43,160,6,122,72,21,128,26,55,137,162,128,57,41,49,32,29,130,141,54,2,72,6,228,42,68,157,62,117,107,179,102,194,147,1,92,120,85,81,88,126,58,250,251,226,103,70,113,121,67,106,139,22,95,4,178,90,138,241,34,45,93,19,174,219,137,1,196,4,0,7,84,120,8,68,108,28,80,0,47,40,0,91,92,124,26,63,0,232,8,0,51,120,0,27,116,92,16,84,168,84,0,90,0,119,100,12,128,107,36,0,115,95,16,100,244,84,244,104,116,68,48,108,188,38,200,24,152,230,216,116,88,16,0,95,1,160,0

---
#### Here's what I got
![image](https://user-images.githubusercontent.com/4738445/202258401-7705dcef-da33-43c5-965d-e551990a5d6f.png)

---
#### Here's what I was expecting
direct way

---
#### Here's what I think could be improved
i don't know what the routing is blocking here, the ground is grass, that shouldn't be a problem i think, or do i miss something?

and i do expect to be able to ride that by bike as well, at least with a mountain bike

**Comment by sfendrich** [comment]
Thank you for reporting this issue! I can see no issue with the data itself. As the way is only 23 days old, it might not have  entered the ORS graph yet. (https://www.openstreetmap.org/way/1106840206/history)  We will reconsider this issue after the next graph update.

**Comment by Loki-Afro** [comment]
@sfendrich might be might be, but on thing is odd then, this change https://www.openstreetmap.org/changeset/128883188 modified the way slightly between 1-2 (I did that change by the way) and these changes are already applied, the upper left turn in the screenshot would not have been possible

can you elaborate a bit what ORS graph is, how and when is it generated, and how does this affect this project? maybe point me to some information, kinda feel like a noob when it comes to gis^^

**Comment by koebi** [comment]
Hey,
I don't think that the changeset you referred to is reflected in the openrouteservice.
The [OSM history viewer](https://osmhv.openstreetmap.de/changeset.jsp?id=128883188) shows that the change in the first left turn after 1 is the crossing going from a straight 90° T-crossing to a more sharp ~120° T-crossing. 
Looking at the screenshot you provided, you can see the new, rendered crossing just below the route, which is still using the old geometry. 

The ORS graph is the data structure that is used for calculating routes. It is generated from OSM data, converting the nodes and (high)ways of OSM and their tags into a [weighted graph](https://en.wikipedia.org/wiki/Graph_(discrete_mathematics)#Weighted_graph) suitable for routing. As to when it is generated, see [our backend FAQ](https://giscience.github.io/openrouteservice/Frequently-Asked-Questions.html#when-does-the-osm-data-update-in-the-openrouteservice).

Best regards

**Comment by Loki-Afro** [comment]
hi there, routing works now, thanks for the hints :)
