### ISSUE TITLE
Optimization error 500 vroom

### ISSUE THREAD

**Issue by quim96** [GIScience/openrouteservice#1241]
#### Here's what I did
  curl -X POST \
  'https://api.openrouteservice.org/optimization' \
  -H 'Content-Type: application/json; charset=utf-8' \
  -H 'Accept: application/json, application/geo+json, application/gpx+xml, img/png; charset=utf-8' \
  -H 'Authorization: api-key-here' \
  -d '{"jobs":[{"id":1,"service":300,"amount":[1],"location":[1.98935,48.701],"skills":[1],"time_windows":[[32400,36000]]},{"id":2,"service":300,"amount":[1],"location":[2.03655,48.61128],"skills":[1]},{"id":3,"service":300,"amount":[1],"location":[2.39719,49.07611],"skills":[2]},{"id":4,"service":300,"amount":[1],"location":[2.41808,49.22619],"skills":[2]},{"id":5,"service":300,"amount":[1],"location":[2.28325,48.5958],"skills":[14]},{"id":6,"service":300,"amount":[1],"location":[2.89357,48.90736],"skills":[14]}],"vehicles":[{"id":1,"profile":"driving-car","start":[2.35044,48.71764],"end":[2.35044,48.71764],"capacity":[4],"skills":[1,14],"time_window":[28800,43200]},{"id":2,"profile":"driving-car","start":[2.35044,48.71764],"end":[2.35044,48.71764],"capacity":[4],"skills":[2,14],"time_window":[28800,43200]}]}'

(Example Code)

---
#### Here's what I got
 {
     "code": 1,
     "error": "basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 487)"
 }
---
#### Here's what I was expecting

---

**Comment by koebi** [comment]
Hey,

given that this query gives a valid response now, I'd assume that this was an issue with the optimization service not being available at the time of your request.

I'll close this for now, feel free to reopen if it reappears.
