### ISSUE TITLE
Directions calculation error

### ISSUE THREAD

**Issue by jcenrique** [GIScience/openrouteservice#1243]
Hello,
I have tried to follow a route and at marker number 2 it sends me in the opposite direction in a place that is not possible.
Attached link with the route

---
#### Here's what I got

https://maps.openrouteservice.org/#/directions/43.33918589674331,-1.7915332317352297/Irun%20Col%C3%B3n,Ir%C3%BAn,PV,Espa%C3%B1a/43.336678,-1.802276/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,90,1,24,3,160,29,128,14,82,5,96,19,138,128,104,1,96,25,152,231,29,46,128,152,6,226,44,154,0,216,184,0,100,36,43,151,42,34,70,214,100,213,187,17,212,170,13,155,80,121,102,124,75,145,25,52,160,133,109,154,12,17,68,61,16,16,0,58,167,129,17,54,28,160,1,121,64,11,107,144,169,43,55,160,64,1,155,192,0,219,162,224,130,195,67,192,1,185,32,3,155,225,131,35,66,88,131,251,162,7,163,67,162,33,131,133,224,230,64,120,122,230,195,162,192,128,2,249,85,0

---
#### Here's what I was expecting

https://maps.openrouteservice.org/#/directions/43.33918589674331,-1.7915332317352297/Irun%20Col%C3%B3n,Ir%C3%BAn,PV,Espa%C3%B1a/43.336678,-1.802276/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,90,1,24,3,160,29,128,14,82,5,96,19,138,128,104,1,96,25,152,231,29,46,128,152,6,226,44,154,0,216,184,0,100,36,43,151,42,34,70,214,100,213,187,17,212,170,13,155,80,121,102,124,75,145,25,52,160,133,109,154,12,17,68,61,16,16,0,58,167,129,17,54,28,160,1,121,64,11,107,144,169,43,55,160,64,1,155,192,0,219,162,224,130,195,67,192,1,185,32,3,155,225,131,35,66,88,131,251,162,7,163,67,162,33,131,133,224,230,64,120,122,230,195,162,192,128,2,249,85,0

---

**Comment by jcenrique** [comment]
Sorri 
Here's what I got
![Map1](https://user-images.githubusercontent.com/16383217/211733360-32d6d800-71c4-4a0a-bc08-18c683ea08b7.png)
Here's what I was expecting
![Map2](https://user-images.githubusercontent.com/16383217/211733369-d97fc32f-5c33-4ead-b52c-a792b0c773cc.png)

**Comment by koebi** [comment]
Hey,

what is happening here is that the waypoint you entered is being used as a sort of a "new starting point".
This becomes a bit more obvious when looking at the instructions. There, you'll see that the route arrives at point 2 and continues from there, as if starting from there.

To work around this, you can use the `continue_straight` parameter. From the API docs:
```
Forces the route to keep going straight at waypoints restricting uturns there even if it would be faster.
```

Best regards

**Comment by jcenrique** [comment]
Perfect, `continue_straight` it works correctly, 
thank you very much
