### ISSUE TITLE
bridleway with foot=yes not used for foot routing

### ISSUE THREAD

**Issue by koebi** [GIScience/openrouteservice#1244]
This was brought up by [this issue](https://ask.openrouteservice.org/t/routing-ignoring-footpath-options/4466) in the forum - the route in question is [here](https://classic-maps.openrouteservice.org/directions?n1=52.136985&n2=-0.532118&n3=16&a=52.142193,-0.536613,52.132474,-0.545154&b=2&c=0&k1=de&k2=km), not using [the north](https://www.openstreetmap.org/way/132017417) and [south](https://www.openstreetmap.org/way/5888778) part of the green dashed bridleway.

Both have been tagged w/ foot=yes for 5 years, so it should really not be a data issue ;)

**Comment by aoles** [comment]
Should be fixed by https://github.com/GIScience/openrouteservice/pull/1242.

**Comment by koebi** [comment]
I can confirm that #1242 would fix this :)
