### ISSUE TITLE
Doesn't work with GB dataset

### ISSUE THREAD

**Issue by RobertSmart** [GIScience/openrouteservice#125]
Hi,

I'm trying to get this working with this dataset:

http://download.geofabrik.de/europe/great-britain.html

It all runs fine up until this point. It then hangs for ages and eventually crashes.  

ors-core     | 23-Feb-2018 10:45:08.869 WARNING [ORS-pl-vehicles] heigit.ors.routing.graphhopper.extensions.GraphProcessContext.processWay For input string: "defaut". Way id = 561216870

I've given docker (docker for windows 10) 4 cores and 4gb ram, so it has plenty of resources. I've run this several times and it always seems to stop here? could it be an error in the data? The way in question is part of a roundabout 

![capture](https://user-images.githubusercontent.com/12431905/36591092-b8172986-1888-11e8-86f9-b3377a2c4ebb.PNG)

Any thoughts?

Thanks

**Comment by RobertSmart** [comment]
When the process crashes I get an error message of:
ors-core     | 23-Feb-2018 10:45:08.869 WARNING [ORS-pl-vehicles] heigit.ors.routing.graphhopper.extensions.GraphProcessContext.processWay For input string: "defaut". Way id = 561216870
ors-core exited with code 137

**Comment by TimMcCauley** [comment]
@RobertSmart what are your Xmx settings?

**Comment by RobertSmart** [comment]
- JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -Xms1g -Xmx6g

**Comment by TimMcCauley** [comment]
Could you try running Greater London first? It will help us debug 🥇

**Comment by RobertSmart** [comment]
sure

**Comment by RobertSmart** [comment]
Greater London from the same source worked fine

**Comment by TimMcCauley** [comment]
Then you are most likely exceeding the memory limits when importing the bigger pbf file. What profiles are you using? You won't fit more than one group into 6GB RAM for entire Great Britain. Can you try just adding "pedestrian" to active profiles in the app.config ?

**Comment by RobertSmart** [comment]
I’m just loading the vechicle profile. Thats all I really need at the moment.

How much RAM would likely be needed to load this?

**Comment by TimMcCauley** [comment]
@RobertSmart can you disable elevation and just try pedestrian for now? It will help me point you in the right direction.

**Comment by RobertSmart** [comment]
Hi, ped profile didn’t work either.

**Comment by TimMcCauley** [comment]
@RobertSmart can you track the memory consumption of the heap. Are you running docker?

**Comment by RobertSmart** [comment]
Hi, yes I'm running it on docker. 

Whats the best way to memory profile a docker container?

Thanks,

Rob Smart

**Comment by RobertSmart** [comment]
Arghh....pressed the wrong button! How do I uncloise this issue!!?!?!

**Comment by TimMcCauley** [comment]
Please try `docker stats ors-app` right up to the moment it crashes

**Comment by RobertSmart** [comment]
Hi,

That didn't work. There is no ors-app container, only ors-core.

I've attached the log from the ors-core. Not sure if that will help. It just stopped whilst processing one of the ways.

[catalina.2018-03-21.log.zip](https://github.com/GIScience/openrouteservice/files/1834512/catalina.2018-03-21.log.zip)

**Comment by TimMcCauley** [comment]
@RobertSmart  what does `docker logs ors-app` or `docker logs ors-core` say? The logs you sent me are basically saying that the graphs are being built. Which pbf are you now running? What what profiles have you enabled in `app.config` ?

**Comment by eduarsilva** [comment]
Hi Tim,

The same is happening to me at the moment. Trying to load the new york dataset from: https://download.geofabrik.de/north-america.html
It gets to this point and the docker container crashes: 

_**ors-core     | 02-Apr-2018 22:16:06.952 WARNING [ORS-pl-vehicles] heigit.ors.routing.graphhopper.extensions.GraphProcessContext.processWay For input string: "7  ons". Way id = 346338462
ors-core exited with code 137**_

JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -Xms2g -Xmx4g

Only using 1 profile for driving-hgv
Giving docker 4GB of RAM

When doing docker stats on the container I can see the memory % getting to 100% before it crashes.

Docker 18.03.0-ce
MAC High Sierra 10.13.3

**Comment by TimMcCauley** [comment]
@eduarsilva can you please try https://download.geofabrik.de/north-america/us/district-of-columbia-latest.osm.pbf and let me know if it works?

**Comment by TimMcCauley** [comment]
Please reopen when you can provide new information.

**Comment by RobertSmart** [comment]
Sorry been on holiday. Back at work tomorrow so will report back
