### ISSUE TITLE
Routing skips a bridge, anyone can help to understand why?

### ISSUE THREAD

**Issue by eliboni** [GIScience/openrouteservice#1258]
#### Here's what I did
Calculate routing between two close points across a bridge near Ouano pass in Morocco
[link to ORS map](https://bit.ly/3H5H9yf)

---
#### Here's what I got
routing does not cross the brige, a detour of 140km is shown

---
#### Here's what I was expecting
go strait from point 1 to point 2 (graphhopper does it)

---
#### Here's what I think could be improved
I'm not sure if this is a refresh problem, perhaps OSM data had an error that was corrected. However it is more than 2 weeks that I experience the behavior.

**Comment by TheGreatRefrigerator** [comment]
Note regarding OSM edit: The edit 2 weeks ago only changed the `surface` from `ground` to `asphalt`.
https://www.openstreetmap.org/way/1111621367/history
A way with `surface=ground` still should have been traversable.

**Comment by aoles** [comment]
Thanks @TheGreatRefrigerator! I don't think `surface=ground` was an issue either, I rather suspect the way might not have been properly connected prior the mentioned change. The routing works correctly with the recent OSM data snapshot, so I expect the issue to resolve itself in a couple of days once the graphs on the server are updated.

**Comment by eliboni** [comment]
@aoles @TheGreatRefrigerator many thanks for looking into it, and especially having tested with fresh osm data. I will wait a few days to see if  the issue resolves automatically.

**Comment by eliboni** [comment]
Is there a way to know when routing data have been last refreshed in ORS? Looking at the link reported by @TheGreatRefrigerator the last edit occurred 17 days ago.

**Comment by eliboni** [comment]
Just to confirm the issue disappeared, now I can cross the brigde ;) So it was likely what @aoles said, just the refresh took some additional time. Thanks all for your inputs
