### ISSUE TITLE
cannot login with GitHub oauth

### ISSUE THREAD

**Issue by noerw** [GIScience/openrouteservice#127]
This is probably not the right place to report this, but the website repo seems to be private..:

I cannot login with Github to access my API key. This worked a couple of weeks ago.
I noticed you changed the domain from `go.openrouteservice.org` to `openrouteservice.org`, might that be the issue?

**Comment by TimMcCauley** [comment]
@noerw thank you a bunch for pointing this out - I updated the OAuth settings now. Does it work again?

**Comment by noerw** [comment]
yep! :+1:

**Comment by TimMcCauley** [comment]
Phew, thanks 👍
