### ISSUE TITLE
Elevation data always comes to 0.

### ISSUE THREAD

**Issue by puniker** [GIScience/openrouteservice#1270]
#### Here's what I did

Download the map of Spain from Geofabrik and build the docker container with the variable 'BUILD_GRAPHS' = True to generate all the elevation data and graphs. Then I look for a route from the north of Spain to the south

---
#### Here's what I got

When searching for a route, the altitude of each coordinate point and ascent and descent information is 0 for much of the map. The route only returns elevation of the part corresponding to the elevation file srtm_36_04.zip.

---
#### Here's what I was expecting

You should get the route with elevation data other than 0.

---
#### Here's what I think could be improved
Somehow when downloading the elevations of the map of Spain it is not able to get the altitudes of part of the country. I have tried to install the maps of Belgium to test and everything works correctly, it downloads all the elevations and graphics.

**Comment by aoles** [comment]
@puniker Is this still valid or have you managed to resolve the issue? Cheers!

**Comment by sfendrich** [comment]
Closing due to no feedback.
