### ISSUE TITLE
Curl dependency broken by new release

### ISSUE THREAD

**Issue by hypadr1v3** [GIScience/openrouteservice#1283]
#### Here's what I did

I ran `docker-compose up` after all the preceding steps

---
#### Here's what I got

```
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  curl-7.79.1-r5:
    breaks: .build-deps-20230216.060441[curl=7.79.1-r4]
/bin/bash: line 1: curl: command not found
```

---
#### Here's what I was expecting

The build to pass for ORS

---
#### Here's what I think could be improved
I fixed the issue by just editing line 84 in the `DockerFile`  and changed the dependency from `curl='7.79.1-r4` to `curl='7.79.1-r5`

**Comment by MichaelsJP** [comment]
@hypadr1v3 Thanks for reporting. We have a fix waiting in pr https://github.com/GIScience/openrouteservice/pull/1289
