### ISSUE TITLE
docker volume folder connection not working properly

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#1286]
See forum post:
https://ask.openrouteservice.org/t/problems-with-local-installation-of-ors/4558

Probably introduced with https://github.com/GIScience/openrouteservice/pull/1272

#### Here's what i did

`docker compose up`

#### Here's what I got

no new files were created inside the folders `conf`, `elevation_cahche`, `graphs`, and `logs`.

---
#### Here's what I was expecting

the docker compose workflow to work

---
#### Here's what I think could be improved
fixing the workflow

**Comment by TheGreatRefrigerator** [comment]
same issue: https://ask.openrouteservice.org/t/unable-to-use-separate-pbf-file-when-using-base-image-and-docker-compose/4559/4

**Comment by MichaelsJP** [comment]
@TheGreatRefrigerator Thanks for reporting. We have a fix waiting in pr https://github.com/GIScience/openrouteservice/pull/1289
