### ISSUE TITLE
swagger specs differ after springfox update and 'swagger_documentation_url' introduction

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#1296]
With the introduction of the [swagger_documentation_url](https://github.com/GIScience/openrouteservice/commit/8f42060d7f129d3f62189b2b2dddd5b9d63c1701) the host changed from `api.openrouteservice.org` to `https://api.openrouteservice.org/` defined in the config parameter.

The live api documentation was instead resolving the server IP instead, probably because the `swagger_documentation_url` parameter was not set in the production config.

On the staging documentation the config parameter was set to `https://api.openrouteservice.org/` which resulted in urls like `https://https://api.openrouteservice//....`. so both the `https://` and the trailing `/` need to be removed from the default value or the generation of the path adjusted in the ors-website.

In addition switching from `RelativePathProvider` to `DefaultPathProvider` in [springfox update](https://github.com/GIScience/openrouteservice/commit/9335c8491609779b200ac676d19d09c4f57f760d) probably introduced the `/ors` to endpoint paths,
which does not reflect the status of our live API and broke the Playground examples as they were now going to e.g.:
`{host}/ors/v2/directions`

**Comment by MichaelsJP** [comment]
- The problem regarding the host is, that the old configuration wasn't right. The host should have all required protocol identifiers, such as `http(s)://`. When I check the swagger, it all looks quite right. A normal client would just append the host and API-endpoints as expected. I guess what happens is that our developer docs prepend the `https://` artificially since it was missing before. We should fix this part in the dev docs.

- The `/ors/` sub path is also right, from the technical perspective. When the servlet container is started with, e.g., tomcat, it always needs this part of the URL. We cut this from our public API in our API gateway, which is not known to the actual running instance. I'm a bit out of ideas regarding this part. It might also be best to do that special part in the developer docs and strip it from URLs.

- The trailing slash though could be removed, at least from the configs. But IMO it's not urgent. Double slashes shouldn't do any harm. It just doesn't look nice.

**Comment by TheGreatRefrigerator** [comment]
Fully agree with 1. 

Regarding the second point, i don't get why it needs the `/ors/` part. Is it really needed from the technical side or is it just generated due to the folder structure? What exactly requires this sub path? Or is it just generated due to the folder structure?
Most apps i know or APIs that we deploy don't have this "application ID prefix" (vroom, pelias, valhalla, ...) but just deploy their endpoints right after `host+port` (API Version also left out, which can be done either outside the app with several instances or inside the app e.g. by using the API Framework.
As far as i know, the usual approach would be to handle multiple apps on the same server not by prefixing all app endpoints of an app with the name of the app _within_ the app, but by mapping each app to a different port and if you want to prefix it with the app name do that in a web server configuration, or some other software (Tyk, Kong, KrakenD..)

- trailing slash: there might be quite some implications so i think we should remove it. Although it might work similar when opening/querying the URL it's not the same. There might be some JS code doing `url.split('/')` where it ends up with an empty element it can't handle or similar unexpected things when handling the URL. (short practical example: type an additional slash e.g. before `issues` in the browser url of this page after you started writing a comment. You will end up at the issue page but your comment is lost, as it is only stored for the URL without double slash)

**Comment by MichaelsJP** [comment]
> Regarding the second point, i don't get why it needs the /ors/ part. Is it really needed from the technical side or is it just generated due to the folder structure? What exactly requires this sub path? Or is it just generated due to the folder structure?

Me neither, and you're absolutely right on this. It was introduced at some point, and we're now stuck with it. If we remove it, it would be like some kind of breaking API change. 
What do you think, should we wait for v8.x or have it in a 7.x release?

> trailing slash

Yup. Let's remove that from the config files. Not a very intrusive change.

**Comment by TheGreatRefrigerator** [comment]
Ah, and i have to revise my statement to the host (from [swagger 2 specs](https://swagger.io/specification/v2/)):

_The host (name or ip) serving the API. This MUST be the host only and does not include the scheme nor sub-paths. It MAY include a port. If the host is not included, the host serving the documentation is to be used (including the port). The host does not support path templating._

as for the scheme for the Swagger 2 specs:

_The transfer protocol of the API. Values MUST be from the list: "http", "https", "ws", "wss". If the schemes is not included, the default scheme to be used is the one used to access the Swagger definition itself._


For the future OpenAPI 3 there won't be this distinction. Instead it has a server object containing the service URL:
https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by TheGreatRefrigerator** [comment]
This is closed with:
https://github.com/GIScience/openrouteservice/pull/1487
and
https://github.com/GIScience/openrouteservice/pull/1504
