### ISSUE TITLE
'area' attribute for isochrone request calculates in geodetic CRS

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#131]
Response with `total_pop` attribute:
`"area":3.5875821964E8,"total_pop":281579,"total_area_km":151.6472`

`total_area_km` is calculate in Mollweide and should be the right result. Please check where `area` is calculated and if it's in PostGIS, project to EPSG:3035 (LAEA) or ESRI: 54009 (Mollweide). For Mollweide (which would make more sense, to be consistent), you'll have to add it to spatial_ref_sys table manually, since it's apparently not an official EPSG code (really weird..). Here is the query for that:
[http://spatialreference.org/ref/esri/54009/postgis/](url)

**Comment by MichaelsJP** [comment]
The area attribute is calculated in `util/GeomUtility.java`. It is used by the borders and isochrone stuff and I wouldnt like to change it due to consistency.
@nilsnolde any idea how to approach that?

**Comment by rabidllama** [comment]
I think we need to sit down and go over this @nilsnolde @MichaelsJP as I am not clear on what the problem is and what possible solutions there are

**Comment by nilsnolde** [comment]
Ok. Basically, my guess is, that the `area` attribute is somehow miscalculated.. If you check the area of [this polygon](https://api.openrouteservice.org/isochrones?api_key=5b3ce3597851110001cf624870cf2f2a58d44c718542b3088221b684&locations=13.413384,52.491143&profile=driving-car&range=900&intervals=900&attributes=area|total_pop) e.g. in QGIS, the `total_area_km` field is more or less correct, in WGS84 or LAEA. That field is being calculated by `attributes=total_pop` within PostGIS. However, the `area` field is off by a factor of 3. 

Why?

**Comment by TimMcCauley** [comment]
The area attribute wasn't transformed properly, fixed with #326
