### ISSUE TITLE
docker-compose.yml in Windows is not working like it used to.

### ISSUE THREAD

**Issue by AndreasAustriaTech** [GIScience/openrouteservice#1331]
#### Here's what I did

---
I cloned a new ORS (git clone https://github.com/GIScience/openrouteservice) into a new folder, in Windows with the command.
Then i composed it (docker compose up)

#### Here's what I got

---
But the Config File would not copy. (ors-config.json)
When i tried to change the map, .pbf File it wont accept the changes
- ./NEW_MAP_2023_01.pbf:/home/ors/ors-core/data/osm_file.pbf

#### Here's what I was expecting

The map should be changed to my new map.
---
#### Here's what I think could be improved
---
It seems like in the newly cloned docker-compose.yml the Compose-Code changed from:
    volumes:
      - ./graphs:/ors-core/data/graphs
      - ./elevation_cache:/ors-core/data/elevation_cache
      - ./logs/ors:/var/log/ors
      - ./logs/tomcat:/usr/local/tomcat/logs
      - ./conf:/ors-conf
      - ./NEW_MAP_2023_01.pbf:/ors-core/data/osm_file.pbf
to
    volumes:
      - ./graphs:/home/ors/ors-core/data/graphs
      - ./elevation_cache:/home/ors/ors-core/data/elevation_cache
      - ./logs/ors:/home/ors/ors-core/logs/ors
      - ./logs/tomcat:/home/ors/tomcat/logs
      - ./conf:/home/ors/ors-conf
      - ./NEW_MAP_2023_01.pbf:/home/ors/ors-core/data/osm_file.pbf

i deleted the "/home/ors" from the compose.yml and it worked again, like it used to.
Maybe remove this part (/home/ors) from the compose.yml to fix the problem .

---
Sorry i am new to the whole GITHUB thing and i hope i descriped a common porblem other people (maybe with windows) have.

Greeting Andreas

**Comment by MichaelsJP** [comment]
Hi @AndreasAustriaTech, thanks for reporting. What docker version of ors are you using in the docker-compose file?

**Comment by MichaelsJP** [comment]
@AndreasAustriaTech 
Please make sure to pull the latest change from a few minutes ago.

When you include the line `- ./NEW_MAP_2023_01.pbf:/home/ors/ors-core/data/osm_file.pbf` you need to meet the two conditions:
1. `NEW_MAP_2023_01.pbf` needs to be in the same folder as the `docker-compose.yml`
2. `BUILD_GRAPHS` has to be set to `True` before executing `docker-compose up -d` again. You can disable it after the container is started.

The `BUILD_GRAPHS` will trigger a removal of the graph and force ors to rebuild the graphs.

In the folder `./conf` you'll find the config file. That can be adjusted for, e.g., `hgv` as another profile. A simple restart of the container should be enough.

**Comment by AndreasAustriaTech** [comment]
Hello Michaels

i can check the Version of Docker and the ORS tomorrow.
I downloaded docker 1 month ago and cloned the latest ors today. 

my "NEW_MAP_2023" is in the same folder as the compose file, and the .conf wont be created.

only when i remove the "/home/ors" from the paths in the compose file (in volumes), it works
but if i use the original compose file it wont work.

Thanks for your help!

**Comment by MichaelsJP** [comment]
@AndreasAustriaTech 
Please make sure to pull the latest change from a few minutes ago.

When you include the line `- ./NEW_MAP_2023_01.pbf:/home/ors/ors-core/data/osm_file.pbf` you need to meet the two conditions:
1. `NEW_MAP_2023_01.pbf` needs to be in the same folder as the `docker-compose.yml`
2. `BUILD_GRAPHS` has to be set to `True` before executing `docker-compose up -d` again. You can disable it after the container is started.

The `BUILD_GRAPHS` will trigger a removal of the graph and force ors to rebuild the graphs.

In the folder `./conf` you'll find the config file. That can be adjusted for, e.g., `hgv` as another profile. A simple restart of the container should be enough.

**Comment by AndreasAustriaTech** [comment]
Hi, i tried the changes you have recommanded.

It still wont load my Map.pbf and it wont create the config file.

But when i delete the part of the path with "/home/ors" it works as intented.
-> The new Map.pbf is loaded and the config file is created
See the Images

My Docker has version 4.17.0
My ORS is Version 6.8.1 build_date ""2023-03-16T13:32:21Z""
![ComposeCloned](https://user-images.githubusercontent.com/125260470/225634810-1b115eec-5f87-494e-87b1-359dedd4dd21.png)
![WinPath](https://user-images.githubusercontent.com/125260470/225634844-f48d50ac-f254-4d18-84b9-3dae61af7a8e.png)
![ComposeEdit](https://user-images.githubusercontent.com/125260470/225634914-a0867627-01ae-4552-9d32-a96bee378119.png)

i hope this helps.

Cheers Andreas !

**Comment by MichaelsJP** [comment]
@AndreasAustriaTech It looks a lot like you're using an old version. We're at 7.x. Please try and run the following commands:
```bash
docker-compose pull
docker-compose up --force-recreate -d && docker-compose logs -ft
```

**Comment by AndreasAustriaTech** [comment]
Thank you very much !
Executing this Commands, solved my problem !
Everything is now working as intended again !

Thanks a lot !

**Comment by MichaelsJP** [comment]
@AndreasAustriaTech You're welcome. Please don't hesitate to reach out to us if you have any more questions.
