### ISSUE TITLE
TD - Core

### ISSUE THREAD

**Issue by MichaelsJP** [GIScience/openrouteservice#1339]
A few adjustments still needed in GH and ors.

#1340 

The API tests for TD access are failing. It's investigated by @aoles.

**Comment by TheGreatRefrigerator** [comment]
- still TODOs and fixme's left
- needs to be rebased on master
- then ready for PR
- needs 2 PRs
- [x]  [graphhopper](https://github.com/GIScience/graphhopper/pull/63)
- [ ] [ors (TODO)]()

**Comment by MichaelsJP** [comment]
connected to https://github.com/GIScience/graphhopper/pull/63

**Comment by TheGreatRefrigerator** [comment]
- proper implementation still needed
- might effect object size in memory
- prob. 1 or 2 days left
- still some issues with running tests (when running all tests)
