### ISSUE TITLE
access:destination - remove GH penalty

### ISSUE THREAD

**Issue by MichaelsJP** [GIScience/openrouteservice#1344]
currently a double penalty both in GH and ORS is done.
Move to previous impl. to reduce differences in results.

- [ ] test locally
- [ ] check output visually
- [ ] merge if ok

touches #1061

**Comment by TheGreatRefrigerator** [comment]
- removing the GH impl. doesn't help but result got worse
- derives from old graphhopper not taking into account hgmi access tags
- isochrone discrepancies probably not related to `access:destination`

-> not ok
