### ISSUE TITLE
getDirection not work 

### ISSUE THREAD

**Issue by petrot** [GIScience/openrouteservice#135]
For a dew days I got the following error message when trying to get direction to a point:

UPD: the error caused by the "elevation=true" parameter:

working:
`https://api.openrouteservice.org/directions?api_key=<MY_EXISTING_API_KEY>&
profile=driving-car&preference=recommended&language=hu&geometry=true&geometry_format=geojson&coordinates=20.1810948,46.269903799999994%7C27.867883,43.229733%7C20.001267,45.972317&options=%7B%22avoid_features%22:%22ferries%22%7D`

not working:
`https://api.openrouteservice.org/directions?api_key=<MY_EXISTING_API_KEY>&elevation=true&
profile=driving-car&preference=recommended&language=hu&geometry=true&geometry_format=geojson&coordinates=20.1810948,46.269903799999994%7C27.867883,43.229733%7C20.001267,45.972317&options=%7B%22avoid_features%22:%22ferries%22%7D
`

```
getDirection error:{  
   "headers":{  
      "normalizedNames":{  

      },
      "lazyUpdate":null
   },
   "status":500,
   "statusText":"OK",
   "url":"https://api.openrouteservice.org/directions?api_key=<MY_EXISTING_API_KEY>&profile=driving-car&preference=recommended&language=hu&geometry=true&geometry_format=geojson&elevation=true&coordinates=20.1810655,46.2699894%7C27.867883,43.229733&options=%7B%22avoid_features%22:%ferries%22%7D",
   "ok":false,
   "name":"HttpErrorResponse",
   "message":"Http failure response for https://api.openrouteservice.org/directions?api_key=58d904a497c67e00015b45fc26ae38f9f5014e0a40c8e2c9cd1ed45a&profile=driving-car&preference=recommended&language=hu&geometry=true&geometry_format=geojson&elevation=true&coordinates=20.1810655,46.2699894%7C27.867883,43.229733&options=%7B%22avoid_features%22:%ferries%22%7D: 500 OK",
   "error":{  
      "error":{  
         "code":2099,
         "message":"Unable to compute a route"
      },
      "info":{  
         "engine":{  
            "version":"4.5.0",
            "build_date":"2018-02-27T14:22:36Z"
         },
         "timestamp":1519894079005
      }
   }
}
```

**Comment by TimMcCauley** [comment]
@petrot, currently elevation is disabled, will be enabled again within the next week.
