### ISSUE TITLE
Export as GeoJSON geometry incorrect

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice#136]
When exporting the whole response as GeoJSON, the coordinates are being truncated to 4 decimal places and so the geometry is innaccurate. 

Below is normal route using JSON response
![screenshot from 2018-03-01 11-27-18](https://user-images.githubusercontent.com/7126643/36839929-ae3f76c4-1d43-11e8-8154-659b1fee14f2.png)

and this is when using a full geojson response
![screenshot from 2018-03-01 11-27-58](https://user-images.githubusercontent.com/7126643/36839930-ae65ca54-1d43-11e8-8995-2d8eec9bada6.png)

**Comment by TimMcCauley** [comment]
Please use 6 decimals, this will suffice.
