### ISSUE TITLE
Flakey test due to conditional infos not being persisted

### ISSUE THREAD

**Issue by koebi** [GIScience/openrouteservice#1363]
Both `testConditionalAccess` and `testConditionalSpeed` will work if the graphs have been built by the running instance, but will not work if the instance is stopped and then started again.

This is probably related to no conditional infos being persisted and reloaded between restarts. 

Persisting infos should probably  be fixed in graphhopper, see the linked issue.

**Comment by aoles** [comment]
Fixed in https://github.com/GIScience/graphhopper/pull/62.
