### ISSUE TITLE
Isochrones: add option to adjust polygon smoothness

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#137]
Make the alpha factor for isochrone polygonization adjustable with a request parameter, either via smoothness categories or numerically. I prefer categories, alpha factors are not really intuitive to set numerically.

Or alternatively, restore the old behavior to return proper alpha shapes (should still be in the code base) and either let clients deal with simplification or add boolean `simplify` parameter.

**Comment by stevevance** [comment]
Thanks for listening, @nilsnolde 
For reference, (former) [Mapzen's isochrone service](https://mapzen.com/documentation/mobility/isochrone/api-reference/#inputs-of-the-isochrone-service), a service I used to use because it incorporated transit routes, had a `denoise` parameter:

> A floating point value from 0 to 1 (default of 1) which can be used to remove smaller contours. A value of 1 will only return the largest contour for a given time value. A value of 0.5 drops any contours that are less than half the area of the largest contour in the set of contours for that same time value.

**Comment by TimMcCauley** [comment]
@stevevance roger, thanks for the information, we'll definitely look into this! Stay tuned.

**Comment by rabidllama** [comment]
I have started looking into the code for this and it seems like it will be quite a large job as a large portion of the geometry generation will need to be rewritten as the main issue lies in ensuring that the different polygons line up at borders
