### ISSUE TITLE
Modularize ORS / Multiproject

### ISSUE THREAD

**Issue by MichaelsJP** [GIScience/openrouteservice#1381]
A potential merge of GH would be easier if a few things like a multi project schema would already be in place.
This discussion could be broadened regarding other restructurings. 

- [ ] Switch to Gradle first? #1262 
- [ ] Modularize?
   - [ ] Separate API and core code?
   - [ ] Make modules part of a multi project?
- [ ] ?

**Comment by jlink** [comment]
Even more important than Maven vs Gradle is the question of how to modularize. There's a few possibilities worthwhile discussing IMO.

**Comment by MichaelsJP** [comment]
Yup. One thing @takb and I discussed earlier was the separation of api/core code into separate modules. Probably a good first start, but should definitely be discussed before and also assessed in terms of a long-term perspective.

**Comment by TheGreatRefrigerator** [comment]
-> will be tackled in floating teams stage

**Comment by koebi** [comment]
Current status is in floating-teams-modularization branch

**Comment by koebi** [comment]
open tasks move to https://github.com/GIScience/openrouteservice/pull/1439

**Comment by jlink** [comment]
Being worked on in https://github.com/GIScience/openrouteservice/pull/1439
