### ISSUE TITLE
directions API does not return correct duration and distance summary

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#139]
Using 'geojson' format, I can't find the summary for `distance` and `duration` anymore, e.g.:
```bash
https://api.openrouteservice.org/directions?coordinates=13.43778%2C52.493555%7C13.419729%2C52.491642%7C13.416129%2C52.491172%7C13.413301%2C52.491394%7C13.391826%2C52.488636%7C13.390423%2C52.487928%7C13.383773%2C52.495045%7C13.382791%2C52.492216%7C13.384248%2C52.493236%7C13.38642%2C52.490935%7C13.387044%2C52.490386%7C13.388747%2C52.491909%7C13.397891%2C52.493024%7C13.400091%2C52.494595%7C13.419486%2C52.499261%7C13.418995%2C52.499973%7C13.420063%2C52.502109%7C13.42019%2C52.502787%7C13.43993%2C52.499526%7C13.440404%2C52.500884%7C13.429866%2C52.50302%7C13.426581%2C52.499713%7C13.423454%2C52.500546%7C13.426142%2C52.496612%7C13.429699%2C52.497941%7C13.43778%2C52.493555&format=geojson&geometry=true&optimized=true&profile=driving-car&api_key=key
```

The first object in `segments` says 
```{"distance":2029.3,"duration":240.4,"steps":...```

When summing up all individual segments, it's really a duration of 2471.800 secs.

Please investigate and fix asap! Could be related to #138..

**Comment by MichaelsJP** [comment]
> Using 'geojson' format, I can't find the summary for distance and duration anymore, e.g.:
> 
> https://api.openrouteservice.org/directions?coordinates=13.43778%2C52.493555%7C13.419729%2C52.491642%7C13.416129%2C52.491172%7C13.413301%2C52.491394%7C13.391826%2C52.488636%7C13.390423%2C52.487928%7C13.383773%2C52.495045%7C13.382791%2C52.492216%7C13.384248%2C52.493236%7C13.38642%2C52.490935%7C13.387044%2C52.490386%7C13.388747%2C52.491909%7C13.397891%2C52.493024%7C13.400091%2C52.494595%7C13.419486%2C52.499261%7C13.418995%2C52.499973%7C13.420063%2C52.502109%7C13.42019%2C52.502787%7C13.43993%2C52.499526%7C13.440404%2C52.500884%7C13.429866%2C52.50302%7C13.426581%2C52.499713%7C13.423454%2C52.500546%7C13.426142%2C52.496612%7C13.429699%2C52.497941%7C13.43778%2C52.493555&format=geojson&geometry=true&optimized=true&profile=driving-car&api_key=key
> 
> The first object in segments says
> {"distance":2029.3,"duration":240.4,"steps":...
> 
> When summing up all individual segments, it's really a duration of 2471.800 secs.
> 
> Please investigate and fix asap! Could be related to #138..

`{"distance":2029.3,"duration":240.4...` in `segments` always refers to the next step. It's not the overall summary.
In fact the overall summary was missing. I'm adding it now. Thx for the note!
