### ISSUE TITLE
High graph building/response time on Apple Silicon Processors

### ISSUE THREAD

**Issue by rolkool** [GIScience/openrouteservice#1391]
While trying to start custom ORS docker image (built on top of the public image), on Silicon M1 Macbook Pro, we face too long graph building times for a 2GB osm.pbf file.

The same process on an EC2 ubuntu instance, with even lower specs, takes about 10 minutes, using the same Xms and Xmx heap size (`-Xms5g -Xmx7g` for 2GB osm.pbf file)

And even when the graphs are finally built and the service is up and running, the reponse times are higher than on the ubuntu EC2.
Given this difference in performance, we suspect that the delay is caused by docker engine running in compatibility/emulation mode on the macbook pro, as the ORS images are built only for `linux/amd64` architecture.

---

A solution to this, is updating ORS' CI pipeline to build and publish images for `linux/arm64` too,  apart from `linux/amd64` architecture only.
This will remove the need to run the images on Silicon processors in compatibility/emulation mode.

---

It is easy to change this by updating the following two variables on CI:

* [BUILD_PLATFORMS](https://github.com/GIScience/openrouteservice/blob/master/.github/workflows/build-and-publish.yml#L12)

* [DOCKER_PLATFORMS](https://github.com/GIScience/openrouteservice/blob/master/.github/workflows/publish-tagged-release.yml#L47)

from `linux/amd64` to `linux/amd64,linux/arm64`

The final image will be compatible with both platforms, with the correct version automatically pulled

**Comment by rolkool** [comment]
@takb I see you moved it to ToDo. 
I'm trying to imlement it myself, following the contribution guide.

However I see that I'm not allowed to create a branch on this repo, although the contribution guide does not mention anything regarding fork requirement.
Should someone give me access to create branch?

**Comment by MichaelsJP** [comment]
@rolkool Thanks for opening this issue. It would be great to have `linux/arm64` as another build platform for the images, and a PR from you is very much welcome. 

The best would be if you create a fork with a branch and then open a PR from that branch to origin/master. Would that work for you?

**Comment by rolkool** [comment]
@MichaelsJP Sure, here it is: https://github.com/GIScience/openrouteservice/pull/1402

**Comment by hbilgrami1** [comment]
Hi, I am also experiencing this issue, where my linux machine can build the graph for the US relatively fast, but my M2 Mac takes a very long time. Is there a timeline for this release?
Thanks!

**Comment by MichaelsJP** [comment]
@hbilgrami1 Not yet. You can use [nightly](https://hub.docker.com/layers/openrouteservice/openrouteservice/nightly/images/sha256-120e89834afea775fd6bd3d149ff39e96d27b169a3e9511c827a5be8e0b5d51c?context=explore) if you want to have it now.

**Comment by hbilgrami1** [comment]
@MichaelsJP thanks for this! I am getting an issue when I try to pull the nightly:
`docker pull openrouteservice/openrouteservice:nightly
nightly: Pulling from openrouteservice/openrouteservice
no matching manifest for linux/arm64/v8 in the manifest list entries
`

**Comment by joeldebont** [comment]
> 

I have the same problem when pulling the nightly build on M2 Macbook. Is there a way to pull it anyway?
