### ISSUE TITLE
create test data set for Here traffic

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#1393]
To be able to compare outputs of results with traffic data with normal ones, we need a small test data set for heidelberg.
Probably some bridges with high factor (1 m/s) to verify usage of the traffic data.

**Comment by TheGreatRefrigerator** [comment]
-> put minimal test dataset to traffic reintegration branch

**Comment by rabidllama** [comment]
Data added to the reintegrate-traffic branch in commit 9ce7213
