### ISSUE TITLE
Add .editorconfig to openrouteservice

### ISSUE THREAD

**Issue by jlink** [GIScience/openrouteservice#1400]
.editorconfig is supported by all (or most) editors including IntelliJ

Cover:
- Indent: 4 spaces
- Java imports
- what else?

**Comment by takb** [comment]
introduced by [a2810a12aca328856377377e430d3def48b9b672](https://github.com/GIScience/openrouteservice/commit/a2810a12aca328856377377e430d3def48b9b672)
