### ISSUE TITLE
Here routing tests using mock data from #1393

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#1403]
- for now API tests are needed

**Comment by aoles** [comment]
Map matching is not working so it needs to be fixed first, see https://github.com/GIScience/openrouteservice/pull/1430.

**Comment by aoles** [comment]
Speed patterns of the traffic test dataset are illustrated in the graph below. On weekdays the speed drops down as low as 5km/h between 08:45-09:30 and 17:30-18:15.
![image](https://github.com/GIScience/openrouteservice/assets/6545356/cb9d63dc-caac-4c78-8694-f906b8fe32c6)

Affected streets are basically the two bridges across Neckar. The corresponding [GeoJSON](https://github.com/GIScience/openrouteservice/files/11463391/Streets.geojson.txt) can be visualized e.g. in [geojson.tools](https://geojson.tools/).
