### ISSUE TITLE
Integrate API documentation 

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/openrouteservice#141]
@rabidllama @MichaelsJP @HendrikLeuschner @TheGreatRefrigerator can you please communicate and integrate the api docs for matrix, isochrones and directions to the backend. @TheGreatRefrigerator can you please check how we can merge different ymls from arbitrary repositories in apiary?

**Comment by rabidllama** [comment]
I think this will need to go on hold for a while until we have got the GH stuff sorted

**Comment by TimMcCauley** [comment]
Will be handled in #233
