### ISSUE TITLE
Maneuver type description for icon mapping for direction API

### ISSUE THREAD

**Issue by Koxx3** [GIScience/openrouteservice#1419]
Hello,
where can I find a description of the different maneuvers for the direction API ?
The goal is to be able to map icons on those maneuver types.
Regards,
F.

**Comment by koebi** [comment]
Is [this](https://giscience.github.io/openrouteservice/documentation/Instruction-Types.html) what you're looking for?

**Comment by Koxx3** [comment]
Yes, perfect ! thanks a lot
