### ISSUE TITLE
Broken link on "services" page

### ISSUE THREAD

**Issue by RainerBielefeld** [GIScience/openrouteservice#1429]
STR:
1. Visit [services](https://openrouteservice.org/services/) page 
2. Below heading "Up to 2.500 distance pairs" click on "[developers](https://openrouteservice.org/developers)"
   » Expected: info concerning devs
    Actual: "Page Not Found" 😥

**Comment by TheGreatRefrigerator** [comment]
Thx for reporting.
This is fixed now
