### ISSUE TITLE
Evaluate correctness of map-matching algorithm

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#1435]
Changes to the code of map matching algorithm over the past few years might have introduced some subtle bugs to the original implementation. For example, consider the following two places.

1. https://github.com/GIScience/openrouteservice/blob/40753affbf2055d908e59efe7bb5f46b3a2049e2/openrouteservice/src/main/java/org/heigit/ors/mapmatching/hmm/HiddenMarkovMapMatcher.java#L264-L267 `distances` array contains precomputed distances between consecutive points which `xi` and `xj` not necessarily are.

2. https://github.com/GIScience/openrouteservice/blob/40753affbf2055d908e59efe7bb5f46b3a2049e2/openrouteservice/src/main/java/org/heigit/ors/mapmatching/hmm/HiddenMarkovMapMatcher.java#L397-L403

ORS map matching is based on the idea presented in the paper _Hidden Markov Map Matching Through Noise and Sparseness_ by Paul Newson and John Krumm. The description of the algorithm can be found [here](https://www.microsoft.com/en-us/research/publication/hidden-markov-map-matching-noise-sparseness/), see presentation slides.

**Comment by MichaelsJP** [comment]
@aoles inline to-dos are ok, but please collect the relevant parts in here. Just hard links to the files or rows in files that contain your todos

**Comment by aoles** [comment]
There have been identified some serious issues with the implementation of the ORS map matcher. Therefore, rather than fixing it it the decision was to switch to using the more reliable GraphHopper map matching endpoint.
