### ISSUE TITLE
Add support for more than 4 columns in the csv file in `CsvGraphStorageBuilder`

### ISSUE THREAD

**Issue by redfrexx** [GIScience/openrouteservice#1436]
Requests with `extra_info": ["csv"]` fail because the csv file contains more than 4 columns. Can we add support for more than 4 columns?

**Comment by MichaelsJP** [comment]
@redfrexx Please elaborate a bit more in detail why this change is needed, for documentation purposes. Thanks :)

**Comment by redfrexx** [comment]
For the HEAL routing client we provide 5 points in time: now and 4 timestamps of a typical heat day (10am, 1 pm, 4pm and 7pm). So that makes 5 columns in the csv file. 

Ideally and if possible with reasonable effort, it would be good if even up to 8 or 10 columns could be supported to conduct further route analyses, e.g. provide heat indices for several months to see how the detours evolve across the year compared to the fastest route.

**Comment by sfendrich** [comment]
I have looked through the code and didn't find an indication that this limit is in place. Can you provide some details that show that this limit exists?

**Comment by redfrexx** [comment]
Request work, but when adding `extra_info: ["csv"]`  to the request, I get the error:

```
ERROR [routing.RoutingProfile] - java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 18 out of bounds for byte[4]
```
