### ISSUE TITLE
Return specific status code when route not found

### ISSUE THREAD

**Issue by kontrollanten** [GIScience/openrouteservice#144]
**Current behavior:**
When a route isn't found, a 500 HTTP status is returned with the following response
```
{
  "error":{
    "code":2099,
    "message":"Connection between locations not found"
  },
  "info":{
    "engine":{
      "version":"4.5.0",
      "build_date":"2018-02-27T14:22:36Z"
    },
    "timestamp":1520362248836
  }
}
```

**Expected behavior**
A 404 HTTP status code, or eventually an unique error code (not 2099, which is [Unknown error](https://openrouteservice.org/documentation/#/reference/directions/directions/directions-service)).

According to this test case, it seems that it's by design:
https://github.com/GIScience/openrouteservice/blob/e703b6c9a0f1f7528a157450ce6ff26c0f4e6b2a/openrouteservice-api-tests/src/test/java/heigit/ors/services/routing/ResultTest.java#L722

Is there any reason it is implemented like this?

Thanks!

**Comment by rabidllama** [comment]
Code has been updated so that a 2009 internal error code is returned with a 404 http response
