### ISSUE TITLE
Route calculation failure (2) - ref issue 89

### ISSUE THREAD

**Issue by eliboni** [GIScience/openrouteservice#145]
https://maps.openrouteservice.org/directions?n1=35.793398&n2=51.017831&n3=17&a=35.810244,51.012086,35.78983,51.018147&b=0&c=0&k1=en-US&k2=km

see https://github.com/GIScience/openrouteservice/issues/89 - the issue on the roundabout seem solved but the link above fails. What is weird if I try to narrow down the issue the problem disappears.

**Comment by rabidllama** [comment]
This should be fixed now in the last minor release made on 26/3/2018

@eliboni - can you double check and make sure that it works and if so I will close the issue

**Comment by eliboni** [comment]
confirmed. pls. you can close. Many thanks!
