### ISSUE TITLE
Redo github templates

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#1456]
#### Here's what I did

opening an issue

---
#### Here's what I got

complex markdown and html code

---
#### Here's what I was expecting

a github issue template (e.g. text inputs/check boxes/dropdowns and more)

---
#### Here's what I think could be improved

use multiple templates to choose from depending on what its about (e.g. automatically adds labels like docs.

See e.g. https://github.com/chartjs/Chart.js/issues/new/choose

Should use the latest synatx though:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

Could do for issue and PR templates.

**Comment by TheGreatRefrigerator** [comment]
those can also be configured Organization wide, which might be helpful.

**Comment by MichaelsJP** [comment]
@TheGreatRefrigerator Yup. Good idea. Let's add that to ors as well.

**Comment by MichaelsJP** [comment]
Yes good idea. Can you open a quick PR and add a basic template?
