### ISSUE TITLE
Swapped lat/lng in GeoJSON output

### ISSUE THREAD

**Issue by guestisp** [GIScience/openrouteservice#146]
GeoJSON output is not RFC 7946 compliant.

GeoJSON needs coordinates to be stored as lng,lat but openrouteservice is making GeoJSON with lat,lng

**Comment by TimMcCauley** [comment]
Hi, this isn’t true, ors responds in lng lat, can you please double check?

**Comment by guestisp** [comment]
Did you change this recently? Because i've checked our geoJson (created a couple of months ago) and are swapped.

**Comment by nilsnolde** [comment]
We didn’t offer geoJson a couple of months ago. And no, it’s always been that way in the raw Json. It’s only google who does lat lng, everyone else is sensible and uses x y.

**Comment by nilsnolde** [comment]
I recommend checking your input.

**Comment by guestisp** [comment]
Sorry, I'm talking about isochone output

**Comment by TimMcCauley** [comment]
This is also correct, a polygon in Berlin:

```{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[13.266049,52.51077],[13.266305,52.50718],[13.273504,52.501778],[13.275819,52.49902],[13.284066,52.492197],[13.288964,52.487219],[13.291555,52.482162],[13.29246,52.481569],[13.300909,52.476103],[13.302521,52.472884],[13.30442,52.470886],[13.30802,52.470807],[13.315275,52.468395],[13.31619,52.468008],[13.319743,52.467014],[13.31921,52.456394],[13.319449,52.452931],[13.319935,52.452868],[13.320206,52.452887],[13.320597,52.452979]...```
