### ISSUE TITLE
Documentation for running with docker wrong

### ISSUE THREAD

**Issue by danceb** [GIScience/openrouteservice#1466]
It seems that the mentioned paths for folder mountings are wrong in:
https://giscience.github.io/openrouteservice/installation/Running-with-Docker.html

There is often mentioned `ors-core` in the path:
  -v $PWD/graphs:/home/ors/ors-core/data/graphs \
  -v $PWD/elevation_cache:/home/ors/ors-core/data/elevation_cache \
  -v $PWD/conf:/home/ors/ors-conf \
  -v $PWD/logs/ors:/home/ors/ors-core/logs/ors \
  -v $PWD/logs/tomcat:/home/ors/tomcat/logs \
  #-v $PWD/your_osm.pbf:/home/ors/ors-core/data/osm_file.pbf \

But the graph building only works, if I am mounting the folders to
  -v $PWD/graphs:/home/ors/data/graphs \
  -v $PWD/elevation_cache:/home/ors/data/elevation_cache \
  #-v $PWD/your_osm.pbf:/home/ors/data/osm_file.pbf \

I am using v7.0.1.

**Comment by MichaelsJP** [comment]
@danceb Thanks for opening this issue. Could you please provide some more input into what doesn't work when you use the provided documentation?

For me, it seems to work nicely on a fresh setup.

**Comment by danceb** [comment]
Hi @MichaelsJP, thanks for your reply! Ok, so maybe there is something else not as aspected in my configuration. I think there are some other issues here...

The first thing I got already:
If the path, to which the osm file is mounted, is changed, it has to be updates as well in the ors-config.json, like:
```
"routing": {
  "sources": [
    "ors-core/data/osm_file.pbf"
  ],
```
The path in the sample config file points on `"src/main/files/heidelberg.osm.gz"`, so I didn't get this, my fault.
With this, the graphs are generated. 

But if I am mounting the local graphs folder to `/home/ors/ors-core/data/graphs` as mentioned in the documentation, the graphs are still generated within `/home/ors/data/graphs` in the container instead.

So I have to mount the local folder to `/home/ors/data/graphs` that they are showing up there as well.

So where is this come from?

**Comment by takb** [comment]
HI @danceb , the path to where the generated graph files are stored is set by the parameter `ors.services.routing.profiles.default_params.graphs_root_path`. We are aware that the configuration options are sometimes hard to find, and we are in the process of restructuring the configuration from the ground up. 
The documentation needs reworking as you have pointed out correctly, but this is also already in the pipeline and should be merged sometime soon.
Thank you for reporting, for further questions we have a forum where we are happy to give config support as well: https://ask.openrouteservice.org/

**Comment by danceb** [comment]
Ah, there it is! Thanks! 
Actually the configs are very clear to understand und findable, if someone (me) tries to find it either ...

So, to understand it correctly: What is the correct behavior since ors 6.8.2? 
v1: The folder paths have to be with `ors-core` like mentioned in the docs and the paths in the `ors-config.json` have to be updated like that as well, or
v2: It does not matter, if with `ors-core` or without, as long as they are the same in mounting and the config?

**Comment by MichaelsJP** [comment]
> v1: The folder paths have to be with ors-core like mentioned in the docs and the paths in the ors-config.json have to be updated like that as well, or

No, they don't need to be, but should. This is just the location where the default graphs are stored. It's a very complex thing with having Maven with a war-File deployment in a Dockerfile and still having a non-root user in the docker execution. That's why it looks so weird with the paths. Everything needs to be accessible by the user. If you start storing things outside the users' home folder, such as `/`, there is a high chance Maven will mess up the access rights. If you're not concerned around user rights in a docker container, just run it with `0:0` or `1000:1000`. Will save you time!

> v2: It does not matter, if with ors-core or without, as long as they are the same in mounting and the config?

As said above. This approach should work if you give the docker user  `0:0` or `1000:1000` rights. 

Please remember to do a `docker pull openrouteservice/openrouteservice:latest` before starting a container. `latest` doesn't update itself.

**Comment by danceb** [comment]
Ok, thanks again! So the best variation is to go with v1, to use the ors-core folders and adjust the paths in the ors-config respectivly. I did this, and the graphs are generated as they should and the routing service works well!

Sorry for my confusion! In the future I will telling my questions in the forum :-)
