### ISSUE TITLE
Fail to build some isochrone on some profile from a point

### ISSUE THREAD

**Issue by adrian-azad** [GIScience/openrouteservice#1491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Where did you encounter this issue?

live API, self-hosted instance

### Request URL

https://api.openrouteservice.org/v2/isochrones/cycling-regular

### POST Request Body

```JSON
{"locations":[[2.873519,48.957348]],"range":[1000]}
```

### Response

<details><summary>Response</summary>

```JSON
{"error":{"code":3099,"message":"Unable to build an isochrone map."},"info":{"engine":{"build_date":"2023-07-09T01:31:50Z","version":"7.1.0"},"timestamp":1689023575609}}
```
</details>

### Current behavior

An isochrone isn't build, it's the case for profiles `cycling-regular` and `foot-walking` at least, while `driving-car` is working fine.

This happen on multiple points within a train station, [2.873519,48.957348] being only one exemple.

While i'm unsure if maybe the `driving-car` profile have something like "start from the nerest drivable road", i'm sure it's a bit weird in the present case to be able to build a `driving-car` profile and not an `foot-walking` at least. 

This does not look like the issue when some node/way/relation are missing in the data (i assume) and we're trap in the station like with [1.98569,46.948807]

### Expected behavior

An isochrone is returned for profiles `cycling-regular` and `foot-walking`

### Openrouteservice Version

7.1.0

### Build date

2023-07-09T01:31:50Z

**Comment by MichaelsJP** [comment]
@adrian-azad Thanks for reporting. Indeed, weird. [Routes with foot-walking](https://maps.openrouteservice.org/#/directions/2.873519,48.957348/Place%20de%20la%20Gare,Meaux,France/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,38,0,232,0,224,29,128,102,1,88,4,96,19,128,26,0,89,140,54,202,46,96,110,34,202,162,227,106,215,192,13,150,181,0,12,141,25,49,102,212,169,106,141,170,151,22,63,35,16,244,64,64,0,234,158,4,68,216,114,128,5,229,0,45,174,106,196,180,238,129,0,25,188,0,54,233,112,132,117,21,0,90,0,238,200,46,0,214,72,0,230,154,32,246,232,142,232,208,232,136,96,238,120,113,144,22,22,241,176,232,176,32,0,190,57,64,0,0) can be calculated nicely, just not isochrones.

Weird enough, [another example](https://maps.openrouteservice.org/#/reach/Lyc%C3%A9e%20g%C3%A9n%C3%A9ral%20et%20technologique%20Henri%20Moissan,Meaux,France/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,38,0,232,0,224,29,128,86,1,24,4,224,13,150,129,153,205,63,7,44,160,22,114,1,160,248,195,171,150,169,92,177,54,99,75,20,17,196,55,16,16,0,58,167,129,17,54,28,160,1,121,64,11,107,146,177,57,11,160,64,6,111,0,13,186,92,33,77,69,64,22,128,59,178,11,1,172,144,7,53,146,24,250,83,232,208,232,136,96,214,120,65,144,58,58,193,176,232,176,62,208,200,136,158,232,0,250,168,0,158,10,97,32,8,152,168,73,161,9,73,41,184,0,218,148,0,12,213,0,186,114,72,24,208,0,110,174,250,213,149,0,190,29,64,0,0) without train tracks and isochrones it works. The center point is correctly snapped to an even further away road.

We'll investigate that.

**Comment by hulsiejames** [comment]
In addition to the above, and likely related, I have a couple of further examples I expect should work, as there is no _confusing_ infrastructure, such as a train station, and the very close proximity to a useable network without access restrictions.

**ors/v2/status**
```
{"languages":["cs","cs-cz","de","de-de","en","en-us","eo","eo-eo","es","es-es","fr","fr-fr","gr","gr-gr","he","he-il","hu","hu-hu","id","id-id","it","it-it","ja","ja-jp","ne","ne-np","nl","nl-nl","pl","pl-pl","pt","pt-pt","ro","ro-ro","ru","ru-ru","tr","tr-tr","zh","zh-cn"],"engine":{"build_date":"2023-06-13T12:36:00Z","version":"7.1.0"},"profiles":{"profile 1":{"storages":{"HillIndex":{"gh_profile":"pedestrian_ors_fastest"},"WayCategory":{"gh_profile":"pedestrian_ors_fastest"},"WaySurfaceType":{"gh_profile":"pedestrian_ors_fastest"},"TrailDifficulty":{"gh_profile":"pedestrian_ors_fastest"}},"profiles":"foot-walking","creation_date":"","limits":{"maximum_distance":100000,"maximum_waypoints":50,"maximum_distance_dynamic_weights":100000,"maximum_distance_avoid_areas":100000}}},"services":["routing","isochrones","matrix","mapmatching"]}
```

Specifically: 
   - Colinsbrough grove: -1.374681, 53.789393
   - Wesley close:   -0.599108, 53.656714

<img width="568" alt="not_so_much" src="https://github.com/GIScience/openrouteservice/assets/58815827/5d86d826-c242-4df1-a91e-3aefc38b02c8">

Both result in failed API calls: 
<img width="393" alt="colin_new_api" src="https://github.com/GIScience/openrouteservice/assets/58815827/dc36dec2-535a-4beb-9e63-15786c52e7cb">
<img width="373" alt="final_api" src="https://github.com/GIScience/openrouteservice/assets/58815827/e6ba5f78-8453-45f2-bf0a-1e64ad978065">

**Returned failure**
```
{"error":{"code":3099,"message":"Unable to build an isochrone map."},"info":{"engine":{"build_date":"2023-06-13T12:36:00Z","version":"7.1.0"},"timestamp":1691502194318}}
```


Though both Colinsbrough grove and Wesley close centroids are technically not on a network, I am assuming that both should snap to the nearest network and successfully build the Isochrone. 

As with the example above, trying the same coordinates above with car-driving, the snapping occurs exactly as I expect it would for foot-walking, and the isochrone is built:
(snapped locaion circled in Blue)
<img width="314" alt="snapped_colin_car" src="https://github.com/GIScience/openrouteservice/assets/58815827/5b457952-ea8c-4d70-89e5-a15f54c561c5">
<img width="401" alt="wesley_snapped_car" src="https://github.com/GIScience/openrouteservice/assets/58815827/e910e190-0527-401f-9a44-796c3897139e">



Do foot-walking isochrones not currently attempt to snap to the nearest location and build the isochrone from the passed location?

**Comment by sfendrich** [comment]
Thanks for reporting this issue! Seems to be fixed in PR https://github.com/GIScience/openrouteservice/pull/1566.
