### ISSUE TITLE
Docker container does NOT build graphs with my_osm.pbf.

### ISSUE THREAD

**Issue by junpei-n** [GIScience/openrouteservice#1494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

_Though this issue may be related to closed issue #1466 , I opened becuase I could not find the solution about docker image itself. I hope the latest docker image fixed soon._

I ran a Docker container with my_osm.pbf using `-v` syntax, following [Running with Docker](https://giscience.github.io/openrouteservice/installation/Running-with-Docker.html#running-with-docker), and changed to use the line
```dockerfile
  -v $PWD/your_osm.pbf:/home/ors/ors-core/data/osm_file.pbf \
```
Here, the container could not find "/home/ors/ors-core/data/osm_file.pbf", and not to build graphs.

### Proposed solution

I built a new Docker image, and it could resolve the problem (at least for me). The Dockerfile is
```
FROM openrouteservice/openrouteservice:latest
WORKDIR /home/ors/ors-core  # similar to <=v6.8.1, `WORKDIR /ors-core`
ENTRYPOINT ["/home/ors/ors-core/docker-entrypoint.sh"]
CMD ["/home/ors"]
```
`WORKDIR` was only changed.

#### Docker Image Information
openrouteservice/openrouteservice:v7.1.0
Digest: sha256:8a663e53fd6e5803b139822d7524b14d138b9ee0defed5374b2d8e01290aa02f

---
I didn't check the all, e.g. docker-entrypoint.sh of <=v6.8.1, so it is possible this is a bad solution. If it is right and safe for current and future images, I would like it fixed.

BTW, I appreciate your great works. Thank you.

**Comment by MichaelsJP** [comment]
@junpei-n Thanks for your issue. We're aware of the difficulties with our docker container and are working on two solutions.

A lot of it stems from having to use tomcat + war in a docker container. User rights etc. is just a pain with that combination.
We're moving soon to a Docker + Jar solution with native spring-boot support, and are working on a configuration file overhaul that will make most of the problems redundant.

I tried the docker example and it worked for me. It could have various reasons for not working. 
For now, I'd say stay with your solution if it works and wait a few weeks until our current effort is done.

Greetings!

**Comment by junpei-n** [comment]
@MichaelsJP Thank you for your quick response. I got reasons for the docker image not working. I'd hope your effort done well.
Thanks!
