### ISSUE TITLE
Latest openrouteservice image throwing java.net.SocketTimeoutException: Connect timed out error

### ISSUE THREAD

**Issue by debasmitadasgupta** [GIScience/openrouteservice#1495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

 12 Jul 11:09:34 INFO [ors.Application] - Starting Application v7.1.0 using Java 17.0.7 on 47f4236b049d with PID 1 (/home/ors/tomcat/webapps/ors/WEB-INF/classes started by root in /home/ors)
ors-app    | 12 Jul 11:09:35 DEBUG [ors.Application] - Running with Spring Boot v2.7.12, Spring v5.3.27
ors-app    | 12 Jul 11:09:35 INFO [ors.Application] - No active profile set, falling back to 1 default profile: "default"
ors-app    | 12 Jul 11:09:40 INFO [ors.Application] - Started Application in 6.205 seconds (JVM running for 12.418)
ors-app    | 12 Jul 11:09:40 INFO [logging.LoggingUtility] - Logging configuration loaded from DEBUG_LOGGING.json, logging to file /home/ors/ors-core/logs/ors/ors-logs.log
ors-app    | 12 Jul 11:09:40 INFO [routing.RoutingProfileManager] -  Total - 1024 MB, Free - 655.91 MB, Max: 2 GB, Used - 368.09 MB
ors-app    | 12 Jul 11:09:40 INFO [routing.RoutingProfileManager] -       
ors-app    | 12 Jul 11:09:40 INFO [routing.RoutingProfileManager] - ====> Initializing profiles from '/home/ors/ors-core/data/osm_file.pbf' (1 threads) ...
ors-app    | 12 Jul 11:09:40 INFO [routing.RoutingProfileManager] - 1 tasks submitted.
ors-app    | 12 Jul 11:09:40 INFO [routing.RoutingProfile] - [1] Profiles: 'driving-car', location: '/home/ors/ors-core/data/graphs/car'.
ors-app    | 12-Jul-2023 11:09:40.764 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
ors-app    | 12 Jul 11:09:40 INFO [core.CoreLMPreparationHandler] - Loaded landmark splitting collection from 
ors-app    | 12 Jul 11:09:40 INFO [extensions.ORSGraphHopper] - version 4.0|2023-06-12T14:59:08Z (7,20,5,4,5,7)
ors-app    | 12 Jul 11:09:40 INFO [extensions.ORSGraphHopper] - graph CH|car_ors|RAM_STORE|3D|turn_cost|,,,,, details:edges:0(0MB), nodes:0(0MB), name:(0MB), geo:0(0MB), bounds:1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308, shortcuts:0 (0MB), nodesCH:-1 (0MB), shortcuts:0 (0MB), nodesCH:-1 (0MB), shortcuts:0 (0MB), nodesCH:-1 (0MB)
ors-app    | 12 Jul 11:09:41 INFO [extensions.ORSGraphHopper] - No custom areas are used, custom_areas.directory not given
ors-app    | 12 Jul 11:09:41 INFO [extensions.ORSGraphHopper] - start creating graph from /home/ors/ors-core/data/osm_file.pbf
ors-app    | 12 Jul 11:09:41 INFO [extensions.ORSGraphHopper] - using CH|car_ors|RAM_STORE|3D|turn_cost|,,,,, memory:totalMB:1024, usedMB:471
ors-app    | 12 Jul 11:10:20 ERROR [routing.RoutingProfileManager] - java.util.concurrent.ExecutionException: java.lang.RuntimeException: Couldn't process file /home/ors/ors-core/data/osm_file.pbf, error: java.net.SocketTimeoutException: Connect timed out
ors-app    | 12 Jul 11:10:20 ERROR [routing.RoutingProfileManager] - Failed to initialize RoutingProfileManager instance.
ors-app    | java.util.concurrent.ExecutionException: java.lang.RuntimeException: Couldn't process file /home/ors/ors-core/data/osm_file.pbf, error: java.net.SocketTimeoutException: Connect timed out
ors-app    | 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
ors-app    | 	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
ors-app    | 	at org.heigit.ors.routing.RoutingProfileManager.initialize(RoutingProfileManager.java:181) ~[classes/:7.1.0]
ors-app    | 	at org.heigit.ors.routing.RoutingProfileManager.getInstance(RoutingProfileManager.java:72) ~[classes/:7.1.0]
ors-app    | 	at org.heigit.ors.servlet.listeners.ORSInitContextListener.lambda$contextInitialized$0(ORSInitContextListener.java:40) ~[classes/:7.1.0]
ors-app    | 	at java.lang.Thread.run(Thread.java:833) [?:?]
ors-app    | Caused by: java.lang.RuntimeException: Couldn't process file /home/ors/ors-core/data/osm_file.pbf, error: java.net.SocketTimeoutException: Connect timed out
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.writeOsmToGraph(OSMReader.java:334) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:185) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.importOSM(GraphHopper.java:740) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.gtfs.GraphHopperGtfs.importOSM(GraphHopperGtfs.java:67) ~[graphhopper-reader-gtfs-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.process(GraphHopper.java:704) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:667) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at org.heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.importOrLoad(ORSGraphHopper.java:166) ~[classes/:7.1.0]
ors-app    | 	at org.heigit.ors.routing.RoutingProfile.initGraphHopper(RoutingProfile.java:193) ~[classes/:7.1.0]
ors-app    | 	at org.heigit.ors.routing.RoutingProfile.<init>(RoutingProfile.java:140) ~[classes/:7.1.0]
ors-app    | 	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:39) ~[classes/:7.1.0]
ors-app    | 	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:25) ~[classes/:7.1.0]
ors-app    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
ors-app    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
ors-app    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
ors-app    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
ors-app    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
ors-app    | 	... 1 more
ors-app    | Caused by: java.lang.RuntimeException: java.net.SocketTimeoutException: Connect timed out
ors-app    | 	at com.graphhopper.reader.dem.AbstractTiffElevationProvider.downloadFile(AbstractTiffElevationProvider.java:172) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.reader.dem.AbstractTiffElevationProvider.getEle(AbstractTiffElevationProvider.java:134) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.reader.dem.MultiSourceElevationProvider.getEle(MultiSourceElevationProvider.java:53) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.reader.dem.ElevationProvider.getEle(ElevationProvider.java:52) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.getElevation(OSMReader.java:689) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at org.heigit.ors.routing.graphhopper.extensions.ORSOSMReader.getElevation(ORSOSMReader.java:436) ~[classes/:7.1.0]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.addNode(OSMReader.java:662) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.processNode(OSMReader.java:630) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.writeOsmToGraph(OSMReader.java:301) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:185) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.importOSM(GraphHopper.java:740) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.gtfs.GraphHopperGtfs.importOSM(GraphHopperGtfs.java:67) ~[graphhopper-reader-gtfs-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.process(GraphHopper.java:704) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:667) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at org.heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.importOrLoad(ORSGraphHopper.java:166) ~[classes/:7.1.0]
ors-app    | 	at org.heigit.ors.routing.RoutingProfile.initGraphHopper(RoutingProfile.java:193) ~[classes/:7.1.0]
ors-app    | 	at org.heigit.ors.routing.RoutingProfile.<init>(RoutingProfile.java:140) ~[classes/:7.1.0]
ors-app    | 	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:39) ~[classes/:7.1.0]
ors-app    | 	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:25) ~[classes/:7.1.0]
ors-app    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
ors-app    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
ors-app    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
ors-app    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
ors-app    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
ors-app    | 	... 1 more
ors-app    | Caused by: java.net.SocketTimeoutException: Connect timed out
ors-app    | 	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[?:?]
ors-app    | 	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
ors-app    | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
ors-app    | 	at java.net.Socket.connect(Socket.java:633) ~[?:?]
ors-app    | 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
ors-app    | 	at sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]
ors-app    | 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:531) ~[?:?]
ors-app    | 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:636) ~[?:?]
ors-app    | 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
ors-app    | 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
ors-app    | 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]
ors-app    | 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
ors-app    | 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
ors-app    | 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
ors-app    | 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142) ~[?:?]
ors-app    | 	at com.graphhopper.util.Downloader.fetch(Downloader.java:68) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.util.Downloader.downloadFile(Downloader.java:114) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.reader.dem.AbstractTiffElevationProvider.downloadFile(AbstractTiffElevationProvider.java:168) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.reader.dem.AbstractTiffElevationProvider.getEle(AbstractTiffElevationProvider.java:134) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.reader.dem.MultiSourceElevationProvider.getEle(MultiSourceElevationProvider.java:53) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.reader.dem.ElevationProvider.getEle(ElevationProvider.java:52) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.getElevation(OSMReader.java:689) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at org.heigit.ors.routing.graphhopper.extensions.ORSOSMReader.getElevation(ORSOSMReader.java:436) ~[classes/:7.1.0]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.addNode(OSMReader.java:662) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.processNode(OSMReader.java:630) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.writeOsmToGraph(OSMReader.java:301) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:185) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.importOSM(GraphHopper.java:740) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.gtfs.GraphHopperGtfs.importOSM(GraphHopperGtfs.java:67) ~[graphhopper-reader-gtfs-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.process(GraphHopper.java:704) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:667) ~[graphhopper-core-v4.8.1.jar:?]
ors-app    | 	at org.heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.importOrLoad(ORSGraphHopper.java:166) ~[classes/:7.1.0]
ors-app    | 	at org.heigit.ors.routing.RoutingProfile.initGraphHopper(RoutingProfile.java:193) ~[classes/:7.1.0]
ors-app    | 	at org.heigit.ors.routing.RoutingProfile.<init>(RoutingProfile.java:140) ~[classes/:7.1.0]
ors-app    | 	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:39) ~[classes/:7.1.0]
ors-app    | 	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:25) ~[classes/:7.1.0]
ors-app    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
ors-app    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
ors-app    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
ors-app    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
ors-app    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
ors-app    | 	... 1 more

### Proposed solution

The code suggests that it is not able to process the pbf file. This is a problem even with the default pbf in the latest image

**Comment by MichaelsJP** [comment]
@debasmitadasgupta Thanks for reporting. Please do me a favour and delete the elevation tile folder once if you have that mounted in your container. It could be that one of the files is corrupt.

**Comment by MichaelsJP** [comment]
Closed as inactive
