### ISSUE TITLE
Docker install Win10 fails ..

### ISSUE THREAD

**Issue by Maj0rrush** [GIScience/openrouteservice#152]
When i try to boot up docker im getting this error ....

Is Windows Host OS not supported ?

C:\Entwicklung\docker\openrouteservice-master>cd docker && docker-compose up

Building ors-build
Step 1/11 : FROM maven:3-jdk-8
 ---> 908bdbacafc2
Step 2/11 : ENV MAVEN_OPTS="-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
 ---> Using cache
 ---> f73f4f5152c8
Step 3/11 : ENV MAVEN_CLI_OPTS="--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
 ---> Using cache
 ---> 27751ebfe5ad
Step 4/11 : ARG APP_CONFIG=docker/conf/app.config.sample
 ---> Using cache
 ---> a64d3ae3c003
Step 5/11 : RUN mkdir -p /ors-core/build
 ---> Using cache
 ---> 00a2ab9ca950
Step 6/11 : COPY .git /ors-core/.git
ERROR: Service 'ors-build' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder667633253/.git: no such file or directory

**Comment by rabidllama** [comment]
Hi @Maj0rrush 

did you clone the repository or download it as a zip archive? For the docker build to work, it needs to be cloned as this produces the .git folder and contents which are needed by one of the images in the docker build.

Hope that helps

**Comment by TimMcCauley** [comment]
Yea, this will be the case @rabidllama can you add some information regarding this in the README.md for docker installation?

**Comment by Maj0rrush** [comment]
Ok ... this works for me .. but now we have a new error :-)..

Maybe i should not try it on windows.

1368 [INFO] --------------------< heigit.ors:openrouteservice >---------------------
1374 [INFO] Building OpenRouteService 4.5.0
1377 [INFO] --------------------------------[ war ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/pl/project13/maven/git-commit-id-plugin/2.2.1/git-commit-id-plugin-2.2.1.pom
21826 [INFO] ------------------------------------------------------------------------
21827 [INFO] BUILD FAILURE
21831 [INFO] ------------------------------------------------------------------------
21833 [INFO] Total time: 20.634 s
21833 [INFO] Finished at: 2018-03-17T12:19:33Z
21835 [INFO] ------------------------------------------------------------------------
21842 [ERROR] Plugin pl.project13.maven:git-commit-id-plugin:2.2.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for pl.project13.maven:git-commit-id-plugin:jar:2.2.1: Could not transfer artifact pl.project13.maven:git-commit-id-plugin:pom:2.2.1 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Temporary failure in name resolution: Unknown host repo.maven.apache.org: Temporary failure in name resolution -> [Help 1]
21844 [ERROR]
21844 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
21845 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
21845 [ERROR]
21845 [ERROR] For more information about the errors and possible solutions, please read the following articles:
21846 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
ERROR: Service 'ors-build' failed to build: The command '/bin/sh -c mvn -f ./openrouteservice/pom.xml package -DskipTests' returned a non-zero code: 1

**Comment by Maj0rrush** [comment]
thx work now!
