### ISSUE TITLE
move to vitepress

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#1528]
### Page Link

https://vitepress.dev/

### Documentation is ...

Missing/Needed

### Please Explain in Detail:

The current docs frontend could be better.
Dark theme: No
Layout: ok but could be better

### Your Proposal for Changes:

VitePress comes with out of the box dark theme has a more modern look and renders markdown very similar to the current solution but (not sure but i think) more light weight and could be easily run in a dev environment.
Also supports same [Frontmatter](https://vitepress.dev/guide/frontmatter) options.

Search can be included via a plugin.
Supports versioning as well i think

**Comment by koebi** [comment]
Hey,
I assume you're talking about [our github pages documentation](https://giscience.github.io/openrouteservice/)?
Currently, they use the [Just-the-docs](https://just-the-docs.com/)-Theme, a simple Jekyll Theme that needs very little configuration, apart from the `_config.yml`-file in the `docs/`-folder. Currently, we have a custom header and footer, inserted our logo and changed the colorscheme to fit the ors better.

It seems to me that vitepress doesn't support GitHub Pages out of the box - or at least, a custom action seems necessary to deploy it.

From my point of view, this is quite a bit of overhead, both in terms of development and maintenance. I have not experienced the js-world as an icon of stability, so I definitely see things breaking, and GitHub Pages does not seem to be one of the major concerns of vitepress.

A dark theme for the docs is about an hour of choosing colors away from existing - it hasn't happened.
