### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by Maj0rrush** [GIScience/openrouteservice#153]
hi,

again .. :-) Sorry im not really experienced with docker.

The buld steps run trough 10/11

but then after a bit downloading ...

Downloaded from central: https://repo.maven.apache.org/maven2/junit/junit/4.4/junit-4.4.pom (1.2 kB at 20 kB/s)
441199 [INFO] ------------------------------------------------------------------------
441204 [INFO] BUILD FAILURE
441208 [INFO] ------------------------------------------------------------------------
441213 [INFO] Total time: 07:20 min
441215 [INFO] Finished at: 2018-03-17T12:53:09Z
441216 [INFO] ------------------------------------------------------------------------
441228 [ERROR] Failed to execute goal on project openrouteservice: Could not resolve dependencies for project heigit.ors:openrouteservice:war:4.5.0: Failed to collect dependencies at org.geotools:gt-main:jar:16.1: Failed to read artifact descriptor for org.geotools:gt-main:jar:16.1: Could not transfer artifact org.geotools:geotools:pom:16.1 from/to osgeo (http://download.osgeo.org/webdav/geotools/): GET request of: org/geotools/geotools/16.1/geotools-16.1.pom from osgeo failed: Premature end of Content-Length delimited message body (expected: 72371; received: 8213 -> [Help 1]
441240 [ERROR]
441240 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
441240 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
441241 [ERROR]
441241 [ERROR] For more information about the errors and possible solutions, please read the following articles:
441241 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
ERROR: Service 'ors-build' failed to build: The command '/bin/sh -c mvn -f ./openrouteservice/pom.xml package -DskipTests' returned a non-zero code: 1

**Comment by rabidllama** [comment]
From the error it seems to have been a problem with the osgeo repository rather than the docker build itself. Have you tried it again since that error in case it was a temporary issue with their server as I have just tried locally and it managed to download the required dependencies?

**Comment by TimMcCauley** [comment]
Considering this as closed for now.
