### ISSUE TITLE
foot-walking Isochrones snapping to inappropriate locations

### ISSUE THREAD

**Issue by hulsiejames** [GIScience/openrouteservice#1533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I have successfully been using a local install of open route service, installed with docker, to request foot-walking travel time isochrones for every Output Area (OA) in the UK.

A small subset of isochrone requests have been failing for numerous reasons, mostly understandable (too far from rout-able network, trapped by access restrictions) but some I could not explain. Thus, I created a post on the ORS forum looking for clarification and a response has brought me here. 

Specifically, I believe that the coordinate snapping that occurs when a request is made for foot-walking snaps to unsuitable infrastructure.

For example, the OA centered at Wesley close: -0.599108, 53.656714
![wesley](https://github.com/GIScience/openrouteservice/assets/58815827/90cbb3d0-4b8e-47e6-b480-30891f594e5c)

When I attempt to request an isochrone for this location I am returned a 3099 internal error that an isochrone could not be built. 

I should note that this issue occurs in the public facing ORS instance too (requested 24/08/2023@18:55 through API Playground): 
<img width="390" alt="recent_example" src="https://github.com/GIScience/openrouteservice/assets/58815827/57de1ef4-d460-4424-b451-25d8a96a77b7">
<img width="392" alt="recent_exmaple_body" src="https://github.com/GIScience/openrouteservice/assets/58815827/e8b34242-ed34-4c31-ad11-782b1f9b2b0a">

Additionally, when making the same request with car-driving, the centroid is correctly snapped to the neighboring road (blue circle) and an isochrone is built successfully: 
![wesley_snapped_car](https://github.com/GIScience/openrouteservice/assets/58815827/e2f1b331-9d8d-403e-8a81-68d60be183e5)

As can be seen in the screenshot above, there is a footpath to the right of the road where the car-driving isochrone has snapped to. 

A user on the ORS-forum has suggested that the foot-walking ischorne request is indeed attempting to snap to nearby infrastructure, however it is snapping to this footpath which is a standalone feature rather than being connected to the network.

_"This guess is strengthened by the fact that moving the point to the left of Wesley Close enables it in building an isochrone."_

<img width="811" alt="bad_footpath" src="https://github.com/GIScience/openrouteservice/assets/58815827/53c5a65d-5fa2-4b8e-8d0a-f8054cdca8e2">
**please note I have since connected this footpath to the network**

As such the build request is failing. As suggested I have duplicated the issue here (keeping only the information relating to this issue, my other questions have been answered).

### Proposed solution

Instead, as suggested on the ORS-forum post, I believe there should be some sort of check that the infrastructure being snapped to when a foot-walking request is made is not a standalone feature and is part of a route-able network.

If not, perhaps a secondary snapping attempt should be made (if there are still untried infrastructure within say a 25m buffer) - if the build isochrone request fails on this second or third attempt, return a build error.

Alternatively, given the issue arose due to the footpath being nearer to the passed coordinate than a route-able road, thus the OA location was snapped to this, perhaps one could apply some sort of _small_ jitter to the passed coordinates after a failed build attempt before re-trying a request - I imagine moving the centroid slightly would result in the correct snapping to the route-able road. 

However I'm not sure about this approach, perhaps it is better to allow the user to implement their own coordinate jittering and ors instead attempts to build from the actual passed coordinate, this way we can have confidence that successful requests are from the passed coordinates and not some client side _jittered_ coordinate to get a correct snapping.

### Forum Topic Link

https://ask.openrouteservice.org/t/unable-to-build-subset-of-foot-walking-isochrone-requests/5166

**Comment by sfendrich** [comment]
Thanks for reporting this issue! Seems to be fixed in PR #1566.
