### ISSUE TITLE
Evaluate directions 'options' object on backend

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#154]
The `options` object should be evaluated server-side. Now, it simply fails silently, when a parameter is specified in the wrong way, i.e. `maximumspeed` instead of `maximum_speed`, and returns the route without an error.

@MichaelsJP if and when you have the ressources. Or coordinate with @Elli96 if that makes sense. No urgency here though. But let's keep it in mind for 4.6 the latest.

**Comment by rabidllama** [comment]
I am moving this to 4.7 as we will have more resources available in the next couple of months

**Comment by TimMcCauley** [comment]
Related to #233 - will be done then.

**Comment by rabidllama** [comment]
Lets put this on hold then until v5

**Comment by rabidllama** [comment]
So in the newer API which will be released in 5.0, mismatched values/parameters should always return an error
