### ISSUE TITLE
[3099] Unable to build an isochrone map

### ISSUE THREAD

**Issue by Rimberse** [GIScience/openrouteservice#1560]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Where did you encounter this issue?

live API

### Request URL

https://api.openrouteservice.org/v2/isochrones/foot-walking

### POST Request Body

```JSON
{
    "locations": [
        [
            -1.672090348265983,
            48.1042122740196
        ],
        [
            -1.6875995214295976,
            48.11813709448315
        ],
        [
            -1.6754515636297707,
            48.09754272915888
        ],
        [
            -1.693399896148019,
            48.121556772432825
        ],
        [
            -1.6603595692692328,
            48.086437185898
        ]
    ],
    "range": [
        300
    ],
    "interval": 300
}
```

### Response

<details><summary>Response</summary>

```JSON

{
    "error": {
        "code": 3099,
        "message": "Unable to build an isochrone map."
    },
    "info": {
        "engine": {
            "build_date": "2023-07-09T01:31:50Z",
            "version": "7.1.0"
        },
        "timestamp": 1696843325107
    }
}

```
</details>

### Current behavior

Hello,

I am trying to generate several isochrones with ORS using Isochrones Service V2.

However, for the provided coordinates I receive an error 3099. I've also tried reversing the coordinates, but I continue receiving the same error. Worth mentioning that I can successfully generate isochrones for any other profiles involving vehicles: driving-car, driving-hgv, but not for foot-walking, foot-hiking, etc.

I also haven't been able to create the isochrones using the web-app: https://maps.openrouteservice.org/#/reach/-1.6542782964825173,48.08773187670475/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,90,1,24,3,160,13,128,86,0,88,2,96,29,128,14,106,4,229,50,199,204,54,129,152,1,163,120,128,12,245,107,116,44,52,173,1,149,107,145,3,196,4,0,14,169,224,68,77,135,40,48,233,16,102,139,148,0,27,52,185,250,16,20,222,155,38,76,196,13,32,254,97,196,1,205,113,19,45,212,184,150,149,202,146,96,180,160,5,247,144,2,242,128,5,181,195,23,148,86,128,128,3,55,132,55,69,193,4,74,133,71,192,7,118,68,48,6,178,67,119,150,134,69,119,64,7,213,64,4,244,83,75,193,84,139,77,47,41,112,104,6,210,224,16,16,5,215,146,67,208,3,119,205,198,232,22,14,10,0,0. 

### Expected behavior

Receiving generated isochrones for the provided coordinates [foot-walking profile], which are representing metro stations.

### Openrouteservice Version

7.1.0

### Build date

2023-07-09T01:31:50Z

**Comment by sfendrich** [comment]
Thanks for reporting this issue! Seems to be fixed in PR #1566.
