### ISSUE TITLE
Routing over solid line

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#158]
[This route](https://maps.openrouteservice.org/directions?n1=48.787541&n2=8.334761&n3=16&a=48.790439,8.324397,48.786523,8.342121&b=0&c=0&k1=en-US&k2=km) is taking an unusual and dangerous shortcut.
[The request (change key)](https://api.openrouteservice.org/directions?api_key=api_key&attributes=detourfactor|percentage&coordinates=8.324397,48.790439|8.342121,48.786523&elevation=true&extra_info=steepness|waytype|surface&geometry=true&geometry_format=geojson&instructions=true&instructions_format=html&preference=fastest&profile=driving-car&units=m)

This might be fixed with graphhopper update.

**Comment by rabidllama** [comment]
Just checked and it is definitely a problem in the underlying routing algorithms as it happens on the graphhopper site as well

**Comment by TheGreatRefrigerator** [comment]
Hmm you are right: on the [graphhopper](https://graphhopper.com/maps/?point=48.787895%2C8.326135&point=48.785887%2C8.341627&locale=en&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale) website it takes the shortcut.
But it works on the OSM website [using graphhopper](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=48.7888%2C8.3252%3B48.7864%2C8.3420)??

**Comment by sfendrich** [comment]
Seems to be a CH issue, as it works fine with [landmarks](https://graphhopper.com/maps/?point=48.787895%2C8.326135&point=48.785887%2C8.341627&locale=en&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale&ch.disable=true).

**Comment by rabidllama** [comment]
Yes we see similar issues with missing out restrictions when CH is applied (#176 )

> But it works on the OSM website using graphhopper??

OSM automatically tells GH not to use CH in their request

**Comment by rabidllama** [comment]
OK, so as this is an issue relating to how the core algorithms in GH work, I will close this issue as it would need addressing by Graphhopper
