### ISSUE TITLE
isochrones bug:  "intersections" parameter not registered in query - no effect on isochrones

### ISSUE THREAD

**Issue by jaronimoe** [GIScience/openrouteservice#159]
hi,

I'm trying to receive non-overlapping isochrones from the query, which I assume can be retrieved by setting the `intersections` parameter to "true"?
(the default seems to be "false" where the returned shape files are overlapping.)
(the description in the documentation could be a bit more verbose).

anyway, since I was not sure whether intersections should be true or false for retrieving non-overlapping polygons, I tried both parameter variations, only to find out that the query returns exactly the same isochrones/features.

for reference, this is the query string that I used:
"https://api.openrouteservice.org/isochrones?api_key=yourapikey&locations=16.30405159999998%2C48.2108321&profile=driving-car&range_type=time&range=3600&interval=900&location_type=destination&attributes=area&options=&intersections=true&id=foo";

in the response .info.query object there is no notion of the intersections parameter:

```
info:
attribution: "openrouteservice.org | OpenStreetMap contributors"
engine: {version: "4.5.0", build_date: "2018-03-26T14:15:39Z"}
osm_file_md5_hash: "9577c06762ca275905abdfaa738d6ccf"
query:
attributes: "area"
id: "foo"
location_type: "destination"
locations: [Array(2)]
profile: "driving-car"
range_type: "time"
ranges: "900.0,1800.0,2700.0,3600.0"
__proto__: Object
service: "isochrones"
timestamp: 1522231510093
__proto__: Object
type: "FeatureCollection"
```

 ...and a visual comparison of the isochrones as well as a diff of the shape files does not show any difference.
is this a bug or am I doing something wrong?

kind regards,
Johannes

**Comment by TimMcCauley** [comment]
@jaronimoe the intersections parameter will work when you use two input locations for isochrones. If they overlap and intersections are set to false, it will look like this:

<img width="396" alt="screen shot 2018-03-30 at 22 45 40" src="https://user-images.githubusercontent.com/10322094/38153289-2e92f65e-346c-11e8-80f6-50def04d7d0a.png">

If you set intersections to `true` the overlapping ranges will become one merged polygon.

Example without merged intersections:

`https://api.openrouteservice.org/isochrones?format=json&interval=900&location_type=start&locations=8.339138,48.767731|8.53363,49.100847&profile=driving-car&range=1800&range_type=time&api_key=xxx&intersections=false`

And with merged intersections:

`https://api.openrouteservice.org/isochrones?format=json&interval=900&location_type=start&locations=8.339138,48.767731|8.53363,49.100847&profile=driving-car&range=1800&range_type=time&api_key=xxx&intersections=true`

**Comment by TimMcCauley** [comment]
@jaronimoe I got this wrong, sorry, the purpose of the "intersections" parameter is to include additional polygons which describe the intersection of isochrones that belong to different locations
