### ISSUE TITLE
Hiking profile includes train tracks (car_shuttle)

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/openrouteservice#1614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When routing in the hiking profile across the alps from [Kandersteg in Switzerland](https://www.openstreetmap.org/node/30851539) to [Iselle di Trasquere in Italy](https://www.openstreetmap.org/node/52255676), ORS suggests to take the train tracks including multiple tunnels:

https://maps.openrouteservice.org/#/directions/Innere%20Meriweg,Kandersteg,BE,Switzerland/Via%20Isella%204,Crevoladossola,VB,Italy/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,118,0,232,3,103,192,70,98,6,96,9,159,99,78,178,170,1,96,6,153,227,14,96,78,1,89,127,192,1,155,165,110,130,201,144,235,192,55,0,14,66,212,198,151,206,211,153,74,205,123,86,98,21,136,8,0,29,83,192,136,155,14,80,0,188,160,5,181,194,164,1,232,16,1,155,192,3,110,151,8,23,81,80,5,160,0,183,128,6,178,64,7,53,212,118,135,65,119,65,140,67,2,243,193,140,129,177,183,68,69,135,69,129,0,5,243,202,0

I think the root of the problem is this OSM object:

https://www.openstreetmap.org/way/328536872 

### Proposed solution

I'm don't know which one of the tags of the way triggered its inclusion in the hiking graph, therefore I cannot propose a solution.

**Comment by takb** [comment]
ORS is treating the mentioned OSM way as a ferry route due to the tag `route:shuttle_train`. You can get around this by activating the option `"avoid_features": ["ferries"]`. We would need to discuss if we might disallow ferries for the hiking profile by default, but obviously this could lead to other problems, e.g. where ferries are the only way to getting to a place.

**Comment by SlowMo24** [comment]
Interesting. I would not expect to get ferry routing (or any other public transport routing) on a hiking profile.

For me there would just not be a hiking route leaving any island. So I would invert the process (make `"avoid_features": ["ferries"]` the default, but that is of course a design choice.

Thanks for checking!
