### ISSUE TITLE
Processing OSM map throws java.net.SocketTimeoutException, external connectivity? (firewall/setting)

### ISSUE THREAD

**Issue by andresC98** [GIScience/openrouteservice#1620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I am deploying a self-hosted ORS docker image (v7.2.0) on an enterprise AWS cloud account. When booting up the ORS server, it throws the following error while processing the default (example Heildeberg) OSM file:

`java.lang.RuntimeException: Couldn't process file /home/ors/ors-core/data/osm_file.pbf, error: java.net.SocketTimeoutException: Read timed out`

Given that it is a socket timeout exception, my understanding is that it is due to an attempt to perform an external (internet-faced) connection. These connections are tightly blocked at my company's firewall. Is it possible to disable any internet-connection operation done in the server startup so that it only works with local files? If not, it is possible to know the exact list of URLs that ORS will attempt to connect to so that I can whitelist them on the firewall?

Thank you very much in advance.

### Proposed solution

A config can be setup so that it disables some feature (elevation?) that attempts to fetch data from the internet. ELSE provide list of URLs that ORS will attempt to connect to.

**Comment by sfendrich** [comment]
This might be ORS trying to download elevation data. Does this also happen when you disable elevation in your profile configurations?

**Comment by andresC98** [comment]
> This might be ORS trying to download elevation data. Does this also happen when you disable elevation in your profile configurations?

@sfendrich thanks for the fast response, yes, it seems it is also happening when disabling elevation. This is my current ors-config file, I have tried disabling every mention to `elevation`, and unless I am missing something, it should be disabled this way but still get the same error.

**Update**: turns out even though I modified the ors-config.json, the `example-ors-config.json` file was being copied and overwrited my config that was attemtping to disable the elevation. Now it works, however I would still appreciate to understand (or have some docs/info provided) the different external connections (URLs) that are fetched on ORS initialization, as my assumption is that for firewall-restricted networks this may become an issue and require a list of URLs that ORS attemtp.

**Comment by sfendrich** [comment]
Here are the URLs currently used by ORS depending on which elevation provider is configured:
SRTM: https://srtm.kurviger.de/SRTM3/
CGIAR: https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/
MULTI: same as CGIAR and GMTED

The underlying GraphHopper also lists the following URLs, but I don't know whether these elevation providers are supported by ORS.
GMTED: https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/downloads/GMTED/Global_tiles_GMTED/075darcsec/mea/
SRTMGL1: https://cloud.sdsc.edu/v1/AUTH_opentopography/Raster/SRTM_GL1/SRTM_GL1_srtm/
SKADI: https://elevation-tiles-prod.s3.amazonaws.com/skadi/

If you do not want to open your firewall, you could also download the elevation data manually and put it into the elevation cache dir.

**Comment by andresC98** [comment]
> Here are the URLs currently used by ORS depending on which elevation provider is configured: SRTM: https://srtm.kurviger.de/SRTM3/ CGIAR: https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/ MULTI: same as CGIAR and GMTED
> 
> The underlying GraphHopper also lists the following URLs, but I don't know whether these elevation providers are supported by ORS. GMTED: https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/topo/downloads/GMTED/Global_tiles_GMTED/075darcsec/mea/ SRTMGL1: https://cloud.sdsc.edu/v1/AUTH_opentopography/Raster/SRTM_GL1/SRTM_GL1_srtm/ SKADI: https://elevation-tiles-prod.s3.amazonaws.com/skadi/
> 
> If you do not want to open your firewall, you could also download the elevation data manually and put it into the elevation cache dir.

Thank you very much @sfendrich , this was exactly what I was looking for! I can close the issue now.
