### ISSUE TITLE
Implement proper logging for the traffic data matching

### ISSUE THREAD

**Issue by MichaelsJP** [GIScience/openrouteservice#1625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

We need traffic data matching statistics.		

### Proposed solution

Either integrate a log output for the progress or some sensible statistics after logging.

**Comment by aoles** [comment]
As of ORS v7, the progress bar for map matching of traffic data is redirected from the console output to the logger instance at `DEBUG` logging level. Effectively, the former [interactive progress bar](https://github.com/GIScience/openrouteservice/blob/v6.8.3/openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HereTrafficGraphStorageBuilder.java#L309) visible during startup of ORS 6.x instance

```
18 Dec 13:14:05 INFO                                            ORS-pl-car [ r.g.e.s.b.HereTrafficGraphStorageBuilder ]   Starting MapMatching traffic data
Processing traffic patterns 100% │███████████│ 12870/12870 (0:00:00 / 0:00:00) 
Matching Here Links   0% │               │    6000/1190529 (0:00:19 / 1:02:31)
```

has been replaced by a [static sequence of log entries](https://github.com/GIScience/openrouteservice/blob/ef99b46dc7458de63b180e1fd7ce2c2f8d2367ab/ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HereTrafficGraphStorageBuilder.java#L319).

```
18 Dec 12:39:16 INFO                                            ORS-pl-car [ r.g.e.s.b.HereTrafficGraphStorageBuilder ]   Starting MapMatching traffic data
18 Dec 12:39:17 DEBUG                                          ProgressBar [ r.g.e.s.b.HereTrafficGraphStorageBuilder ]   Processing traffic patterns   0% │            │     2/12870 (0:00:00 / 0:00:02) 
18 Dec 12:39:17 DEBUG                                          ProgressBar [ r.g.e.s.b.HereTrafficGraphStorageBuilder ]   Processing traffic patterns 100% │████████████│ 12870/12870 (0:00:00 / 0:00:00) 
18 Dec 12:39:17 DEBUG                                          ProgressBar [ r.g.e.s.b.HereTrafficGraphStorageBuilder ]   Processing traffic patterns 100% │████████████│ 12870/12870 (0:00:00 / 0:00:00) 
18 Dec 12:39:17 DEBUG                                          ProgressBar [ r.g.e.s.b.HereTrafficGraphStorageBuilder ]   Matching Here Links   0% │                      │       0/1190529 (0:00:00 / ?) 
18 Dec 12:39:36 DEBUG                                          ProgressBar [ r.g.e.s.b.HereTrafficGraphStorageBuilder ]   Matching Here Links   0% │                │    2000/1190529 (0:00:19 / 3:08:13) 
18 Dec 12:39:42 DEBUG                                          ProgressBar [ r.g.e.s.b.HereTrafficGraphStorageBuilder ]   Matching Here Links   0% │                │    4000/1190529 (0:00:25 / 2:03:37) 
```

One possible solution could involve reverting the progress bar to the interactive mode known from ORS v6, but including a summary on the matching success rate in the logger too. These statistics should probably be logged at `INFO` level.

**Comment by MichaelsJP** [comment]
OK, nice. So in fact, it's still there, just not in production log files. Yeah. Having it there would be great. What are your thoughts on providing that information additionally in the status endpoint when the graph was built with traffic?
