### ISSUE TITLE
IN1-JAVA-ORGMOZILLA-1314295 - org.mozilla:rhino

### ISSUE THREAD

**Issue by joewragg** [GIScience/openrouteservice#1627]
### Scope

pom.xml

### Report Link

https://security.snyk.io/vuln/SNYK-JAVA-ORGMOZILLA-1314295

### Dependency affected

org.mozilla:rhino 1.7.7.2

### Proposed solution / further info

Upgrade your installed software packages to the proposed fixed in version and release.

    Update rhino to 1.7.12

**Comment by sfendrich** [comment]
This is a transitive dependency of swagger-parser.
The latest version has not upgraded rhino: https://mvnrepository.com/artifact/io.swagger.parser.v3/swagger-parser/2.1.19
Our version is not yet flagged as vulnerable on maven central: https://mvnrepository.com/artifact/io.swagger.parser.v3/swagger-parser/2.1.16

**Comment by MichaelsJP** [comment]
it's only used in one test, but not `test scope only`. We could do that to remove the dependency from the runtime class paths.
