### ISSUE TITLE
CORS HTTPS-'options' preflight-request counts to API rate limits

### ISSUE THREAD

**Issue by CramericaIndustries** [GIScience/openrouteservice#164]
Hello there,
Outgoing from a HTTPS website, I'm querying the openrouteservice api using a jQuery.ajax() request. What jQuery.ajax() automatically does is, it sends an 'OPTIONS'-preflight-request to the api-webserver to test if the cross origin request is secure or not. After it found out that the 'OPTIONS' request is secure it will send the real 'GET' request. Problem now is that the first 'OPTIONS' request (which contains no real data) counts to the API rate limits. So instead of 40 requests per minute I can only do 20.

```
jQuery.ajax({
    type: "GET" //rest Type
   ,dataType: 'json'
   ,url: "https://api.openrouteservice.org/directions?coordinates=10.942365999999993,49.185013|10.946323000000007,49.192914|10.959033966064453,49.19292297279707"
		  + "&profile=driving-car"
		  + "&preference=shortest"
		  + "&format=geojson"
		  + "&units=m"
		  + "&geometry_format=geojson"
		  + "&geometry_simplify=false"
		  + "&instructions=false"
		  + "&elevation=true"
		  + "&extra_info=surface|waytype|steepness"
		  + "&api_key=----------YOUR KEY HERE----------"
    ,async: false
    ,contentType: "application/json; charset=utf-8"
    ,success: function (data) {
    	console.log(data);
    }
});

```
As a workaround I've disabled the OPTIONS request by changing the `content-type` header to `text/plain; charset=utf-8`

```
jQuery.ajax({
    type: "GET" //rest Type
   ,dataType: 'json'
   ,url: "https://api.openrouteservice.org/directions?coordinates=10.942365999999993,49.185013|10.946323000000007,49.192914|10.959033966064453,49.19292297279707"
		  + "&profile=driving-car"
		  + "&preference=shortest"
		  + "&format=geojson"
		  + "&units=m"
		  + "&geometry_format=geojson"
		  + "&geometry_simplify=false"
		  + "&instructions=false"
		  + "&elevation=true"
		  + "&extra_info=surface|waytype|steepness"
		  + "&api_key=----------YOUR KEY HERE----------"
    ,async: false
    ,contentType: "text/plain; charset=utf-8"
    ,success: function (data) {
    	console.log(data);
    }
});
```

**Comment by TimMcCauley** [comment]
@CramericaIndustries thank you for sharing this, I will investigate to remove preflight requests from the counter.

**Comment by TimMcCauley** [comment]
@CramericaIndustries , we made the necessary changes in the backend. Please try and let us know if this problem still persists.

**Comment by CramericaIndustries** [comment]
Still getting following error at the 21th request
```
Failed to load https://api.openrouteservice.org/directions?coordinates=10.975578000000041,49.142967|10.970207999999957,49.144465|10.96435546875,49.14612048658428&profile=driving-car&preference=shortest&format=geojson&units=m&geometry_format=geojson&geometry_simplify=false&instructions=false&elevation=true&extra_info=surface|waytype|steepness&api_key=----api-key-here----: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.rallyekarte.de' is therefore not allowed access. The response had HTTP status code 429.
```

**Comment by TimMcCauley** [comment]
Mhhh, can you try again now?

**Comment by TimMcCauley** [comment]
@CramericaIndustries could you please include a functional html file with the code that I can test this on my machine directly?

**Comment by CramericaIndustries** [comment]
@TimMcCauley sorry for the long response time... was out of the office.
The attachment contains a zipped html file which you can use to test the issue. You must upload it somewhere where it is served with HTTPS. It won't work when you directly open it (from your desktop) due to your browser not setting all http headers then. If your setup is ready, just open the file in your browser and enter your API key into the input field. Then hit the request button 20 times + 1 more time which then will trigger the error (message box pops up). If you open the developer tools you will see the API response in the console. Also you could monitor the network tab there to see the requests going through.

[CORS.zip](https://github.com/GIScience/openrouteservice/files/1899372/CORS.zip)

**Comment by CramericaIndustries** [comment]
@TimMcCauley does the html file work?

**Comment by TimMcCauley** [comment]
@CramericaIndustries yes, I haven't found time to look into this issue yet but it's on my high priority list! You aren't the first experiencing these problems, unfortunately..

**Comment by TimMcCauley** [comment]
@CramericaIndustries can you please try again now? If it works for you - can you check if the headers look ok?

**Comment by CramericaIndustries** [comment]
@TimMcCauley Is working now. Thanks! Headers look the same as before.

**Comment by TimMcCauley** [comment]
Great, I'll close this issue for now, let me know if anything weird arises, we'll fix it asap
