### ISSUE TITLE
missing "content-encoding" header with invalid authorization

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#165]
This is related to the Apiary Documentation:

If a request contains an invalid api_key or non at all, there is no content-encoding header in the response. Apiary then returns this:
![screenshot-2018-4-9 openrouteservice editor](https://user-images.githubusercontent.com/23240110/38510871-98d73ca2-3c26-11e8-97f7-e52458f4de92.png)
instead of the actual "key not authorized" error

**Comment by koebi** [comment]
Apiary isn't used and this is therefore not an issue anymore.
