### ISSUE TITLE
Lack of a manual/freehand route option

### ISSUE THREAD

**Issue by Martin868** [GIScience/openrouteservice#167]
On all the routing engines I know that allow the user to draw a route, there is on option to bypass routing for a section of the route and manually link two points. This option is handy when the route need to follow a missing way on the map, or that there is a routing error in the map database. I do a lot of cycling route planning and this happens all the time. For example the route planners in Strava, RideWithGPS, Garmin, all offer this. In ORS this should be a type of via point.

**Comment by nilsnolde** [comment]
This is a frontend issue, please register it here:
https://github.com/GIScience/openrouteservice-app/issues

**Comment by TimMcCauley** [comment]
Frontend will consume this but it’s a feature that has to be implemented to the backend ultimately. 

The idea is: if a direct connection should be returned the backend simply doesn’t optimize between those two waypoints. We have the code for this in an older version (which was implemented), I might be able to find it.

**Comment by dlichtistw** [comment]
I agree that this would be really useful for hiking route planning, too. I used it earlier, and am missing it now.

**Comment by rabidllama** [comment]
@TimMcCauley Did you find where the old code was for this?

**Comment by TimMcCauley** [comment]
@rabidllama sorry, I checked and I can't find it (most likely on my old laptop which was stolen 👎). The idea is quite straightforward, every waypoint gets an additional attribute optimize which is either `null` (startpoint), `true` (find an optimized path between it and the previous wp) or `false` which won't optimize but return the input coordinates (between it and the previous wp) as flight of the crow.

```
wp1 | optimize: null
wp2 | optimize: true
wp3 | optimize: false

paths:
wp1 - wp2 => optimized path
wp2 - wp3 => flight of the crow
```

**Comment by rabidllama** [comment]
OK, I don't think this will be too major a thing to add, so lets aim for getting it in there for v4.7

**Comment by rabidllama** [comment]
Moved to 4.7.2

**Comment by MichaelsJP** [comment]
`"coordinates": [[8.688812, 49.414352],[8.688169, 49.413193],[8.689349, 49.413291],[8.688898, 49.410652], [8.687375, 49.409549]]`
![auswahl_035](https://user-images.githubusercontent.com/22392104/52954911-a13b4e80-338b-11e9-8b57-70938d1a70c8.png)
If you add `"skip_segments": [3]` it will add a direct connection between the third and fourth coordinate (third segment).
![auswahl_036](https://user-images.githubusercontent.com/22392104/52954901-9d0f3100-338b-11e9-889e-1cefcd6f2f6e.png)

**Comment by Martin868** [comment]
Can it be done in the current front-end or this is coming ?

**Comment by TimMcCauley** [comment]
@Martin868 yep, we will include this in the client as soon as it is released!
