### ISSUE TITLE
There is no info how to apply the docker instance to use with open_route_service dart plugin

### ISSUE THREAD

**Issue by MiesSuomesta** [GIScience/openrouteservice#1671]
### Page Link

N/A

### Documentation is ...

Missing/Needed

### Please Explain in Detail:

I'd like instructions how to apply the working docker installation to be used by open_route_service dart plugin? 

It seems that the modification of the file $HOME/.pub-cache/hosted/pub.dev/open_route_service-1.2.3/lib/src/open_route_service_base.dart:

```
 /// The base URL of all the endpoints, https://api.openrouteservice.org
  //static const String _baseURL = 'https://api.openrouteservice.org';
  static const String _baseURL = 'https://api.mypublicdomain.fi/';
```

does nothing ?

### Your Proposal for Changes:

I'd like documentation of the process to take the docker instance really to use with dart plugin (witch is awesome!) ..

**Comment by MichaelsJP** [comment]
@MiesSuomesta great to see your interest in ors, and thanks for sharing the dart package.

You are welcome to provide any solutions as a PR into this repository, either as code or as part of the documentation.
You could also write a short post at [ask.openrouteservice.org/](ask.openrouteservice.org/), so others can learn from your experience.

The package is not maintained by us directly, and it's not a directly code related question. I'm closing this.
