### ISSUE TITLE
Error validating GPX response with schema

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#170]
There seem to be some problem with the GPX response format or the schema describing it. When I try to validate the resulting [XML](https://api.openrouteservice.org/directions?api_key=...&coordinates=8.34234,48.23424|8.34423,48.26424&profile=driving-car&format=gpx) with [XSD](https://raw.githubusercontent.com/GIScience/openrouteservice-schema/master/gpx/v1/ors-gpx.xsd) I get several errors:
> Element '{https://raw.githubusercontent.com/GIScience/openrouteservice-schema/master/gpx/v1/ors-gpx.xsd}type': [facet 'enumeration'] The value '2' is not an element of the set {'11', '0', '1', '6', '5', '7', '4', '3'}.

These seem to be triggered by the presence of the `<type>2</type>` nodes which are not listed [here](https://github.com/GIScience/openrouteservice-schema/blob/9f1e9870cd5b527b37984b351967258b673f53f7/gpx/v1/ors-gpx.xsd#L10-L19).

```xml
<gpx version="1.0" creator="openrouteservice">
  <rte>
    <rtept>
      <extensions>
        <type>2</type>
      </extensions>
    </rtept>
  </rte>
</gpx>
```

**Comment by MichaelsJP** [comment]
@aoles Thx for pointing this out. I will upload the fix in a minute!
Link to the correct issue --> GIScience/openrouteservice-schema#1

**Comment by aoles** [comment]
Thanks, I confirm that the now the XML validates fine.
