### ISSUE TITLE
How can I determine the location along a given route using mileage? - OpenRouteService extensions

### ISSUE THREAD

**Issue by dgokhan** [GIScience/openrouteservice#1701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

For example, given a route between Miami and New York (driving), I'd like to figure out the lat/long of a location along that same route after some number of KM

This is possible with Google Maps extensions but i could not find a solution with **OpenRouteService**

GoogleMaps extension; http://econym.org.uk/gmap/epoly.htm & http://www.geocodezip.com/scripts/v3_epoly.js

demo : http://www.geocodezip.com/v3_GoogleEx_directions-atMileage.html

### Proposed solution

x

**Comment by koebi** [comment]
This is a duplicate of [this question in the forum](https://ask.openrouteservice.org/t/how-can-i-determine-the-location-along-a-given-route-using-mileage-openrouteservice-extensions/5829/2).
