### ISSUE TITLE
Missing translation for the last step of directions

### ISSUE THREAD

**Issue by devsware** [GIScience/openrouteservice#171]
I was experimenting with Leaflet + OpenStreetMaps + openrouteservice and I created a map where the user can obtain directions from a specific address to a point of interest.

In my request to the openrouteservice Directions Service I set `'language':'it'` parameter to obtain instructions in Italian: all steps but the last have an instruction in italian, while the last one ("Arrive at...") is in English.

If it could be of any help, the correct italian translation for "Arrive at" is "Arrivo a".

I tried with some other languages: switching to French (`'language':'fr'`) the problem persist while with German (`'language':'de'`) it seems that the last step is correctly translated.

**Comment by rabidllama** [comment]
I can confirm that this is not an issue with the code, but instead simply that we are missing the corresponding translations for the arrival messages for the various languages in the resource files.
