### ISSUE TITLE
Use sac_scale=difficult_alpine_hiking also for "walking"?

### ISSUE THREAD

**Issue by pathmapper** [GIScience/openrouteservice#173]
Follow up from: https://github.com/GIScience/openrouteservice-app/issues/220#issuecomment-389080656

Currently `sac_scale=difficult_alpine_hiking` is used for "hiking", not for "walking".

**Comment by MichaelsJP** [comment]
@TimMcCauley @rabidllama the issue goes right into the `graphhopper.extensions`. Does it correlate somehow  with the gh stuff coming up or with any wip?

**Comment by rabidllama** [comment]
Looking at OSM info relating to these tags, and us moving the foot encoders to ORS, it is more realistic to actually limit the walking profile to only include a sac_scale of hiking. Any others are not particularly suitable for a general walk, and so these should only appear if the user selects the hiking profile

**Comment by aoles** [comment]
So still no [_via ferratas_](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dvia_ferrata) with this update?
