### ISSUE TITLE
Document what is taken into account for which profiles

### ISSUE THREAD

**Issue by pathmapper** [GIScience/openrouteservice#174]
It would be useful to document which tags are considered for each profiles, e.g. to be able to find out easily which is the difference between the profiles `walking` and `hiking` or `Road bike` and `e-bike`.

Related: 
https://github.com/GIScience/openrouteservice-app/issues/220#issuecomment-389080656
https://github.com/GIScience/openrouteservice/issues/173

**Comment by pathmapper** [comment]
Additionally it would be useful to document if/how elevation and gradient changes are taken into account for the different profiles.

Related:
https://github.com/GIScience/openrouteservice/issues/198

**Comment by rabidllama** [comment]
We are currently in the process of updating how our routing profiles work, so we will include this information in the release that includes these changes

**Comment by rabidllama** [comment]
I am currently coming up with a template that we can use as a way of storing the tag information. When that is finalised the assignments will be:

Car - @aoles 
HGV - @aoles 
Bike (regular) - @marq24 
Mountain bike - @marq24 
Electric bike - @marq24 
Road bike - @marq24 
Walking - @rabidllama 
Hiking - @rabidllama 
Wheelchair - @rabidllama 

@marq24 - I guess that the bike ones are all pretty similar so once one is done the others should be pretty straightforward. If you need some assistance though let me know and we can see about getting @MichaelsJP involved

It will likely take a couple of iterations to get everything properly documented, but at least the flagencoders should be done for the 4.7.2/5.0 release

**Comment by rabidllama** [comment]
We have begun documenting this information on the wiki that we have recently set up:

https://github.com/GIScience/openrouteservice/wiki/Tag-Filtering

**Comment by pathmapper** [comment]
@rabidllama great, thanks a lot!

`Conditional`
> acceptance/rejection is based on other tags and logic

Some information regarding "other tags and logic" would be nice.

**Comment by rabidllama** [comment]
The problem with a number of the items is that the logic behind them can be quite complex and very difficult to show in a table or diagram. Sometimes they can be simpler (i.e. based on an app.config setting) but other times they can be quite complex, such as being dependant on a varaible in the code that is calculated based on a number of other factors.

**Comment by rabidllama** [comment]
Bike has been documented on the wiki now, so I will close this.

https://github.com/GIScience/openrouteservice/issues/558

https://github.com/GIScience/openrouteservice/wiki/Tag-Filtering#cycling-regular-bike---cycling-mountain-cycling-road-cycling-electric

**Comment by pathmapper** [comment]
> Bike has been documented on the wiki now, so I will close this.

@rabidllama looks like 
- cycling-mountain
- cycling-road
- cycling-electric 

are still missing.

Or are there no differences between the different bike profiles anymore?

**Comment by rabidllama** [comment]
@marq24 are there differences in the tags used?

**Comment by marq24** [comment]
there is/was one different handling of the sac_scale tag - I have updated the difference in the docu... 

https://github.com/GIScience/openrouteservice/wiki/Tag-Filtering#cycling-regular-bike-cycling-electric-cycling-road--cycling-mountain

Might be, that I totally missunderstand the source - but when I read the wiki and compare it to the encoder, then *only* the code of the ` acceptWay(ReaderWay way)` method will be documented... which at the end of the day define the "possible travel network"... from the network/possible ways the four cycling rofiles are almost identical - the main difference is the possible speeds for the dfferent ways/surfaces [that makes a big difference]
