### ISSUE TITLE
`hgv=delivery`-tags not considered properly

### ISSUE THREAD

**Issue by koebi** [GIScience/openrouteservice#1743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Where did you encounter this issue?

live API

### Request URL

https://api.openrouteservice.org/v2/pdirections/driving-hgv/geojson

### POST Request Body

```JSON
{
"preference":"recommended",
"geometry":true,
"options":{"vehicle_type":"delivery"},
"coordinates":[[10.857732,48.415395],[10.893041,48.369262]]
}
```

### Response

<details><summary>Response</summary>

```JSON

{"error":{"code":2009,"message":"Route could not be found - Unable to find a route between points 1 (10.8577320 48.4153950) and 2 (10.8930410 48.3692620)."},"info":{"engine":{"build_date":"2024-01-29T14:41:12Z","version":"7.1.1"},"timestamp":1710158524932}}

```
</details>

### Current behavior

The whole inner city of Augsburg is tagged with `hgv:delivery`.
Currently, a regular  `hgv` vehicle (no vehicle type) is able to enter the city, but a vehicle with vehicle type `delivery` is not.

### Expected behavior

A regular `hgv` vehicle (no vehicle type) should not be able to enter the city, but a vehicle with vehicle type `delivery` should be.

### Openrouteservice Version

7.1.1

### Build date

2024-01-29T14:41:12Z

**Comment by aoles** [comment]
Actually, the issue can be reproduced as well with the test graph on [Alstater Straße](https://www.openstreetmap.org/way/31791684) in HD-Kirchheim. 

Route for `vehicle_type` set to `hgv`:

![image](https://github.com/GIScience/openrouteservice/assets/6545356/938fa8cc-bf37-4627-82d7-8714b455f51b)

vs. `delivery`:

![image](https://github.com/GIScience/openrouteservice/assets/6545356/d7768cb2-b052-4747-a46c-51ec0ff7792c)
