### ISSUE TITLE
Error when opening page with installation instructions

### ISSUE THREAD

**Issue by eusener** [GIScience/openrouteservice#1747]
### Page Link

https://giscience.github.io/openrouteservice/run-instance/installation/

### Documentation is ...

Missing/Needed

### Please Explain in Detail:

the link has no documentation associated with it

### Your Proposal for Changes:

link url with documentation

**Comment by MichaelsJP** [comment]
@eusener Thanks for posting. Where did you encounter the dead link?
New documentation: https://giscience.github.io/openrouteservice/run-instance/

Generally, we're reworking the docs at this very moment and release a new version once finished.
Make sure to revisit them in the next days!

**Comment by eusener** [comment]
Tanks!
