### ISSUE TITLE
Preparation mode does not exit successfully after mapgen is complete

### ISSUE THREAD

**Issue by joewragg** [GIScience/openrouteservice#1763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If using preperation mode in routing the mapgen should finish and then the process should exit 0 instead it will just continue

### Proposed solution

In preperation mode it should exit 0 post mapgen

**Comment by aoles** [comment]
Fixed in https://github.com/GIScience/openrouteservice/pull/1772
