### ISSUE TITLE
Cannot find routable point

### ISSUE THREAD

**Issue by sfendrich** [GIScience/openrouteservice#1777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I can reproduce the issue mentioned in https://ask.openrouteservice.org/t/could-not-find-routable-point/5969 locally with the Guyana pbf downloaded from Geofabrik. The same request works on the public API.

### Proposed solution

?

### Forum Topic Link

https://ask.openrouteservice.org/t/could-not-find-routable-point/5969

**Comment by sfendrich** [comment]
The issue is caused by using an extract of Guyana instead of Guyane (French Guyana).

**Comment by sfendrich** [comment]
The issue is caused by using an extract of Guyana instead of Guyane (French Guyana).

**Comment by jpfleischer** [comment]
can also be because the user has latitude and longitude switched
