### ISSUE TITLE
Geojson format strips important extra_info

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#180]
When using `format=geojson`, any `extra_info=x` is missing from the response. Please integrate while staying geojson compliant. Add functional tests!!

`https://api.openrouteservice.org/directions?api_key=key&coordinates=8.34234,48.23424|8.34423,48.26424&instructions=false&profile=driving-car&extra_info=tollways|steepness&format=geojson`

**Comment by aoles** [comment]
When `format=geojson` any data for `extra_info` should probably go into an `extras` element under `properties` of a given `feature`.
