### ISSUE TITLE
How to instructions for adding more language

### ISSUE THREAD

**Issue by Namec** [GIScience/openrouteservice#181]
hello,

is there any directives or best practices to add more language to ORS.

great piece of engineering you have made !!

**Comment by rabidllama** [comment]
Hi @Namec,

thanks, and to add more languages you just need to add the new language file to the openrouteservice/src/main/resources/resources/locales folder following the format ors_xx.resources. 

In terms of best practices, you just need to make sure that you add translations for all of the items there (you can use ors_EN.resources as a guide to what needs to be entered). There are two entries for each item, one where there is a name of the street/road (name) and one where there is not (default).
