### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space despite correct configuration

### ISSUE THREAD

**Issue by luckyhandler** [GIScience/openrouteservice#1819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I'm using `openrouteservice:v8.1.1`

When running my container I run into a `java.lang.OutOfMemoryError: Java heap space` exception.
I start my container like:

```
docker run -d \
    --memory=20g \
    --memory-swap=20g \
    ors
```

and set the corresponding java flags in my DOCKERFILE

```
# Set default environment variables
ENV BUILD_GRAPHS=True
ENV JAVA_OPTS="-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms10g -Xmx20g"
ENV CATALINA_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"
```

Is there anything that I oversee or is it a bug?

In the logs I also see:

`ORS-Init [ o.h.o.r.RoutingProfileManager            ]   Total - 1024 MB, Free - 968.06 MB, Max: 2 GB, Used - 55.94 MB`

### Proposed solution

Consider the XMS and XMX params and make sure that container doesn't run into a `java.lang.OutOfMemoryError`.

**Comment by MichaelsJP** [comment]
@luckyhandler , thanks for opening this. The setup manages available memory and maps the graph using **three different parameters**.

# JVM Memory Settings XMX and XMS:
These parameters define the overall memory limit that the JVM can use at the system level.
Ensure these settings do not exceed your system's available RAM, keeping other processes in mind.
**Set the values as low as possible to avoid excessive usage.**
Example settings:
For a 2GB graph: XMS=512M and XMX=1G
For a larger graph (e.g., 15GB): XMS=512M and XMX=3G

# Data Access Property:
Besides the JVM settings, you need to instruct ORS to use memory mapping with the graphs data access property.
The relevant parameter is `ors.engine.graphs_data_access=MMAP"`.

**Example Setup:**
Below is an example of how to set up the directories and run the ORS Docker container with the appropriate settings:
```
# create directories for volumes to mount as local user
mkdir -p ors-docker/config ors-docker/elevation_cache ors-docker/graphs ors-docker/files ors-docker/logs 
docker run -dt --name ors-app \
  -p 8080:8082 \
  -v $PWD/ors-docker/config:/home/ors/config \
  -e "BUILD_GRAPHS=True" \
  -e "XMS=512M" \
  -e "XMX=3g" \
  -e "ors.engine.graphs_data_access=MMAP" \
  -v $PWD/ors-docker/config:/home/ors/config \
  -v $PWD/ors-docker/elevation_cache:/home/ors/elevation_cache \
  -v $PWD/ors-docker/graphs:/home/ors/graphs \
  -v $PWD/ors-docker/files:/home/ors/files \
  -v $PWD/ors-docker/logs:/home/ors/logs \
  openrouteservice/openrouteservice:latest
```
Add the `-e "ors.engine.source_file=your.osm.pbf" \` to reference a custom file in the ` $PWD/ors-docker/files` folder.

Please be aware, building graphs with MMAP activated takes longer. Running Graphs with MMAP is almost the same performance.

**Comment by MichaelsJP** [comment]
Closing due to probably being solved/inactivity.

**Comment by luckyhandler** [comment]
Just for the sake of completeness. What solved the issue for me was to exchange the once needed environment variables for ORS 7 

```
ENV BUILD_GRAPHS=False
ENV JAVA_OPTS="-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms10g -Xmx20g"
ENV CATALINA_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"
```

with those environment variables for ORS 8++
```
ENV BUILD_GRAPHS=False
ENV XMS=10g
ENV XMX=20g
```
