### ISSUE TITLE
no population returned for some isochrones

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#183]
the api returns a 3099 error _Unable to compute isochrone attributes._ for the following request
https://api.openrouteservice.org/isochrones?api_key=my-key&attributes=total_pop&format=json&interval=60&location_type=start&locations=8.411751,49.352414&profile=driving-car&range=540&range_type=time

with `interval=540` it works
also with `range` up to `300` and `interval=60`
but `range=360` then fails
but `range=360` and `interval=360` works again

**Comment by TimMcCauley** [comment]
Same as #297, fix in PR #330
