### ISSUE TITLE
Bike Profile - missing turn instruction (might be caused by the absence of surface tag?)

### ISSUE THREAD

**Issue by marq24** [GIScience/openrouteservice#184]
Initially this was posted in the google group - @TimMcCauley  asked me to bring that over o here... so I do...

Again I am struggling with a "missing" turn instruction...

first let's take a look at the road/map:
![image](https://user-images.githubusercontent.com/8012359/40915295-d22291a4-67fb-11e8-8a65-c10f9665f3a0.png)

ok that's quite easy - but you might be surprised (like me) that for bike(s) this is no right turn...

https://maps.openrouteservice.org/directions?n1=51.82876&n2=8.191611&n3=17&a=51.8305,8.191381,51.826999,8.190479&b=1a&c=0&g1=-1&g2=0&h2=3&k1=en-US&k2=km

give you the turn instructions:
![image](https://user-images.githubusercontent.com/8012359/40915384-1b095510-67fc-11e8-9702-d2d41a734dbf.png)

while for the car profile you get it!
https://maps.openrouteservice.org/directions?n1=51.82876&n2=8.191611&n3=17&a=51.8305,8.191381,51.826999,8.190479&b=0&c=0&k1=en-US&k2=km
![image](https://user-images.githubusercontent.com/8012359/40915317-e4f195c8-67fb-11e8-8fb8-6dfbc03358c8.png)

a quick check with GraphHopper's default bike profile:
https://graphhopper.com/maps/?point=51.830991%2C8.19108&point=51.827026%2C8.190351&locale=de-DE&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale
and also there you get the turn instruction...

So I spend time with the OSM-data of this place

the difference in the data is, that the both ways have the surface:asphalt tag - while the (red marked) section does not have any surface information - all three are tagged as highway:unclassified

![image](https://user-images.githubusercontent.com/8012359/40915401-2e90d356-67fc-11e8-8b78-43cdc8dcdd59.png)

So I finally have started to dig into the Routing profiles - and for now I was not able to find the root cause of this "missing" turn info - obviously GraphHopper (based on the given bike profile) believes that there is "no turn"... Any hint what could cause this? I am assuming it's somewhere in your extended heigit.ors.routing.graphhopper.extensions.flagencoders

**Comment by marq24** [comment]
I have investigated this issue further - and have some more insights that I wanted to share with you.

When I create separate ORS profiles (own graphs) for cycling-mtb and cycling-road then I get a turn instruction for road bikes - but none for mtb - as soon as I combine different cycling profiles to a single graph folder the turn instruction is missing when the mtb FlagEncoder is included.

So we have (IMHO) two issues here:

1. For some reason mtb FlagEncoder ignoring the one path the red one (in the OSM-DATA-Screenshot)
2. Combining different FlagEncoders into one Profile might cause some issues (but this is just a speculation right now)

**Comment by rabidllama** [comment]
@marq24 Was this fixed in the update?

**Comment by rabidllama** [comment]
Just checked and it seems that I get a "turn right" instruction for that route on bike now so I will mark it as closed
