### ISSUE TITLE
Unable to scroll the sidenav in https://openrouteservice.org/dev/#/api-docs/

### ISSUE THREAD

**Issue by Harshal141** [GIScience/openrouteservice#1845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

While scrolling through the docs I noticed I was not able to scroll and see all the available options in the sidebar on the page, https://openrouteservice.org/dev/#/api-docs/isochrones%20service. 

I tried putting the cursor in various sections and scrolling but was not able to see all the available content in the sidebar.

### Proposed solution

Not sure what the problem is maybe the event bubbling.

### Additional context

none

**Comment by TheGreatRefrigerator** [comment]
This was an issue with how the navigation sidebar was done. You should now be able to scroll it at any window height.
