### ISSUE TITLE
Drivetime Isochrones vs. google maps

### ISSUE THREAD

**Issue by JK87iab** [GIScience/openrouteservice#185]
Hi
I am trying to get drivetime isochrones but if I check the polygon inside google maps the drive time is way off.

`https://api.openrouteservice.org/isochrones?api_key=**APIKEY**&locations=-74.184299%2C40.7828954&profile=driving-car&range_type=time&range=120&interval=60&location_type=destination&attributes=&options=&intersections=&id=`

returns

`{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-74.193192,40.781677],[-74.19315,40.781616],[-74.191131,40.778674],[-74.190483,40.777736],[-74.185977,40.775431],[-74.174191,40.776145],[-74.172405,40.777707],[-74.172394,40.77772],[-74.172357,40.777896],[-74.172788,40.77946],[-74.178279,40.786368],[-74.178756,40.786654],[-74.178875,40.786726],[-74.179233,40.786941],[-74.179715,40.78723],[-74.180311,40.787588],[-74.182452,40.788728],[-74.191761,40.789845],[-74.193174,40.786534],[-74.193192,40.781677]]]},"properties":{"group_index":0,"value":60,"center":[-74.184299,40.782895]}},{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-74.202805,40.782161],[-74.197882,40.771655],[-74.195735,40.770116],[-74.195596,40.770075],[-74.183806,40.768047],[-74.182226,40.768502],[-74.17949,40.769288],[-74.171456,40.771136],[-74.166759,40.771831],[-74.165418,40.772401],[-74.164837,40.773317],[-74.163043,40.776948],[-74.163934,40.779077],[-74.166396,40.780836],[-74.171128,40.789708],[-74.171538,40.790485],[-74.173634,40.790453],[-74.180355,40.791422],[-74.189658,40.795921],[-74.191267,40.797125],[-74.197474,40.797469],[-74.199211,40.796033],[-74.200577,40.792083],[-74.200602,40.792003],[-74.202775,40.782472],[-74.202805,40.782161]]]},"properties":{"group_index":0,"value":120,"center":[-74.184299,40.782895]}}],"bbox":[-74.202805,40.768047,0,40.797469],"info":{"osm_file_md5_hash":"783b5a0ed086d6cc3eb6f98df9d5d79b","engine":{"version":"4.5.0","build_date":"2018-03-26T13:41:46Z"},"service":"isochrones","query":{"ranges":"60.0,120.0","profile":"driving-car","locations":[[-74.184299,40.782895]],"range_type":"time","location_type":"destination"},"attribution":"openrouteservice.org | OpenStreetMap contributors","timestamp":1528131829299}}`

If I just check the distance between `-74.184299, 40.782895`  and  `-74.200602,40.792003` I get 8min in google maps vs. 2 min in openrouteservice 

I assume the api call returns WGS84  #?

**Comment by rabidllama** [comment]
Hi @JK87iab , 
This is an issue to do with traveling speeds and we are currently working on getting it fixed (see issue #178)
