### ISSUE TITLE
missing Vietnamese translation

### ISSUE THREAD

**Issue by haupv1m** [GIScience/openrouteservice#1857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature/Enhancement Proposal

There is currently not a translation file for OpenRouteService in Vietnamese

### Possible Implementation

Add a translation file.

**Comment by TheGreatRefrigerator** [comment]
Hi @haupv1m,

feel free to contribute a PR.
You can find more info on how to [contribute a language](https://giscience.github.io/openrouteservice/contributing/contributing-translations#translations) in our docs.

Best regards

**Comment by haupv1m** [comment]
Thank @TheGreatRefrigerator, I already create a PR for this issue. Could you help me review it.

Best regards,
