### ISSUE TITLE
Take into account hazmat tunnel categories

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#1874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature/Enhancement Proposal

Currently, filtering on `hazmat` roads is performed only for ways tagged with `hazmat=no` ignoring more detailed tagging relevant for [tunnel restrictions](https://wiki.openstreetmap.org/wiki/Key:hazmat#Tunnel_restrictions). A query to taginfo revealed that as for today there are in total around 10k ways tagged with `hazmat:[B|C|D|E]=no` compared to 17K ways tagged with `hazmat=no`.

``` r
# query data from taginfo
url <- "https://taginfo.openstreetmap.org/api/4/key/values?key=%s&filter=ways&sortname=count&sortorder=desc&qtype=value"

ran <- 2:5
key <- "hazmat"
keys <- c(key, paste(key, LETTERS[ran], sep=":"))

# distribution of hazmat "no" tags
(res <- sapply(keys, function(key) {
  data <- jsonlite::fromJSON(sprintf(url, key))$data
  with(data, count[value=="no"])
}))
#>   hazmat hazmat:B hazmat:C hazmat:D hazmat:E 
#>    17308     2966     2887     1942     2201

sum(res[ran])
#> [1] 9996
```

<sup>Created on 2024-10-26 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### Possible Implementation

Extend the tag list in the following.
https://github.com/GIScience/openrouteservice/blob/c8ef81c9c77d7625a053884102a81fc2c0b9ce0f/ors-engine/src/main/java/org/heigit/ors/routing/graphhopper/extensions/storages/builders/HeavyVehicleGraphStorageBuilder.java#L186-L188

### Forum Topic Link

https://ask.openrouteservice.org/t/hazmat-options-or-workaround/6614

**Comment by MichaelsJP** [comment]
Nice. 10k additional haznat tags in tunnels would be pretty cool
