### ISSUE TITLE
Add UA (ukrainian) translation

### ISSUE THREAD

**Issue by ownerofglory** [GIScience/openrouteservice#1880]
### Documentation is ...

Missing/Needed

### Please Explain in Detail:

I'd like to add Ukrainian translation for the openrouteservice instruction.

### Your Proposal for Changes:

Adding a Ukrainian translation for the openrouteservice instruction.

**Comment by aoles** [comment]
Thanks for reaching out! ❤️ 

You can find information on how to add a new translation of the instructions generated by ORS in the [backend documentation](https://giscience.github.io/openrouteservice/contributing/contributing-translations). Feel free to have a look at the [maps client](https://github.com/GIScience/ors-map-client/#add-language) if you would like to contribute the language to there as well.

Looking forward to your pull request. Cheers!
