### ISSUE TITLE
Parameter 'profile' has incorrect value of 'unknown'

### ISSUE THREAD

**Issue by Seafarine** [GIScience/openrouteservice#1922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Where did you encounter this issue?

self-hosted instance

### Request URL

http://localhost:8082/ors/v2/directions/diving-car

### POST Request Body

```JSON
{"error":{"code":2003,"message":"Parameter 'profile' has incorrect value of 'unknown'."},"info":{"engine":{"build_date":"2024-12-02T11:09:21Z","graph_version":"1","version":"9.0.0"},"timestamp":1733148649519}}
```

### Response

<details><summary>Response</summary>

```JSON

{"error":{"code":2003,"message":"Parameter 'profile' has incorrect value of 'unknown'."},"info":{"engine":{"build_date":"2024-12-02T11:09:21Z","graph_version":"1","version":"9.0.0"},"timestamp":1733148649519}}

```
</details>

### Current behavior

I was setup the openrouteservice in docker and there's no case to the "profile", i was 2 hours trying to solve the problem and nothing, someone can help me?

This is my profile:
<pre>
<code>
################################################################################################
################################################################################################

################################################################################
################################################################################
##### General server settings #####
server:
  port: 8082
#  error:
#    whitelabel:
#      enabled: false
#  # Keep the context-path at / else the war file run with tomcat will have the context-path of /ors/v2 as well.
#  servlet:
#    context-path: /ors
#  tomcat:
#    keep-alive-timeout: 30000
spring:
  profiles:
    active: default
#  mvc:
#    servlet:
#      path: /
##### Settings related to springdoc #####
#springdoc:
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui
#    tryItOutEnabled: true
#    filter: false
#    syntaxHighlight:
#      activated: true
#    showExtensions: true
#  api-docs:
#    path: /v2/api-docs
#    version: OPENAPI_3_0
#  packages-to-scan: org.heigit.ors
#  pathsToMatch: /v2/**
##### Logging settings #####
#logging:
#  file:
#    name: ./logs/ors.log
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight{%-7p} %style{%50t}{Cyan} %style{[ %-40.40c{1.} ]}{Bright Cyan}   %m%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} %p [%-40.40c{1.}] - %m%n"
#  level:
#    root: WARN
#    org.heigit: INFO
##### openrouteservice specific settings #####
ors:
#  cors:
#    allowed_origins: "*"
#    allowed_headers: Content-Type, X-Requested-With, accept, Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization
#    preflight_max_age: 600
#  messages:
#  ##### ORS endpoints settings #####
#  endpoints:
#    routing:
#      enabled: true
#      attribution: openrouteservice.org, OpenStreetMap contributors, tmc - BASt
#      gpx_name: ORSRouting
#      gpx_description: This is a directions instructions file as GPX, generated from openrouteservice
#      gpx_base_url: https://openrouteservice.org/
#      gpx_support_mail: support@openrouteservice.org
#      gpx_author: openrouteservice
#      gpx_content_licence: LGPL 3.0
#      maximum_avoid_polygon_area: 200000000
#      maximum_avoid_polygon_extent: 20000
#      maximum_alternative_routes: 3
#    matrix:
#      enabled: true
#      attribution: openrouteservice.org, OpenStreetMap contributors
#      maximum_routes: 2500
#      maximum_routes_flexible: 25
#      maximum_visited_nodes: 100000
#      maximum_search_radius: 2000
#      u_turn_costs: -1
#    isochrones:
#      enabled: true
#      attribution: openrouteservice.org, OpenStreetMap contributors
#      maximum_locations: 2
#      maximum_intervals: 1
#      allow_compute_area: true
#      maximum_range_distance_default: 50000
#      maximum_range_distance:
#        - profiles: driving-car, driving-hgv
#          value: 100000
#      maximum_range_time_default: 18000
#      maximum_range_time:
#        - profiles: driving-car, driving-hgv
#          value: 3600
#      fastisochrones:
#        maximum_range_distance_default: 50000
#        maximum_range_distance:
#          - profiles: driving-car, driving-hgv
#            value: 500000
#        maximum_range_time_default: 18000
#        maximum_range_time:
#          - profiles: driving-car, driving-hgv
#            value: 10800
#    snap:
#      enabled: true
#      attribution: openrouteservice.org, OpenStreetMap contributors
#      maximum_locations: 5000
#  ##### ORS engine settings #####
  engine:
#    init_threads: 1
#    preparation_mode: false
#    graphs_data_access: RAM_STORE
#    elevation:
#      preprocessed: false
#      data_access: MMAP
#      cache_clear: false
#      provider: multi
#      cache_path: elevation_cache
    profile_default:
#      enabled: false
#      graph_path: graphs
      build:
        source_file: /home/ors/files/chile-latest.osm.pbf
#        elevation: true
#        elevation_smoothing: false
#        encoder_flags_size: 8
#        instructions: true
#        optimize: false
#        traffic: false
#        maximum_speed_lower_bound: 80
#        location_index_resolution: 500
#        location_index_search_iterations: 4
#        interpolate_bridges_and_tunnels: true
#        preparation:
#          min_network_size: 200
#          methods:
#            lm:
#              enabled: true
#              threads: 1
#              weightings: recommended,shortest
#              landmarks: 16
#      service:
#        maximum_distance: 100000
#        maximum_distance_dynamic_weights: 100000
#        maximum_distance_avoid_areas: 100000
#        maximum_waypoints: 50
#        maximum_snapping_radius: 400
#        maximum_distance_alternative_routes: 100000
#        maximum_distance_round_trip_routes: 100000
#        maximum_visited_nodes: 1000000
#        force_turn_costs: false
#        execution:
#          methods:
#            lm:
#              active_landmarks: 8
#    ##### Profile specific settings,                               #####
#    ##### overriding the properties in ors.engine.profile_default. #####
#    ##### Profile defaults defined here are not overridden by      #####
#    ##### a custom YAML file's ors.engine.profile_default, but by  #####
#    ##### a custom YAML file's ors.engine.profiles.<profile>       #####
    profiles:
      driving-car:
        enabled: true
        encoder_name: driving-car
        build:
          encoder_options:
            turn_costs: true
            block_fords: false
            use_acceleration: true
          preparation:
            min_network_size: 200
            methods:
              ch:
                enabled: true
                threads: 1
                weightings: fastest
              lm:
                enabled: false
              core:
                enabled: true
                threads: 1
                weightings: fastest,shortest
                landmarks: 64
                lmsets: highways;allow_all
          ext_storages:
            WayCategory:
            HeavyVehicle:
            Tollways:
            WaySurfaceType:
            RoadAccessRestrictions:
              use_for_warnings: true
        service:
          execution:
            methods:
              lm:
                active_landmarks: 6
              core:
                active_landmarks: 6
#      driving-hgv:
#        encoder_name: driving-hgv
#        build:
#          encoder_options:
#            turn_costs: true
#            block_fords: false
#            use_acceleration: true
#          preparation:
#            min_network_size: 200
#            methods:
#              ch:
#                enabled: true
#                threads: 1
#                weightings: recommended
#              lm:
#                enabled: false
#              core:
#                enabled: true
#                threads: 1
#                weightings: recommended,shortest
#                landmarks: 64
#                lmsets: highways;allow_all
#          ext_storages:
#            WayCategory:
#            HeavyVehicle:
#              restrictions: true
#            Tollways:
#            WaySurfaceType:
#        service:
#          execution:
#            methods:
#              core:
#                active_landmarks: 6
#      cycling-regular:
#        encoder_name: cycling-regular
#        build:
#          encoder_options:
#            consider_elevation: true
#            turn_costs: true
#            block_fords: false
#          ext_storages:
#            WayCategory:
#            WaySurfaceType:
#            HillIndex:
#            TrailDifficulty:
#      cycling-mountain:
#        encoder_name: cycling-mountain
#        build:
#          encoder_options:
#            consider_elevation: true
#            turn_costs: true
#            block_fords: false
#          ext_storages:
#            WayCategory:
#            WaySurfaceType:
#            HillIndex:
#            TrailDifficulty:
#      cycling-road:
#        encoder_name: cycling-road
#        build:
#          encoder_options:
#            consider_elevation: true
#            turn_costs: true
#            block_fords: false
#          ext_storages:
#            WayCategory:
#            WaySurfaceType:
#            HillIndex:
#            TrailDifficulty:
#      cycling-electric:
#        encoder_name: cycling-electric
#        build:
#          encoder_options:
#            consider_elevation: true
#            turn_costs: true
#            block_fords: false
#          ext_storages:
#            WayCategory:
#            WaySurfaceType:
#            HillIndex:
#            TrailDifficulty:
#      foot-walking:
#        encoder_name: foot-walking
#        build:
#          encoder_options:
#            block_fords: false
#          ext_storages:
#            WayCategory:
#            WaySurfaceType:
#            HillIndex:
#            TrailDifficulty:
#      foot-hiking:
#        encoder_name: foot-hiking
#        build:
#          encoder_options:
#            block_fords: false
#          ext_storages:
#            WayCategory:
#            WaySurfaceType:
#            HillIndex:
#            TrailDifficulty:
#      wheelchair:
#        encoder_name: wheelchair
#        build:
#          encoder_options:
#            block_fords: true
#          ext_storages:
#            WayCategory:
#            WaySurfaceType:
#            Wheelchair:
#              kerbs_on_crossings: true
#            OsmId:
#        service:
#          maximum_snapping_radius: 50
#      public-transport:
#        encoder_name: public-transport
#        build:
#          encoder_options:
#            block_fords: false
#          elevation: true
#          gtfs_file: ./src/test/files/vrn_gtfs_cut.zip
#        service:
#          maximum_visited_nodes: 1000000
</code>
</pre>

### Expected behavior

Give me the instructions

### Openrouteservice Version

9.0.0

### Build date

today

### Graph date

today

### Forum Topic Link

https://ask.openrouteservice.org/t/problem-with-different-profiles/2096

**Comment by MichaelsJP** [comment]
@Seafarine Thanks for opening. Please correct `http://localhost:8082/ors/v2/directions/diving-car` to `http://localhost:8082/ors/v2/directions/driving-car` and try again. The `r` in `driving-car` seems missing.

**Comment by Seafarine** [comment]
{"error":{"code":2003,"message":"Parameter 'profile' has incorrect value of 'unknown'."},"info":{"engine":{"build_date":"2024-12-02T11:09:21Z","graph_version":"1","version":"9.0.0"},"timestamp":1733425279336}}

<pre><code>
import requests
import json

# Coordenadas de ejemplo (origen y destino)
coords = [
    [-70.7086576, -33.3995031],  # Origen (longitud, latitud)
    [-70.789104, -33.215856]    # Destino (longitud, latitud)
]

# URL base de OpenRouteService
base_url = 'http://localhost:8082/ors/v2/directions/driving-car'

# Parámetros de costos (puedes personalizarlos según tus necesidades)
precio_bencina_por_litro = 1.50  # dólares/litro
consumo_km_por_litro = 10  # km/litro
costo_diario_viaticos = 100  # dólares/día
dias_viaje = 2  # días

# Construir la carga útil de la solicitud
payload = {
    "coordinates": coords,
    "instructions": True,
    "extra_info": ["tollways"]
}

try:
    # Realizar la solicitud HTTP POST
    response = requests.post(base_url, json=payload)

    # Comprobar el estado de la respuesta
    if response.status_code != 200:
        print(f"Error en la solicitud: {response.status_code} - {response.text}")
    else:
        # Procesar la respuesta JSON
        routes = response.json()

        # Imprime el JSON completo de respuesta
        print("Respuesta JSON completa:")
        print(json.dumps(routes, indent=4))

        # Extraer la distancia total del resultado (en metros)
        distancia_metros = routes['routes'][0]['summary']['distance']
        distancia_km = distancia_metros / 1000  # convertir a kilómetros

        # Extraer la duración total del viaje (en segundos)
        duracion_segundos = routes['routes'][0]['summary']['duration']
        duracion_minutos = duracion_segundos / 60  # convertir a minutos

        # Extraer los pasos detallados de la ruta
        pasos = routes['routes'][0]['segments'][0]['steps']

        # Extraer los peajes de la respuesta (en la sección de detalles de la ruta)
        peajes_totales = 0  # Inicialmente en 0
        if 'extras' in routes['routes'][0]:
            tollways = routes['routes'][0]['extras'].get('tollways', {}).get('values', [])
            for tollway in tollways:
                peajes_totales += tollway[2]  # Acumular los costos de los peajes

        # Cálculo del costo de bencina
        costo_bencina = (distancia_km / consumo_km_por_litro) * precio_bencina_por_litro

        # Cálculo de los viáticos
        costo_viaticos = dias_viaje * costo_diario_viaticos

        # Cálculo del costo total
        costo_total = costo_bencina + peajes_totales + costo_viaticos

        # Imprime los resultados
        print(f"Distancia total del viaje: {distancia_km:.2f} km")
        print(f"Duración estimada del viaje: {duracion_minutos:.2f} minutos")
        print(f"Costo de bencina: ${costo_bencina:.2f}")
        print(f"Costo de peajes: ${peajes_totales:.2f}")
        print(f"Costo de viáticos: ${costo_viaticos:.2f}")
        print(f"Costo total del viaje: ${costo_total:.2f}")

        # Detalles de los pasos de la ruta
        print("\nDetalles de la ruta:")
        for i, paso in enumerate(pasos, start=1):
            distancia_paso = paso['distance']
            duracion_paso = paso['duration']
            instruccion = paso['instruction']
            print(f"Paso {i}:")
            print(f"  Instrucción: {instruccion}")
            print(f"  Distancia: {distancia_paso:.2f} metros")
            print(f"  Duración: {duracion_paso:.2f} segundos\n")

except requests.RequestException as e:
    print("Ocurrió un error al realizar la solicitud HTTP:", e)


<pre><code>



Do you know what can be happening to the main.py?

**Comment by Dave33KK** [comment]
I have the same issue with almost identical setup, since v9.0.0
Is there any news to this issue?

**Comment by sfendrich** [comment]
From studying the code I have no explanation for this behavior, except a typo as @MichaelsJP already pointed out. If you are certain, there is no typo you may try the following to narrow down the issue:
* Does it also happen when using curl instead of python?
* Does it also happen when using one of the alternative output formats? You would need to append `/json`, `/geojson` or `/gpx` to your bas-url.

**Comment by koebi** [comment]
In addition to that, it seems like you are running your own instance of openrouteservice.
Note, that the profile names might have changed in version 9.0.0, see [the backend documentation on profiles.](https://giscience.github.io/openrouteservice/run-instance/configuration/engine/profiles/)

**Comment by Dave33KK** [comment]
I found the mistake in my config.

For v8.2.0 I had following config: 
ors.engine.profiles.car.profile=driving-car
ors.engine.profiles.bike-regular.profile=cycling-regular
ors.engine.profiles.walking.profile=foot-walking

so my endpoints were...

 /ors/v2/isochrones/driving-car
 /ors/v2/isochrones/cycling-regular
 /ors/v2/isochrones/foot-walking


We updated to v.9.0.0 and changed the config to:
ors.engine.profiles.driving-car
ors.engine.profiles.cycling-regular
ors.engine.profiles.foot-walking

Now the endpoints are working fine again.
Setting this: ors.engine.profiles.<random_profile_name>.profile=foot-walking does not seem to be supported anymore

**Comment by Dave33KK** [comment]
I found the mistake in my config.

For v8.2.0 I had following config:
ors.engine.profiles.car.profile=driving-car
ors.engine.profiles.bike-regular.profile=cycling-regular
ors.engine.profiles.walking.profile=foot-walking

so my endpoints were...

/ors/v2/isochrones/driving-car
/ors/v2/isochrones/cycling-regular
/ors/v2/isochrones/foot-walking

We updated to v.9.0.0 and changed the config to:
ors.engine.profiles.driving-car
ors.engine.profiles.cycling-regular
ors.engine.profiles.foot-walking

Now the endpoints are working fine again.
Setting this: ors.engine.profiles.<random_profile_name>.profile=foot-walking does not seem to be supported anymore

**Comment by sfendrich** [comment]
> Setting this: ors.engine.profiles.<random_profile_name>.profile=foot-walking does not seem to be supported anymore

I believe that this was not working prior to version 9. Although it was possible to set an arbitrary name and build graphs, AFAIK, it was not possible to send requests to this profile name, because the profile name and the encoder name where strongly coupled. With version 9 this has been decoupled and should work now. The profile name is arbitrary, the encoder names are fixed, the request is sent to the profile name.

**Comment by sijakubo** [comment]
Just a short info from our side. 

We encountered the same problem and constantly tried to change around the configuration. 
But it turned out, that the Service just needed some time to calculate its graphs.

Beforehand, the service always returned the error: `Parameter 'profile' has incorrect value of 'unknown'.` 

As soon as the graph was calculated:
```
ORS-pl-driving-car [ o.h.o.r.g.e.c.CoreLMPreparationHandler   ]   Finished LM preparation, ...
ORS-pl-driving-car [ o.h.o.r.g.e.ORSGraphHopper               ]   flushing graph CH|car_ors|RAM_STO...
ORS-pl-driving-car [ o.h.o.r.g.e.ORSGraphHopper               ]   flushed graph ...
```

we were able to get "driving-car" directions
