### ISSUE TITLE
Directions API is not working

### ISSUE THREAD

**Issue by ZanhNe** [GIScience/openrouteservice#1934]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Where did you encounter this issue?

live API

### Request URL

https://api.openrouteservice.org/v2/directions/driving-car/geojson

### POST Request Body

```JSON
body = {"coordinates":[[8.681495,49.41461],[8.686507,49.41943],[8.687872,49.420318]]}
```

### Response

<details><summary>Response</summary>

```JSON

Invalid API key or access to this API has been disallowed

```
</details>

### Current behavior

I want to get directions from Directions API but i always get error with status code 403. But 2 days ago I used it normally, no problem, I also attached the API KEY so the problem is not with the API KEY

### Expected behavior

It must return an direction object

### Openrouteservice Version

9.0.0

**Comment by koebi** [comment]
Hey,
you seem to have caught the ~30 mins or so where we re-load new data into the openrouteservice.
Feel free to re-open the issue if the problem persists, but it should work again :)
Best regards
