### ISSUE TITLE
Docker compose changes not reflected in documentation

### ISSUE THREAD

**Issue by takb** [GIScience/openrouteservice#1937]
### Page Link

https://giscience.github.io/openrouteservice/run-instance/running-with-docker

### Documentation is ...

Incorrect

### Please Explain in Detail:

The documentation still assumes the docker-compose.yml is configured to pull the image from dockerhub by default, which has been changed lately.  

### Your Proposal for Changes:

Adjust accordingly.

**Comment by koebi** [comment]
As I see it, the documentation does not mention where the image is pulled from.
Did I overlook that?
Should we mention that?

**Comment by takb** [comment]
@jhaeu cleared up, the docker compose is modified in workflow and the release artifact version of docker compose still works the old way
