### ISSUE TITLE
Missing <rte> tag in GPX response when instructions or geometry set to false

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#196]
When `instructions=false` or `geometry=false` there is no `<rte>` element in the response, e.g. the following request `https://api.openrouteservice.org/directions?api_key=<ors_api_key>&coordinates=8.34234%2C48.23424|8.34423%2C48.26424&profile=driving-car&format=gpx&instructions=false` produces the result below.

This is probably the cause of https://github.com/GIScience/openrouteservice-schema/issues/2.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<gpx version="1.0" creator="openrouteservice" xmlns="https://raw.githubusercontent.com/GIScience/openrouteservice-schema/master/gpx/v1/ors-gpx.xsd">
    <metadata>
        <name>openrouteservice directions</name>
        <desc>This is a directions instructions file as GPX, generated from openrouteservice</desc>
        <author>
            <name>openrouteservice</name>
            <email id="support" domain="@openrouteservice.org"/>
            <link href="https://go.openrouteservice.org/">
                <text>https://go.openrouteservice.org/</text>
                <type>text/html</type>
            </link>
        </author>
        <copyright author="openrouteservice.org | OpenStreetMap contributors">
            <year>2018Z</year>
            <license>Apache License 2.0</license>
        </copyright>
        <time>2018-05-30T07:55:11.005Z</time>
        <bounds minlat="48.23194589239238" minlon="8.327138051252172" maxlat="48.26355238245595" maxlon="8.345244266359007"/>
    </metadata>
    <extensions>
        <attribution>openrouteservice.org | OpenStreetMap contributors</attribution>
        <engine>4.5.0</engine>
        <build_date>2018-03-26T14:15:39Z</build_date>
        <profile>fastest</profile>
        <preference>driving-car</preference>
        <language>en</language>
        <distance-units>Meters</distance-units>
        <instructions>false</instructions>
        <elevation>false</elevation>
    </extensions>
</gpx>
```

**Comment by MichaelsJP** [comment]
I found kind of a fix. The parser is now able to parse requests without instructions and returns the bare route. But when geometry is turned off the result will be empty. The reason is that it's not possible to return a route in a gpx without any coordinates. It is not "legal" in terms of the gpx standard.

**Comment by aoles** [comment]
Many thanks @MichaelsJP for your work on this and for the explanation. I'm not sure I understand this correctly, but according to [GPX 1.1 Schema](http://www.topografix.com/GPX/1/1/gpx.xsd) `rteType` doesn't need to contain any `<rtept>` elements containing coordinates:

```xml
<xsd:complexType name="rteType">
    ...
    <xsd:element name="rtept" type="wptType" minOccurs="0" maxOccurs="unbounded">
```
So it seems to me that a GPX response containing a `<rte>` without any `<rtept>`s but with`<extensions>` would be perfectly fine. For a query with `geometry=false` I would expect to get at least `<distance>` and `<duration>` under `<rte><extensions>`, which would be in pair with the json output format.
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<gpx version="1.0" creator="openrouteservice" xmlns="https://raw.githubusercontent.com/GIScience/openrouteservice-schema/master/gpx/v1/ors-gpx.xsd">
    <metadata>
       ...
    </metadata>
    <rte>
        <extensions>
            <distance>5799.7</distance>
            <duration>857.1</duration>
            <distanceActual>5799.8</distanceActual>
            <ascent>0.0</ascent>
            <descent>0.0</descent>
            <avgSpeed>24.4</avgSpeed>
        </extensions>
    </rte>
    <extensions>
        ...
    </extensions>
</gpx>
```

**Comment by MichaelsJP** [comment]
@aoles 

> <xsd:complexType name="rteType"> ... <xsd:element name="rtept" type="wptType" minOccurs="0" maxOccurs="unbounded">

That is true. I investigated the ors backend a bit and it seems that when geometry=false and instructions=true are set, internally there are no route steps calculated. So there is no way to get the bare route step instructions without the coordinates.


> <?xml version="1.0" encoding="UTF-8" standalone="yes"?> <gpx version="1.0" creator="openrouteservice" xmlns="https://raw.githubusercontent.com/GIScience/openrouteservice-schema/master/gpx/v1/ors-gpx.xsd"> <metadata> ... </metadata> <rte> <extensions> <distance>5799.7</distance> <duration>857.1</duration> <distanceActual>5799.8</distanceActual> <ascent>0.0</ascent> <descent>0.0</descent> <avgSpeed>24.4</avgSpeed> </extensions> </rte> <extensions> ... </extensions> </gpx>

When geometry=false I will always return at least this. Hope that is kind of understandable?!

**Comment by MichaelsJP** [comment]
@aoles So geometry=true and instructions=true

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:gpx version="1.0" creator="openrouteservice" xmlns:ns2="https://raw.githubusercontent.com/GIScience/openrouteservice-schema/master/gpx/v1/ors-gpx.xsd">
    <ns2:metadata>
        <ns2:name>openrouteservice routing</ns2:name>
        <ns2:desc>This is a routing file from openrouteservice</ns2:desc>
        <ns2:author>
            <ns2:name>openrouteservice</ns2:name>
            <ns2:email id="support" domain="@openrouteservice.org"/>
            <ns2:link href="https://go.openrouteservice.org/">
                <ns2:text>https://go.openrouteservice.org/</ns2:text>
                <ns2:type>text/html</ns2:type>
            </ns2:link>
        </ns2:author>
        <ns2:copyright author="openrouteservice.org, OpenStreetMap contributors">
            <ns2:year>2018+02:00</ns2:year>
            <ns2:license>Apache License 2.0</ns2:license>
        </ns2:copyright>
        <ns2:time>2018-06-27T12:09:01.708+02:00</ns2:time>
        <ns2:bounds minlat="49.415936297702714" minlon="8.681480080490838" maxlat="49.41727610865107" maxlon="8.681872867387671"/>
    </ns2:metadata>
    <ns2:rte>
        <ns2:rtept lat="49.415936297702714" lon="8.681480080490838">
            <ns2:ele>115.5</ns2:ele>
            <ns2:name>Wielandtstraße</ns2:name>
            <ns2:desc>Head north on Wielandtstraße</ns2:desc>
            <ns2:extensions>
                <ns2:distance>151.8</ns2:distance>
                <ns2:duration>21.9</ns2:duration>
                <ns2:type>11</ns2:type>
                <ns2:step>0</ns2:step>
            </ns2:extensions>
        </ns2:rtept>
        <ns2:rtept lat="49.41608736849027" lon="8.681509279046415">
            <ns2:ele>115.25</ns2:ele>
            <ns2:name>Wielandtstraße</ns2:name>
            <ns2:desc>Head north on Wielandtstraße</ns2:desc>
            <ns2:extensions>
                <ns2:distance>151.8</ns2:distance>
                <ns2:duration>21.9</ns2:duration>
                <ns2:type>11</ns2:type>
                <ns2:step>1</ns2:step>
            </ns2:extensions>
        </ns2:rtept>
        <ns2:rtept lat="49.416600340975826" lon="8.681673936881287">
            <ns2:ele>114.64285714285714</ns2:ele>
            <ns2:name>Wielandtstraße</ns2:name>
            <ns2:desc>Head north on Wielandtstraße</ns2:desc>
            <ns2:extensions>
                <ns2:distance>151.8</ns2:distance>
                <ns2:duration>21.9</ns2:duration>
                <ns2:type>11</ns2:type>
                <ns2:step>2</ns2:step>
            </ns2:extensions>
        </ns2:rtept>
        <ns2:rtept lat="49.4170792270544" lon="8.681815311651274">
            <ns2:ele>114.875</ns2:ele>
            <ns2:name>Wielandtstraße</ns2:name>
            <ns2:desc>Head north on Wielandtstraße</ns2:desc>
            <ns2:extensions>
                <ns2:distance>151.8</ns2:distance>
                <ns2:duration>21.9</ns2:duration>
                <ns2:type>11</ns2:type>
                <ns2:step>3</ns2:step>
            </ns2:extensions>
        </ns2:rtept>
        <ns2:rtept lat="49.41727610865107" lon="8.681872867387671">
            <ns2:ele>115.03571428571429</ns2:ele>
            <ns2:name>Wielandtstraße</ns2:name>
            <ns2:desc>Head north on Wielandtstraße</ns2:desc>
            <ns2:extensions>
                <ns2:distance>151.8</ns2:distance>
                <ns2:duration>21.9</ns2:duration>
                <ns2:type>11</ns2:type>
                <ns2:step>4</ns2:step>
            </ns2:extensions>
        </ns2:rtept>
        <ns2:extensions>
            <ns2:distance>151.8</ns2:distance>
            <ns2:duration>21.9</ns2:duration>
            <ns2:distanceActual>151.8</ns2:distanceActual>
            <ns2:ascent>0.4</ns2:ascent>
            <ns2:descent>0.9</ns2:descent>
            <ns2:avgSpeed>25.0</ns2:avgSpeed>
            <ns2:BBox>
                <minLon>8.681480080490838</minLon>
                <maxLon>8.681872867387671</maxLon>
                <minLat>49.415936297702714</minLat>
                <maxLat>49.41727610865107</maxLat>
                <minEle>NaN</minEle>
                <maxEle>NaN</maxEle>
            </ns2:BBox>
        </ns2:extensions>
    </ns2:rte>
    <ns2:extensions>
        <ns2:attribution>openrouteservice.org, OpenStreetMap contributors</ns2:attribution>
        <ns2:engine>4.5.0</ns2:engine>
        <ns2:build_date>2018-06-27T09:56:44Z</ns2:build_date>
        <ns2:profile>fastest</ns2:profile>
        <ns2:preference>driving-ecar</ns2:preference>
        <ns2:language>en</ns2:language>
        <ns2:distance-units>Meters</ns2:distance-units>
        <ns2:instructions>true</ns2:instructions>
        <ns2:elevation>true</ns2:elevation>
    </ns2:extensions>
</ns2:gpx>`

**Comment by MichaelsJP** [comment]
@aoles geometry=true & instructions=true
```<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:gpx version="1.0" creator="openrouteservice" xmlns:ns2="https://raw.githubusercontent.com/GIScience/openrouteservice-schema/master/gpx/v1/ors-gpx.xsd">
    <ns2:metadata>
        <ns2:name>openrouteservice routing</ns2:name>
        <ns2:desc>This is a routing file from openrouteservice</ns2:desc>
        <ns2:author>
            <ns2:name>openrouteservice</ns2:name>
            <ns2:email id="support" domain="@openrouteservice.org"/>
            <ns2:link href="https://go.openrouteservice.org/">
                <ns2:text>https://go.openrouteservice.org/</ns2:text>
                <ns2:type>text/html</ns2:type>
            </ns2:link>
        </ns2:author>
        <ns2:copyright author="openrouteservice.org, OpenStreetMap contributors">
            <ns2:year>2018+02:00</ns2:year>
            <ns2:license>Apache License 2.0</ns2:license>
        </ns2:copyright>
        <ns2:time>2018-06-27T12:09:01.708+02:00</ns2:time>
        <ns2:bounds minlat="49.415936297702714" minlon="8.681480080490838" maxlat="49.41727610865107" maxlon="8.681872867387671"/>
    </ns2:metadata>
    <ns2:rte>
        <ns2:rtept lat="49.415936297702714" lon="8.681480080490838">
            <ns2:ele>115.5</ns2:ele>
            <ns2:name>Wielandtstraße</ns2:name>
            <ns2:desc>Head north on Wielandtstraße</ns2:desc>
            <ns2:extensions>
                <ns2:distance>151.8</ns2:distance>
                <ns2:duration>21.9</ns2:duration>
                <ns2:type>11</ns2:type>
                <ns2:step>0</ns2:step>
            </ns2:extensions>
        </ns2:rtept>
        <ns2:rtept lat="49.41608736849027" lon="8.681509279046415">
            <ns2:ele>115.25</ns2:ele>
            <ns2:name>Wielandtstraße</ns2:name>
            <ns2:desc>Head north on Wielandtstraße</ns2:desc>
            <ns2:extensions>
                <ns2:distance>151.8</ns2:distance>
                <ns2:duration>21.9</ns2:duration>
                <ns2:type>11</ns2:type>
                <ns2:step>1</ns2:step>
            </ns2:extensions>
        </ns2:rtept>
        <ns2:rtept lat="49.416600340975826" lon="8.681673936881287">
            <ns2:ele>114.64285714285714</ns2:ele>
            <ns2:name>Wielandtstraße</ns2:name>
            <ns2:desc>Head north on Wielandtstraße</ns2:desc>
            <ns2:extensions>
                <ns2:distance>151.8</ns2:distance>
                <ns2:duration>21.9</ns2:duration>
                <ns2:type>11</ns2:type>
                <ns2:step>2</ns2:step>
            </ns2:extensions>
        </ns2:rtept>
        <ns2:rtept lat="49.4170792270544" lon="8.681815311651274">
            <ns2:ele>114.875</ns2:ele>
            <ns2:name>Wielandtstraße</ns2:name>
            <ns2:desc>Head north on Wielandtstraße</ns2:desc>
            <ns2:extensions>
                <ns2:distance>151.8</ns2:distance>
                <ns2:duration>21.9</ns2:duration>
                <ns2:type>11</ns2:type>
                <ns2:step>3</ns2:step>
            </ns2:extensions>
        </ns2:rtept>
        <ns2:rtept lat="49.41727610865107" lon="8.681872867387671">
            <ns2:ele>115.03571428571429</ns2:ele>
            <ns2:name>Wielandtstraße</ns2:name>
            <ns2:desc>Head north on Wielandtstraße</ns2:desc>
            <ns2:extensions>
                <ns2:distance>151.8</ns2:distance>
                <ns2:duration>21.9</ns2:duration>
                <ns2:type>11</ns2:type>
                <ns2:step>4</ns2:step>
            </ns2:extensions>
        </ns2:rtept>
        <ns2:extensions>
            <ns2:distance>151.8</ns2:distance>
            <ns2:duration>21.9</ns2:duration>
            <ns2:distanceActual>151.8</ns2:distanceActual>
            <ns2:ascent>0.4</ns2:ascent>
            <ns2:descent>0.9</ns2:descent>
            <ns2:avgSpeed>25.0</ns2:avgSpeed>
            <ns2:BBox>
                <minLon>8.681480080490838</minLon>
                <maxLon>8.681872867387671</maxLon>
                <minLat>49.415936297702714</minLat>
                <maxLat>49.41727610865107</maxLat>
                <minEle>NaN</minEle>
                <maxEle>NaN</maxEle>
            </ns2:BBox>
        </ns2:extensions>
    </ns2:rte>
    <ns2:extensions>
        <ns2:attribution>openrouteservice.org, OpenStreetMap contributors</ns2:attribution>
        <ns2:engine>4.5.0</ns2:engine>
        <ns2:build_date>2018-06-27T09:56:44Z</ns2:build_date>
        <ns2:profile>fastest</ns2:profile>
        <ns2:preference>driving-ecar</ns2:preference>
        <ns2:language>en</ns2:language>
        <ns2:distance-units>Meters</ns2:distance-units>
        <ns2:instructions>true</ns2:instructions>
        <ns2:elevation>true</ns2:elevation>
    </ns2:extensions>
</ns2:gpx>```

**Comment by MichaelsJP** [comment]
@aoles geometry=false & instructions=false/true (reminder: no geometries, no route steps)
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:gpx version="1.0" creator="openrouteservice" xmlns:ns2="https://raw.githubusercontent.com/GIScience/openrouteservice-schema/master/gpx/v1/ors-gpx.xsd">
    <ns2:metadata>
        <ns2:name>openrouteservice routing</ns2:name>
        <ns2:desc>This is a routing file from openrouteservice</ns2:desc>
        <ns2:author>
            <ns2:name>openrouteservice</ns2:name>
            <ns2:email id="support" domain="@openrouteservice.org"/>
            <ns2:link href="https://go.openrouteservice.org/">
                <ns2:text>https://go.openrouteservice.org/</ns2:text>
                <ns2:type>text/html</ns2:type>
            </ns2:link>
        </ns2:author>
        <ns2:copyright author="openrouteservice.org, OpenStreetMap contributors">
            <ns2:year>2018+02:00</ns2:year>
            <ns2:license>Apache License 2.0</ns2:license>
        </ns2:copyright>
        <ns2:time>2018-06-27T12:14:47.477+02:00</ns2:time>
        <ns2:bounds minlat="49.415936297702714" minlon="8.681480080490838" maxlat="49.41727610865107" maxlon="8.681872867387671"/>
    </ns2:metadata>
    <ns2:rte>
        <ns2:extensions>
            <ns2:distance>151.8</ns2:distance>
            <ns2:duration>21.9</ns2:duration>
            <ns2:distanceActual>151.8</ns2:distanceActual>
            <ns2:ascent>0.4</ns2:ascent>
            <ns2:descent>0.9</ns2:descent>
            <ns2:avgSpeed>25.0</ns2:avgSpeed>
            <ns2:BBox>
                <minLon>8.681480080490838</minLon>
                <maxLon>8.681872867387671</maxLon>
                <minLat>49.415936297702714</minLat>
                <maxLat>49.41727610865107</maxLat>
                <minEle>NaN</minEle>
                <maxEle>NaN</maxEle>
            </ns2:BBox>
        </ns2:extensions>
    </ns2:rte>
    <ns2:extensions>
        <ns2:attribution>openrouteservice.org, OpenStreetMap contributors</ns2:attribution>
        <ns2:engine>4.5.0</ns2:engine>
        <ns2:build_date>2018-06-27T09:56:44Z</ns2:build_date>
        <ns2:profile>fastest</ns2:profile>
        <ns2:preference>driving-ecar</ns2:preference>
        <ns2:language>en</ns2:language>
        <ns2:distance-units>Meters</ns2:distance-units>
        <ns2:instructions>true</ns2:instructions>
        <ns2:elevation>true</ns2:elevation>
    </ns2:extensions>
</ns2:gpx>
```

**Comment by aoles** [comment]
🎉  Top, thanks a lot @MichaelsJP!

You mentioned at some point that after the fix some API tests fail, do you plan to work on them as well?
