### ISSUE TITLE
Unable to get an appropriate route profile when using POST (Directions API)

### ISSUE THREAD

**Issue by Twometer** [GIScience/openrouteservice#200]
I am trying to use a POST request with the Directions API, which works fine when I use the route profile `driving-car`. But when I try to use anything else, I get a response code 500 and the following JSON:
```
{"error":{"code":2099,"message":"Unable to get an appropriate route profile for RoutePreference = foot-walking"},"info":{"engine":{"version":"4.5.0","build_date":"2018-06-13T06:21:46Z"},"timestamp":1529477255914}}
```

I am using the following form data in my request:
```
api_key=<omitted>&coordinates=8.63115,49.635798|8.62721,49.63652&preference=shortest&profile=foot-walking&format=json&unit=m&geometry=true&geometry_format=encodedpolyline&instructions=false&optimized=false&options={"avoid_polygons": ...
```

I know that using a POST request on `/directions` is not documented, but I can't use a GET request because my application needs a lot of `avoid_polygons` and when I try to submit the request using GET the server closes the connection without any error code. (probably because the request uri string is too long)

Is there a way to use a POST request and `profile: foot-walking`?

I looked at issue #33 and tried using `optimized: false` as suggested there but that didn't change anything.

**Comment by TimMcCauley** [comment]
@Twometer thank you for finding this bug - it has got to do with our apache settings. Please, until this is fixed, append the profile to the query in addition to the POST body - I will keep this open until it's fixed. One example:

```
curl -X POST \
  'https://api.openrouteservice.org/directions?profile=cycling-regular&api_key=XY' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'profile=cycling-regular&geometry=true&geometry_format=geojson&coordinates=6.626129%2C53.073402%7C6.573844%2C53.20521%20'
```

**Comment by Twometer** [comment]
Thank you very much, that fixed the issue!

**Comment by Twometer** [comment]
I now noticed however, that when using `foot-walking` and many `avoid_polygons` I always get a 404 error without a response body
EDIT: I also receive 404 when I don't send any options

**Comment by TimMcCauley** [comment]
This works for me:

```
curl -X POST \                                                          
  'https://api.openrouteservice.org/directions?profile=foot-walking&api_key=XY' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'profile=foot-walking&geometry=true&geometry_format=geojson&coordinates=6.626129%2C53.073402%7C6.573844%2C53.20521%20'
```

**Comment by TimMcCauley** [comment]
regarding avoid polygons 404: please open a new ticket with the example request for us to look into

**Comment by Twometer** [comment]
The reason for the 404 without response was a typo I made in the URL, I'm sorry.

However, when I send a lot of polygons it sometimes can't find a route.

**Comment by rabidllama** [comment]
@Twometer the issue with avoid polygons could be related to a bug we found a bit ago (#95) which will be applied on the next update (hopefully within the next week).

**Comment by TimMcCauley** [comment]
I will fix this asap, for the mean time please add the profile to the URL, such as
https://api.openrouteservice.org/matrix?api_key=XXX&profile=cycling-mountain with the POST payload
