### ISSUE TITLE
Response seems to be cut off for large requests

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#203]
E.g.
https://api.openrouteservice.org/directions?geometry_format=geojson&profile=driving-hgv&api_key=58d904a497c67e00015b45fcdd970a3a925843bfafe57ae96d61c08b&coordinates=38.7697649,59.8828053|39.8506308,59.18733|39.8397732,57.6686847|38.8934684,57.9744673|38.8530529,57.8940654|38.980329,57.6876748|38.9708018,57.4652553|39.3821239,57.1877968|39.1486752,56.9287062|38.9399564,56.7470348|38.5823107,56.5629816|38.2638896,56.3417423|37.4752879,56.3692725|36.7028546,56.3261855|36.2038565,55.7103503|36.3985527,55.5389571|30.9868848,54.6908212|27.882024,54.0144539|27.6794851,53.9427638|27.4105668,53.913281|26.7612147,54.0509212|25.6995213,54.5443404|25.2396941,54.6687627|23.8601375,54.8146319|23.6842704,54.7258401|23.3833158,54.5868373|23.1225514,54.3101943|22.8896284,54.0487003|22.7894425,53.974328|23.1091511,53.5857618|23.0601311,53.1484008|20.8457208,52.2030187|14.5779133,52.3156285|13.7340045,52.3241472|12.826184,52.3285782|6.8023288,51.44449|6.2162876,51.3841617|5.446279,51.405437|5.2090538,51.3190913|4.3583,51.2152147|3.1213188,50.7962&extra_info=tollways

**Comment by rabidllama** [comment]
@TimMcCauley Did this get fixed in the servers?

**Comment by TimMcCauley** [comment]
@rabidllama not yet

**Comment by TimMcCauley** [comment]
I have set nginx to `proxy_buffering off;` after reading https://github.com/request/request/issues/1418 - I will keep this open for now.

**Comment by rabidllama** [comment]
Seems to be working now so I will mark this as closed
