### ISSUE TITLE
Geocoding query resulted in a 500 Internal Server Error

### ISSUE THREAD

**Issue by nic2711** [GIScience/openrouteservice#204]
I'm trying to get the coordinates for an address. However, I always get an 500 Error. Have I overlooked something or is it a bug on the server side?

Requested the following URI:

> https://api.openrouteservice.org/geocoding?api_key=[MyAPIKey]&query=Berlin

I've requested coordinates for Berlin and I'm getting this error:

`{
    "error": {
        "code": 1099,
        "message": "Unknown internal server error has occured."
    },
    "info": {
        "engine": {
            "version": "4.5.0",
            "build_date": "2018-06-12T14:47:57Z"
        },
        "timestamp": 1529921177913
    }
}`

**Comment by TimMcCauley** [comment]
Hi @nic2711 please use our new endpoints for this -> https://openrouteservice.org/documentation/#/reference/geocode/geocodesearch
