### ISSUE TITLE
Cant seem to get OSM Tools (routing)  to run Error is "Extra data: line 1 column 5 - line 2 column 1 (char 4 - 19)"

### ISSUE THREAD

**Issue by civil142** [GIScience/openrouteservice#210]
An error has occurred while executing Python code: 

JSONDecodeError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 19) 
Traceback (most recent call last):
  File "C:/Users/Ian Kirk-Ellis/.qgis2/python/plugins\OSMtools\osm_tools.py", line 144, in run
    route.directions_calc()
  File "C:/Users/Ian Kirk-Ellis/.qgis2/python/plugins\OSMtools\directions.py", line 88, in directions_calc
    route_dict = self._selectInput()
  File "C:/Users/Ian Kirk-Ellis/.qgis2/python/plugins\OSMtools\directions.py", line 235, in _selectInput
    response_dict = geocode.reverse_geocode(self.client, *point_geom)
  File "C:/Users/Ian Kirk-Ellis/.qgis2/python/plugins\OSMtools\geocode.py", line 17, in reverse_geocode
    response = client.request('/geocoding', params)['features'][0]
  File "C:/Users/Ian Kirk-Ellis/.qgis2/python/plugins\OSMtools\client.py", line 162, in request
    result = self._get_body(response)
  File "C:/Users/Ian Kirk-Ellis/.qgis2/python/plugins\OSMtools\client.py", line 185, in _get_body
    body = response.json()
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\simplejson\__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\simplejson\decoder.py", line 373, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
JSONDecodeError: Extra data: line 1 column 5 - line 2 column 1 (char 4 - 19)

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.17 Las Palmas, 98e769f70e 

Python Path:
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python
C:/Users/Ian Kirk-Ellis/.qgis2/python
C:/Users/Ian Kirk-Ellis/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Ian Kirk-Ellis/.qgis2//python
C:/Users/Pedro/.qgis2/python/plugins/AequilibraE/
C:\Users\Ian Kirk-Ellis\.qgis2\python\plugins\AequilibraE
C:\Users\Ian Kirk-Ellis\.qgis2\python\plugins\AequilibraE
C:\Users\Ian Kirk-Ellis\.qgis2\python\plugins\AequilibraE
C:\Users\Ian Kirk-Ellis\.qgis2\python\plugins\AequilibraE\paths_procedures/aequilibrae/
C:/Users/Ian Kirk-Ellis/.qgis2/python/plugins\NNJoin
C:\Users\Ian Kirk-Ellis\.qgis2\python\plugins\SelectTools/tools
C:/Users/Ian Kirk-Ellis/Dropbox (ADC Infrastructure)/!!! ADC  Projects/ADC1739 Litecast, Ansley Common/Calculations/GIS

**Comment by TimMcCauley** [comment]
@civil142 thank you - please add this issue to the corresponding repository https://github.com/nilsnolde/OSMtools
