### ISSUE TITLE
Add functionailty for obtaining osm way ids

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice#217]
In some instances it would be useful to have information returned for the route about the osm ids of ways that the route goes along. 
This could be implemented as an "extra info" item in the route response

**Comment by rabidllama** [comment]
Currently need to check how much storage it needs for such information as the osm ids need to be stored as longs

**Comment by marq24** [comment]
would be "cool", if we would be able to pass this additional info's also to the frontend - so that the additional data is visible in the route...

Additionally to the source way-id I would have the need to see the EdgeId (int) and at least some of the encoded values (like speed/reverse speed)
