### ISSUE TITLE
Elevation profile not available above 60 deg N

### ISSUE THREAD

**Issue by Sandmania** [GIScience/openrouteservice#220]
Elevation data currently only works for below 60 deg N. See profile of this route, for example:

https://maps.openrouteservice.org/directions?n1=59.843317&n2=22.552207&n3=8&a=59.808843,22.892606,60.384955,23.121477&b=2b&c=0&g1=-1&g2=0&k1=en-US&k2=km

Previous discussion can be found on this ticket: https://github.com/GIScience/openrouteservice-app/issues/116 Opening new issue in this repo as requested on said discussion.

**Comment by TimMcCauley** [comment]
@Sandmania thank you - we will be tackling this issue with one of our next updates - stay tuned!

**Comment by marq24** [comment]
jfyi - the multi-elevation-provider will generate also an out of bounds when
`lat > 84 || lat < -70`

so still not the full coverage - but at least not like before: 
`lat >= 60 || lat <= -56`

**Comment by rabidllama** [comment]
The reason for the no data above 60° or below -52° is because it comes from the SRTM, which only collected data between these two values.

**Comment by Sandmania** [comment]
@marq24 I think the northernmost point of land is < 84, so that shouldn't be a problem. And anything south from approx -60 is the Antarctic, in which there are no paths to draw routes, so that might not be a problem either?

**Comment by TimMcCauley** [comment]
@Sandmania  this feature ( https://lta.cr.usgs.gov/GMTED2010 )  will be included in 4.7 end of September

**Comment by rabidllama** [comment]
This should all be fixed now with the update to the newest version
