### ISSUE TITLE
[/matrix] cycling profile not appropriate profile on POST request

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#224]
The Matrix POST endpoint doesn't recognize cycling profiles 
`{"profile":"cycling-regular","metrics":"duration","optimized":true,"units":"m","locations":[[4.3939470564405,51.208787230241],[4.3943189234121,51.208220575997]]}`
while its fine in the GET request
https://api.openrouteservice.org/matrix?api_key=xxx&profile=cycling-regular&locations=4.3939470564405%2C51.208787230241%7C4.3943189234121%2C51.208220575997

**Comment by TimMcCauley** [comment]
This is a server issue - I will fix this asap, for the mean time please add the profile to the URL, such as 
`https://api.openrouteservice.org/matrix?api_key=XXX&profile=cycling-mountain` with the POST payload

**Comment by TimMcCauley** [comment]
#200
