### ISSUE TITLE
Increase matrix limit for cycling/walking profiles

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#225]
Since we included CH for cycling/walking, it's about time to increase the matrix input limit for `destinations` and `sources` to the same as driving, i.e. 50 each.

**Comment by HendrikLeuschner** [comment]
@nilsnolde This should be fixed "automatically". As soon as there is a CH profile for a given profile, we use the higher matrix limit. I checked on my machine with the newest app.config with the bike profile as used in https://github.com/nilsnolde/OSMtools/issues/64 and it chooses a CH profile for a GET.
Is the problem possibly that it uses POST and the documentation states that "The profile currently has to be passed both as a parameter AND in the body for other profiles than driving-car."?
edit: Just took a look at the matrix.py and it seems that the profile is indeed not passed in the body as far as I can tell. Maybe this causes the error?

Hendrik
