### ISSUE TITLE
Container setup not working

### ISSUE THREAD

**Issue by cwassert** [GIScience/openrouteservice#231]
I followed the instructions in `docker/readme.md` (i.e. `git clone`, `docker-compose up`) on two unrelated machines (ubuntu and arch). The build phase seems to be working, but the `ors-core` container is not working (404 on every url) and outputs a myraid of error messages.

The error messages are different every time. It looks like some kind of class loading race condition.

[docker-compose-logs-2018-07-31-4.txt](https://github.com/GIScience/openrouteservice/files/2244455/docker-compose-logs-2018-07-31-4.txt)
[docker-compose-logs-2018-07-31-3.txt](https://github.com/GIScience/openrouteservice/files/2244456/docker-compose-logs-2018-07-31-3.txt)
[docker-compose-logs-2018-07-31-2.txt](https://github.com/GIScience/openrouteservice/files/2244457/docker-compose-logs-2018-07-31-2.txt)
[docker-compose-logs-2018-07-31-1.txt](https://github.com/GIScience/openrouteservice/files/2244458/docker-compose-logs-2018-07-31-1.txt)

**Comment by TimMcCauley** [comment]
@cwassert could you please disable elevation and for starters use one profile `driving-car` and send me the logs again?

**Comment by boooch** [comment]
The same issue.
the first error in logs :
```
 31-Jul-2018 20:42:01.292 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
 31-Jul-2018 20:42:01.292 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/ors] startup failed due to previous errors
```

full log attached
[logs.txt](https://github.com/GIScience/openrouteservice/files/2247036/logs.txt)

**Comment by boooch** [comment]
seems this 2 parameters conflicted in web.xml
![image](https://user-images.githubusercontent.com/1180031/43488378-375da588-9522-11e8-97f1-97c310a6a55f.png)
`31-Jul-2018 21:06:58.138 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [CorsFilter]
 javax.servlet.ServletException: It is not allowed to configure supportsCredentials=[true] when allowedOrigins=[*]`

**Comment by cwassert** [comment]
I can confirm that changing `cors.support.credentials` in `openrouteservice/WebContent/WEB-INF/web.xml` from `true` to `false` fixes the problem.

**Comment by TimMcCauley** [comment]
Thank you both, this bug has been fixed in development branch last week - I should have mentioned. Cheers, Tim
