### ISSUE TITLE
optimal application config

### ISSUE THREAD

**Issue by boooch** [GIScience/openrouteservice#232]
What is optimal application config for routing?

Routing results is different between openrouteservice.org  and my installation with default config.

This is server  openrouteservice.org  result:
![image](https://user-images.githubusercontent.com/1180031/43516322-ec692f36-958d-11e8-8a80-119625403034.png)
"distance": 66557.5,
"duration": 3041.2

This is my installation result:
![image](https://user-images.githubusercontent.com/1180031/43516365-1681bd10-958e-11e8-9905-d86f3209b8e6.png)
"distance": 72125.5,
"duration": 3369.6

All request parameters are the same. But result is different.

**Comment by TimMcCauley** [comment]
@boooch can you please paste your app.config in here? I will dig in.

**Comment by boooch** [comment]
problem resolved
