### ISSUE TITLE
HGV access restrictions

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#235]
Access restrictions/permissions doesn't seem to be properly resolved for `driving-*` profiles. Consider the following example for `driving-hgv` with`vehicle_type=agricultural`:

https://maps.openrouteservice.org/directions?n1=49.465&n2=8.658385&n3=15&a=49.469532,8.658686,49.464359,8.660789&b=4d&c=0&k1=en-US&k2=km

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/6545356/43587105-b031dc8e-9669-11e8-8290-6873941c83e2.png">

The direct route is not found even though the way has the [OSM tag `access=agricultural`](https://www.openstreetmap.org/way/26513511).

Interestingly, the same route is returned for `driving-car`~despite that these roads are restricted to agricultural usage~: https://overpass-turbo.eu/s/AL3.  **UPDATE:** `access=agricultural` alone just permits agricultural usage without restricting it for regular traffic unless used in combination with `motor_vehicle`  restrictions such as

![image](https://user-images.githubusercontent.com/6545356/43635681-14aac012-9710-11e8-8047-e66acdbe4df9.png)

Things get even more funky when profile restrictions, such as `hazmat=true` are enabled. Then the route above changes the one below, even though [there are no hazmat restrictions in this area](https://overpass-turbo.eu/s/AK3)! Seems to be related to #209 and #211.

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/6545356/43587264-1a101c2e-966a-11e8-81a8-1252c1326992.png">

**Comment by aoles** [comment]
**UPDATE** `highway=track` below `tracktype=grade1` are excluded from the road network by `HeavyVehicleFlagEncoder` based on `maxTrackGradeLevel`. While this can be specified in the encoder options in **app.config**, the defaults for `CarFlagEncoder` and `HeavyVehicleFlagEncoder` are `3` and `1`, respectively. 

Consider revising these settings to allow routing of `agricultural` or `forestry` vehicles on lower grade tracks.

**Comment by aoles** [comment]
Roads with `access=agricultural` are filtered out by both `CarFlagEncoder` and `HeavyVehicleFlagEncoder` because of `agricultural` being in `restrictedValues`. However, ways tagged with multiple values such as `agricultural;forestry` are not picked up by this filter which explains why it's still possible to still go around from A to B in the example above.

Consider keeping ways tagged as `agricultural` for hgv profile because of agricultural and forestry subprofiles.

**Comment by aoles** [comment]
Interesting test cases:

- [x] just [`access=agricultural`](https://www.openstreetmap.org/way/246583765) or [`motor_vehicle=agricultural`](https://www.openstreetmap.org/way/27116436) [:car:](https://maps.openrouteservice.org/directions?n1=49.465705&n2=8.64933&n3=17&a=49.462964,8.650596,49.463411,8.647978&b=4d&c=0&f5=2&k1=en-US&k2=km)
- [x] [`agricultural=yes` and `motor_vehicle=agricultural`](https://www.openstreetmap.org/way/25188349) [:car:](https://maps.openrouteservice.org/directions?n1=49.465698&n2=8.653193&n3=15&a=49.463522,8.66684,49.467594,8.665466&b=4d&c=0&f5=2&k1=en-US&k2=km)
- [x] [`agricultural=yes` and `motor_vehicle=destination`](https://www.openstreetmap.org/way/33733626) [:car:](https://maps.openrouteservice.org/directions?n1=49.368472&n2=8.693147&n3=17&a=49.368304,8.691226,49.370526,8.691398&b=4d&c=0&f5=2&k1=en-US&k2=km)
- [x] [`agricultural=no`](https://www.openstreetmap.org/way/227413611) [:car:](https://maps.openrouteservice.org/directions?n1=49.368213&n2=8.687525&n3=17&a=49.368388,8.685433,49.368325,8.690314&b=4d&c=0&f5=2&k1=en-US&k2=km)
- [x] [`hgv=agricultural` and `motorcar=yes`](https://www.openstreetmap.org/way/32266681) [:car:](https://maps.openrouteservice.org/directions?n1=49.280152&n2=8.588991&n3=15&a=49.275589,8.594055,49.282084,8.583369&b=4d&c=0&f5=2&k1=en-US&k2=km)

**Comment by rabidllama** [comment]
What is the status of this as in the new release it does not go down the direct way?

**Comment by aoles** [comment]
> What is the status of this as in the new release it does not go down the direct way?

It does not route down the direct way because it is of [`tracktype=grade3`](https://www.openstreetmap.org/way/26513511) as mentioned previously:

> **UPDATE** `highway=track` below `tracktype=grade1` are excluded from the road network by `HeavyVehicleFlagEncoder` based on `maxTrackGradeLevel`. While this can be specified in the encoder options in **app.config**, the defaults for `CarFlagEncoder` and `HeavyVehicleFlagEncoder` are `3` and `1`, respectively.
> 
> Consider revising these settings to allow routing of `agricultural` or `forestry` vehicles on lower grade tracks.

The actual test cases for https://github.com/GIScience/openrouteservice/pull/366 have been listed in my last post above.
