### ISSUE TITLE
access conditional issue "no @ (oct-jun)"

### ISSUE THREAD

**Issue by eliboni** [GIScience/openrouteservice#238]
it seems ORS does not properly recognize access:conditional attribute when set to "no @ (oct-jun)"

Example: http://bit.ly/2neSK5v point B is not reached (although it is august)

**Comment by rabidllama** [comment]
We will look into it as you are correct, the route should take you down that path and it seems to happen on all profiles.

Notes:
As we do not implement temporal restrictions yet, this road should be routed down (as seen in GH). 
It could be due to an issue in an edge filter used by all profiles.

**Comment by rabidllama** [comment]
So, I have had a look into this on my local machine using the latest OSM data and the branch that the graphs were built on and it seems that routing works OK then. So it could be a problem with that particular graph build. We are looking at getting new graphs built this week and so then we can test again on the full graphs to see if the problem is still there (it seems that the whole way and also the neighbouring way of Strada del Vallone di Riofreddo are completely missing from the graph from their intersection)

**Comment by eliboni** [comment]
Many thanks! I'll test when available. Thanks

**Comment by eliboni** [comment]
On the other side - the problem is surely wider at the moment, see here as well:
http://bit.ly/2nnIM1v
The route is "no @ Nov-Jun" https://www.openstreetmap.org/edit?editor=id#map=16/45.3027/6.9550

(as a side note I really wish you skip or allow to ignore access:conditional since in several cases it is not accurate and prevents to plan routes for the future...)

**Comment by rabidllama** [comment]
hmm, that's strange as another route https://bit.ly/2MfEQ1S works ok and that uses a way with the `access:conditional=no @ (Oct-Apr)` tag

**Comment by aoles** [comment]
The tag `access:restriction` is not processed by ORS itself but rather by the underlying Graphhopper routing engine in [`ConditionalOSMTagInspector`](https://github.com/GIScience/graphhopper/blob/ors/core/src/main/java/com/graphhopper/reader/osm/conditional/ConditionalOSMTagInspector.java). The current release of GH works fine for the provided examples: https://bit.ly/2MkASFi and https://bit.ly/2MPm39Z. See also the discussion at https://github.com/graphhopper/graphhopper/issues/374. Needs further investigation..

**Comment by rabidllama** [comment]
As soon as we have the newest version (4.6) up and running we will test out whether there are still these problems. I suspect though that it was a problem in the parsing process (maybe a corrupt osm file) as in the case of the first example at least it appeared in all profiles, yet other places where a similar tag appears the roads are present.
I will keep you updated, but for now I will remove it from the 4.6.1 release until we have had chance to check if it is still present and if so, we will look into getting it fixed.

**Comment by eliboni** [comment]
@rabidllama is there any planned release date for 4.6? ORS is currently unusable across Alps or other mountain areas with conditional access...

**Comment by eliboni** [comment]
Also, will there be in 4.6 the possibility to completely  ignore conditional access settings? That is  to plan trips in the future - for example during the winter you can't use OSR to plan a summer trip in Norway.

Thanks!

**Comment by eliboni** [comment]
The items I reported on my initial post seems fixed now, however  I still see issues, for example look at this barrier:
https://www.openstreetmap.org/node/4550696272
although it is "no @ (Nov-Apr)", as of today ORS refuse to pass through:  [link](https://maps.openrouteservice.org/directions?n1=46.213195&n2=11.421597&n3=15&a=46.213861,11.422348,46.20466,11.419601&b=0&c=0&k1=en-US&k2=km)

**Comment by eliboni** [comment]
Folks, since the problem in my original post seems solved, and from what I see the issue I mentioned in the previous one is just related to barriers, let me open a new issue and this one can be closed

**Comment by rabidllama** [comment]
OK cool, glad that the initial issue is now resolved :)
