### ISSUE TITLE
"shortest" route is actually longer than the "fastest" one

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#239]
Consider the following [simple route](https://maps.openrouteservice.org/directions?n1=49.378961&n2=8.679923&n3=17&a=49.379446,8.679156,49.378357,8.680487&b=0&c=0&k1=en-US&k2=km) with default  weight `fastest`.

<img width="898" alt="image" src="https://user-images.githubusercontent.com/6545356/43839662-ee0a33c6-9b1e-11e8-8cbc-de4ab57b7e58.png">

Once  the weighting is switched to `shortest` a different longer route is returned (**412** vs **245** m).

<img width="898" alt="image" src="https://user-images.githubusercontent.com/6545356/43839583-c6a6a922-9b1e-11e8-82c3-9ecaa9cc53af.png">

**Comment by TimMcCauley** [comment]
Afaik fastest uses CH, shortest doesn't - this might help debugging.

**Comment by TimMcCauley** [comment]
And afaik, fastest doesn't consider turn restrictions which is why this result could be "correct".

**Comment by aoles** [comment]
Thanks @TimMcCauley! I'm pretty sure in reality there are no turn restrictions on these roads, so I wonder where would these come from...

**Comment by TimMcCauley** [comment]
https://www.openstreetmap.org/way/23771000#map=18/49.37893/8.68051 - I would compute the graphs for this region with and w/o CH for further investigation.

**Comment by HendrikLeuschner** [comment]
Turns out this bug stems from the original ALT implementation using landmarks. If instead we force ALT to use the beeline approximator, it returns the correct values. No idea what the actual problem is though.
I have instead now tested this using Core-ALT. We do not observe this problem here anymore. This might be due to the fact that the route is so short we don't even enter the ALT phase but stay outside the core in the CH phase. I will put this on awaiting release

**Comment by rabidllama** [comment]
I'm still seeing the same problem in the new release

**Comment by nilsnolde** [comment]
What's the status on this? It will resolve once we release C-ALT?

**Comment by aoles** [comment]
Correct, CALT seems to handle this example correctly.

**Comment by aoles** [comment]
The observed behavior was because of a [bug](https://github.com/graphhopper/graphhopper/issues/1557) in the original ALT implementation. The problem does not occur anymore in the [patched version](https://github.com/GIScience/graphhopper/pull/22) of our GH fork.

This issue will resolve itself as soon as we switch to the new GH version [0.10.1.13](https://github.com/GIScience/graphhopper/releases/tag/v0.10.1.13).
