### ISSUE TITLE
No results for structured geocoding

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#240]
The following request to endpoint `geocode/search/structured` used to work, now it does't return any results.

`https://api.openrouteservice.org/geocode/search/structured?api_key=API_KEY&locality=Heidelberg&county=Heidelberg`

**Comment by rabidllama** [comment]
The goecoder has been updated and this should now work

**Comment by TimMcCauley** [comment]
Another working example: https://api.openrouteservice.org/geocode/search/structured?api_key=xxx&country=AUS
