### ISSUE TITLE
JSONArray bbox contains only the last segment

### ISSUE THREAD

**Issue by ostermannBernd** [GIScience/openrouteservice#241]
I have requested a route from Innsbruck via Munich to Pfaffenhofen with:

https://api.openrouteservice.org/directions?api_key=MyKey&profile=driving-car&format=json&units=m&geometry=true&geometry_format=encodedpolyline&instructions=true&instructions_format=text&maneuvers=true&coordinates=11.4041024%2C47.2692124%7C11.5819805%2C48.1351253%7C11.512417899999999%2C48.5274509&language=de
I assumed, that the JSONArray bbox contains the total route, but in fact it contains only the last segment from Munich to Pfaffenhofen.
Or is may assumption about bbox wrong?
In the attached screenshot the green rectangle shows the bbox.
![route_innsbruck_munchen_pfaffenhofen](https://user-images.githubusercontent.com/41343199/43910429-1a65eb52-9bfd-11e8-8b89-7fbb8c700553.png)

**Comment by rabidllama** [comment]
@ostermannBernd I believe that your assumption is correct and that the bounding box should cover the entire route and not just the last segment.

@MichaelsJP It might be useful to have it so that the bounding box in the base object covers the whole route, and then an extra bounding box for each of the segments contained in the `segments` object array i.e.:

``` 
...,
segments: [
  {
    distance: 148843.8,
    duration: 6288.4,
    steps : […],
    bbox: [...]
  }, {
    distance: 51671.4,
    duration: 2324.6,
    steps: […],
    bbox: [...]
  },...
```

**Comment by MichaelsJP** [comment]
@rabidllama @ostermannBernd I investigated the bug a bit and it revealed that as soon as there is more than one segment calculated in  `ors/routing/RouteResultBuilder.java` the bbox is always overwritten with the latest segment bbox and in the end just appended to the summary.
I'll think about a nice fix. @ostermannBernd Thank you for posting the issue. It was hidden in the code for quite some time!

**Comment by rabidllama** [comment]
Will close when 4.6.1 is released
