### ISSUE TITLE
Problem: Downloaded GPX-Files are corrupted

### ISSUE THREAD

**Issue by Toni-Reitz** [GIScience/openrouteservice#270]
Hi, Team of Open Route Service

After calculating a route on maps.openrouteservice.org and downloading a GPX file, the results seem to be corrupt. Eg. Routeconverter cannot read or modifiy the data. The problem exists for downloads with and without instructions, and can be replicated.
Please find attached two examples of corrupted output, without and with instructions.

Best wished to Heidelberg
Toni Reitz

[ors-export-linestring(18).zip](https://github.com/GIScience/openrouteservice/files/2384758/ors-export-linestring.18.zip)

P.S. There is a corresponding discussion in the google group. Unfortunately, the workaround advised there by Amandus does not help, as GPX-files with instructions seem to be corrupted, too.
P.P.S. I beg your pardon that I posted the issue in the wrong category, too. I didn't understand the structure of the ticket system at the first shot.

**Comment by Toni-Reitz** [comment]
P.S. I use Routeconverter for checking and editing, the komoot app on the android smart phone, and various Garmin Edge devices for navigating.

**Comment by TimMcCauley** [comment]
@Toni-Reitz we will close this for now. The reason that our new xml format doesn't work is the incompatibility with old (Garmin etc.) devices and RouteConverter. We checked the file and it can be read by other apps (gpsies, for instance). We will eventually add an option to the web-app that a user can decide which gpx to use.
