### ISSUE TITLE
ERROR: Service 'ors-build' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder265193547/.git: no such file or directory

### ISSUE THREAD

**Issue by finessum-github** [GIScience/openrouteservice#271]
If i run "docker-compose up -d", the following error occurs:

**Step 6/11 : COPY .git /ors-core/.git
ERROR: Service 'ors-build' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder265193547/.git: no such file or directory**

I've also tested this on a fresh installed Debian 9 with docker ce installed: Same error.

If i remove/comment out the line "COPY .git /ors-core/.git" from the "../Dockerfile", the setup fails later with:

ERROR: Service 'ors-build' failed to build: The command '/bin/sh -c mvn -f ./openrouteservice/pom.xml package -DskipTests' returned a non-zero code: 1

because of

[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.1:revision (default) on project openrouteservice: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]

**Comment by kimjohans** [comment]
+1

**Comment by kimjohans** [comment]
Is not working here either - same error.

**Comment by kimjohans** [comment]
Found the solution:
[https://www.yourhelpcenter.de/2018/08/error-service-ors-build-failed-to-build-copy-failed/](https://www.yourhelpcenter.de/2018/08/error-service-ors-build-failed-to-build-copy-failed/)

**Comment by rabidllama** [comment]
Hi, I believe before when we have seen this issue it was because the whole repository had been downloaded as a zip and then extracted rather than using the `git clone ...` command. Thanks @kimjohans for providing the assistance.

I will close this and create an issue to add this to the installation on the main page
