### ISSUE TITLE
Please create an installation guide for manual installation (without docker etc)

### ISSUE THREAD

**Issue by kimjohans** [GIScience/openrouteservice#272]
Good morning,

as my topic tells:
May you please write an installation guide for manual installation without docker etc.
There are no installation details at all within your readme or docs (or am i blind ?)

Thanks.

**Comment by rabidllama** [comment]
We are currently writing these up and they should be put onto the front end in the 4.7.1 release.

**Comment by rabidllama** [comment]
Currently we can only provide this information based on our server setup which would be Ubuntu 16.04.
