### ISSUE TITLE
Isochrones: units parameter is not working

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#289]
https://api.openrouteservice.org/isochrones?api_key=xxx&locations=8.34234,48.23424&profile=driving-car&range_type=time&range=60&units=mi&location_type=start&intersections=false
will result in:
```{"error":{"code":3003,"message":"Parameter 'units' has incorrect value or format."},"info":{"engine":{"version":"4.5.0","build_date":"2018-06-12T14:47:57Z"},"timestamp":1537793370652}}```
it doesn't matter which of the 3 values `m`, `km` and `mi` are passed.

**Comment by aoles** [comment]
Might be related to https://github.com/GIScience/openrouteservice/issues/91

**Comment by TimMcCauley** [comment]
What is the status of #91  @aoles @HendrikLeuschner ?

**Comment by TimMcCauley** [comment]
Forget my comment, didn't read it to the end

**Comment by HendrikLeuschner** [comment]
Why was this closed now? Is #91 related or not?

**Comment by TimMcCauley** [comment]
Sorry, please check and close if resolved

**Comment by HendrikLeuschner** [comment]
This behavior is correct and expected. You have specified range_type=time, but provide units for range_type=distance, which obviously cannot be processed. Try
http://localhost:8082/openrouteservice-4.5.0/isochrones?api_key=xxx&locations=8.34234,48.23424&profile=driving-car&range_type=distance&range=60&location_type=start&intersections=false
