### ISSUE TITLE
language=zh-CN results in empty error

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#290]
A request with `language=zh-CN` will get back an empty error.
Maybe this is a graphhopper issue?
https://api.openrouteservice.org/directions?api_key=xxx&coordinates=8.34234,48.23424|8.304977,48.251427&elevation=true&instructions=true&language=zh-CN&preference=fastest&profile=driving-car&units=m

**Comment by TimMcCauley** [comment]
Fixed with #305
