### ISSUE TITLE
[Core-ALT] DefaultEdgeFilter in Core-ALT leads to route not found

### ISSUE THREAD

**Issue by HendrikLeuschner** [GIScience/openrouteservice#298]
CH does not have the filter. ALT does not need the filter for shortcuts. So it is probably a problem when applying the defaultedgefilter on a shortcut.
Example: Build HD graph with the normal heidelberg.osm.gz
http://localhost:8082/openrouteservice-4.5.0/routes?api_key=58d904a497c67e00015b45fc6c712bad9f6f409eae1ade20337f7871&attributes=detourfactor|percentage&coordinates=8.670273,49.44324|8.627186,49.377902&elevation=true&extra_info=steepness|waytype|surface&geometry=true&geometry_format=geojson&instructions=true&instructions_format=html&language=en-US&options={"avoid_features":"ferries"}&preference=fastest&profile=driving-hgv&units=m 

Disabling the DefaultEdgeFilter resovles the issue, but we need to know why.

**Comment by aoles** [comment]
Confirmed, fails with both `CoreDijkstra` and `CoreALT`. Might be a problem specific to the two-stage algorithm, as `CoreDijkstraFilter` from https://github.com/GIScience/openrouteservice/commit/321d7ab65f13fc6b6c98d666a8bc5aa94c40c00c returns correct route.
