### ISSUE TITLE
Distance_Matrix: 'Unable to find an appropriate routing profile.' - for all but 'driving-car'

### ISSUE THREAD

**Issue by AvePazuzu** [GIScience/openrouteservice#299]
I have been using the the function few weeks ago and it worked properly. 

Since yesterday I get the titled error message for all profiles but 'driving-car'. 

I have tried the examples but I always get the same result.

Here is my test code(py 3.6):

`req_param = {'profile': 'driving-hgv',
metrics' : ['duration', 'distance'], 
'optimized': 'true',
'units': 'km', 
'locations': [[9.970093,48.477473], [9.207916,49.153868]]}
`

`dist_mat = clnt2.distance_matrix(**req_param)`

And as response I get:

> ApiError:  500 ({'error': {'code': 6099, 'message': 'Unable to find an appropriate routing profile.'}, 'info': {'engine': {'version': '4.5.0', 'build_date': '2018-09-23T13:46:49Z'}, 'timestamp': 1538421210721}})

Also, is there a lito find an mit for the number of elements of 25 now? 

> ApiError: 400 ({'error': {'code': 6004, 'message': "Parameter 'sources/destinations=36' is out of range. Maximum possible value is 25."}, 'info': {'engine': {'version': '4.5.0', 'build_date': '2018-09-23T13:47:22Z'}, 'timestamp': 1538421896753}})

Did I do something wrong here?

Many Thanks & bis dann.

**Comment by rabidllama** [comment]
Hi @AvePazuzu - Are you using the python library for this? If so I will direct it over to the people who write that package as I assume it would be something that has changed there

**Comment by AvePazuzu** [comment]
Hi @rabidllama - Thank your for the quick response. Yes, I am using the python package which I installed with pip.
regards

**Comment by rabidllama** [comment]
OK cool, I will create an issue over on that repository and then close it here
