### ISSUE TITLE
Directions API: Elevation data missing & NaN value for "encodedpolyline"

### ISSUE THREAD

**Issue by thijssmudde** [GIScience/openrouteservice#323]
Hi. There is an issue with the Directions API when using the **elevation=true** and **geometry_format=encodedpolyline**. The values returned contain a NAN value and there is no elevation data.

Here is the **full request**:
https://api.openrouteservice.org/directions?api_key={API_KEY}&coordinates={coordinates}&profile=driving-car&preference=fastest&format=json&units=m&language=en&geometry=true&geometry_format=encodedpolyline&geometry_simplify=true&instructions=false&elevation=true

The last value is [Correct LatCoordinate, **NaN**]

The response does not contain any elevation data.

**Comment by rabidllama** [comment]
Hi @fullhdpixel 
can you confirm which service/algorithm you are using to decode the encoded polyline? From my understanding the elevation aspect is something custom to openrouteservice as the normal EncodedPolyline algorithm does not take into account any elevation information (only latitude and longitude), so I believe that most conversion libraries would not provide the elevation component.

**Comment by nilsnolde** [comment]
ors-py has it implemented, if you're looking for reference client-side:
https://github.com/GIScience/openrouteservice-py/blob/master/openrouteservice/convert.py#L135

**Comment by thijssmudde** [comment]
Thanks for the quick answer. I use the mapbox polyline repo for decoding/encoding: https://github.com/mapbox/polyline

Do you have a javascript library which does the same thing?

**Comment by TimMcCauley** [comment]
@fullhdpixel just checked, this method should do the job https://github.com/graphhopper/directions-api-js-client/blob/master/src/GHUtil.js#L27

**Comment by TimMcCauley** [comment]
Closing this as I assume this is resolved.
