### ISSUE TITLE
return raw points for isochrones

### ISSUE THREAD

**Issue by natanlaurett** [GIScience/openrouteservice#324]
Hi there. I'm developing a research project using the ORS api to gather data and optimize routes. One of the needs of my program is to discover the nearest coordinate in a road, given the start point (if the start point already is at a road, it must return himself). 

I'm using the Isochrone API to find the "range points" of the start Coordinate, in intervals of 300 or 100 meters. I was expecting that this would return coordinates on streets, so I could analize which one is the closest. 

However, when I use the Isochrone API, nearly every time it returns coordinates that aren't on roads or even landmasses (in some coastal cities that we are working with). Is this a bug or it  really should work in this way? And if yes, is there any other tool in the API that could provide this information?

Examples (in both cases some of the response coordinates are in water or out of roads):

New York:
 https://api.openrouteservice.org/isochrones?api_key=your-API-Key&locations=-73.924464%2C40.758376&profile=foot-walking&range_type=distance&range=3000&interval300&units=m&location_type=start&attributes=total_pop&options=&intersections=&id=

When we run this query of New York, we receive, among other coordinates, the one in this image (https://imgur.com/a/RmDn4g5), which is: Lat: 40.760543, Lon: -73.95258.

Flensburg:
https://api.openrouteservice.org/isochrones?api_key=your-API-Key&locations=9.429804%2C54.795665&profile=foot-walking&range_type=distance&range=3000&interval300&units=m&location_type=start&attributes=total_pop&options=&intersections=&id=

**Comment by nilsnolde** [comment]
So, what isochrones return is a polygon of reachability. It calculates the distance on all possible roads you can reach within the given time/distance limit and wraps that as a polygon. You can imagine that that's quite a few points, so there's an alpha shape whose smoothing you can regulate a little with the `smoothing` parameter. You don't get the raw points the polygon is made up of. Could be an option though, I like the idea.

However, for what you're trying to achieve, the isochrone API is not the right tool. Download OSM data for the region of interest and derive your points on the road network with nearest functions.

**Comment by rabidllama** [comment]
I think different ways of returning isochrone data is definitely something that we are interested in doing, but at the minute we do not have a time frame for when we would be looking at what else we can do other than the polygons.

We will keep it in mind though when we are planning the next features
