### ISSUE TITLE
consider_elevation resulting in diversions

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice#327]
See #212 for more info, but to quote:

> I didn't know whether to start a new issue, or using this issue about some strange cycling results I'm having as well. I'm playing around with ORS and "cycling-road" directions for some time now, but frequently i get strange cycling issue like this one. While it should stay on the "Ingbergrachtweg" and "Ingberdorpstraat" (which are perfect for road cycling), it takes some strange side-ways and I cannot see why?

Original URL used: https://maps.openrouteservice.org/directions?n1=50.816822&n2=5.879692&n3=16&a=50.814151,5.88879,50.819344,5.870454&b=1a&c=0&g1=-1&g2=0&h2=3&k1=en-US&k2=km

I guess this is something to do with speeds on these roads as  as @marq24 notes, switching from quickest to shortest provides the correct result

**Comment by rabidllama** [comment]
Had a little look into this and I believe it is something to do with how the elevation is being taken into account as when you reverse the waypoints, you get the expected result

**Comment by rabidllama** [comment]
ok, so the findings I have are basically showing that the section on the main road is 70m in length and is shown as having an incline of 11%. The system tries to take into account the length of the section with the incline and the incline itself, so for that section it limits it to 2km/h which means that to cover that section it takes 125 seconds.
On the other hand, in the service roads the system sees that there is one section with a length of 31m and an incline of 33%, so for that it works out that it would take 57 seconds to cover (again at 2km/h). The other 2 parts of this service road however have much shallower inclines, and so they only need 11 seconds to travel across them, meaning that the whole of the service road section takes about 65 seconds to cover.

**Comment by TimMcCauley** [comment]
Note: `cycling-regular` is currently using `consider_elevation=true` whereas the other bike profiles aren't and produce the expected result. We have to come up with a softer approach for `consider_elevation` to account for these diversions which don't make too much sense.

**Comment by TimMcCauley** [comment]
Note: `cycling-regular` is currently using `consider_elevation=true` whereas the other bike profiles aren't and produce the expected result. We have to come up with a softer approach for `consider_elevation` to account for these diversions which don't make too much sense.

**Comment by TimMcCauley** [comment]
Note: `cycling-regular` is currently using `consider_elevation=true` whereas the other bike profiles aren't and produce the expected result. We have to come up with a softer approach for `consider_elevation` to account for these diversions which don't make too much sense.

**Comment by rabidllama** [comment]
OK, lets assign this to the 4.7.2 release so we can re-evaluate the elevation usage

**Comment by rabidllama** [comment]
As this seems to be the same issue as #212, I will close this issue and we can continue any discussion there to reduce duplication
