### ISSUE TITLE
Unable to find appropriate routing profile

### ISSUE THREAD

**Issue by torfsen** [GIScience/openrouteservice#33]
I'm playing with the examples in the documentation, but I can't get the one for `matrix` to work: the URL https://api.openrouteservice.org/matrix?profile=foot-walking&locations=9.970093%2C48.477473|9.207916%2C49.153868|37.573242%2C55.801281&metrics=distance&resolve_locations=false&units=m&optimized=true&api_key=XXX (generated by the docs) yields

```
{
  "error": {
    "code": 699,
    "message": "Unable to find an appropriate routing profile."
  },
  "info": {
    "engine": {
      "version": "4.3.0",
      "build_date": "2017-10-05T19:36:11Z"
    },
    "timestamp": 1507484237075
  }
}
```

The return code is 500, so that's either a documentation or a code issue.

**Comment by TimMcCauley** [comment]
Thanks for pointing this one out to us. Please note that you can not use optimized=true for any profile except vehicles. Please use optimized=false for your request, however as you found a bug, this will work from tomorrow on ;) we are fixing this now, commit will follow.

**Comment by torfsen** [comment]
Thanks, @TimMcCauley! It now works for the `foot-walking` profile, but not for `wheelchair` (which is also offered by the documentation's example). For the latter I get the same error as before (return code 500, "Unable to find an appropriate routing profile.").

**Comment by TimMcCauley** [comment]
Wheelchair is currently not active @torfsen - we will be adding this back in the future. For Germany you can use the client labs.openrouteservice.org which has wheelchair integrated

**Comment by MichalSayYes** [comment]
Is it possible to get a wheelchair now?

**Comment by TimMcCauley** [comment]
Not yet, no. We are working on an update wheelchair profile at the moment.

**Comment by MichalSayYes** [comment]
Thank you!!!
this is definitely an important and useful thing.
Have a Nice Day!

2018-04-30 10:55 GMT+03:00 Timothy <notifications@github.com>:

**Comment by MichalSayYes** [comment]
Is there an approximate date when the service will be active?I need this for my app and I want to know if it is possible...
Thanks.

**Comment by TimMcCauley** [comment]
Currently not, no, sorry.

**Comment by Mattomanka** [comment]
@TimMcCauley labs.openrouteservice.org does not work. Perhaps you have some kind of test version, where it is possible to try wheelchair profile?

**Comment by TimMcCauley** [comment]
@Mattomanka we will be adding it back to maps.openrouteservice.org within the next 2-3 weeks.

**Comment by MichalSayYes** [comment]
According to what the route with wheelchair profile is calculated?
