### ISSUE TITLE
Isochrones should return snapped coordinate as center

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#336]
The center in properties of each isochrone feature response should hold the snapped center position.
Currently the queried center coordinate is used which is also displayed in the info.query already.

**Comment by TimMcCauley** [comment]
@TheGreatRefrigerator is this a bug?

**Comment by TheGreatRefrigerator** [comment]
bug or extension. Depends on what SHOULD be returned as the isochrone center.
But IMO it should return the point the iso is based on (Snapped) and not the queried.
A centerpoint outside the actual isochrone doesn't make much sense to me.
![screenshot_2018-10-22 isochrones get ors api](https://user-images.githubusercontent.com/23240110/47304812-f5296700-d627-11e8-81fb-ee1fa3c2575a.png)

**Comment by TimMcCauley** [comment]
Agreed, will fix
