### ISSUE TITLE
Using interval and range vs range only for isochrones produces different contours

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/openrouteservice#337]

**Comment by koebi** [comment]
This was brought up again by a mail that mentioned that two 15min isochrone differed when one was queried with `range=[900]` and the other was queried with `range=[300,600,900]`.

After investigating this for some time, there is no recognizable pattern in why isochrones of the same queried size differ between different types of querying (single query, query w/ multiple ranges).

Isochrones seem to be bigger when queried alone or as the "first" isochrone in a set of range, but there were instances where querying them as the first or an "intermediate" isochrone in a set of ranges didn't make a difference.

Algorithmically, everything should stay the same, but it apparently doesn't.

**Comment by MichaelsJP** [comment]
That is most likely connected to how the final isochrone geometries are build. There is some logic that fine tunes multiple isochrones with each other.

**Comment by MichaelsJP** [comment]
This is not something that can really be "fixed". We'll soon move over to the fast isochrones in our live api that don't show this behaviour in such visible manner.

For the normal isochrones this behaviour also got massively better over the last releases. Especially v7
