### ISSUE TITLE
[Directions API] Residential road | Code 2009: Route could not be found

### ISSUE THREAD

**Issue by mkalygin** [GIScience/openrouteservice#341]
I'm trying to build a route through a `residential` road. And I'm getting `Code 2009: Route could not be found` error. It's OK in Graphhopper though. Here are the routes:
- [OpenRouteService](https://maps.openrouteservice.org/directions?n1=61.939018&n2=30.593609&n3=15&a=61.936249,30.590388,61.944289,30.580125&b=0&c=0&k1=en-US&k2=km)
- [Graphhopper](https://graphhopper.com/maps/?point=61.936831%2C30.590229&point=61.944406%2C30.580097&locale=ru&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale)

What could be possibly wrong with this route and how can we fix it?

**Comment by aoles** [comment]
Interesting, looking at the [OSM tags](https://www.openstreetmap.org/way/144337155) I don't see any obvious reason why the route is not found. Needs further investigation.

**Comment by TimMcCauley** [comment]
@aoles will you take this one ?

**Comment by rabidllama** [comment]
I've had a quick look into it and from what I can tell the edges for those roads are added to the graph but then the algorithm doesn't detect them for some reason, so I believe this is most likely a more in depth issue embedded in the core system.

**Comment by aoles** [comment]
Fixed by https://github.com/GIScience/openrouteservice/pull/357.

**Comment by mkalygin** [comment]
@rabidllama @aoles guys, thanks for the fix! Is there any approximate date for release of this fix?

**Comment by rabidllama** [comment]
We are in the process of doing the release at the minute, and so it should be within hopefully the next week, but maybe two weeks. I will announce on https://ask.openrouteservice.org/c/announcements when it is all done :)

**Comment by rabidllama** [comment]
Fixed in release 4.7.2
