### ISSUE TITLE
Distance >1km in meters

### ISSUE THREAD

**Issue by PublicTransportPlanning** [GIScience/openrouteservice#347]
Hello, would it be possible (for transport planning purpose) to get the distance in meter values even above 1km?

**Comment by ragapack** [comment]
You can define units in the /directions call:

https://openrouteservice.org/documentation/#/reference/directions/directions/directions-service

**Comment by PublicTransportPlanning** [comment]
Thanks for the feedback!
So far I used only https://maps.openrouteservice.org/
Is there a possibility to define units?

Am 01.11.2018 19:07 schrieb ragapack:

**Comment by nilsnolde** [comment]
Pleeease use the right channel for questions:
https://ask.openrouteservice.org
