### ISSUE TITLE
Error while compose.

### ISSUE THREAD

**Issue by gzmichael84** [GIScience/openrouteservice#351]
Hello. Can you help me? I am getting the following error while trying to compose the service..

$ docker-compose up -d
Starting docker_ors-build_1 ... done
Starting ors-core           ... error

ERROR: for ors-core  Cannot start service ors-core: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/c/users/user/documents/github/openrouteservice/docker/conf/catalina.properties\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/0b414e61e029ee6e1824c32c6aec646bb67b69e6fbd1a2d54864d5b0b9d89326\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/0b414e61e029ee6e1824c32c6aec646bb67b69e6fbd1a2d54864d5b0b9d89326/usr/local/tomcat/conf/catalina.properties\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for ors-core  Cannot start service ors-core: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/c/users/user/documents/github/openrouteservice/docker/conf/catalina.properties\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/0b414e61e029ee6e1824c32c6aec646bb67b69e6fbd1a2d54864d5b0b9d89326\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/0b414e61e029ee6e1824c32c6aec646bb67b69e6fbd1a2d54864d5b0b9d89326/usr/local/tomcat/conf/catalina.properties\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by rabidllama** [comment]
As a quick look, based on the file paths it seems that the catalina.properties file is trying to be mounted as a folder. @TimMcCauley do you have any experience with this.

For the future though @gzmichael84 - you should ask this on the ask.openrouteservice.org board as there may be other people who have experienced similar issues, and this seems to be something in relation to the system setup as opposed to the code base.

**Comment by TimMcCauley** [comment]
@gzmichael84 docker is telling you that a directory does not exist `/c/users/user/documents/github/openrouteservice/docker/conf/catalina.properties` did you make sure it actually does? Something similar: https://stackoverflow.com/questions/45972812/are-you-trying-to-mount-a-directory-onto-a-file-or-vice-versa

**Comment by gzmichael84** [comment]
Yes catalina.properties file exist on that path.. Between im in windows 10 home edition with docker toolbox. Today i tried also to install on windows 7 machine but i get also the same error.

Its strange because it looks simple. Althought its first time i try to play with these kind of tool im experienced with programming and pc in general. 

I clone the openrouteservice from Github.
I install docker toolbox with all options selected.
I run docker, i went to the docker folder of openrouteservice directory and type the command docker-compose up -d

Is there anything i miss or i can check? The ors-core is tomcat container? Can i replace it with other tomcat container? If i open the kitematic i cant start the ors-core container. But if i install new tomcat8 jre8 container from the options there i can turn it on.

**Comment by TimMcCauley** [comment]
@gzmichael84 then I am uncertain what the issue is. The specific images are listed in the docker-compose file, tomcat/mvn. Please add your issue with details in our forum https://ask.openrouteservice.org - maybe you will be able to find help there.
