### ISSUE TITLE
Common driving profile superclass from which car and hgv would inherit

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#362]
There are a lot of similarities between `CarFlagEncoder` and `HeavyVehicleFlagEncoder` which lead to duplicated code. In order to make things easier to maintain and to comprehend move all the stuff shared between these two profiles into a `DrivingFlagEncoder`, similar to the approach taken in `CommonBikeFlagEncoder`.

**Comment by rabidllama** [comment]
Postponing to a later version as this is relatively low priority at the minute

**Comment by aoles** [comment]
Prerequisite for https://github.com/GIScience/openrouteservice/issues/372.

**Comment by aoles** [comment]
Addressed in https://github.com/GIScience/openrouteservice/commit/8ed5668098680dc30f5b1c65c692287f6e270d7a, https://github.com/GIScience/openrouteservice/commit/ebd2dd080e02000ec101ff453c96982da442503b, https://github.com/GIScience/openrouteservice/commit/eaf23eae9872ed8964b77ad98be169b2a294932f and https://github.com/GIScience/openrouteservice/commit/e29d92a60f6c37ef9d5bb5814591899295dfaeb2.
