### ISSUE TITLE
Point 0 is out of bounds

### ISSUE THREAD

**Issue by jendrusk** [GIScience/openrouteservice#364]
Hi all
I've deployed ors on my server using dockers - on default settings everything went well, but when I' trying to use some other extract (poland in this case) I'm getting exception "Point 0 is out of bounds".
1. I downloaded extract into ./docker/data folder
2. I made new config basing on template to point this extract
3. I've found also additional ./Dockerfile with a path to config so changed there also 
4. I've removed all containers and images from docker and everything from ./docker/build
5. "docker-compose up" was running about 2h and I got "8922076 [INFO] BUILD SUCCESS"
6. Script failed on step 11 "An HTTP request took too long to complete" so "export COMPOSE_HTTP_TIMEOUT=240" and rerun
7. ors-core launched with proper extract "====> Initializing profiles from 'data/poland-latest.osm.pbf' (1 threads) ..."

After all doesn't work properly... when I ask: 
http://ors.xploria.live/ors/routes?attributes=detourfactor|percentage&coordinates=20.146179,51.954845|21.007233,52.238733&elevation=true&extra_info=steepness|waytype|surface&geometry=true&geometry_format=geojson&instructions=true&instructions_format=html&preference=fastest&profile=driving-car&units=m

Im getting:

error |  
-- | --
code | 2010
message | "Point 0 is out of bounds: 51.954845,20.146179"

Attaching log from ors-core

Is there something else? What am I doing wrong?
[orsCore.log](https://github.com/GIScience/openrouteservice/files/2628887/orsCore.log)

**Comment by TimMcCauley** [comment]
Answered on the forum https://ask.openrouteservice.org/t/point-0-is-out-of-bounds/113/4

**Comment by DejavuDaniel** [comment]
i get the same error : {
    "code": 3,
    "error": "Source point(s) [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18] out of bounds: 25.272143,54.709692; 25.26989,54.69305; 25.289531,54.68374; 25.293319,54.685166; 25.281992,54.685856; 25.292441,54.681682; 25.29242,54.6763; 25.27714,54.684549; 25.285071,54.677009; 25.288001,54.684012; 25.287042,54.679161; 25.28805,54.675749; 25.280552,54.680044; 25.057288,54.592051; 25.279566,54.683943; 25.276155,54.687952; 25.286386,54.67644; 25.281333,54.682603; 25.282857,54.680198. Destination point(s) [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18] out of bounds: 25.272143,54.709692; 25.26989,54.69305; 25.289531,54.68374; 25.293319,54.685166; 25.281992,54.685856; 25.292441,54.681682; 25.29242,54.6763; 25.27714,54.684549; 25.285071,54.677009; 25.288001,54.684012; 25.287042,54.679161; 25.28805,54.675749; 25.280552,54.680044; 25.057288,54.592051; 25.279566,54.683943; 25.276155,54.687952; 25.286386,54.67644; 25.281333,54.682603; 25.282857,54.680198"
}

my body is : 

{"vehicles":[{"id":1,"profile":"driving-car","start":[54.709692, 25.272143],"capacity":[2000]}],"jobs":[{"id": 179,"service":300,"amount":[1],"location":[54.693050, 25.269890]},{"id": 178,"service":300,"amount":[1],"location":[54.683740, 25.289531]},{"id": 182,"service":300,"amount":[1],"location":[54.685166, 25.293319]},{"id": 181,"service":300,"amount":[1],"location":[54.685856, 25.281992]},{"id": 183,"service":300,"amount":[1],"location":[54.681682, 25.292441]},{"id": 185,"service":300,"amount":[1],"location":[54.676300, 25.292420]},{"id": 186,"service":300,"amount":[1],"location":[54.684549, 25.277140]},{"id": 187,"service":300,"amount":[1],"location":[54.677009, 25.285071]},{"id": 189,"service":300,"amount":[1],"location":[54.684012, 25.288001]},{"id": 190,"service":300,"amount":[1],"location":[54.679161, 25.287042]},{"id": 191,"service":300,"amount":[1],"location":[54.675749, 25.288050]},{"id": 194,"service":300,"amount":[1],"location":[54.680044, 25.280552]},{"id": 180,"service":300,"amount":[1],"location":[54.592051, 25.057288]},{"id": 193,"service":300,"amount":[1],"location":[54.683943, 25.279566]},{"id": 176,"service":300,"amount":[1],"location":[54.687952, 25.276155]},{"id": 195,"service":300,"amount":[1],"location":[54.676440, 25.286386]},{"id": 192,"service":300,"amount":[1],"location":[54.682603, 25.281333]},{"id": 177,"service":300,"amount":[1],"location":[54.680198, 25.282857]}]}


im using map : europe-latest.osm.pbf

**Comment by koebi** [comment]
Hey,
have you checked the forum for answers? The same thread linked above might be relevant.
Best regards

**Comment by DejavuDaniel** [comment]
Fixed it , just needed to change the bpf file in home/ors/ors-core/data in docker and delete graph folder

**Comment by DejavuDaniel** [comment]
But now i have problem with the limits, how do i change them in ors ? 

Map.js:94 Server responded with 400: {"error":{"code":2004,"message":"Request parameters exceed the server configuration limits. The approximated route distance must not be greater than 100000.0 meters."},"info":{"engine":{"build_date":"2023-11-16T15:05:35Z","version":"7.2.0"},"timestamp":1708820585903}}


and 

Error response: {"code":3,"error":"Request parameters exceed the server configuration limits. Only a total of 2500 routes are allowed."}

**Comment by koebi** [comment]
Hey,

that would be done in the config file, the corresponding parameters should be named accordingly.
Note, that some options may be set in the defaults, some for each profile.

Best regards
