### ISSUE TITLE
Enable GraphHopper's alternative wayfinding methods

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#377]
Let's evaluate the dev effort for

- round trip
- alternative routes

Ref. https://github.com/graphhopper/graphhopper/blob/master/docs/web/api-doc.md#flexible

Not sure who to assign here. @sfendrich? What do you think? Smth to look forward to in the new year?;)

**Comment by rabidllama** [comment]
I have started looking into the round trip thing which seems like it could be promising - though some things that need ironing out first. I will split that one out into a separate issue.

**Comment by rabidllama** [comment]
I will switch assignment of this over to @takb - @sfendrich if you have started looking into things on this already, then we can look at transferring things across

**Comment by sfendrich** [comment]
That's fine, I haven't started so far.

**Comment by TimMcCauley** [comment]
@marq24 @takb @rabidllama it might make sense to update our gh-ors fork once this PR is in? What do you think?
https://github.com/graphhopper/graphhopper/pull/1524

**Comment by marq24** [comment]
@TimMcCauley sounds like a task for me :-)

**Comment by TimMcCauley** [comment]
@marq24 hehe, I think you will be the fastest ;) however I think we should wait a little until it's merged into gh's master and released - what do you think?
