### ISSUE TITLE
Geometry_simplify=true parameter doesn’t work

### ISSUE THREAD

**Issue by JeromeHoen** [GIScience/openrouteservice#381]
Hello, I keep getting a long encoded polyline when I set the geometry_simplify to true. For me it’s a real issue as having to deal with an extended polyline (and not an overview like with Google API) impacts the performance of my web app a lot.

To reproduce the issue, simply compare the results in the demo example of the API Playground and set the geometry_simplify to true.
You’ll see that the results are the same.

**Comment by nilsnolde** [comment]
Yes, you're right. I'll make this my first issue:)

**Comment by nilsnolde** [comment]
Using `geometry_simplify` doesn't make sense with `extra_info`. Should I let it fail when both are requested? Think I'd prefer to prioritize `geometry_simplify` and turn off `extra_info` in that case. @rabidllama any thoughts?

**Comment by rabidllama** [comment]
If we are making it so that one doesn't work with the other, then it should result in an error message when both are provided else it might be confusing as to why information isn't being returned

**Comment by nilsnolde** [comment]
Ok, I'll raise an error then.
