### ISSUE TITLE
Innaccurate isochrones for smaller distances

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice#382]
When generating small isochrones (e.g. walking for 1, 2 or 3 minutes) the results can be inaccurate. In some cases, the isochrones show that you can be on another side of a water body even if there is no crossable bridge in range. 

![image](https://user-images.githubusercontent.com/7126643/50628744-a8241400-0f39-11e9-91ca-e556ed3d69f6.png)

Raised from https://ask.openrouteservice.org/t/isochrone-for-small-distances-pedestrian/181

**Comment by TimMcCauley** [comment]
@rabidllama this has most likely got to do with the approximations in the two-fold processing of the contours ( @Rungee please correct me if I'm wrong ). Or what have you found out so far? Making the result more exact will ultimately have an impact on the computation time which is comparably quite high already. As we are currently working on a drastic speedup using many-to-many route computations, maybe we should keep this on hold and tackle it thereafter?

**Comment by rabidllama** [comment]
from what i can see, the issue is to do with adding buffer points. In some cases (e.g. when an edge crosses an isochrone boundary) buffer points are added to the polygon. What it seems is that these are there to smooth out the polygon more than anything else as when the buffer value is set to 0 (rather than 0.0018) the problem disappears

**Comment by TimMcCauley** [comment]
@rabidllama thanks for investigating, sounds good. Shall we introduce something similar to `resolution` ➡️ https://developer.here.com/documentation/routing/topics/resource-calculate-isoline.html ?

**Comment by rabidllama** [comment]
I don't know if a specific resolution thing would be beneficial as it would probably be quite complicated to take into account in the code. At the minute I just have it where if the maximum radius of the isochrone is smaller than a specific value, then the buffer size is decreased. So if the maximum radius is less than 2000m, then the buffer is 0.00018, and anything more it is 0.0018. I am not sure where that initial 0.0018 came from as it is hard coded

**Comment by TimMcCauley** [comment]
Yup, sounds a like a good plan, ty!

**Comment by rabidllama** [comment]
With default buffer
![image](https://user-images.githubusercontent.com/7126643/50774625-3549ce80-1294-11e9-90e3-18668a71df2e.png)

With reduced buffer
![image](https://user-images.githubusercontent.com/7126643/50774696-60ccb900-1294-11e9-8386-bb2101186edd.png)


When doing a pedestrian route on the live data to the edge of the 5 minute isochrone, the route actually says it takes 8 minutes

![image](https://user-images.githubusercontent.com/7126643/50774863-e51f3c00-1294-11e9-9d31-c560dced94a4.png)

whereas to the edge of a 5 minute isochrone using the reduced buffer distance we get correctly 5 minutes for the route duration

![image](https://user-images.githubusercontent.com/7126643/50774943-1e57ac00-1295-11e9-978c-9f2a012b7315.png)


Need to look into it more though as you can travel farther to the west in 5 minutes than is indicated

**Comment by TimMcCauley** [comment]
@rabidllama beautiful, thanks -
