### ISSUE TITLE
Ability to read app.config naming alterations

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/openrouteservice#387]
The app.config reader could follow some kind of heuristic:

1. If environment variables are present, use these to determine which `app.config` to use
2. Else if use `app.config`
3. Else if use the first config starting with `app.config...`

**Comment by nilsnolde** [comment]
How about all the rest about running API tests? I find it a tedious process changing paths manually in the app.config, replacing .pbf's and other files. If you agree let's extend this to a bigger checklist

**Comment by nilsnolde** [comment]
Will postpone until spring is availabel in `development` branch:

https://docs.spring.io/spring-framework/docs/2.5.x/api/org/springframework/core/io/support/PathMatchingResourcePatternResolver.html

**Comment by nilsnolde** [comment]
I think we can close this. From what you suggested, 1. and 2. are actually working. Is 3. really necessary?

What ya think @TimMcCauley ?

**Comment by TimMcCauley** [comment]
Not really, should suffice, closing.
