### ISSUE TITLE
Cycling profiles making major unexpected detour

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice#389]
From #212 

In some cases, the bike profiles make major unexpected detours. This is after using elevation in graph building has been turned off, and when using dynamic weightings so it is not an issue with contraction hierarchies.

> Although it works a lot better now, I'm still getting weird results on some roads where it's making very strange detours. For example this road: http://maps.openrouteservice.org/directions?n1=50.808531&n2=5.929109&n3=16&a=50.808484,5.919753,50.806179,5.924013&b=1c&c=0&g1=-1&g2=0&h2=31&k1=en-US&k2=km
> While it should stay on the same straight road from A to B (Partijerweg), it takes a very odd detour. That road is perfectly suitable for cycling and not closed or somehow.

http://maps.openrouteservice.org/directions?n1=50.806891&n2=5.925177&n3=17&a=50.808484,5.919753,50.807074,5.922554&b=1a&c=0&g1=-1&g2=0&h2=31&d=25&k1=en-US&k2=km

**Comment by pathmapper** [comment]
There is a `cycleway` along the Partijerweg where the destination B is located:
https://www.openstreetmap.org/way/219230473#map=19/50.80652/5.92417

It looks like the cycling profile is not considering the short part `highway=tertiary` (https://www.openstreetmap.org/way/516006808) and pefers the longer way with `highway=cycleway` and `highway=track`.

**Comment by marq24** [comment]
the oneway tagged cycleway should IMHO not be the issue - IMHO the https://www.openstreetmap.org/way/45895304 & https://www.openstreetmap.org/way/523292271 is not tagged "correct" - or better the tagging of this element is causing the issue - the cycleway:left=lane...

What I don't understand is, there is this additional cyclepath in the OSM-data - why this is some sort of "duplicated" then on the street...  

I would remove the cycleway:left=lane - for both ways - and make them identical like the https://www.openstreetmap.org/way/219230470...

IMHO the tagging of the two sections (45895304 & 523292271) of the 'Partijerweg' will make it impossible for a bike to ride from NorthWest to SouthEast direction

Just as side node for the roadbike profile cycleways typically tried to be ignored... 

Just as a side node - the route is get's even more confusing - http://maps.openrouteservice.org/directions?n1=50.80626&n2=5.930375&n3=16&a=50.806186,5.924077,50.804477,5.926373&b=1c&c=0&g1=-1&g2=0&h2=31&k1=en-US&k2=km

**Comment by brmnr** [comment]
On that part of the road is a separated oneway cyclepath on the other side of the road (in the other direction). In the direction A => B there is a "lane" as you can see on: https://www.google.nl/maps/@50.8065852,5.9235946,3a,75y,113.2h,66.3t/data=!3m6!1e1!3m4!1s2WVYYUUmgDbEQdCD1_dXkg!2e0!7i13312!8i6656
Shouldn't the lane be tagged on that road then?

**Comment by marq24** [comment]
I am sorry - I was just wrong - when I understand everything correct, then there is a cycle lane from A->B and then there is a separate cycle-path from B->A (oneway)...

looking at detail into the attributes all seams to be correct - https://www.openstreetmap.org/edit?way=45895304

![image](https://user-images.githubusercontent.com/8012359/51172545-be27c200-18b3-11e9-8254-fd7e4c590ae2.png)

looks like that the **_cycleway:left=lane_** is not handled correctly by the code - at least that's the information that is required for a bike to pass the Partijerweg from A->B

OR when you compare it to https://www.openstreetmap.org/edit?way=523292271 - then  it's the **_bicycle:forward=use_sidepath_** which is causing the 'block' from A->B

**Comment by marq24** [comment]
just some more URL's to indicate, that the current tagging in combination with the implementation of the tag reading in our code is working suboptimal (I use my private routing server simply cause there I can make use of a higher zoom)....

Partijerweg "blocked" from A-B (way 45895304)
http://route.emacberry.com/directions?n1=50.805835&n2=5.925272&n3=19&a=50.805858,5.924597,50.805806,5.924675&b=1a&c=0&g1=-1&g2=0&h2=31&k1=en-US&k2=km

Partijerweg "passable" from A-B (just way 523292271)
http://route.emacberry.com/directions?n1=50.805835&n2=5.925272&n3=19&a=50.805833,5.924635,50.805806,5.924675&b=1a&c=0&g1=-1&g2=0&h2=31&k1=en-US&k2=km

**Comment by marq24** [comment]
just as update this seams to be a common error - already present in the graphhopper base... ;-)

https://graphhopper.com/maps/?point=50.806999%2C5.922827&point=50.805935%2C5.924517&locale=de&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale

at least I did not broke it ;-)

It's in the BikeCommonFlagEncoder

	// handle oneways        
	boolean isOneway = way.hasTag("oneway", oneways)
			|| way.hasTag("oneway:bicycle", oneways)
			|| way.hasTag("vehicle:backward")
			|| way.hasTag("vehicle:forward")
			|| way.hasTag("bicycle:forward");

	if (!way.hasTag("bicycle_road", "yes") && (isOneway || way.hasTag("junction", "roundabout"))
			&& !way.hasTag("oneway:bicycle", "no")
			&& !way.hasTag("bicycle:backward")
			&& !way.hasTag("cycleway", oppositeLanes)
			&& !way.hasTag("cycleway:left", oppositeLanes)
			&& !way.hasTag("cycleway:right", oppositeLanes))
	{
		boolean isBackward = way.hasTag("oneway", "-1")
				|| way.hasTag("oneway:bicycle", "-1")
				|| way.hasTag("vehicle:forward", "no")
				|| way.hasTag("bicycle:forward", "no");

		if (isBackward) {
			encoded |= backwardBit;
		} else {
			encoded |= forwardBit;
		}
	} else {
		encoded |= directionBitMask;
	}

I have to analyze this section more in detail - but we are running in this IF clause - and at the end the result will be, that this way will be handled as oneway... **thinking**

**Comment by aoles** [comment]
> just as update this seams to be a common error - already present in the graphhopper base... ;-)
> 
> https://graphhopper.com/maps/?point=50.806999%2C5.922827&point=50.805935%2C5.924517&locale=de&vehicle=bike&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale")

On GraphHopper maps the issue is gone now. So it seems to have been already fixed in their current codebase, probably through https://github.com/graphhopper/graphhopper/pull/1769.

@marq24 would you like to verify this? Cheers!

**Comment by marq24** [comment]
I'll make sure that this change (https://github.com/graphhopper/graphhopper/pull/1769/files/ad4fe02d3d9b5deb66dc0b88d02b61b28b52871c) will be integrated into the ors bike encoders

**Comment by aoles** [comment]
Awesome, thanks a lot @marq24 ! Looking forward to your PR :)

**Comment by marq24** [comment]
@aoles I would need some simple help (might be just to early)...

please take a look at this statement, when this becomes 'true'?

`boolean isOneway = A || B || C && (D || E)`

Visiting the java class room is/was quite a while ago... but IMHO in order that isOneway becomes to be true it's required, that either D or E would be true - do you agree?

please take now a look at the new graphhopper https://github.com/ratrun/biketourplanner/blob/ad4fe02d3d9b5deb66dc0b88d02b61b28b52871c/core/src/main/java/com/graphhopper/routing/util/BikeCommonFlagEncoder.java#L636
```
boolean isOneway = way.hasTag("oneway", oneways)
                || way.hasTag("oneway:bicycle", oneways)
                || way.hasTag("vehicle:backward")
                || way.hasTag("vehicle:forward")
                || way.hasTag("bicycle:forward") && (way.hasTag("bicycle:forward", "yes") || way.hasTag("bicycle:forward", "no"));
```
so IMHO - with the graphhopper change a way that have to be treated as **oneway for bikes** must have _bicycle:forward=yes_ or _bicycle:forward=no_ - in any other case the way will be handled as bi-directional (cause isOneway = false).

so at lest the code can be simplified to 
```
boolean isOneway = way.hasTag("oneway", oneways)
                || way.hasTag("oneway:bicycle", oneways)
                || way.hasTag("vehicle:backward")
                || way.hasTag("vehicle:forward") && (way.hasTag("bicycle:forward", "yes") || way.hasTag("bicycle:forward", "no"));
```
even if I doubt, that we will find a way tagging like 'oneway:bicycle=yes' together with a 'bicycle:forward=yes' (which would be necessary with the gh change)... I would even have the trend to simplify it then to:
```
boolean isOneway = way.hasTag("bicycle:forward", "yes") || way.hasTag("bicycle:forward", "no");
```

**Comment by aoles** [comment]
I don't think you are right on this.  The `&&` takes precedence over `||`, so the statement
```
A || B || C && (D || E)
```
is equivalent to
```
A || B || (C && D) || (C && E)
```
Back to the original code, one could clarify the evaluation order by adding parentheses like so:

```
boolean isOneway = way.hasTag("oneway", oneways)
                || way.hasTag("oneway:bicycle", oneways)
                || way.hasTag("vehicle:backward")
                || way.hasTag("vehicle:forward")
                || ( way.hasTag("bicycle:forward") && (way.hasTag("bicycle:forward", "yes") || way.hasTag("bicycle:forward", "no")) );
```

The GH's condition looks fine to me. Their latest change requires that if the tag `bicycle:forward` is present only the values `yes` or `no` yield `isOneway = true`. This makes sense because [other values](https://taginfo.openstreetmap.org/keys/bicycle%3Aforward) such as the most commonly used `use_sidepath` doesn't imply that the street is blocked in the other direction. The code handling this could be, however, simplified to examine just the values of `bicycle:forward` and not the presence of the tag itself.

```
boolean isOneway = way.hasTag("oneway", oneways)
                || way.hasTag("oneway:bicycle", oneways)
                || way.hasTag("vehicle:backward")
                || way.hasTag("vehicle:forward")
                || way.hasTag("bicycle:forward", "yes")
                || way.hasTag("bicycle:forward", "no")
```

**Comment by marq24** [comment]
thanks a lot @aoles teaching a old guy a basic java lesson... so expect my PR quite soon.. I would always write my code like this
`A || B || (C && (D || E))`
even if the brackets does not have any effect - it would IMHO simply the reading & understanding (to avoid possible misunderstandings from noobs like me)
