### ISSUE TITLE
Add code contribution explanations

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#393]
To complement our new `CONTRIBUTING.md`. 

- Base explanation on IntelliJ
- similar to internal confluence how-to
- but more explanatory on how to run `openrouteservice-api-tests`, i.e. which `app.config` and OSM .pbf to put where

**Comment by aoles** [comment]
Should we have these on the Wiki?

**Comment by TimMcCauley** [comment]
Yea, when we have finished it, sure!

**Comment by aoles** [comment]
Not sure I understand: I thought you would like to have IntelliJ ORS setup documented for potential developers. If this is the intended use case and audience, then maybe we could put it together with  the rest of documentation.

**Comment by TimMcCauley** [comment]
These are CONTRIBUTION guidelines, basically getting a best-practice in place for contributing code, created PR's etc.

**Comment by aoles** [comment]
I'm sorry but somehow I don't really get the point of putting the detailed instructions on how to set up a specific IDE to use with our project into the code CONTRIBUTION guidelines.

First of all, it is irrelevant what tool one uses to achieve the goals outlined there. Secondly, such instructions would just bloat up the document discouraging potential readers. Last but not least, while the initial setup is typically done only once, the rest of the guidelines is probably relevant throughout the whole development process so one might want to come back to them more often.

Therefore, even if we recommend to use IntelliJ I would rather suggest that we have a link to a separate resource documenting it, such as a Wiki page - I'm happy to come up with one! :)

**Comment by TimMcCauley** [comment]
Who says that is the case? You asked if we should have the contribution guidelines on the wiki? Did you have a look at this PR (wip) https://github.com/GIScience/openrouteservice/pull/395/files ?

**Comment by aoles** [comment]
Let me apologize @TimMcCauley for the misunderstanding! I should have been more precise in my comment:

>Should we have these on the Wiki?

where I was referring to the IntelliJ explanations listed above the comment rather than the contribution guidelines as a whole.

**Comment by nilsnolde** [comment]
No offense, I'll do it myself.

**Comment by nilsnolde** [comment]
https://github.com/GIScience/openrouteservice/wiki/Contributing-Code
