### ISSUE TITLE
Routing used not allowed turn

### ISSUE THREAD

**Issue by Hiawd** [GIScience/openrouteservice#397]
#### Here's what I did

Routing from 49.60563, 6.54410 to 49.60470, 6.54559. (Germany, Rheinland-Pfalz)

---
#### Here's what I got

Not allowed turn to the left was made.
http://bit.ly/2TYMY6c
![image](https://user-images.githubusercontent.com/46829027/51414609-599a8a80-1b73-11e9-8fab-9b6599b49cdd.png)
(openrouteservice)
---
#### Here's what I was expecting

Obviously i was expecting the correct routing :)
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=49.60563%2C6.54410%3B49.60470%2C6.54559#map=16/49.6040/6.5473
![image](https://user-images.githubusercontent.com/46829027/51414759-ca41a700-1b73-11e9-9a28-42543e4b0dc7.png)
(routing in osm)
---
#### Here's what I think could be improved
Same issue happend on different intersections with the same street properties as well. I haven't seen the issue in any osm routing I used. Thanks for helping

-spelling mistakes edited, 19.1.19

**Comment by aoles** [comment]
Thank you for reaching out!

The behavior you observe is expected. The reason for it is that the default routing algorithm which is optimized for speed does not support turn restrictions. This algorithm is used when no route preferences are specified.

You will get the proper route once you enable some filters, for example try *Avoid road types: ferries*. This of course doesn't have a direct influence on this particular route, however, it triggers another algorithm at our backed which does resolve turn restrictions correctly, see [here](https://maps.openrouteservice.org/directions?n1=49.605391&n2=6.545073&n3=16&a=49.605711,6.543914,49.604606,6.545491&b=0&l1=1&c=0&k1=en-US&k2=km).

![image](https://user-images.githubusercontent.com/6545356/51464221-59fa7780-1d65-11e9-9cf9-7f55d4280b6d.png)

For the record, when querying the API directly one can force the latter algorithm by appending to the request `optimized=false` without the need of specifying any custom route preferences.

Cheers,
Andrzej
