### ISSUE TITLE
Nothing after Clean Install

### ISSUE THREAD

**Issue by Devmaticz** [GIScience/openrouteservice#410]
Dears,

after a clean on Ubuntu 18, and after a lot of succeful builds.

i can no more access the endpoints /ors/health, after installation where no error where found.

is there any way to check what is hapening with my docker build ??

thank you

**Comment by TimMcCauley** [comment]
@Devmaticz thank you for your message - do all other endpoints work as expected? Can you please send me the curl request you are using for the health API?

**Comment by TimMcCauley** [comment]
@Devmaticz has this issue been solved or what is the status?
