### ISSUE TITLE
"Flying" Broken Image

### ISSUE THREAD

**Issue by tkan** [GIScience/openrouteservice#412]
This is a rather odd (and minor) bug…

#### Here's what I did
Planning a route from Salzburg to Leipzig, added a 'via point' to go through Prague (happened regardless of the placement of the origin, via and end point though). As the route computation is done, a broken image starts "flying" from Paris to Kiev. 

---
#### Here's what I got
I recorded an example "flight": https://streamable.com/7rrrd

The HTML of the affected element:
`<img src="https://maps.openrouteservice.org/images/marker-icon.png" class="leaflet-marker-icon leaflet-zoom-animated leaflet-interactive" style="margin-left: -12px; margin-top: -41px; width: 25px; height: 41px; transform: translate3d(2397px, 370px, 0px); z-index: 370;" alt="" tabindex="0">`

The `translate3d(2397px, 370px, 0px)` can be observed as changing as the animation progresses.

---
#### Here's what I was expecting
Well, no flying images. ;)

---
#### Further information
Not reproducible on Chromium (same machine). 

Used Browser:
Firefox 65.0.1, Linux 4.20.7-arch1-1-ARCH
with extensions:
```
Cookie AutoDelete
Decentraleyes (tested with activated and deactivated status)
Disable WebRTC
DuckDuckGo Privacy Essentials
I don't care about cookies (tested with activated and deactivated status)
LeechBlock NG
Mind the Time
minimal
Offline QR Code Generator
Old Reddit Redirect
OneTab
Shut Up: Comment Blocker
uBlock Origin

```

**Comment by nilsnolde** [comment]
Haha that's more for the fun category. Pity that doesn't exist.. 

Thanks for the good laugh! Haha that's so random, Paris to Kiev.. 

However, closing this, we have a separate repo for the [webapp](https://github.com/GIScience/openrouteservice-app).

**Comment by tkan** [comment]
Oh sorry, I was not aware of the separation. But glad I could lift up the spirits. :) Should I repost this to the webapp issues or is it too minor/special?

**Comment by pathmapper** [comment]
@tkan the [original creator of Leaflet](https://agafonkin.com/) is from Kiev, maybe you discovered an [Easter egg](https://en.wikipedia.org/wiki/Easter_egg_(media))  ...

**Comment by tkan** [comment]
@pathmapper 
I don't understand what is going on. The webapp uses (for what reason I can only wonder) the [MovingMarker](https://github.com/ewoken/Leaflet.MovingMarker) plugin. In the build code of the webapp ([scripts.[…].js](https://maps.openrouteservice.org/scripts.ff2acea2e9b40ca0.js)) there is the following code which can not be found in the repo:

```
var movingSleigh = L.Marker.movingMarker([[48.8567, 2.3508],[50.45, 30.523333]],[20000]).addTo($scope.mapModel.geofeatures[actionPackage.layerCode]);
movingSleigh.start();
```

So Paris and Kiev as well as the animation are definitely not at random in the code. Someone wanted to have an animated … … sleigh? From Paris to Kiev? o_O 

Gonna open [an issue in the other repo](https://github.com/GIScience/openrouteservice-app/issues/276).
