### ISSUE TITLE
highway=bridleway

### ISSUE THREAD

**Issue by pathmapper** [GIScience/openrouteservice#413]
#### Here's what I did
https://maps.openrouteservice.org/directions?n1=34.062899&n2=77.512236&n3=13&a=34.075199,77.421534,34.067281,77.418594&b=2&c=0&g1=-1&g2=0&k1=en-US&k2=km

---
#### Here's what I got
![auswahl_530](https://user-images.githubusercontent.com/20856381/52900078-dca21580-31f1-11e9-9bde-b870277bb213.png)

---
#### Here's what I was expecting
The much shorter way from A to B via this highway=bridleway 
https://www.openstreetmap.org/way/40634938

---
#### Here's what I think could be improved
Probably there is no easy answer on this.

The bridleway is not considered because it has no foot=yes.

Problems: 
- There is a different situation in Germany compared to other countries regarding the use of bridleway by foot.
- The English Wiki page states that highway=bridleway implies foot=yes: 
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbridleway
 while the German Wiki page doesn't mention this: 
https://wiki.openstreetmap.org/wiki/DE:Tag:highway%3Dbridleway

BTW: 
The [ORS Wiki for tag-filtering](https://github.com/GIScience/openrouteservice/wiki/Tag-Filtering#wheelchair) states
highway=[bridleway, cycleway] is accepted for the wheelchair profile which is kind of strange and seems to be not true:
https://maps.openrouteservice.org/directions?n1=34.071698&n2=77.420102&n3=17&a=34.074861,77.421491,34.067707,77.418305&b=3&c=0&h1=any&h2=31&h3=0.31&h4=-1&k1=en-US&k2=km

![auswahl_532](https://user-images.githubusercontent.com/20856381/52900220-9483f280-31f3-11e9-9be1-4ba9e1baf81a.png)

**Comment by pathmapper** [comment]
Would it be possible to consider `highway=bridleway` different for pedestrian routing based on the country where the bridleway is located?

| **Germany**  |      Accept     |  Reject |
|:----------|:-------------:|:------:|
| highway=bridleway |   | :heavy_check_mark:   |
| highway=bridleway AND foot=yes | :heavy_check_mark:    |  |
| **Other Countries** |      **Accept**     |  **Reject** |
| highway=bridleway | :heavy_check_mark:   |  |

**Comment by rabidllama** [comment]
Hi @pathmapper it seems that the rejection of the bridleway feature is introduced at the Graphhopper level of the code (https://graphhopper.com/maps/?point=34.067734%2C77.418852&point=34.1015%2C77.409389&locale=en-US&vehicle=foot&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale) so I would recommend raising an issue with them.

Currently, it is not possible to have different restrictions depending on different countries.

And for the wheelchair profile, wheelchair routing is only available within Europe, and so it is not possible to do a route in India. But there does seem to an issue in the wheelchair profile in that even in Europe the bridleways are ignored, so I will create a new issue for that one.

In summary though, the non-use of bridleway for pedestrian/hiking is an issue with GraphHopper itself and so it would be good if you raised the issue with them, and then when it is addressed there it will make it's way through to our codebase when we upgrade our GH library. And unfortunately it is not currently possible to limit these restrictions based on location. It may be something we look into in the future, but that would again be more in the GH code and so currently we don't have a planned development for it yet. finally for the wheelchair profile - it is only available in Europe, but there is a bug that means bridleways are not being accepted, which I will create a new Issue for.

 I will close this issue now though and open one (#415) that is just for the wheelchair bridleway inclusion (we have control of that profile whereas the pedestrian profiles are within GH)

**Comment by pathmapper** [comment]
Thanks @rabidllama,

There is an open GH issue, left a comment in https://github.com/graphhopper/graphhopper/issues/469.

Open GH PR for reference: https://github.com/graphhopper/graphhopper/pull/1408

> wheelchair routing is only available within Europe

Is this documented somewhere?

I do think that how `highway=bridleway` is  handled currently in OSM is unfortunate, because for routing engines covering Germany and other countries the only way to handle this is to have different restrictions depending on different countries (see my comment in https://github.com/GIScience/openrouteservice/issues/415#issuecomment-464668506).
