### ISSUE TITLE
Bridleways not being included in wheelchair profile

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice#415]
See Issue #413 for source

#### Here's what I did

Requested a route using the wheelchair profile that should include a bridleway but this way is not included
https://maps.openrouteservice.org/directions?n1=49.363637&n2=8.638226&n3=16&a=49.367745,8.638752,49.363217,8.637185&b=3&c=0&h1=any&h2=31&h3=0.31&h4=-1&k1=en-US&k2=km

---
#### Here's what I got

See above

---
#### Here's what I was expecting

The wheelchair profile should route over the bridleway next to Alter Speyerer Str. as it is not declared as a horse only way (OSM wiki states that highway=bridleway should be seen as foot=yes - https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbridleway)

---
#### Here's what I think could be improved

The problem seems to lie in the pedestrian processor when the OSM file is read in that both bridleway and cycleway have been omitted from the isPedestrianisedWay check.

**Comment by pathmapper** [comment]
> as it is not declared as a horse only way (OSM wiki states that highway=bridleway should be seen as foot=yes - https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbridleway)

@rabidllama the OSM Wiki page states as **_country-dependent regulation_** for Germany:

> In Germany, bridleways on public land is regulated by the traffic code (Straßenverkehrsordnung). The blue sign StVO 238 designates a way for riding only. **Thus using by pedestrians, bicycles and motor vehicles is excluded**, as long as no special permission is given by additional signage.
> 
> **Only those public bridleways should tagged with highway=bridleway.** 

I understand it that way, that there is no need to declare it as a horse only way, if the highway=bridleway is located in Germany and you have to add `foot=yes` explicitly if it is available for pedestrians.

**Comment by rabidllama** [comment]
hmm, that certainly makes things more difficult as we don't have a way the ability to do conditional values based on location

**Comment by pathmapper** [comment]
Despite this I don't think it's safe to assume that all `highway=bridleway` which are allowed for pedestrians are suitable for wheelchairs. Personally I know a lot of bridleways which are having loose, uneven ground or are muddy because they are used by horses.

What about considering `highway=bridleway` for the wheelchair profile only if they are having one of `wheelchair=[yes, permissive, limited]`?

This would also close this issue here :smile:

**Comment by rabidllama** [comment]
Generally, what would be needed in the case of those bridleways would be for people to tag them on osm with the relavent information. so when they are bare earth, they should be tagged using the surface:earth or similar. In general, the way type just says whether the way "could" be used, but then the other information is used to actually determine if it is useful for that particular user.

I think we could do yhat you suggested and limit the bridleways to be only if they have been tagged as wheelchair=*, but I believe that tehre are very few that would be tagged that way

**Comment by pathmapper** [comment]
You're right, there are only very few tagged that way. Worldwide according to overpass turbo only:

21 ways with `wheelchair=yes`: http://overpass-turbo.eu/s/Gfd
3 ways with `wheelchair=limited`: http://overpass-turbo.eu/s/Gfc

My point was that I think that if there is no wheelchair tagging, it is more likely the case that a `highway=bridleway` is not suitable for wheelchairs.

From what I can tell after having a look at different aerial imagery data (e.g. https://service.lgl-bw.de/dgm-dop-viewer/client/index.html and the other usual suspects) it seems like this is also true for your sample case:

https://maps.openrouteservice.org/directions?n1=49.363637&n2=8.638226&n3=16&a=49.367745,8.638752,49.363217,8.637185&b=3&c=0&h1=any&h2=31&h3=0.31&h4=-1&k1=en-US&k2=km

There seems to be no distinct additional way aside _Alte Speyer Straße_, the bridleway looks like a green strip in between the street and the field.

**Comment by rabidllama** [comment]
Probably seems better then to just remove the bridleways from the wheelchair profile

**Comment by rabidllama** [comment]
I have added an extra bit of code that only allows going over bridleways if they are explicitly set to be accessible for foot or wheelchair
