### ISSUE TITLE
Docker ORS enforces rate limit

### ISSUE THREAD

**Issue by jkanounji** [GIScience/openrouteservice#417]
Hey guys

I cloned the code and I'm running ORS in docker.
When I'm issuing requests, I'm still being constrained by the 40 per minute rate limit.
I only have one application that uses the service, so I don't need to implement such a rate limit. I tried looking in the code to where this limit is being set so I can either disable it or at at the very least increase it, but I couldn't find it anywhere. 
How can I go about disabling/increasing this limit?

**Comment by TimMcCauley** [comment]
@jkanounji this is really weird, it shouldn't be restricting at all. What is happening after the 40th request exactly? How are you firing requests? With some other library such as openrouteservice-py or directly via curl etcpp?

**Comment by jkanounji** [comment]
I'm using openrouteservice-py , and after the 40th request I get a message saying that I've exceeded the rate limit of 40 requests per minute , waiting for xxxx seconds, exactly as if I was using the public ORS api.

**Comment by TimMcCauley** [comment]
That is the reason, openrouteservice-py currently will restrict to 40 requests per minute; we will be adding an option though within to disable this for local running ors instances as it doesn't make sense for that case - could you please add an issue to the corresponding github repo? https://github.com/GIScience/openrouteservice-py/issues/new I will consider this closed in here for now.

**Comment by nilsnolde** [comment]
Noo, don't open an issue. It's an optional parameter when you instantiate a [`Client()` class](https://github.com/GIScience/openrouteservice-py/blob/ec75b9277b8a411a1138cd523839532d9d25d364/openrouteservice/client.py#L53).. No worries, I'll put the parameter to `None` in next version
