### ISSUE TITLE
Build fails when anything other than "ORSRoutingFile" set for "routing_name"

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice#424]
#### Here's what I did

Setting the routing_name property within the app.config and building ORS

--- 

#### Here's what I got

the build fails with on the unit test testCreateRouteFeatureType in SimpleFeatureTypeTest as it expects always to be named as ORSRoutingFile even when a value has been set in the app.config - it seems that the creation of the feature always accesses the app.config even for running unit tests

--- 

#### Here's what I was expecting

That ors should build when a value is entered in the app.config for routing_name. Also, the name of the property itself is a bit vague, and it seems that when applying the name to the feature, anything after a space is ignored.

---

#### Here's what I think could be improved

Either the unit tests should ensure that the app.config is not used for building the object, or the test should be removed as unit tests shouldn't be dependant on external items

**Comment by MichaelsJP** [comment]
@rabidllama It seems like the `routing_name` variable is a bit redundant. It's not correctly documented in the wiki documentation as it is just called `name` in there and it seems it was actually never returned. I didn't implement it correctly back then. `I would suggest dropping the config variable completely`, as we already have `attributions` in it. And that is basically the "same" if not better suited to brand a result. What you think?

**Comment by rabidllama** [comment]
I believe it was introduced when the gpx output was added as it was some sort of required value in the response
