### ISSUE TITLE
Directions for adding a map in docker container

### ISSUE THREAD

**Issue by yakovkeselman** [GIScience/openrouteservice#428]
I am trying to set up the service locally in a container. I was able to follow the directions in README to get it to work with the sample config/map. However, I'm unable to add another map without a rebuild. Is there a quick way to add a map file? Adding directions for this common use case would be much appreciated!

**Comment by TimMcCauley** [comment]
@yakovkeselman if you are sharing a volume holding the specific osm file, you can change the app.config to point it to the new osm file. Then delete the graphs folder and restart the container with `docker restart ors-app`
