### ISSUE TITLE
Adjust height Data for Tunnels

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#43]
Currently the Height data in tunnels is taken from the surface above.

This might be solved by using the tunnel entry and exit as border values and assign mean height values for points in between depending on the distance.

![tunnel](https://user-images.githubusercontent.com/23240110/32906290-c44cfd04-cafc-11e7-8f17-0782c6e70ee0.png)

**Comment by karussell** [comment]
See https://github.com/graphhopper/graphhopper/pull/798

**Comment by TimMcCauley** [comment]
thanks @karussell !

**Comment by TimMcCauley** [comment]
Will be added automatically when graphhopper updated
