### ISSUE TITLE
Update pom to build using ors.war

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice#432]
#### Here's what I did

Build ors via mvn:package

---
#### Here's what I got

output war is openrouteservice-5.0

---
#### Here's what I was expecting

It would be beneficial to have a consistent build file name so that the endpoint is always http://localhost:8082/ors/... rather than having to change the endpoint whenever a version increase happens

---
#### Here's what I think could be improved
Modifying the pom.xml to include a <finalName>ors</finalName> in the build section will always build the war as ors.war

**Comment by sfendrich** [comment]
Closed by #439
