### ISSUE TITLE
Add app.config documentation to wiki

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/openrouteservice#437]
It is currently almost impossible to understand how the app.config works. The comments within should be added to the wiki that a user understands how to configure running openrouteservice locally.

https://github.com/GIScience/openrouteservice/wiki/Configuration

Extract the information from https://github.com/GIScience/openrouteservice/blob/1d2837a9d24cfad6840646069234f4f61c40bb57/openrouteservice/src/main/resources/app.config.sample

**Comment by TimMcCauley** [comment]
@aoles @HendrikLeuschner could you please add the remaining information in the descriptions of lm/ch preparation/execution in https://github.com/GIScience/openrouteservice/wiki/Configuration-(app.config) ? Please keep it brief 👍

**Comment by rabidllama** [comment]
I will reopen this until the information from @aoles / @HendrikLeuschner has been added so that we don't lose track of it
