### ISSUE TITLE
How can i get the shortest sum of a matrix the shortest path

### ISSUE THREAD

**Issue by 123bistami** [GIScience/openrouteservice#452]
Hello,

I have a route matrix like attachment, where you is list the distance in km to the next location, i would like to get the shortest sum ( the shortest path ) of this matrix, how can i do that.!
Link to image:
https://www.dropbox.com/s/he3wxysl067dsvz/IMG_1465.jpg?raw=1

**Comment by nilsnolde** [comment]
for questions please use our [forum](https://ask.openrouteservice.org)
