### ISSUE TITLE
Accurate of isochrone service.

### ISSUE THREAD

**Issue by nguyen-dinh-dh** [GIScience/openrouteservice#46]
Hi ORS team,

I have a question about the results of isochrone service. I created an isochrone of 300meters by this api:
http://35.197.231.53:8080/ors/isochrones?format=json&locations=6.7750371,51.2122639&interval=300&profile=driving-car&range=300&range_type=distance

Then I calculate the distance between the center and the points in polygon:

http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.772056,51.210703&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.773549,51.20887&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.774529,51.208534&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.775116,51.208332&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.776894,51.20898&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.77966,51.210609&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.780431,51.211671&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.780444,51.212103&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.779679,51.214209&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.777318,51.215769&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.776942,51.215769&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.776746,51.215768&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.776206,51.215768&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.774259,51.21577&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.773846,51.215769&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.77384,51.215769&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.773427,51.21577&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.772079,51.21088&profile=driving-car
http://35.197.231.53:8080/ors/routes?coordinates=6.7750371,51.2122639|6.772056,51.210703&profile=driving-car

The distance results are:
[393, 477.4, 425.6, 634.4, 1239.2, 493.1, 673, 721, 834.5, 1049.7, 831.8, 831.5, 864, 1002.1, 1030.6, 1030.9, 1181, 399.8, 393]

Why does this happen? 

Thank you

**Comment by TimMcCauley** [comment]
@nguyen-dinh-dh , to visualize the issue:

![screen shot 2017-11-28 at 12 23 53](https://user-images.githubusercontent.com/10322094/33317316-085fc1b4-d437-11e7-82af-ad095ec495fa.png)

Step 1: The isochrone algorithm cuts off when the distance of 300 meters is reached and saves the corresponding coordinates. These are used for building the contour lines in step 2. The contour line of the isochrone is built in this second step which is a little more complicated using alpha shapes. So basically if you use the coordinates of the polygon border these aren't necessarily those of the cutoff points and the route distance will differ. Please dig in to the code if you want to find out how this is done.

**Comment by nguyen-dinh-dh** [comment]
Thank you for your explanation.
