### ISSUE TITLE
value of geometry_simplify=false is interpreted as 'true'

### ISSUE THREAD

**Issue by CramericaIndustries** [GIScience/openrouteservice#463]
#### Here's what I did

Requested:
`https://api.openrouteservice.org/directions?coordinates=10.999659000000065,49.217501|11.001968000000033,49.218401|10.999775329730937,49.21936818962267&profile=foot-hiking&preference=shortest&format=geojson&units=m&geometry_format=geojson&geometry_simplify=false&instructions=false&elevation=true&extra_info=surface|waytype|steepness&api_key=[CENSORED]
`
#### Here's what I got

`{"error":{"code":2011,"message":"geometry_simplify - true is not valid with coordinates - count > 2"},"info":{"engine":{"version":"5.0","build_date":"2019-03-13T15:24:45Z"},"timestamp":1552644179843}}`

Getting this even though `geometry_simplify` is set to `false` in the url parameter. This worked before and stopped working a few days ago. When I entirely remove the `geometry_simplify` parameter from the url, then it is working again.

#### Here's what I was expecting

As the `geometry_simplify` url parameter is set to `false` it should work.

**Comment by nilsnolde** [comment]
Jup, will fix on Monday.

**Comment by nilsnolde** [comment]
Think I actually found a solution to #457 which doesn't need to raise to an exception for waypoints > 2 and makes this issue redundant. Expect a fix in the next release (hopefully in a few weeks).

Until then, pls just dismiss `geometry_simplify` altogether if not wanted, on our backend it defaults to `False` anyways.
