### ISSUE TITLE
Possible bug isodistance - range in meters returning  out of range

### ISSUE THREAD

**Issue by yujorodrigues** [GIScience/openrouteservice#47]
range=300 returns out of range, saying range=15 (different from the input). units=m, range_type=distance.

Bad request or a bug?

https://api.openrouteservice.org/isochrones?api_key=my_key&locations=-48.263390%2C-18.882508&profile=foot-walking&range_type=distance&range=300&interval=20&units=m&location_type=start&attributes=area&options=&intersections=&id=

{"error":{"code":304,"message":"Parameter 'range=15' is out of range. Maximum possible value is 10."},"info":{"engine":{"version":"4.4.0","build_date":"2017-11-19T14:55:19Z"},"timestamp":1512215972786}}

**Comment by TimMcCauley** [comment]
Hi @yujorodrigues - it is because 300/20 equals great 10. Please try 30 for the interval setting.
