### ISSUE TITLE
RV/carvan/trailer profile

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#479]
It might be interesting to have a RV/carvan/trailer profile to complement seasonal access restrictions in national parks ;) There is already [interest for it](https://ask.openrouteservice.org/t/bug-maximum-speed-option-not-taken-in-account-for-isochrones-maps/305).

The idea would be to take into account country-specific speed regulations, and allow vehicle weight/dimension specification as for HGV.

![image](https://user-images.githubusercontent.com/6545356/55003943-9bafd480-4fd9-11e9-8076-3aeccf1fdc99.png)

**Comment by rabidllama** [comment]
I think this is something that we would not look into for a while as we do not have the resources in terms of people and servers to have the extra profile running

**Comment by aoles** [comment]
![image](https://user-images.githubusercontent.com/6545356/55006176-9e142d80-4fdd-11e9-9acb-798a71ec2d6e.png)

**Comment by aoles** [comment]
There are currently no plans of implementing a tailored rv/trailer profile because of limited resources and a relativelly narrow use case of a such highly specialized subprofile. Instead, we will look into a more generic solution of re-introducing the recently disabled option to set [maximum speed](https://github.com/GIScience/openrouteservice/issues/480) which we believe will serve a broader audience.
