### ISSUE TITLE
Configuration of max locations for isochrones not used in code

### ISSUE THREAD

**Issue by cDanowski** [GIScience/openrouteservice#482]
#### Here's what I did
I increased the parameter "ors.services.isochrones.maximum_locations" within app.config (i.e. to 5 or 10 or 100), because I intended to create isochrones requests with more than 2 start points.

---
#### Here's what I got
However I always got ParameterValueException saying that the max number of isochrone locations is limited to 2 (in contrary to the value set within app.config).
---
#### Here's what I was expecting
The value "ors.services.isochrones.maximum_locations" set in app.config should actually be applied to limit the number of allowed isochrone locations. Thus it should allow isochrone requests with the set number of locations.

---
#### Here's what I think could be improved
The dynamic parameter "ors.services.isochrones.maximum_locations" should be used within the class "IsochronesRequestHandler" at line 163, 164. I inspected the code (https://github.com/GIScience/openrouteservice/blob/master/openrouteservice/src/main/java/heigit/ors/api/requests/isochrones/IsochronesRequestHandler.java#L163) and currently it still uses the constant value of "2" to determine whether the submitted number of locations is valid. It should instead use "IsochronesServiceSettings.getMaximumLocations()" to compare to the value set in app.config.

Hope this helps.
Best regards,
Christian

**Comment by nilsnolde** [comment]
It does help, thanks so much! I'll take the low-hanging fruit;)

**Comment by cDanowski** [comment]
no problem ;)

**Comment by nilsnolde** [comment]
I found it, but it'll take a while for the change to propagate to `master`.

In the meantime, if you use the old API (i.e. GET with `localhost:8082/openrouteservice-5.0/isochrones?query_params`, it will respect your app.config settings.
