### ISSUE TITLE
Investigate 'recommended' weighting and decide which parts to remove or keep

### ISSUE THREAD

**Issue by HendrikLeuschner** [GIScience/openrouteservice#488]
If recommended weighting is to be kept, it has to be adapted to be a stand-alone weighting for core-alt.

**Comment by HendrikLeuschner** [comment]
Currently in the core-alt-bike branch. Will probably be merged into dev as soon as core-alt is updated to the GH 0.12 code style

**Comment by rabidllama** [comment]
I will close this as there is more being done on the issue #665
