### ISSUE TITLE
Classpath problems on Windows: resources not found

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#489]
We have an error when trying to run ORS on Windows, which seems to be related to the way we try to access `resources`, like `app.config` and `locales`.

Tomcat trying to build the webapp, raises a `NullPointerException` for `app.config`. When we set `File file = new File("C:\\absolute\\path\\to\\app.config")`, then it works.

Relevant lines in `AppConfig.java`:
https://github.com/GIScience/openrouteservice/blob/e23e9ced3e3e4015334714378138db7043983135/openrouteservice/src/main/java/heigit/ors/config/AppConfig.java#L51

However, when it finds the app.config, we can't request a route from the `directions` endpoint, a query gives:
```
{
    "error": {
        "message": "Resources can not be found."
    },
    "info": {
        "engine": {
            "version": "5.0",
            "build_date": "2019-04-03T09:06:15Z"
        },
        "timestamp": 1554282722566
    }
}
```
We suspect, it's due to a similar path problem in `LocalizationManager.java`. Relevant lines:
https://github.com/GIScience/openrouteservice/blob/e23e9ced3e3e4015334714378138db7043983135/openrouteservice/src/main/java/heigit/ors/localization/LocalizationManager.java#L62

@marq24 are you running Windows by any chance? Do you have an idea how to solve both these issues platform independently? Any hints are appreciated. Thx!

**Comment by marq24** [comment]
sorry - just catching up... so by default the WAR should be auto extracted by the Tomcat... and then the app.config file should be present in the FileSystem...

I have a slight different setup here locally - I jave "linked" my IntelliJ 'webContent' folder to a context named "ors"

by placing a ors.xml in the conf\Catalina\localhost folder of my tomcat installation :

```
<Context
docBase="D:\DEV\projects.osm\openrouteservice\openrouteservice\WebContent" reloadable="yes">
</Context>
```

in the AppConfic class you might like to move away from File... The ConfigFactory have an alternative constructor thet works with Resources... parseResources(...) - of course that is just a quess

**Comment by marq24** [comment]
then I just looked into the LocalizationManager class - to be honest - just let's refactor that completly - the purpose is to create hashmaps with key value pairs - this can be done completly different...
