### ISSUE TITLE
Wrong coordinate order in isochrones bounding box

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#493]
The bounding box returned for **isochrones**  seems to have the coordinates ordered as

```
max Longitude, min Longitude, max Latitude, min Latitude
```

However, according to the [geoJSON specification](https://tools.ietf.org/html/rfc7946#section-5) these should be rather in the order

```
min Longitude , min Latitude , max Longitude , max Latitude
```

> The value of the bbox member MUST be an array of
   length 2*n where n is the number of dimensions represented in the
   contained geometries, with all axes of the most southwesterly point
   followed by all axes of the more northeasterly point.  The axes order
   of a bbox follows the axes order of geometries.

This problem  is evident in [API playground](https://openrouteservice.org/dev/#/api-docs/v2/isochrones/{profile}/post) where for the default example yields

```
"bbox" :  [ 8.701228 , 8.658792, 49.436847, 49.406197 ]  
```

The **directions** endpoint doesn't seem to be affected.

**Comment by nilsnolde** [comment]
I'll take the cheap one.

**Comment by aoles** [comment]
As this is a rather serious bug which renders the bounding box unusable we should consider publishing the fix without any unnecessary delay, certainly before ORS 5.2.

**Comment by nilsnolde** [comment]
it's alright, not that crazy serious. not a single issue reported so far. I can take care of it on Thursday. Feel free to quickly do it if you want.

**Comment by aoles** [comment]
Thanks @nilsnolde ! No stress, but it's important in the sense that anyone trying to visualize the isochrones will probably run across this issue, at least that was the case for me as soon as I updated the R package to API v2.

**Comment by nilsnolde** [comment]
Not every implementation takes `bbox` into account necessarily. We're displaying them into our web app without issues.

**Comment by aoles** [comment]
> We're displaying them into our web app without issues.

This might be just because maps.openrouteservice.org still queries the legacy API. I didn't experience the issue with API v1 either but only after upgrading to API v2.
