### ISSUE TITLE
Unable to validate API v2 GPX response

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#496]
An attempt to validate API v2 GPX response against XML schema [fails](http://www.utilities-online.info/xsdvalidation/?save=63531f0f-d03b-42f4-8516-da8b48ab4f06-xsdvalidation).

Apparently the response is missing the namespace specification as after changing 
```xml
<gpx version="1.0" creator="openrouteservice">
```
to
```xml
<gpx version="1.0" creator="openrouteservice" xmlns="https://raw.githubusercontent.com/GIScience/openrouteservice-schema/master/gpx/v2/ors-gpx.xsd">
```
validation [succeeds](http://www.utilities-online.info/xsdvalidation/?save=1ba406e9-4d58-47b0-8cf4-32b908233115-xsdvalidation).

**Comment by MichaelsJP** [comment]
@aoles it's an easy fix. I'll do it next week.
