### ISSUE TITLE
Routing with profile bike normal doesn't work

### ISSUE THREAD

**Issue by elutz** [GIScience/openrouteservice#502]
#### Here's what I did

Tried to calculate a route with profile bicycle normal on https://maps.openrouteservice.org/directions

---
#### Here's what I got

There wasn't any route calculated. 
Some errors were shown in the JS console of the browser. See attached logs from the console.
[maps.openrouteservice.org-1555612995538.log](https://github.com/GIScience/openrouteservice/files/3095839/maps.openrouteservice.org-1555612995538.log)

If I change the profile to bicycle mountain bike it works!

---
#### Here's what I was expecting

A calculated route of course.

---

**Comment by nilsnolde** [comment]
This is not a backend issue. Good to know though. But please use our [forum](https://ask.openrouteservice.org) next time.
