### ISSUE TITLE
API v2 matrix generates wrong ordered output for non-square matrices

### ISSUE THREAD

**Issue by ivoburger** [GIScience/openrouteservice#511]
#### Here's what I did

I call the v2 matrix API with body:
{"locations":[[9.70093,48.477473],[9.207916,49.153868],[37.573242,55.801281],[115.663757,38.106467]],"metrics":["distance","duration"],"sources":[0,1],"units":"m"}
---
#### Here's what I got

![image](https://user-images.githubusercontent.com/48688535/57409036-87b9de00-71e7-11e9-8e4a-b144eee3efd8.png)
The results are probably in a wrong order.
---
#### Here's what I was expecting

The red rectangle on the left should be 0 sec, the rectangle on the right should have some value.
---
#### Here's what I think could be improved
Please check the ordering of the outputs if only some sources / destinations are required in the output matrix.

**Comment by rabidllama** [comment]
I have checked on a local instance running the latest version and this doesn't seem to be occuring after another fix was made (relating to the arrays for output in the matrix results). This latest version should be getting deployed in the next week or two.

**Comment by ivoburger** [comment]
Thanks for the info.

**Comment by nilsnolde** [comment]
Fixed in v5.0.1
