### ISSUE TITLE
Request parameters exceeding server config, even when changed

### ISSUE THREAD

**Issue by Devmaticz** [GIScience/openrouteservice#517]
dear all,

i have a brand new ORS server runing and everything works well, using the docker installation guide as mentioned in the doc

when i make changes to the docker > conf > app config sample, by putting bigger values to the maximum routes.

after lunching my container, my changes doesn't take effect, even when i delete the graphs folder before building the container again

**Comment by nilsnolde** [comment]
Which maximum routes? Please give the exact parameter.

**Comment by TimMcCauley** [comment]
Closing this for now, please open again if not resolved.
