### ISSUE TITLE
Index of turn instructions is shifted in the presence of way points

### ISSUE THREAD

**Issue by marq24** [GIScience/openrouteservice#519]
Please take a look at this simple route
https://maps.openrouteservice.org/directions?n1=51.815798&n2=8.488516&n3=16&a=51.818501,8.474434,51.814187,8.497066&b=1c&c=0&k1=en-US&k2=km

all is fine - please open the TurnInstruction details - and check/confirm that the TURN LEFT is at the correct position (aka index)
![image](https://user-images.githubusercontent.com/8012359/58280379-b962a580-7da0-11e9-893f-3c675fc309a0.png)

Then allow me to slightly modify the route to this here:
https://route.emacberry.com/directions?n1=51.815891&n2=8.48785&n3=16&a=51.818501,8.474434,51.81684,8.479772,51.814187,8.497066&b=1c&c=0&k1=en-US&k2=km

so placing a via point inbetween - please open again the TurnInstruction details and see that now the TURN LEFT is shifted
![image](https://user-images.githubusercontent.com/8012359/58280482-fdee4100-7da0-11e9-9448-524f7c1219a1.png)

looking closer into the JSON-Response for the specific turn

GOOD:
`{"distance":921.7,"duration":138.2,"type":0,"instruction":"Turn left onto <b>Westerwieher Straße, L 836<\/b>","name":"Westerwieher Straße, L 836","way_points":[14,24]}`

BAD:
`{"distance":921.7,"duration":138.2,"type":0,"instruction":"Turn left onto <b>Westerwieher Straße, L 836<\/b>","name":"Westerwieher Straße, L 836","way_points":[16,26]}`

I hope you notice, that in the second case the way_points info is shifted by +2

**Comment by TimMcCauley** [comment]
<img width="1251" alt="Screenshot 2019-05-24 at 18 34 00" src="https://user-images.githubusercontent.com/10322094/58346329-88db4400-7e52-11e9-904e-f843e5fe3387.png">

Healthy again @marq24  ;-)

**Comment by marq24** [comment]
GREAT - and also inside my app all TurnInstructions are back at the correct place - thanks that you are so flexible to update all servers in less then 24h
