### ISSUE TITLE
foot-hiking query stopped working

### ISSUE THREAD

**Issue by CramericaIndustries** [GIScience/openrouteservice#522]
#### Here's what I did
Requested [https://api.openrouteservice.org/directions?coordinates=-8.285694128863724,42.90609872641957|-8.297824398499415,42.908103477868934|-8.300573612820926,42.91533275672189|-8.294116876280896,42.91189116434972&profile=foot-hiking&preference=shortest&format=geojson&units=m&geometry_format=geojson&instructions=false&elevation=true&extra_info=surface|waytype|steepness&api_key=[CENSORED]](https://api.openrouteservice.org/directions?coordinates=-8.285694128863724,42.90609872641957|-8.297824398499415,42.908103477868934|-8.300573612820926,42.91533275672189|-8.294116876280896,42.91189116434972&profile=foot-hiking&preference=shortest&format=geojson&units=m&geometry_format=geojson&instructions=false&elevation=true&extra_info=surface|waytype|steepness&api_key=[CENSORED])

---
#### Here's what I got

> {"error":{"code":2099,"message":"Unable to compute a route"},"info":{"engine":{"version":"5.0.1","build_date":"2019-05-23T11:46:41Z"},"timestamp":1558703603397}}

---
#### Here's what I was expecting
Last used this a few days ago with no problems. But now, all of a sudden it returns that error.
If I switch the profile/travel-mode to driving or cycling it works just fine.

**Comment by TimMcCauley** [comment]
@CramericaIndustries this will work again by Monday, it's a bug in the most recent update. Sorry about this!

**Comment by TimMcCauley** [comment]
@CramericaIndustries if you remove extra_info for now it will compute a route and from next week onwards the API's will work normally again.

**Comment by CramericaIndustries** [comment]
You guys should consider pushing new versions on Mondays, instead of Fridays ;D
Last time my open route service API code also stopped working on a Friday afternoon. Fortunately there was an easy workaround...

**Comment by nilsnolde** [comment]
Wouldn't matter. It's not because we're not doing anything on weekends, the graphs just take 3 days to build. It might be a good idea though to have fallback option (either your own ORS Server that you can deploy on short notice or another provider in case you don't need all the extra options we offer).

**Comment by CramericaIndustries** [comment]
> Wouldn't matter. It's not because we're not doing anything on weekends, the graphs just take 3 days to build. 
Ah now I understand. My apologizes if  you understood my comment as criticism. It was meant to be constructive. I really appreciate the work you guys are doing!

> It might be a good idea though to have fallback option (either your own ORS Server that you can deploy on short notice or another provider in case you don't need all the extra options we offer).
Yeah I already have Google Maps routing as a backup. However sometimes it doesn't has roads/trails but OSM does have those and vice versa.

**Comment by nilsnolde** [comment]
Oh no, guess I have to work on my communication;) Not offended or anything.

I'd recommend you use Mapbox as a fallback option. It's also OSM and their routing engines are quite good.

**Comment by CramericaIndustries** [comment]
Is working again. Thanks a lot!
