### ISSUE TITLE
Hgv routing does not respect `destination` access restriction

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#525]
Reported at [ask.openrouteservice.org](https://ask.openrouteservice.org/t/hgv-routing-does-not-respect-access-resriction/574), transit [routing](https://maps.openrouteservice.org/directions?n1=49.855862&n2=10.023931&n3=15&a=49.746073,9.93649,49.852153,10.000563&b=4a&c=0&f1=20&k1=en-US&k2=km) over trunk road tagged with [`hgv:destination`](https://overpass-turbo.eu/s/Jn6).

Cause: `HeavyVehicleFlagEncoder` is missing the `destination_speed` reduction for [`CarFlagEncoder`](https://github.com/GIScience/openrouteservice/blob/development/openrouteservice/src/main/java/heigit/ors/routing/graphhopper/extensions/flagencoders/CarFlagEncoder.java#L450).

Compare to [this road](https://www.openstreetmap.org/way/31791781) tagged with `access:destination`, driving [car makes a detour](https://maps.openrouteservice.org/directions?n1=49.81442&n2=9.925653&n3=15&a=49.813495,9.918547,49.816084,9.932714&b=4a&c=0&f1=20&k1=en-US&k2=km) unlike [hgv](https://maps.openrouteservice.org/directions?n1=49.81442&n2=9.925653&n3=15&a=49.813495,9.918547,49.816084,9.932714&b=4a&c=0&k1=en-US&k2=km).

**Comment by aoles** [comment]
Should be fixed via https://github.com/GIScience/openrouteservice/commit/e29d92a60f6c37ef9d5bb5814591899295dfaeb2 upon migration to GH 0.12.

**Comment by rabidllama** [comment]
Did the update of GH fix this?

**Comment by aoles** [comment]
Nope, apparently because `destination_speed` [has been disabled again](https://github.com/GIScience/openrouteservice/blame/master/openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/flagencoders/HeavyVehicleFlagEncoder.java#L120).

**Comment by aoles** [comment]
A proper solution taking into account tags such as `hgv:destination` for hgv subprofiles requires reducing the travel speed at query time because when the graphs are build we don't know *a priori* whether the restriction will apply to the profile selected for routing.

**Comment by aoles** [comment]
Will be closed after successful release.
