### ISSUE TITLE
Avoid Multiple Polygons

### ISSUE THREAD

**Issue by novotnytom** [GIScience/openrouteservice#530]
Hi!

Does the function 'Avoid Polygons' works with multiple Polygons?

If I call the API Request with just one polygon everything is fine, but with two Polygons I got the 400 Error.

My Params:
`
avoid_polygons: {
      type: Polygon,
      coordinates: {
[
  [ //first polygon
      [[xx, yy], [xx, yy],[xx,yy]],
  [ //second polygon
      [[xx, yy], [xx, yy],[xx,yy]]
]
}` 

Thank you Tomas

**Comment by aoles** [comment]
Hi Tomas,

The geometry specifications of  `avoid_polygons` follows the GeoJSON standard, try [MultiPolygon](https://en.wikipedia.org/wiki/GeoJSON#Geometries).

Cheers,
Andrzej

**Comment by novotnytom** [comment]
Thank you Andrzej,
it works ;)

Tomas
