### ISSUE TITLE
Routing issue on some hiking trails

### ISSUE THREAD

**Issue by Duke74** [GIScience/openrouteservice#532]
Hi, 

I noticed that some hiking trails are not used when computing a route (using the hiking profile)
It's seems like it's a bug because the trails have highway=path or the higway=footway attribute so it should be working. (most of the trails are working good btw)

Here is 2 exemple where the issue is present : 
https://maps.openrouteservice.org/directions?n1=52.191443&n2=-117.105696&n3=15&a=52.193114,-117.129493,52.18259,-117.113056&b=2b&c=1&k1=en-US&k2=km

and

https://maps.openrouteservice.org/directions?n1=52.191443&n2=-117.105696&n3=15&a=52.191246,-117.115717,52.183853,-117.107692&b=2b&c=1&k1=en-US&k2=km

Here is one just next to it where everything works great : 

https://maps.openrouteservice.org/directions?n1=52.191443&n2=-117.105696&n3=15&a=52.193929,-117.127862,52.205345,-117.128892&b=2b&c=1&k1=en-US&k2=km

I can provide other exemples of non-working trails if that's usefull.
Do you have an idea why this trails are not taken into account for route computation ?
Is there some openstreet map attributes that can prevent the routing system to avoid some trails ?

**Comment by TimMcCauley** [comment]
Greetings @Duke74 - thank you. We will investigate, usually these situations can arise when seasonal access restricts the path but this seems not to be the case. @rabidllama any ideas?

Here a link to the [OSM way 71500717](https://www.openstreetmap.org/way/71500717#map=14/52.1797/-117.0969) 

<img width="927" alt="Screenshot 2019-06-03 at 13 46 40" src="https://user-images.githubusercontent.com/10322094/58799704-41994400-8606-11e9-8d20-c27a2cadd538.png">

**Comment by aoles** [comment]
> Here a link to the [OSM way 71500717](https://www.openstreetmap.org/way/71500717#map=14/52.1797/-117.0969)

... and to the working one: [OSM way 519739830](https://www.openstreetmap.org/way/519739830#map=15/52.1921/-117.1099)

![image](https://user-images.githubusercontent.com/6545356/58805519-81672800-8614-11e9-9d70-9f6aff3c4b8f.png)

One difference is the highway type (`path` vs. `footway`), plus the working one has an explicit `foot` access tag.

**Comment by Duke74** [comment]
> One difference is the highway type (path vs. footway), plus the working one has an explicit foot access tag.

Yes I noticed this too but there is another trail in the area that is a `path` and have the `foot` attribute too but it's not taken by the routing system either.

https://www.openstreetmap.org/way/264966225

**Comment by aoles** [comment]
Right, thanks for sharing your observation! This is really weird, as both the working and the non-working trail are tagged virtually the same.

**Comment by lucamanga** [comment]
See this: https://ask.openrouteservice.org/t/strange-thing-with-waliking-directions/602

**Comment by aoles** [comment]
I can confirm this issue with `development` branch on the latest OSM dataset.

**Comment by rabidllama** [comment]
Think I have found the problem - it is not actually to do with ORS but the fact that none of the footpath ways are connected to the road. Therefore during the build process, the footpaths are not included as they make a subgraph network with only a handful of edges

**Comment by aoles** [comment]
Makes sense @rabidllama, thanks for chiming in!

@Duke74 I've made a quick [edit in OSM](https://www.openstreetmap.org/changeset/71140284) which should address some of the problems, feel free to correct any remaining ones.
