### ISSUE TITLE
Problems with visualizing ORS GPX response

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#533]
Reported in [forum](https://ask.openrouteservice.org/t/gpx-endpoint-returns-erroneous-routes/591). Tried various viewers, all seem to have a problem to visualize the response.

![image](https://user-images.githubusercontent.com/6545356/58809536-6bf5fc00-861c-11e9-8d62-e3a7edfe4f2f.png)

**Comment by aoles** [comment]
Minimal GPX response illustrating the issue:

`<gpx version="1.0" creator="openrouteservice"><metadata><name>openrouteservice directions</name><desc></desc><author><name>openrouteservice</name><email id="support" domain="openrouteservice.org"/><link href="https://openrouteservice.org/"><text>https://openrouteservice.org/</text><type>text/html</type></link></author><copyright author="openrouteservice.org | OpenStreetMap contributors"><year>2019</year><license>LGPL 3.0</license></copyright><time>2019-06-03T14:49:19.145Z</time><bounds maxLat="49.415766" maxLon="8.687879" minLat="49.415104" minLon="8.68576"/></metadata><rte><rtept lat="49.415104" lon="8.685861"><name>Keplerstraße</name><desc>Head north on Keplerstraße</desc><extensions><distance>68.1</distance><duration>16.3</duration><type>11</type><step>0</step></extensions></rtept><rtept lat="49.415713" lon="8.68576"><name>Keplerstraße</name><desc>Head north on Keplerstraße</desc><extensions><distance>68.1</distance><duration>16.3</duration><type>11</type><step>0</step></extensions></rtept><rtept lat="49.415734" lon="8.686667"><name>Keplerstraße</name><desc>Head north on Keplerstraße</desc><extensions><distance>68.1</distance><duration>16.3</duration><type>11</type><step>0</step></extensions></rtept><rtept lat="49.415766" lon="8.687771"><name>Keplerstraße</name><desc>Head north on Keplerstraße</desc><extensions><distance>68.1</distance><duration>16.3</duration><type>11</type><step>0</step></extensions></rtept><rtept lat="49.415198" lon="8.687879"><name>Keplerstraße</name><desc>Head north on Keplerstraße</desc><extensions><distance>68.1</distance><duration>16.3</duration><type>11</type><step>0</step></extensions></rtept><rtept lat="49.415713" lon="8.68576"><name>Schröderstraße</name><desc>Turn right onto Schröderstraße</desc><extensions><distance>145.6</distance><duration>34.9</duration><type>1</type><step>1</step></extensions></rtept><rtept lat="49.415734" lon="8.686667"><name>Schröderstraße</name><desc>Turn right onto Schröderstraße</desc><extensions><distance>145.6</distance><duration>34.9</duration><type>1</type><step>1</step></extensions></rtept><rtept lat="49.415766" lon="8.687771"><name>Schröderstraße</name><desc>Turn right onto Schröderstraße</desc><extensions><distance>145.6</distance><duration>34.9</duration><type>1</type><step>1</step></extensions></rtept><rtept lat="49.415198" lon="8.687879"><name>Schröderstraße</name><desc>Turn right onto Schröderstraße</desc><extensions><distance>145.6</distance><duration>34.9</duration><type>1</type><step>1</step></extensions></rtept><rtept lat="49.415766" lon="8.687771"><name>Werderstraße</name><desc>Turn right onto Werderstraße</desc><extensions><distance>63.6</distance><duration>9.2</duration><type>1</type><step>2</step></extensions></rtept><rtept lat="49.415198" lon="8.687879"><name>Werderstraße</name><desc>Turn right onto Werderstraße</desc><extensions><distance>63.6</distance><duration>9.2</duration><type>1</type><step>2</step></extensions></rtept><rtept lat="49.415198" lon="8.687879"><name/><desc>Arrive at Werderstraße, on the left</desc><extensions><distance>0.0</distance><duration>0.0</duration><type>10</type><step>3</step></extensions></rtept><extensions><distance>277.3</distance><duration>60.4</duration><ascent>0.0</ascent><descent>0.0</descent><avgspeed>16.5</avgspeed><bounds maxLat="49.415766" maxLon="8.687879" minLat="49.415104" minLon="8.68576"/></extensions></rte><extensions><attribution>openrouteservice.org | OpenStreetMap contributors</attribution><engine>5.0.1</engine><build_date>2019-05-29T14:58:37Z</build_date><profile>driving-car</profile><language>en</language><distance-units>m</distance-units><instructions>true</instructions><elevation>false</elevation></extensions></gpx>`

![image](https://user-images.githubusercontent.com/6545356/58811576-52ef4a00-8620-11e9-8db8-72d28ab2bd0f.png)

**Comment by MichaelsJP** [comment]
@aoles this is interesting. I just tried it myself and it looks quite reproducible and therefore resolvable. It's present in dev and master as well. At least it's wrong the same way across branches hehe ;). So, let's see. Onto it :rocket:  
![image](https://user-images.githubusercontent.com/22392104/58814609-54237580-8626-11e9-9229-2f9c69f7b599.png)

**Comment by MichaelsJP** [comment]
![image](https://user-images.githubusercontent.com/22392104/58888311-8052fb00-86e7-11e9-8baf-20d704032018.png)
Looks fixed. I'll leave it for a day or two, just in case :+1:

**Comment by aoles** [comment]
Awesome, thanks a lot for the prompt fix!
