### ISSUE TITLE
External storage might not contain entries for all edge IDs

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#535]
`setEdgeValue()` methods in `*GraphStorage` classes contain a call to `ensureEdgesIndex()` which use `DataAccess.ensureCapacity()` to control the storage size which is not fixed during initialization. This approach might lead to missing storage entries for edges with high IDs unless `setEdgeValue()` is called for every edge by `processEdge()` method in `*GraphStorageBuilders`. Currently some builders, such as `HeavyVehicleGraphStorageBuilder`, call this method conditionally, which _might_ lead to an error when the storage is queried with an edge ID exceeding the storage capacity. This, however,  occurs only if the ID overflows the pre-allocated segment size.

**Comment by rabidllama** [comment]
Fixed in Release 5.0.2
