### ISSUE TITLE
One-way streets not resolved properly

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#539]
Reported in the [forum](https://ask.openrouteservice.org/t/directions-does-not-longer-respect-one-way-road/628).

In the following [example](http://maps.openrouteservice.org/directions?n1=49.018927&n2=1.754428&n3=17&a=49.019324,1.755527,49.019937,1.754637&b=0&c=0&k1=en-US&k2=km) roads tagged with `oneway: yes` such as [46721415](https://www.openstreetmap.org/way/46721415) are not respected.

![image](https://user-images.githubusercontent.com/6545356/59147351-848a5b80-89fa-11e9-9b45-92748cb17ef7.png)

**Comment by aoles** [comment]
Thanks a lot @MichaelsJP for taking the lead on this one!

**Comment by MichaelsJP** [comment]
The ways with the IDs `46721420` (Rue Pierre Curie) and `46721415` (Rue Léon Andrieux) were added the tag `oneway=yes` on the 5th of June 2019. 
I'll wait the next global Graph and test ist again. Maybe the one-way routes were not present in the global file used for the current graph.

**Comment by aoles** [comment]
It seems this has been indeed a data issue as stated above as it has resolved itself by now.
