### ISSUE TITLE
Identify the date of osm data used in a profile

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice#542]
It would be useful to know when the data is from that is being used in the different profiles. This should be returned somewhere so that it can be used by services making use of the data and by the maps front end to display when the data for each profile is from.

Currently this information is already available in the GraphHopper objects via the `datareader.data.date` graph property, so it just needs passing through to responses

**Comment by HendrikLeuschner** [comment]
I added this sort of feature concerning the md5 hash a year or so ago. I guess you can just use the same pipeline

**Comment by takb** [comment]
Implemented in development-v6 branch, awaiting merge
