### ISSUE TITLE
Use funiculars for foot-* and wheelchair

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#552]
Asked on the [forum](https://ask.openrouteservice.org/t/ors-tools-and-osm-in-qgis-for-an-accessibility-and-mobility-project/652/5).

They're fairly rare with [1500 ways worldwide](https://taginfo.openstreetmap.org/tags/railway=funicular) but could be really useful for `foot-*`  and even more for `wheelchair`. As far as I can see we don't include them yet.

Examples from Spain:
https://www.openstreetmap.org/way/40111357

**Comment by HendrikLeuschner** [comment]
imho this should not be considered as long as we don't have a proper framework for public transport. I think funiculars could be categorized alongside cable cars, two-stop-railways, ferries. It's public transport. Already the integration of ferries in our current algos is problematic, as it is multi-modal while we have no support for multi-modal conditions such as timetables, capacities etc. We should not expand something that is already problematic.

**Comment by rabidllama** [comment]
I will close this as it seems the answer was that we shouldn't use it until we have a proper public transport viable solution
