### ISSUE TITLE
Document bike routing profiles

### ISSUE THREAD

**Issue by emilyeros** [GIScience/openrouteservice#558]
Hi, could you add documentation that explains the OSM tags you've incorporated for your cycling profiles? I was experimenting with this tool in QGIS but couldn't find info for the profiles I was after.

I'm especially interested in:
- cycling-safe (does this relate to the level of traffic stress, or other methodologies?)
- cycling-regular
- cycling-road

thanks!

![image](https://user-images.githubusercontent.com/9657971/59799799-f9328500-9299-11e9-9553-9c68718ca6cb.png)

**Comment by TimMcCauley** [comment]
Hi Emily, please find more information here: 

https://github.com/GIScience/openrouteservice/wiki/Tag-Filtering

**Comment by emilyeros** [comment]
Hi, I looked before filing this issue but the info isn't there. Biking profiles are empty:

![image](https://user-images.githubusercontent.com/9657971/59824284-8818bf00-92e5-11e9-9444-36d4f446834a.png)

**Comment by TimMcCauley** [comment]
Oops, @marq24 are you able to add the missing profiles for @emilyeros ?

**Comment by marq24** [comment]
I'll will (have) to do that...

**Comment by marq24** [comment]
just to double check - it's "this" document that I need to update - correct?
https://github.com/GIScience/openrouteservice/wiki/Tag-Filtering

or will this be generated from somewhere else?

**Comment by marq24** [comment]
ok - sorry that this took that long...
https://github.com/GIScience/openrouteservice/wiki/Tag-Filtering#cycling-regular-bike---cycling-mountain-cycling-road-cycling-electric
