### ISSUE TITLE
Strange Isocrone generated

### ISSUE THREAD

**Issue by geovista116** [GIScience/openrouteservice#559]
Dear OpenRouteService,

We have some issues with isochrone generation with 3 points. Some colored fringes appear along street that no exist in OSM street layer. 

See to believe... I have just attached some screenshots.

![isocrones_openrouteservice_v3](https://user-images.githubusercontent.com/51724737/59802832-6ac8fe00-92af-11e9-948c-d79e0a5e1926.png)

![isocrones_openrouteservice_v2](https://user-images.githubusercontent.com/51724737/59801794-15402180-92ae-11e9-9303-7bc23b53b204.png)

![isocrones_openrouteservice](https://user-images.githubusercontent.com/51724737/59801796-15d8b800-92ae-11e9-9c4c-026751fa267a.png)

![qgis-ltr-bin_iBXuff0qUi](https://user-images.githubusercontent.com/51724737/59802388-97304a80-92ae-11e9-886f-c0e91e280478.png)

Also it should be cool when we build isocrone with multipoint as input that the fastest be over the slowest segments... without transparency in order to avoid confusion of reader (user).

best regards, 

Vincent

**Comment by nilsnolde** [comment]
Well, in very isolated areas like that one with a terrible OSM coverage obviously, isochrones don't work that smoothly. There's just too little data points to make a proper polygon geometry. 

Regarding feature ordering: that's your job in QGIS;) definitely nothing ORS can change.

**Comment by geovista116** [comment]
Hi Nils, 

Thanks for your answer. You and your team are doing a very great job. It is a very useful tool for peruvian firemen in order to understand better the coverage service and to plan where to build new firestation.

Sorry to insist but I think it is important you could check what's happening in this specific sector:  http://bit.ly/2FpXoHa  because the algorithm seems to use street that do not existe in OSM cartographic. Do you only use OSM highway to build isochrone?

I have enhanced the issue with a black circle using MS Paint. I hope the issue better described now.

![isocrone](https://user-images.githubusercontent.com/51724737/59936953-d5487e00-9416-11e9-82a2-a66188c8c646.png)

best regards,

Vincent

**Comment by nilsnolde** [comment]
I see what you mean, but still, it's hard for us to respond or even act on such things, as I have no idea what you did to get there. There should be some way there crossing the river. Please have a look on https://openstreetmap.org.

If there is no road, then can you pls give us the exact request producing this? It's in QGIS Log Messages.
