### ISSUE TITLE
Routig around Ölmühle/Saxony

### ISSUE THREAD

**Issue by jolerche** [GIScience/openrouteservice#570]
#### Here's what I did
https://maps.openrouteservice.org/directions?n1=50.773359&n2=13.474957&n3=16&a=50.771581,13.486265,50.771411,13.485096&b=1a&c=2&k1=en-US&k2=km

---
#### Here's what I got
Regardless of routing preferences (shortest, quickest, recommended) I only see the correct and direct route between A and B for walking. Choosing car or bicycle huge indirections are calculated. This doesn't change when A and B are swapped.

---
#### Here's what I was expecting
As there are no restrictions for walkers, bicycles and cars (below 3,8m height) there, I expect a direct connection of 90m length for all three profiles.

---
#### Here's what I think could be improved
Openstreetmap routing between A and B delivers this shortest path in all above three cases. ORS routing issue?

**Comment by jolerche** [comment]
Comming from A the traffic from B has right of way through the bridge as it's quite narrow.
Bridge heigth is only 3,8m. No other restrictions applied as of 27th of July 2019.

**Comment by rabidllama** [comment]
I believe this is because up until 3 months ago the bridge was marked as under construction. We will be deploying new graphs towards the end of the week so hopefully then it will route as expected

**Comment by jolerche** [comment]
I just checked that but unf. there's no change in behaviour today. the beta maps show the same misbehaviour. 

Moreover, OSM calculates direct (short) routes A-B and B-A for all transportation profiles.
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=50.77146%2C13.48514%3B50.77154%2C13.48640

**Comment by rabidllama** [comment]
Yes, we have had problems with the build process so we still haven't been able t deploy new graphs yet. The OSM routing will most likely be using more up to date graphs than we are, which would be why they work there and not on ors

**Comment by rabidllama** [comment]
Looks like the new graphs take into account this bridge now.
