### ISSUE TITLE
waytype=ferry does not resolve for extra_info directions request

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#573]
If ferries are part of the itinerary, the parameter [`extra_info=[waytype]`](https://github.com/GIScience/openrouteservice-docs#waytype) does not resolve the ferries (ID 9) and instead responds with ID 0 (unknown) to the ferry sections. 

E.g. Konstanz - Friedrichshafen:
```
curl -X POST \
  'http://api.openrouteservice.org/v2/directions/driving-hgv/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "coordinates": [
        [
            9.169464,
            47.659607
        ],
        [
            9.493561,
            47.666312
        ]
    ],
    "extra_info": [
        "waycategory",
        "waytype"
    ],
    "instructions": false,
    "geometry": false
}'
```

**Comment by aoles** [comment]
I think we decided once to leave issues open until the actual release.

**Comment by takb** [comment]
oh ok sorry
