### ISSUE TITLE
Requesting a matrix bigger then size 50 does not work even though maximum locations is set to 200

### ISSUE THREAD

**Issue by clarknovaold** [GIScience/openrouteservice#575]
#### Here's what I did
I deployed my own openrouteservice instance according to the docker setup instructions.
Using the api i request a matrix bigger than 50x50.
---
#### Here's what I got 
```
{
  error: {
    code: 6004,
    message: 'Request parameters exceed the server configuration ' +
      'limits. Only a total of 2601 routes are allowed.'
  },
  info: {
    engine: { version: '5.0.1', build_date: '2019-08-04T20:10:58Z' },
    timestamp: 1564952164917
  }
}
```
It always states the number of total routes allowed are the total routes i requested. When i request 51x51 it says 2601.
52x52 2.704 etc.
Requesting a matrix <= 50 works as expected.
---
#### Here's what I was expecting 
The actual correct matrix.     
I am using the default app.config.sample which states "maximum_locations":200
---

**Comment by nilsnolde** [comment]
> Found the error: app.config.sample is missing the "maximum_routes" key in the master branch
What does this mean? Solved? Then please close the issue!

Anyways, as far as I can see the `maximum_routes` key **is** in the [master branch](https://github.com/GIScience/openrouteservice/blob/master/openrouteservice/src/main/resources/app.config.sample), `maximum_locations` is not in there and was the old key (> 2 months ago).

I'll close this bcs I think it's invalid, feel free to open another issue. I guess the error message is still not really correct, will have a look

**Comment by Kingshuk-Deb** [comment]
@clarknovaold were you able to fix it?

**Comment by MichaelsJP** [comment]
@Kingshuk-Deb Is this an active issue for you?
