### ISSUE TITLE
Error 2010: "Cannot find point 1"

### ISSUE THREAD

**Issue by LRitzdorf** [GIScience/openrouteservice#584]
I'm encountering an issue when using the ORS Python API, although it appears to be server-related, since the same thing happens on https://maps.openrouteservice.org.

When I make a Directions V2 query in either location (API or website), using the point 45.2475833, -108.0732222 (lat, lon), I'm given the following error (taken here from the Python error trace): `{'error': {'code': 2010, 'message': 'Cannot find point 1: 45.247583,-108.073222'}, 'info': {'engine': {'version': '5.0.1', 'build_date': '2019-05-29T14:22:56Z'}, 'timestamp': 1567040601050}}`.

Note that I *did* enter my coordinates in lon, lat order in the actual program, so that shouldn't be the issue here.

As mentioned above, the same thing happens on the website:
![image](https://user-images.githubusercontent.com/42657792/63906033-75042880-c9d3-11e9-8da6-1466bbbf4853.png)
(Note the message at bottom left)

Also, this seems similar to #89 and #145, except that no roundabouts appear to be involved. (And that class of problem should be fixed, right?)

**Comment by LRitzdorf** [comment]
Informational Update: Following the lead of #89, I tested the route in OpenStreetMap, with interesting results.

In OpenStreetMap's (apparently default) "Car (OSRM)" mode, the route works - see https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.202%2C-114.317%3B45.238%2C-108.077. (Although OSM appears to use a different coordinate projection than ORS does - the link is edited to reflect that, and uses the correct point.)

However, in "Car (GraphHopper)" mode, OSM "couldn't find a route between those two places."

**Comment by nilsnolde** [comment]
I didn't check all the way now on openstreetmap, but to me it seems ORS and GH are doing the right thing and OSRM is not:

https://www.openstreetmap.org/way/334482979#map=13/45.1471/-107.9674&layers=H

That road is `highway=path`, which is not a valid tag for motorized vehicles:
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpath

Rather open an issue with OSRM;) They shouldn't route cars on `track`s. 

ORS and GH would only route to the nearest road eligible for motorized vehicles and in this case none can be found within the vicinity of your destination point, so the routing fails.
