### ISSUE TITLE
Docker limitation

### ISSUE THREAD

**Issue by Fefe111** [GIScience/openrouteservice#586]
Hi, I am sorry to bother you. However, I am stuck in a question. Why do I still encounter the API limitation error after I have configured the docker in Ubuntu 16.04? Thank you!
![微信图片_20190909131833](https://user-images.githubusercontent.com/41660018/64504894-591e5200-d304-11e9-8933-5b6a1f0dc156.png)

**Comment by nilsnolde** [comment]
Cross posted, see here:
https://ask.openrouteservice.org/t/docker-limitation/926

Also, this would be a [openrouteservice-py](https://github.com/GIScience/openrouteservice-py) issue, not an openrouteservice issue.
