### ISSUE TITLE
Proxy problem: Couldn't process file data/osm_file.pbf, error: java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by stevecambridge** [GIScience/openrouteservice#587]
Hi,
I'm having trouble launching the app via the docker-compose config.

I've been able to build the image after git cloning and docker-compose brings the server up, but it never enters the ready state. Instead, shortly after launching, I get a long list of Java stack traces, summarized in the ors.log file as:

2019-09-10 20:08:37,681 ERROR [routing.RoutingProfileManager] - java.util.concurrent.ExecutionException: java.lang.RuntimeException: Couldn't process file data/osm_file.pbf, error: java.net.SocketTimeoutException: connect timed out
2019-09-10 20:08:40,079 ERROR [routing.RoutingProfileManager] - java.util.concurrent.ExecutionException: java.lang.RuntimeException: Couldn't process file data/osm_file.pbf, error: Index: 7754600, Size: 0
2019-09-10 20:08:42,377 ERROR [routing.RoutingProfileManager] - java.util.concurrent.ExecutionException: java.lang.RuntimeException: Couldn't process file data/osm_file.pbf, error: Index: 7754600, Size: 0
2019-09-10 20:08:44,573 ERROR [routing.RoutingProfileManager] - java.util.concurrent.ExecutionException: java.lang.RuntimeException: Couldn't process file data/osm_file.pbf, error: Index: 7754600, Size: 0

I have verified that osm_file.pbf is present in the Docker container. I'm not sure what a socket timeout on reading a file means.

The data and configuration files I am using are unmodified from the initial git clone. The only difference I have made is modifying MAVEN_OPTS in the Dockerfile to add the corporate proxy that I am working behind.

I'd appreciate any advice on the subject.

**Comment by samcrawford** [comment]
Just an idea: Verify that your host has access to the internet, functioning DNS, etc without needing proxies or any special config.

When parsing and creating the routing data it will also download evelation data from a third party server. So if you can't reach the internet, then you'll get an error, and SocketTimeoutException is perhaps indicative of an error like that.

**Comment by stevecambridge** [comment]
I see. Unfortunately our docker host is behind a corporate proxy so I'm not sure of a way to provide full internet access without extra configuration. Is there a way to configure the image with a proxy server?

**Comment by samcrawford** [comment]
Modify https://github.com/GIScience/openrouteservice/blob/master/docker/docker-compose.yml to add in your corporate proxy details. e.g.

JAVA_OPTS=-Dhttp.proxyHost=10.0.0.100 -Dhttp.proxyPort=8800 -Djava.awt.headless=true ...

**Comment by stevecambridge** [comment]
This didn't work exactly as written, but I got it working by moving JAVA_OPTS and CATALINA_OPTS from the "environment" section of docker-compose.yml to the build arguments section. They're declared as arguments in the Dockerfile anyway, and the `RUN echo` lines appear to copy them into an environment setup script on build. If these values aren't passed as build args, the setup script appears to simply unset those variables by running `JAVA_OPTS=""` and `CATALINA_OPTS=""` when the container is run.

As a side point, I also had to add my proxy information to `MAVEN_OPTS` in the Dockerfile in order to build the image.

Perhaps the repository's default docker-compose.yml should be changed?

**Comment by nilsnolde** [comment]
Glad you figured it out! And thanks @samcrawford for supporting here! 

Happy to accept a PR to change the docker-compose.yml @stevecambridge :)

**Comment by stevecambridge** [comment]
Sure. PR is open @nilsnolde.

**Comment by nilsnolde** [comment]
Awesome, thanks @stevecambridge ! @rabidllama will merge when he's back next week.
