### ISSUE TITLE
Wrong localization

### ISSUE THREAD

**Issue by RataxesKhal** [GIScience/openrouteservice#595]
Good afternoon,

When I ask https://maps.openrouteservice.org for the localization behind:
Rue du Bugnon 44,  1011 Lausanne

I got wrong coord. (46.540111, 6.594661), it shoud be 46.524656, 6.640967

I notice that the postal code 1020 is associate to "Lausanne", but it is "Renens".

Thanks for your help.

#### Here's what I did

---
#### Here's what I got

---
#### Here's what I was expecting

---

**Comment by rabidllama** [comment]
This is the repository for the routing aspect of ORS and not the geocoder, so I will close the issue as it is not for here. You can try asking on the ask.openrouteservice.org forum, but we do not have too much control over the Geocoding as we use the Pelias geocoder on our servers. It may be also worth checking on their service to see if the same problem exists, and if so you could raise an issue with them :)
