### ISSUE TITLE
ascent and descent missing in API response

### ISSUE THREAD

**Issue by bayethiernodiop** [GIScience/openrouteservice#597]
When calling the direction using the API the ascent and descent are not in the response but when using the [openrouteservice](https://maps.openrouteservice.org/directions?n1=-1.31672&n2=36.849046&n3=15&a=-1.305249,36.82239,-1.333275,36.870815&b=0&c=0&k1=en-US&k2=km) website  they are present. Any help here and please what these two means, i suppose it's the max and minimum duration. Thanks

request : client.directions(coords,profile="cycling-regular")

**Comment by aoles** [comment]
Hi,
thank you for your inquiry!

In order to get the ascent and descent information in route summary add the parameter `elevation: true` to your query as described in the [directions endpoint documentation](https://openrouteservice.org/dev/#/api-docs/v2/directions/{profile}/post).

Cheers,
Andrzej

**Comment by nilsnolde** [comment]
And @bayethiernodiop, please use https://ask.openrouteservice.org for questions or anything not related to a bug.

**Comment by bayethiernodiop** [comment]
@nilsnolde  please can you help in this question, i asked the question in the form but my account is temporarily in hold and i am really in a hurry here. thanks

**Comment by nilsnolde** [comment]
Your question was answered by @aoles. Don't know what else you might want...

Your account is now unblocked in our forum. Please shift the conversation over there.

**Comment by bayethiernodiop** [comment]
thanks and sorry. didn't saw that one at all. thanks @aoles
