### ISSUE TITLE
How much time for status": "ready"

### ISSUE THREAD

**Issue by 2803media** [GIScience/openrouteservice#598]
I just wonder the average time for getting a status": "ready", my container start 1 hour ago with a .pbf of France (3.5G) and I wonder have an estimation of the time for the setup.

Thanks

**Comment by nilsnolde** [comment]
Please follow the instructions in the issue template: questions and anything not being a bug should be posted at https://ask.openrouteservice.org. 

1-2 hours I'd expect, depending on the hardware obviously. Look into the container logs.
