### ISSUE TITLE
Avaialiability of the POI service

### ISSUE THREAD

**Issue by bayethiernodiop** [GIScience/openrouteservice#599]
Hello, I am using openrouteservice local but can't find any route to compute Poi, however it's available on the public API. is this a bug from my local installation or not? thanks.

**Comment by nilsnolde** [comment]
Straight from the README:

> Our locations/API is another service which we have coined openpoiservice which can be found here.

https://github.com/GIScience/openpoiservice

And again: use the forum mate. In **all** cases/packages/languages it's safe to assume that you're doing a mistake and there is no bug. Only after intense research and 60 mins of meditation to reflect on the matter should you file a bug. And if you're too lazy for that, **use the forum**.
