### ISSUE TITLE
No answer from certain queries for isochrones

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/openrouteservice#6]
> When I query for isochrones at lat lon  40.87668, -97.09879   context here:
> 
> http://www.openstreetmap.org/search?query=40.87668%2C-97.09879#map=17/40.87668/-97.09879
> 
> which is in the middle of a building, not very far from the nearest road, I get no answer from the web and the API version.
> 
> Is this a known issue?
> 
> When I moved the lat lon to the nearest road it works fine.
> 
> I can wrap my queries in a shim that finds the nearest road segment via OSM and retries but it seems that would be better handled for reasonable cases server side.
> 
> Other queries that give the same null answer:
> 
> 37.04076, -76.37905
> 44.82852, -93.16191
> 42.01283, -87.71914

**Comment by Rungee** [comment]
The issue has been fixed in the previous release.
Closing.
