### ISSUE TITLE
Detour_factor not working

### ISSUE THREAD

**Issue by realthargor** [GIScience/openrouteservice#60]
I'm trying to get the detour_factor, precentage and avgspeed from the 
directions api via attributes and it's not working.

Each segment has an avgspeed, but detour_factor and precentage is missing.

Here is my query:

https://api.openrouteservice.org/directions?coordinates=172.77756%2C-34.45213%7C172.77763%2C-34.45213%7C172.77904%2C-34.45242%7C172.78153%2C-34.45332%7C172.78333%2C-34.45366%7C172.7843%2C-34.45384%7C172.78567%2C-34.45513%7C172.78782%2C-34.45513%7C172.79071%2C-34.45503%7C172.7932%2C-34.45529%7C172.79492%2C-34.45593%7C172.80383%2C-34.45695%7C172.80681%2C-34.45656%7C172.80861%2C-34.45459%7C172.80861%2C-34.45459%7C172.813%2C-34.4534%7C172.81678%2C-34.45297%7C172.82108%2C-34.45201%7C172.82509%2C-34.45097%7C172.82861%2C-34.4496%7C172.83253%2C-34.44775%7C172.83562%2C-34.44638%7C172.83661%2C-34.44545%7C172.83943%2C-34.44392%7C172.84219%2C-34.44258%7C172.84506%2C-34.44075%7C172.84821%2C-34.43791%7C172.85052%2C-34.43556%7C172.8524%2C-34.43428%7C172.85529%2C-34.43138%7C172.85695%2C-34.42929&profile=foot-hiking&preference=shortest&units=m&geometry=true&geometry_simplify=false&instructions=true&elevation=false&extra_info=surface&api_key=xxxxx%27&attributes=detour_factor|avgspeed|precentage&maneuvers=true

**Comment by TimMcCauley** [comment]
You had two typos, try this:

https://api.openrouteservice.org/directions?coordinates=172.77756%2C-34.45213%7C172.77763%2C-34.45213%7C172.77904%2C-34.45242%7C172.78153%2C-34.45332%7C172.78333%2C-34.45366%7C172.7843%2C-34.45384%7C172.78567%2C-34.45513%7C172.78782%2C-34.45513%7C172.79071%2C-34.45503%7C172.7932%2C-34.45529%7C172.79492%2C-34.45593%7C172.80383%2C-34.45695%7C172.80681%2C-34.45656%7C172.80861%2C-34.45459%7C172.80861%2C-34.45459%7C172.813%2C-34.4534%7C172.81678%2C-34.45297%7C172.82108%2C-34.45201%7C172.82509%2C-34.45097%7C172.82861%2C-34.4496%7C172.83253%2C-34.44775%7C172.83562%2C-34.44638%7C172.83661%2C-34.44545%7C172.83943%2C-34.44392%7C172.84219%2C-34.44258%7C172.84506%2C-34.44075%7C172.84821%2C-34.43791%7C172.85052%2C-34.43556%7C172.8524%2C-34.43428%7C172.85529%2C-34.43138%7C172.85695%2C-34.42929&profile=foot-hiking&preference=shortest&units=m&geometry=true&geometry_simplify=false&instructions=true&elevation=false&extra_info=surface&api_key=58d904a497c67e00015b45fc1ee1bdfc47314e0d4d01239559532ac0%27&attributes=detourfactor%7Cavgspeed%7Cpercentage&maneuvers=true
