### ISSUE TITLE
Error code 2099 for directions on certain coordinates

### ISSUE THREAD

**Issue by ivanpetrushev** [GIScience/openrouteservice#603]
#### Here's what I did

$ curl -X POST   'https://api.openrouteservice.org/v2/directions/foot-walking/geojson'   \
-H 'Content-Type: application/json'   \
-H 'Accept: application/json, application/geo+json, application/gpx+xml, img/png; charset=utf-8'   \
-H 'Authorization: <hidden>'   \
-d '{"coordinates":[[42.152427922192466, 24.73769187927246], [42.15809088268482, 24.743356704711914]]}'

---
#### Here's what I got

{"error":{"code":2099,"message":null},"info":{"engine":{"version":"5.0.2","build_date":"2019-09-30T11:18:17Z"},"timestamp":1571159445162}}
---
#### Here's what I was expecting

Valid result for walking directions between those two points
---
#### Here's what I think could be improved
Errors should be documented - I don't even know what "2099" means and I can't find error listing anywhere in the API docs. 
Providing something in error message instead of just "null" would be helpful, too.
And that error should be fixed, obviously :)

**Comment by TahiraU** [comment]
Hi ivanpetrushev,

have you already tried to swap the coordinates? Your coordinates aren't in the right order. You have to feed the request with longitude, latitude instead of latitude,longitude. Your body request should look like this:

`{“coordinates":[[24.73769187927246,42.152427922192466],[24.743356704711914,42.15809088268482]]}`

**Comment by ivanpetrushev** [comment]
Thanks, that worked!

But shouldn't it be able to find route if coordinates were flipped? 
If they happened to be in some desert with no routes, shouldn't it return "no routes" or similar error message?

**Comment by darshan-rivulet** [comment]
hi @ivanpetrushev

I need you help related the ORS I'm facing the same issues that you were facing before. 
I guess you found the solution. Can you please help me with that. looking forward  to get your help

**Comment by ivanpetrushev** [comment]
Hi @darshan-rivulet 

Check the answers above - coordinate pairs within the target and destination were flipped:

> You have to feed the request with longitude, latitude instead of latitude,longitude

**Comment by koebi** [comment]
The query that started the question currently returns 
```
{"code":2010,"message":"Could not find routable point within a radius of 350.0 meters of specified coordinate 0: 42.1524279 24.7376919.; Could not find routable point within a radius of 350.0 meters of specified coordinate 1: 42.1580909 24.7433567."}
```
which is an appropriate error message in this case.
