### ISSUE TITLE
osm way id for the route api segments

### ISSUE THREAD

**Issue by bayethiernodiop** [GIScience/openrouteservice#606]
Hello, I am using openrouteservice locally using the docker image, I searched a lot on how to get the osm way id along with the segments when using the route API. I am planning on using the osm way id with uber movement data which only has the osm way id for me to join the segment returned by the openrouteservice route API and the data from the uber movement.

I saw that there was a pull request to get them for a wheelchair but I need them on drive or bicycle.

Any guidance that I can follow to have the osm way ids, please.
Thanks for your help.

**Comment by TahiraU** [comment]
Currently the ORS doesn't return the osm ids of ways that the route goes along. As you have already mentioned, this "extra info" is only supported by the wheelchair profile.

**Comment by nilsnolde** [comment]
That's a fairly frequently-asked functionality, see #371 .

I'd still like to have that, so I'll keep this open. Again, don't hold your breath, we're in a major refactoring/upgrading phase. But this should be on our roadmap.

**Comment by akatasonov** [comment]
@nilsnolde Could you give some tips on how to enable osm ids for profiles other than the wheelchair in the source code? I was browsing the source but couldn't spot a place where 'extra_info=osmid' is allowed for only the wheelchair profile. Or is it more involved than simply turning it on in the source? I'd like to estimate the work effort to turn it on.

**Comment by TahiraU** [comment]
@akatasonov you can try by changing the `app.config` file, which should be in this directory: `openrouteservice/src/main/resources`.

As you can see below, the wheelchair profile settings have an `OsmId` row at the end, whereas all the other profiles don't carry this info. If you add the `OsmId`-info in the `extended_storage`-parameter of your specific profile, the response will output the corresponding `OsmId`s along the route. 

However, after changing the app.config file you need to rebuild the graph again. 

```
profile-wheelchair: {
            profiles: "wheelchair",
            parameters: {
              encoder_options: "block_fords=true",
              elevation: true,
              maximum_snapping_radius: 50,
              ext_storages: {
                Wheelchair: {
                  KerbsOnCrossings: "true"
                },
                WaySurfaceType: {},
                WayCategory: {},
                OsmId: {}  //all other profiles don't carry this variable
              }
            }
          }
```
Best 
Tahira

**Comment by nilsnolde** [comment]
If you want to PR it @akatasonov, @rabidllama can give you some info on what to do.

**Comment by akatasonov** [comment]
@TahiraU thanks! Appreciated!

**Comment by sfendrich** [comment]
Closed as resolved in answer.
