### ISSUE TITLE
Bike profile: Isochrones use FastestWeighting, Routing uses PriorityWeighting

### ISSUE THREAD

**Issue by HendrikLeuschner** [GIScience/openrouteservice#619]
The weighting for routing and isochrones are different. This leads to smaller isochrones than what you can reach by using A to B routing. It should be the same weighting (preferably Priority).

**Comment by aoles** [comment]
> An isochrone is an isoline for travel time, that is a curve of equal travel time. Closely related is isodistance, which is a curve of equal travel distance. [[OSM wiki](https://wiki.openstreetmap.org/wiki/Isochrone)]

The problem of finding an isoline is different from the problem of computing a route from A to B in the sense that while in the former one edge weight is purely defined by time or distance, the latter one tries to find an optimal route under a given set of constrains which can include additional factors such as priorities of roads based on their suitability for bikes, etc. Therefore, **isochrones** and **isodistances** should be computed with **fastest** and **shortest** weightings, respectively. On the other hand it is fine to use prioritized weighting (aka *recommended*) to compute routes.
