### ISSUE TITLE
Failure to connect when querying a locally hosted ORS in parallel

### ISSUE THREAD

**Issue by jonzarecki** [GIScience/openrouteservice#626]
#### Here's what I did

I've loaded the ORS docker on my machine and it works great.
However, when I use multiple processes to query the ORS rest API (from around 16) I get a failure to make a connection to the API.

---
#### Here's what I got
Failure to connect, or a timeout after multiple retries.

---

#### Here's what I was expecting

I looked for a config option of "max_connections" or something similar to control how many connections I can make, but haven't found any.

---
#### Here's what I think could be improved

Make a config option like that, or at least advertise the maximum connection number.

**Comment by rabidllama** [comment]
hmm, I just looked through the code and on our servers and I can't see anything where a limit is set, so I assume it is a default somewhere either in Spring, Tomcat, Docker or in GraphHopper. Do you get an error message and if so, what is it?

**Comment by jonzarecki** [comment]
I got a pretty simple error of unable to form a connection when running in querying from different processes, and something in the neighborhood "max connection amount achieved" when querying with the same session object. 

Nothing too informative.

I suspect this hidden limit is the reason I wasn't able to form the connection.

**Comment by rabidllama** [comment]
Yes that definitely sounds like something related to Tomcat or Docker then. I will ask around to see if anyone else in the group has seen something similar, but if it is an issue with Docker or Tomcat then there might not be much that can be done about increasing the limit (I'm not an expert in either, so I can't say for sure)

**Comment by jonzarecki** [comment]
Any updates?

**Comment by rabidllama** [comment]
Sorry, things have been a bit hectic with the christmas holidays coming up. It doesn't seem that anyone else here had a similar problem when they were running tests, so we are not sure what to suggest. It may be worth trying t run it without docker (some instructions can be found at https://github.com/GIScience/openrouteservice/wiki/Building-from-Source) and seeing if then you run into the same problems. With that you would also have more control over Tomcat itself so you can play around with the settings of it

**Comment by rabidllama** [comment]
I will close this as there have been no further reports of issues
