### ISSUE TITLE
Docker needs a build to respect new app.config

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#627]
Currently it's only possible to respect new config settings in `app.config.sample` when the image is rebuilt, the same for other PBF files than the default.

Optionally, new graphs should be built and new configuration settings respected on container startup.

**Comment by stefanocudini** [comment]
one question is not clear for me..

If I edit for example some profile settings in the file: app.config
```json
...
 "profile-pedestrian-walk":{
                  "profiles":"foot-walking",
                  "parameters":{
                     "encoder_options":"block_fords=true",
. . .
```
for apply the changes in the new routes results..
rebuild the graphs data is need?

in other words ..  profile settings influence the build of the graphs?

**Comment by nilsnolde** [comment]
Generally: yes, as there's parameters for profiles affecting how the PBF is read and info put on edges. However, in this case I'm not entirely sure, as it could also be a run-time thing (as opposed to pre-processing, i.e. building the graph) since you can avoid `fords` in `options.avoid_features` for `foot-walking`. @aoles or @HendrikLeuschner could say more on that though.

Note, the PR solving this issue is not merged into `master` yet, still in `development`.

**Comment by stefanocudini** [comment]
Fine! I tried to make a version of the Dockerfile in which I use an external volume instead of an argument in the image build for the config file, (in a docker-compose.yml)
```
volumes:
      - ./graphs/:/ors-core/data/graphs
      - ./elevation_cache/:/ors-core/data/elevation_cache/
      - ./logs/:/var/log/ors/
      - ./logs/:/usr/local/tomcat/logs/
      - ./ors/config.json:/ors-core/openrouteservice/target/classes/app.config
```
**- ./ors/config.json:/ors-core/openrouteservice/target/classes/app.config**

now I can edit config file outside of docker container.

this should be enough to avoid the image rebuild for new configuration
and then just do a restart of the right container?

**Comment by nilsnolde** [comment]
Did that work then? Like I said, that might be a parameter which influences the build not the run-time queries. 

I guess what you did works. Note, in the next release the whole Docker setup will change and that's one of the things addressed.

**Comment by stefanocudini** [comment]
I'm trying to edit for example ```ord.services.routing.profiles.active``` but restarting the docker container it remain the same.. 

this is a bit problematic when testing different vehicle profile parameters, because rebuild the image is slow ... is there a way to avoid this problem?

**Comment by stefanocudini** [comment]
for example restarting only the tomcat inside docker?

**Comment by nilsnolde** [comment]
The main point here is, that each profile builds its separate graph. You can't just add a profile and expect to be able to route on it without building the graphs first. However, if you expose the `graphs` folder (i.e. make it permanent) and all profiles you wanna play around with are built, then you can just add/remove them from that section of the `app.config` and even rebuild the image without losing that data. 

Like I said, will be sorta fixed in the next release. If you change the way things are done and intended to be done, we can't support too much.
