### ISSUE TITLE
Restrict polygon properties for avoid_polygons

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#629]
To prevent our servers from crashing, we should restrict some polygon property/properties a user can pass with `avoid_polygon` parameter. That should also go in the `app.config` of course.

Possible property restriction:
- area
- extent in X or Y, e.g. no more than 10 km in X OR Y

**Comment by takb** [comment]
@nilsnolde , 1. do we need both restrictions? 2. what are the values that endanger server stability?

**Comment by takb** [comment]
@nilsnolde it's implemented now and awaiting merge, but we need to have meaningful values to actually set.
