### ISSUE TITLE
Review the logic of matching the routing algorithm to request parameters

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#633]
The current behavior of **non-dynamic** routing with **"fastest"** weighting when no CH is available is to use `DijkstraBidirRef` as fallback regardless of any other available alternatives such as ALT, CALT, or A* with Beeline. This probably needs to be altered such that plain Dijkstra really is the last resort.

**Comment by HendrikLeuschner** [comment]
Should be fixed by #691 .
