### ISSUE TITLE
St abbreviation searching for Saint is not well recognized

### ISSUE THREAD

**Issue by sonigfr** [GIScience/openrouteservice#634]
When I am picking up an address to search containing the St abbreviation (Saint), the api don't recognize it, for example I have to correct my search 3 PLACE DU MARCHE ST HONORE to 3 PLACE DU MARCHE SAINT HONORE to make it work !

**Comment by nilsnolde** [comment]
That's not an issue with the routing service, as it's geocoding, which is served by a https://github.com/pelias/pelias instance.

Please double-check with https://pelias.github.io/compare/#/v1/search%3Ftext=london,%20uk to see if you get the same behaviour. If you do, open an issue in the Pelias repo. If not, then let us know in our [forum](https://ask.openrouteservice.org).
