### ISSUE TITLE
unable to compute route for `extra_info=traildifficulty` with cycling- profiles

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#639]
#### Here's what I did

```
curl -X POST \
  'https://api.openrouteservice.org/v2/directions/cycling-regular/geojson' \
  -H 'Content-Type: application/json' \
  -H 'Accept: application/json, application/geo+json, application/gpx+xml, img/png; charset=utf-8' \
  -H 'Authorization: xxx' \
  -d '{"coordinates":[[8.681495,49.41461],[8.686507,49.41943],[8.687872,49.420318]],"extra_info":["traildifficulty"]}'
```
---
#### Here's what I got

```
{"error":{"code":2099,"message":"Unable to compute a route"},"info":{"engine":{"version":"5.0.2","build_date":"2019-11-14T10:33:51Z"},"timestamp":1576590294220}}
```
The route doesn't matter. It is always the same response.

---
#### Here's what I was expecting

route with extra information for trail difficulty

**Comment by rabidllama** [comment]
The normal bike profile doesn't have the trail difficulty extra info enabled at the minute as we had to turn it off last time we did builds to try and save some memory. mountain bike should have it on though, and it will be available again when the next builds are released

**Comment by TheGreatRefrigerator** [comment]
This was resolved with the new graphs
