### ISSUE TITLE
Invalid GeoJSON when including elevation

### ISSUE THREAD

**Issue by koenekelschot** [GIScience/openrouteservice#640]
When using `"elevation":"true"` in the request body for /directions/foot-walking/geojson, the coordinates in the response include the elevation values. However, the `bbox` properties in the response object contain only 4 items.

According to [RFC 7946 section 5](https://tools.ietf.org/html/rfc7946#section-5):

> The value of the bbox member MUST be an array of length 2*n where n is the number of dimensions represented in the contained geometries

The current implementation leads to incompatibility with parsers following the RFC, such as https://github.com/bamcis-io/GeoJSON

**Comment by nilsnolde** [comment]
Thanks, we weren't aware of that restriction. 

I doubt we can get the z values for the bbox easily, as elevation is imprinted on the edges. However, we could at least append 0 as z value.

**Comment by takb** [comment]
In fact this should be easily fixable, we already have elevations in the pointlist when calculating the bbox. @MichaelsJP , if you haven't already fixed this I'll do it.

**Comment by MichaelsJP** [comment]
@takb Is fixed. Leave me a review when you're ready.

**Comment by aoles** [comment]
Please close the issues only once the corresponding code gets released, thanks!

**Comment by MichaelsJP** [comment]
@aoles Thx for reopening ;). I remember the ors flow now.
