### ISSUE TITLE
Adding intermediate waypoints

### ISSUE THREAD

**Issue by Stemby** [GIScience/openrouteservice#68]
Hi,  
currently when a new waypoint is added (right click → "Add as via point"), it is considered as the last waypoint before the destination (B). In my opinion this is a good general solution, but when I click **on** the calculated route I'd find more natural and productive considering the new waypoint as an intermediate point between the adjacent ones.

![schermata da 2018-01-07 17-37-24](https://user-images.githubusercontent.com/146789/34651552-eef9df74-f3d1-11e7-82da-464a0702f07c.png)

In the previous example here is the current behavior:

- A → A
- 1 → 1
- NEW → 3
- 2 → 2
- B → B

And here is my proposal:

- A → A
- 1 → 1
- NEW → 2
- 2 → 3
- B → B

Best regards,
Carlo

**Comment by TimMcCauley** [comment]
@Stemby this is a client issue which is why I would kindly ask you to move it to https://github.com/GIScience/openrouteservice-app . We can take it further there.

**Comment by Stemby** [comment]
[Thanks](https://github.com/GIScience/openrouteservice-app/issues/174)!
