### ISSUE TITLE
Limited number of waypoints

### ISSUE THREAD

**Issue by Stemby** [GIScience/openrouteservice#69]
Hi,  
currently the number of waypoints is limited to 50 (48 intermediate waypoints + A + B).

When I try to add a further waypoint I get this error:

> Error
>
> Code 204: Request parameters exceed the server configuration limits. The specified number of waypoints must not be greater than 50.

Is it possible to remove this limit? Is this a technical issue, or a political choice?

Thank you!

Carlo

**Comment by TimMcCauley** [comment]
It is a technical issue currently, we might increase this though in the future. What are the limits of other service providers, e.g. google maps ?

**Comment by Stemby** [comment]
Thank you very much! What kind of technical issue?

In Google Maps [the limit](https://developers.google.com/maps/documentation/javascript/directions#Waypoints) currently should be 23 + origin + destination (= 25).

I can't find limits in Strava. Any documentation?

**Comment by TimMcCauley** [comment]
The traversal of the graph/nodes that increases, but I’m not 100% sure how this is currently handled, I will have to check. What would be your desired # of waypoints ?

**Comment by Stemby** [comment]
Hi @TimMcCauley, sorry for the delay. 100 waypoints would be enough for my need, I suppose.

Thank you!
