### ISSUE TITLE
Missing segment distance for POST request

### ISSUE THREAD

**Issue by jcoupey** [GIScience/openrouteservice#695]
#### Here's what I did

Running Openrouteservice using Docker on current `master`, I'm sending a POST request for directions where the two first coordinates are identical: `{"coordinates":[[8.694724,49.409358],[8.694724,49.409358],[8.669243,49.444468]]}`.

---
#### Here's what I got

Focusing on the first segment of the route (filtering with `jq`):

```bash
$ curl -X POST --header "Content-Type:application/json" -d '{"coordinates":[[8.694724,49.409358],[8.694724,49.409358],[8.669243,49.444468]]}' http://localhost:8080/ors/v2/directions/foot-walking | jq '.routes[0].segments[0]'
```
```json
{
  "steps": [
    {
      "distance": 0,
      "duration": 0,
      "type": 11,
      "instruction": "Head east",
      "name": "-",
      "way_points": [
        0,
        1
      ]
    }
  ]
}

```

---
#### Here's what I was expecting

I'm expecting `distance` and `duration` keys (with 0 values) for that segment. Note that it is the behaviour when running the same request with a GET:

```bash
curl "http://localhost:8080/ors/directions?profile=foot-walking&coordinates=8.694724,49.409358|8.694724,49.409358|8.669243,49.444468" | jq '.routes[0].segments[0]'
```
```json
{
  "distance": 0,
  "duration": 0,
  "steps": [
    {
      "distance": 0,
      "duration": 0,
      "type": 11,
      "instruction": "Head east",
      "name": "",
      "way_points": [
        0,
        1
      ]
    }
  ]
}
```

Except for the `name` values and stuff related to different format between POST and GET responses, this is the only change in the response.

---
#### Here's what I think could be improved

Not sure if the current API always guarantee having a `distance` and `duration` key at `segment` level (even if values are zero), but having a consistent response across request types would be safer. Also this breaks [downstream code](https://github.com/VROOM-Project/vroom/blob/fed2ca8b52b687cddabdf9ca77582af54953ec6f/src/routing/ors_wrapper.cpp#L83) that goes through all segments, relying on `distance` keys.

**Comment by nilsnolde** [comment]
Yes, true, we should add that to the segment's response regardless. Should be a small change. 

Note, that you're comparing `v1`  GET with `v2` POST responses. Actually for `v2` both are at least consistent:
`https://api.openrouteservice.org/v2/directions/driving-car?start=8.694724,49.409358&end=8.694724,49.409358`

ref https://openrouteservice.org/dev/#/api-docs/v2/directions/{profile}/get
