### ISSUE TITLE
JAVA/CATALINA_OPTS parameters are ignored by tomcat because of wrong default config

### ISSUE THREAD

**Issue by mehlkopf** [GIScience/openrouteservice#696]
Hi,
unfortunately, the default JAVA_OPTS/CATALINA_OPTS get never passed correctly to setenv.sh for tomcat because of quotation mark mismatch: you get double quotation marks when you use the default docker-compose.yml and docker-entrypoint.sh, leading to a erroneous setenv.sh file, leading to tomcat ignoring the options.
I would propose replacing
`echo "CATALINA_OPTS=\"$CATALINA_OPTS\"" > /usr/local/tomcat/bin/setenv.sh`
`echo "JAVA_OPTS=\"$JAVA_OPTS\"" >> /usr/local/tomcat/bin/setenv.sh`
by
`echo "CATALINA_OPTS=$CATALINA_OPTS" > /usr/local/tomcat/bin/setenv.sh`
`echo "JAVA_OPTS=$JAVA_OPTS" >> /usr/local/tomcat/bin/setenv.sh`
and leaving docker-compose.yml as is to avoid the quotation mark confusion.
Thank you!

**Comment by nilsnolde** [comment]
Sure, can you please test and PR @mehlkopf ? Thx
