### ISSUE TITLE
Swagger documentation is irrelevant for self-hosted instance

### ISSUE THREAD

**Issue by mmorelo** [GIScience/openrouteservice#698]
Api documetnation states: 

API Documentation
For an easy and interactive way to test the api, visit our documentation at openrouteservice.org. After obtaining your key you can try out the different endpoints instantly and start firing requests.

Yet the documentation in openrouteservice.org is not valid for a self hosted openrouteservice engine, endpoints are different and parameters too. So where is the documentation for the actual engine API, regardless of the adaptations done in openrouteservice.org?

**Comment by nilsnolde** [comment]
> endpoints are different and parameters too

Huh? Can you give examples pls?

The [documentation](https://openrouteservice.org/dev/#/api-docs/v2/directions/{profile}/geojson/post) on `openrouteservice.org` **is** the documentation of the actual ORS engine's HTTP API, which is generated from docstrings. There is no difference between the live instance and the one you install, **if it's the same version**. Currently that's 6.1.0.

**Comment by mmorelo** [comment]
How does this?
http://localhost:8080/name_of_war_archive/routes
http://localhost:8080/name_of_war_archive/isochrones
http://localhost:8080/name_of_war_archive/matrix

Match with, for example, this?

https://api.openrouteservice.org/v2/directions/driving-car?api_key=your-api-key&start=8.681495,49.41461&end=8.687872,49.420318

directions endpoint does not exist in the locally hosted engine, or will it be under /routes? How does the matching work here?

**Comment by nilsnolde** [comment]
> How does this?
> http://localhost:8080/name_of_war_archive/routes
> http://localhost:8080/name_of_war_archive/isochrones
> http://localhost:8080/name_of_war_archive/matrix

Classic README fail. Like I said, the **API** documentation is generated from docstrings and therefore guaranteed to be at the latest (unless we forget to update it). Forget about the README, go with the real documentation and please just try it out. It won't bite ;)

Forget about
