### ISSUE TITLE
Replace import sun.misc.Base64Encoder

### ISSUE THREAD

**Issue by sfendrich** [GIScience/openrouteservice#70]
The classes in sun.* are not portable across different Java implementations, e.g., "mvn compile" fails on my machine due to heigit/ors/routing/traffic/TrafficUtility.java importing sun.misc.Base64Encoder (see [Why Developers Should Not Write Programs That Call 'sun' Packages](http://www.oracle.com/technetwork/java/faq-sun-packages-142232.html)). java.util.Base64 would be a better choice.

**Comment by TimMcCauley** [comment]
@sfendrich thanks for pointing this out - feel free to change and push to the repository
