### ISSUE TITLE
how to use custom elevation data

### ISSUE THREAD

**Issue by stefanocudini** [GIScience/openrouteservice#701]
hi

I would like to use my custom data in place of the classic srtm / cgiar, I have available geo-referenced geotif(.TIF) files in the right way that cover my road graph

how can i use them? do I have to put them in a zip file that has the same name as my elevation cache automatically downloaded?
in my case only one file: srtm_39_03.zip
contains: srtm_39_03.tif,srtm_39_03.hdr,srtm_39_03.tfw

changing the elevation cache the graph cache should not be regenerated right?

Could it be an interesting feature support to custom elevation provider

**Comment by nilsnolde** [comment]
Questions please on our forum. Like the template said, which you chose to ignore.

Not worth the hassle for us, there's hardly any free & open **global** elevation data. If you want to contribute, we can discuss. Until then I'll close and you can ask the same on the forum.

**Comment by stefanocudini** [comment]
I apologize I have not ignored the template
I was undecided whether this could be considered a question or a  new feature

many thnaks I continue to the forum
