### ISSUE TITLE
Use priority weighting to discourage routing over `access=destination` ways

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#705]
Routing over ways tagged with `access=destination` is currently discouraged by artificially limiting the travel speed to `destination_speed`. The problem with this approach is:
1. It introduces a spurious time penalty for `fastest` weighting reflected in inaccurate travel time estimation
2. It doesn't solve the issue for `shortest` weighting + has the same problem with travel time estimation as for `fastest`.

Investigate whether an approach of penalizing `access:destination` with priority weighting wouldn't be better. The priority of such ways could be set to `WORST`.

Should help to address https://github.com/GIScience/openrouteservice/issues/253.

**Comment by TheGreatRefrigerator** [comment]
refers to #1184 and #1061

**Comment by aoles** [comment]
This approach has been implemented in fastest weighting via https://github.com/graphhopper/graphhopper/pull/1752. However, it does not address any of the other weightings such as `shortest`. We will look into a more generic solution probably involving a wrapper weighting based on `AbstractAdjustedWeighting`.
