### ISSUE TITLE
Specify location index parameters in the configuration file

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#712]
Add parameters for specifying GH location index settings `index.high_resolution` and `index.max_region_search` to `app.config`. See discussion in the [ask forum thread](https://ask.openrouteservice.org/t/can-not-find-point-within-radius/1543).

**Comment by yortug** [comment]
Thanks for this - very helpful and worked perfectly! Appreciate the effort put in just to get it implemented 😄
