### ISSUE TITLE
Bicycle routing does not use turn restriction exception with weights "shortest" and "recommended"

### ISSUE THREAD

**Issue by elumbella** [GIScience/openrouteservice#714]
#### Here's what I did
Calculating a route between two points
---
#### Here's what I got
https://maps.openrouteservice.org/directions?n1=50.098851&n2=8.761355&n3=18&a=50.098746,8.760256,50.099503,8.758931&b=1a&c=2&k1=en-US&k2=km

---
#### Here's what I was expecting
All weights should directly turn left at the intersection

---
#### Here's what I think could be improved
I guess this should be a simple modification of the routing profiles since it already works with the "fastest" weight.

**Comment by aoles** [comment]
Thank you for your feedback! 

This seems to be a known problem with the routing algorithm which is used for `shortest` and `recommended`. `fastest` uses a different algorithm (CH) which does not have the problem and returns the expected route. In fact, I do not observe the issue on a local build with CH enabled for the other two weightings: all three weightings yield the same route. On the contrary, once you force the faulty algo for `fastest` too by enabling one of the avoidable such as `ferries` it returns the same lengthy route as the one for `recommended`: https://maps.openrouteservice.org/directions?n1=50.097976&n2=8.763365&n3=17&a=50.098746,8.760256,50.099499,8.758925&b=1a&l1=1&c=0&k1=en-US&k2=km

![image](https://user-images.githubusercontent.com/6545356/81511242-3e2f3200-9318-11ea-8be6-70d9f8189444.png)


We are currently in the process of switching over our cycling profiles to a new algorithm which should address this issue, so stay tuned.

**Comment by elumbella** [comment]
Fantastic, thanks a lot for the in-depth answer. I am very much looking forward to the new cycling algorithm!

**Comment by HendrikLeuschner** [comment]
I think it is the other way around: the fastest algorithm is wrong and the others are right. There is a _only_right_turn_ relation on those edges that is ignored by CH. With our new adaptations, fastest will give the same results als shortest and recommended and not the other way around.

**Comment by aoles** [comment]
Thanks @HendrikLeuschner! You are right, currently the turn restriction is ignored by our routing algorithm. Currently there seems to be one another weird behavior which I observe with hgv `shortest` as illustrated by the following screen. Let's keep an eye on it.

![image](https://user-images.githubusercontent.com/6545356/89775899-0b5c2c00-db09-11ea-923e-379fe8e6b32b.png)

**Comment by aoles** [comment]
Seems to be resolved.

![image](https://user-images.githubusercontent.com/6545356/231448458-79222ed1-34d4-431c-a4b9-5596631409c3.png)
