### ISSUE TITLE
Small bug with matrix maximum_routes error response

### ISSUE THREAD

**Issue by FinnStutzenstein** [GIScience/openrouteservice#719]
#### Here's what I did
Request more routes in the matrix service than `maximum_routes`, e.g. 51 points.

#### Here's what I got
I've got an error: `Request parameters exceed the server configuration limits. Only a total of 2601 routes are allowed.`

#### Here's what I was expecting
The error should contain the correct amount of maximum routes, not what the user has given. In my case 2500.

#### Here's what I think could be improved
Fix the error message here:

https://github.com/GIScience/openrouteservice/blob/d1e158a96f1f8053c16f5d60c49772d8c4ccf784/openrouteservice/src/main/java/org/heigit/ors/api/requests/matrix/MatrixRequestHandler.java#L107

**Comment by nilsnolde** [comment]
Yep, absolutely! Do I smell a PR? :innocent:

**Comment by FinnStutzenstein** [comment]
I can do this later :)
