### ISSUE TITLE
total ascent and descent not in summary when requesting geojson

### ISSUE THREAD

**Issue by gegeweb** [GIScience/openrouteservice#734]
Hi,

when requesting a route in geojson format and elevation true, total ascent and descent for the route aren't in the summary, but one level up, in the root of properties.

**Comment by aoles** [comment]
Thanks for your feedback.

We are aware of some inconsistencies in the response formats, in particular regarding the `summary`. In fact, we already had an internal discussion back in February exactly on this topic. We agreed that we need to redesign a clean solution and deploy it at some point as API v3. However, this is a long-term project and we have some more pressing things to do at the moment. 

The agreement back then was that the `summary` element in JSON/GeoJSON is actually redundant. The fields within the summary should be moved to top-level and the summary-element itself removed in v3. 

Back to the original issue: the entries for the total `ascent` and `descent` will probably remain where they are, it is the fields nested under `summary` which will be moved one level up.
