### ISSUE TITLE
Waypoints do not correlate to nodes in the OSM source file

### ISSUE THREAD

**Issue by FinnStutzenstein** [GIScience/openrouteservice#737]
Hi,

I'm using the ORS to calculate routes (yeah!) between two points and try to recreate the route within the original osm file. I've setup the osmid storage to get the osmid for the way used by every segment of the route as well as the amount of waypoints in the segment. With this information I can sucessfully trace back the route in the original files (mapping back the segments to a sequence of "partial-ways" with only the needed nodes). Until today I had no problems using the amount of waypoints as a reliable source how many (osm-)nodes are in a segment. E.g. If I have the segment

```
[2, 5, 360622045],
```
it contains 4 nodes (including both connecting-nodes) in way 360622045. With the knowledge about the start node, I can find the end node, which is +3 or -3 nodes away. This node must be contained in the way of the next segment. In this fashion the code works successive through the segments.

Today I stumbled upon a way with 8 nodes in the OSM-file, but the ORS only "uses" 6 waypoints.

#### Here's what I did

I'm routing from node 416840258 (52.2812810, 8.0439134) to 56307197 (52.2803947, 8.0460430).
These are the two affected ways:

1) https://www.openstreetmap.org/way/35572323
2) https://www.openstreetmap.org/way/7763820

All nodes of both way are used. The first way has 8 nodes, the second has 2 nodes.

---
#### Here's what I got

 This is the osmid part of the response:
```
[0, 1, 35940503],
[1, 6, 35572323],
[6, 7, 7763820]
```

The first segment can be ignored. Both waypoints are the same, just the way is changed.

The second segment is the interesting one: In the response, this segment has 6 waypoints and connects to the second way. So in terms of the original OSM file, all 8 nodes must be used.

---
#### Here's what I was expecting
I was expecting the middle segment to contain 8 waypoints. But here is the thing: I'm not sure, if I can expect this. Either this is a bug in the ORS, or I have falsy assumed that the waypoints correspond to nodes in a 1:1 fashion. If the latter is the case I have to adjust my algorithm ;)

So the first question would be, if this is a desired behavior.

Thanks from Osnabrück (as you can tell from the ways ;) )!

**Comment by HendrikLeuschner** [comment]
Hi, we create a graph for routing from the OSM file. This graph contains so called pillar and tower nodes. Tower nodes are usually the ones where one way crosses another. Pillar nodes are the nodes that form the geometry of the way in between. There is no guarantee of a mapping, and you can see that it does not always apply. If you like to learn more about the nodes, check out this graphhopper doc [tower pillar nodes](https://github.com/graphhopper/graphhopper/blob/master/docs/core/low-level-api.md).
