### ISSUE TITLE
New docker containers always use the default app.config

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice#742]
It's very annoying: whenever a new container is created (e.g. when just changing some env var in `docker-compose.yml`) the new container reads the default `app.config` provided by the image. Regardless if the user actually has a valid config in `./ors-conf`. 

Not hard to remedy:

The problem is that `mvn package` is run in the image itself, which packages the default `app.config` into the WAR file. So currently there's no way to access the `app.config` Tomcat will use since it's inside the WAR.

The lines 
```
    mvn -q -f /ors-core/openrouteservice/pom.xml package -DskipTests && \
    cp -f /ors-core/openrouteservice/target/*.war /usr/local/tomcat/webapps/ors.war && \ 
```
need to be in `docker-entrypoint.sh`, not in the `Dockerfile`, with some logic so we don't package needlessly if nothing changed.

**Comment by 0xd3e** [comment]
@nilsnolde I'm not entirely sure this fixes the issue.

The custom configuration is only copied when `/usr/local/tomcat/webapps/ors` exists, which means when a new container is started, it will still use the default config. In my case I only need one profile, but when I start the container, it always initializes `cycling-regular` and `driving-car`.

**Comment by EWouters** [comment]
How this is implemented now only works when you build the image yourself, and even then there is some code to [scrub out](https://github.com/GIScience/openrouteservice/pull/745/files?file-filters%5B%5D=.gz&file-filters%5B%5D=.md&file-filters%5B%5D=.properties&file-filters%5B%5D=.sh&file-filters%5B%5D=.yml&file-filters%5B%5D=No+extension#diff-3254677a7917c6c01f55212f86c57fbfR33) all profiles except for "car".

This can easily be integrated to work with custom `app.config` at docker run time by checking if the `app.config` file exists before overwriting it on this line: https://github.com/GIScience/openrouteservice/blame/master/docker-entrypoint.sh#L26

**Comment by EWouters** [comment]
```
# if Tomcat built before, copy the mounted app.config to the Tomcat webapp app.config, else copy it from the source
if [ -d "/usr/local/tomcat/webapps/ors" ]; then
	cp -f /ors-conf/app.config $tomcat_appconfig
else
	if [ ! -f /ors-conf/app.config ]; then
		cp -f $source_appconfig /ors-conf/app.config
	fi
	echo "### Package openrouteservice and deploy to Tomcat ###"
	mvn -q -f /ors-core/openrouteservice/pom.xml package -DskipTests && \
	cp -f /ors-core/openrouteservice/target/*.war /usr/local/tomcat/webapps/ors.war
fi
```
Something like this, or add this argument to docker run:
```
-v $PWD/app.config:/ors-core/openrouteservice/src/main/resources/app.config \
```

**Comment by EWouters** [comment]
See #772
