### ISSUE TITLE
Installation Instructions mention non-existing file

### ISSUE THREAD

**Issue by koebi** [GIScience/openrouteservice#744]
#### Here's what I did
I am trying to set up the ORS, but the installation instructions in the Readme mention the file
 `openrouteservice/WebContent/WEB-INF/app.config.sample` which does not exist.

#### Here's what I got
I got no further because of this issue.
I also found a file with the same name at `openrouteservice/src/main/resources/app.config.sample`.

#### Here's what I was expecting
I was expecting to set up ORS somewhat comfortably

#### Here's what I think could be improved
The installation instructions ;)

**Comment by koebi** [comment]
If the file I found is the file in question here, I'm very happy to fix this :)

**Comment by nilsnolde** [comment]
Yeah, the README needs some overhaul anyways, also:
- mention vroom and openelevationservice as external services
- adapt to `/v2` endpoint syntax in [Usage](https://github.com/GIScience/openrouteservice#usage)
- remove the `docker` command and instead only link to the `./docker` directory
.. others?

**Comment by cbayerlein** [comment]
I guess the right file is openrouteservice/src/main/resources/app.config.sample - but what to do with it? Copy it in which folder?

**Comment by rabidllama** [comment]
I assume you are running the Docker setup? 

The file in `openrouteservice/src/main/resources/app.config.sample` is the template that can be used for a basic installation. Where you move that file to depends on the setup process you are using. 

For the standalone Tomcat / Maven build process, the file stays in the same place and needs renaming to `app.config`. 
If you are using the Docker command or docker-compose, then the file would need moving to a `conf` folder in the same directory as the `Dockerfile` file (again renaming to `app.config`). In the docker command, the line  `-v $PWD/conf:/ors-conf \  # will copy the container's app.config to the host` is the part that tells Docker which folder to use, and in the docker compose method, the part in the `docker-compose.yml` file that instructs it to use that folder is the `- ./conf:/ors-conf` part. Note that with the docker-compose file, there is also the build context set to `../` which basically means "all paths are in relation to the folder above me".

There were some modifications to the Docker setup and installation instructions a couple of weeks ago, but maybe some things still need a bit more of an in-depth description in the documentation...
