### ISSUE TITLE
Invalid WayPoints using directions v1 service.

### ISSUE THREAD

**Issue by Marcoshsc** [GIScience/openrouteservice#751]
#### Here's what I did

Hello, eveyone. I am building an app that makes use of openrouteservice v1 directions service. While testing my application, I ran into errors, that was probably caused by an bug in the waypoints returned by the directions service. The error is that some of the step's way points returned are greater or equal to the size of the geometry returned. Since a waypoint is a index of a coordinate contained in the geometry array, this behavior is not expected, and can be a potencial bug.
The URL that results in the error (change my-api-key to your key): 

https://api.openrouteservice.org/directions?api_key=my-api-key&profile=foot-walking&coordinates=-45.307337,-21.615626%7C-45.280070,-21.605660%7C-45.285445,-21.638806%7C-45.290918,-21.722475%7C-45.284430,-21.739616%7C-45.304275,-21.770256%7C-45.318030,-21.769621%7C-45.217897,-21.664320%7C-45.244183,-21.678583%7C-45.217897,-21.664320%7C-45.217897,-21.664320%7C-45.244183,-21.678583%7C-45.170759,-21.805485%7C-45.185688,-21.811051%7C-45.154042,-21.818651%7C-45.170759,-21.805485%7C-45.393713,-21.671211%7C-45.373537,-21.642961%7C-45.361702,-21.650487%7C-45.345026,-21.654219%7C-45.303669,-21.648526%7C-45.303815,-21.650194%7C-45.345026,-21.654219%7C-45.361702,-21.650487%7C-45.368507,-21.639803%7C-45.345026,-21.654219%7C-45.303669,-21.648526%7C-45.334554,-21.641392%7C-45.361702,-21.650487%7C-45.360502,-21.642810%7C-45.190276,-21.749817%7C-45.164093,-21.764173%7C-45.190276,-21.749817%7C-45.164093,-21.764173%7C-45.298497,-21.644432%7C-45.303669,-21.648526%7C-45.240514,-21.598779%7C-45.240880,-21.602789&format=json&geometry_format=geojson

---

#### Here's what I got

https://github.com/GIScience/openrouteservice/files/4808550/jsonOutput.txt

The last two steps of the last segment were showing waypoints 5432, but the geometry array has a size of 5432, so that index is invalid.

---
#### Here's what I was expecting

All the indexes below 5432, which is the size of the geometry.

---

**Comment by TheGreatRefrigerator** [comment]
Hi @Marcoshsc,
If you are currently in the process of developing the app, we would like to urge you to use the V2 version of our API.
V1 is already deprecated and will be removed in the near future.

We will still have a look at this issue.

Best regards

**Comment by Marcoshsc** [comment]
Thank you for the support, I'm currently migrating my app to use the V2 version. I will open another issue if the error persists.

Best regards.
