### ISSUE TITLE
Isochrones V2: Unable to build an isochrone map.

### ISSUE THREAD

**Issue by Marcoshsc** [GIScience/openrouteservice#764]
#### Here's what I did

A POST request to this URL: [https://api.openrouteservice.org/v2/isochrones/foot-walking](url)
With this JSON body: 
`{
	"locations": [
		[-40.85436, -19.239279],
		[-40.888763, -19.190678],
		[-40.889092, -19.209379]
	],
	"range": [1081.4148824157621, 1440.815178129259, 1476.8964290477913],
"range_type": "distance"
}`

---
#### Here's what I got

The following JSON output: 

`{
  "error": {
    "code": 3099,
    "message": "Unable to build an isochrone map."
  },
  "info": {
    "engine": {
      "version": "6.1.1",
      "build_date": "2020-06-18T15:14:48Z"
    },
    "timestamp": 1593807758503
  }
}`

**Note:** When the requests are made using the each of the range values alone, the response is successfully returned with 200 status code. The error happens only when all three ranges are put together in the request. I think this means that there is a bug, since that if any of my coordinates were wrong, the request would not be completed using each of the ranges alone.

**Comment by koebi** [comment]
Looks like this has been fixed in the last year ;)
![Screenshot 2021-10-12 at 16-26-51 V2 Isochrones {Profile} Post ORS API](https://user-images.githubusercontent.com/4692974/136975049-de2f79da-d0ed-4134-bd97-31faa360e470.png)

**Comment by koebi** [comment]
Whoops, didn't set the `range_type`. But it still works ;)
![Screenshot 2021-10-12 at 16-27-53 V2 Isochrones {Profile} Post ORS API](https://user-images.githubusercontent.com/4692974/136975266-8f5bc227-ee8c-47b0-b9b0-4c8b5c577915.png)
