### ISSUE TITLE
Accessibility analysis of custom destination points

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/openrouteservice#79]
The idea here to give the user the ability to input a list of coordinates (waypoints), a centroid and and a limit option length/time. The API returns the indices of those waypoints which can be reached in that time. It is basically a "light" version of a proper accessibility analysis API which will allow you to specify types of POIs you want to reach within given time/distance.

**Comment by rabidllama** [comment]
@TimMcCauley Was this applied in the update to the locations stuff?

**Comment by TimMcCauley** [comment]
@rabidllama I added the description for this

**Comment by takb** [comment]
Wasn't important enough to be worked on for 5 years, and no info provided if any work was already put into this.
