### ISSUE TITLE
straight line segment in computed route

### ISSUE THREAD

**Issue by wmann-celonis** [GIScience/openrouteservice#791]
#### Here's what I did
I'm trying to compute a route with a least one intermediate point.
https://maps.openrouteservice.org/directions?n1=47.952225&n2=12.495575&n3=9&a=47.687427,11.980119,47.730903,11.868442,48.078079,11.510925&b=0&c=0&k1=en-US&k2=km&s=1

---
#### Here's what I got
The first segment is a straight line instead of a proper route.

---
#### Here's what I was expecting
A proper route

---

**Comment by aoles** [comment]
Doesn't look like a bug to me, but rather an intended behavior related to the skip segment feature. Apparently the url parameter `s=1` enables this option for the first segment between the start and the via point. Not sure how it got there though, at least I couldn't find a way to enable the skip segment feature in our apps client. Maybe @TheGreatRefrigerator can give some insights here.

**Comment by TheGreatRefrigerator** [comment]
@wmann-celonis,
@aoles is correct, you might have clicked "Add as direct point" instead of "Add as via point". Removing `&s=1` from the URL or "Add as via point" should produce the route you are looking for.

**Comment by aoles** [comment]
Thanks @TheGreatRefrigerator for the clarification, I missed the "direct point" option.

**Comment by wmann-celonis** [comment]
Thanks for the explanation @TheGreatRefrigerator . Is the s=1 really the only way to see that this a direct point? If yes, I would propose to make this clearer by annotating the point with a D right of the text box. Should I open an issue in the client app?
