### ISSUE TITLE
Error when requesting osmid for wheelchair profile

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice#796]
#### Here's what I did

Requested a route for the wheelchair profile with the osmid extra info

---

#### Here's what I got

An error response:
```json
{
    "error": {
        "message": "Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;"
    },
    "info": {
        "engine": {
            "version": "6.2.1",
            "build_date": "2020-08-18T08:46:24Z"
        },
        "timestamp": 1598350435484
    }
}
```

---

#### Here's what I was expecting

For the osmids of the route to be returned

---

#### Here's what I think could be improved

Fixing the error (possibly to do with Java11 update?)

**Comment by takb** [comment]
This error occurs if you run the current version of the code on Java 8. I looked around quite a bit but there doesn't seem to be an easy way to achieve backwards compatibility for this particular method. Switch the JRE version in your IDE to Java 11 and all is good.

**Comment by rabidllama** [comment]
Yeh, seems that the JRE being used by tomcat was java 8, though the war was built using java 11...
