### ISSUE TITLE
Route directions duplication

### ISSUE THREAD

**Issue by Rich-Tee** [GIScience/openrouteservice#800]
I notice that direction instructions are often duplicated as the route changes very slightly, example

https://maps.openrouteservice.org/directions?n1=52.223428&n2=-0.787232&n3=9&a=52.923468,-1.475258,51.509648,-0.099076&b=0&c=0&k1=en-US&k2=km 2

you can see a series of 15 instructions one after the other all saying the same " Keep right onto M1",
is there any way that duplicates like this can be combined into a single instruction ?
I realise that this is a complicated request as some duplicated instructions would be need to be kept as they are.

Many thanks.

**Comment by rabidllama** [comment]
Hi @Rich-Tee 

sorry for the heavily delayed response. It looks like this is actually an issue with the library we use for our routing core (GraphHopper) as that is where the instructions get generated. It is probably worth checking on their maps demo to see if the same thing happens there and if so, to then raise an issue on their repo. If not, then feel free to reopen this issue and we will look into it again
