### ISSUE TITLE
Directions V2 - driving-hgv profile returns empty response body

### ISSUE THREAD

**Issue by adamdarr** [GIScience/openrouteservice#802]
#### Here's what I did
- POST request to https://api.openrouteservice.org/v2/directions/driving-hgv/geojson

---
#### Here's what I got
- 200 OK status with an empty response body

---
#### Here's what I was expecting
- 200 OK status with directions in response body

---
#### Here's what I think could be improved
- Fixing the issue. This just started happening today (`driving-car` profile still works).

**Comment by kbuilds** [comment]
We are also experiencing this issue

**Comment by adamdarr** [comment]
It appears to be working again

**Comment by rabidllama** [comment]
It was a problem with reloading the graphs after an update
