### ISSUE TITLE
Docker ORS not use '/ors-conf/app.config' file

### ISSUE THREAD

**Issue by tacxou** [GIScience/openrouteservice#803]
Hello, 
While using your Docker container I realized that it ignored the configuration file put in the volume. I managed to solve the problem on my side by modifying the entry point:

```sh
# /docker-entrypoint.sh

cp -f /ors-conf/app.config /ors-core/openrouteservice/src/main/resources/app.config
```

**Comment by tacxou** [comment]
Hello, I think my problem is related to this PR: #784

**Comment by koebi** [comment]
Given that the config file has been renamed and a few things have been put into place regarding this, I don't think this is an issue anymore. 

Feel free to reopen if the problem persists. Please give a more detailed bug report than
> it ignored the configuration file put in the volume
especially quoting the command you use to run docker or the docker-compose file you are using. This will help us a lot in debugging your issues :)
