### ISSUE TITLE
API Playground Results vs Self Hosted very different (Durations)

### ISSUE THREAD

**Issue by ImranHugo** [GIScience/openrouteservice#806]
#### Here's what I did
I spun up a linux VM as I needed to produce distance/duration metrics for around 65000 location pairs.  I could not run using the online version due to rate limits so spinning up my own version for this batch seemed like the easiest route.

I download the latest PBF file for Australia from http://download.geofabrik.de/australia-oceania/australia.html, spun up the docker image using the documentaion provided on your site and enabled the HGV profile.

---
#### Here's what I got
After running the batch, I noticed that the distances matches spot on to the online API playground, but the durations were very different. (much faster).

I checked a few samples using Google Maps too and Google Maps matches the API Playground durations.  Why would my self-hosted version produce much different duration results?

I have used the sample App.Config provided and made a single change to enable HGV profile.

**produced from my version**
`"durations": [
        [
            0.0,
            2809.81
        ],
        [
            2566.62,
            0.0
        ]
    ],
    "distances": [
        [
            0.0,
            51378.84
        ],
        [
            48858.77,
            0.0
        ]
    ],`

**produced from your API Playground**

`"durations": [
        [
            0.0,
            3426.16
        ],
        [
            3316.46,
            0.0
        ]
    ],
    "distances": [
        [
            0.0,
            51375.32
        ],
        [
            48847.5,
            0.0
        ]
    ]`

**request for both**
`{
  "locations": [
    [
      150.8144, -33.7861
    ],
    [
      150.7284, -34.0703
    ]
  ],
  "metrics": [
    "distance",
    "duration"
  ]
}`

**Comment by ImranHugo** [comment]
Good evening. just following up to see if there are any ideas as to why my version would produce much faster durations?  Is it possible to get a version of the config which runs the API playground?

**Comment by FinnStutzenstein** [comment]
Hi, I experienced the same issue: We are calculating matrices and I wrote a script checking the triangle inequality. I noticed that it was false all over the place and I picked three places to debug. If I use the directions API and manually calculate the distances, they are different to the matrix result (and satisfy the inequality). I was using v6.1.0. After updating to 6.3.0 the matrix response seems better since it now satisfied the inequality. I did not checked the whole matrix since I ran into other problems

**Comment by ImranHugo** [comment]
@FinnStutzenstein, I have upgraded my version to 

        "engine": {
            "version": "6.3.0",
            "build_date": "2020-10-13T03:17:58Z",
            "graph_date": "2020-10-13T04:14:47Z"
        }

However, this still has not seemed to resolve the duration difference.

My request to the matrix API is:

{
  "locations": [
    [
      150.8144, -33.7861
    ],
    [
      150.7284, -34.0703
    ]
  ],
  "metrics": [
    "distance",
    "duration"
  ]
}

If I use google maps to get distance duration, this is what I find:

![image](https://user-images.githubusercontent.com/19433765/95820552-fd7a8f80-0d73-11eb-8dcd-ea44b7580c68.png)

When I run this through my local ORS, I get the following:

![image](https://user-images.githubusercontent.com/19433765/95820659-2bf86a80-0d74-11eb-84e3-a8e855dfc637.png)

the slowest time being 2147.77 seconds which is 35 minutes … according to Google (and the API playground) it is longer in terms of duration.  When using hfv, the difference is even bigger.

**Comment by MikeDabrowski** [comment]
Hi, I found this issue while searching for something similar. Using online version of the api to get matrix for just two points (one on the peak of the mountain, the other much lower) the difference between durations was just a few minutes. Given the elevation difference of around 600m the uphill should take much longer than downhill. 

I then went to https://maps.openrouteservice.org/ and used same points and got same result. I believe it internally uses 'directions' endpoint. It also has the information about elevation profile. 

I suspect that the duration is calculated using fixed speed for given transportation, in my case (cycling-mountain) it is around 16km/h. 

**Playground request:** (first point is the lower one)
`{"locations":[[19.001799,49.76153],[19.064541,49.776276]],"metrics":["distance","duration"],"units":"km"}`

**Playground response:**
```
destinations: [
  {location: [19.064463, 49.774855], snapped_distance: 14.3},
  {location: [19.001432, 49.760352], snapped_distance: 8.46}
]
distances: [
  [0, 6.08] <- uphill
  [5.76, 0] <- downhill
]
durations: [
  [0, 1342.04] <- uphill
  [1263.46, 0] <- downhill
]]
```

**[Link to maps.openrouteservice](https://maps.openrouteservice.org/directions?n1=49.76789&n2=19.032999&n3=14&a=49.774287,19.064541,49.759874,19.001552&b=1b&c=0&k1=en-US&k2=km)**
Here you can see uphill time of 21m and downhill 24m.

I can understand the differences between 'directions' and 'matrix' by few minutes but uphill/dowhill should have greater difference.

**Comment by takb** [comment]
The app.config parameter causing the discrepancy is `use_acceleration`, which adds a different heuristic to estimate the travel speed for each edge. 

As for the discussion regarding consideration of the elevation / steepness which is a different issue entirely, we still haven't had the manpower to address it. If anyone wants to tackle the problem, contributions are welcome...
