### ISSUE TITLE
not adhering to turn restrictions without alternative routes

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#807]
#### Here's what I did

Strange behaviour when not having alternative routes:

```
  curl -X POST \
  'https://api.openrouteservice.org/v2/directions/driving-car/geojson' \
  -H 'Content-Type: application/json; charset=utf-8' \
  -H 'Accept: application/json, application/geo+json, application/gpx+xml, img/png; charset=utf-8' \
  -H 'Authorization: xxx' \
  -d '{"coordinates":[[10.952897,48.929647],[10.971179,48.931508]]}'
```
---
#### Here's what I got

![grafik](https://user-images.githubusercontent.com/23240110/93022084-372a7000-f5e7-11ea-8fa7-47890ccbfb4e.png)

---
#### Here's what I was expecting

When setting alternative routes it strangely shows the correct route:
```
  curl -X POST \
  'https://api.openrouteservice.org/v2/directions/driving-car/geojson' \
  -H 'Content-Type: application/json; charset=utf-8' \
  -H 'Accept: application/json, application/geo+json, application/gpx+xml, img/png; charset=utf-8' \
  -H 'Authorization: xxx' \
  -d '{"coordinates":[[10.952897,48.929647],[10.971179,48.931508]],"alternative_routes":{"target_count":2}}'
```

![grafik](https://user-images.githubusercontent.com/23240110/93022113-71940d00-f5e7-11ea-8b7c-dbc4cbefa209.png)

**Comment by takb** [comment]
Likely would be fixed as soon as the Core-ALT turn restrictions fix is done, will check again after that
