### ISSUE TITLE
Add `sac_scale` restrictions on Tag Filtering Wiki

### ISSUE THREAD

**Issue by 1papaya** [GIScience/openrouteservice#812]
Hi all,
As discussed on various issues (#600 #731) the ORS `foot-hiking` profile filters ways based on `sac_scale` value but the restriction is missing from the [ORS Wiki on hiking tag filtering](https://github.com/GIScience/openrouteservice/wiki/Tag-Filtering#Hiking)

**Comment by rabidllama** [comment]
I've just updated the wiki page to show that the normal foot profile only allows the hiking sac_scale (if the tag is present) and the hiking profile allows up to the alpine_hiking
