### ISSUE TITLE
After upgrade: Search exceeds the limit of visited nodes

### ISSUE THREAD

**Issue by FinnStutzenstein** [GIScience/openrouteservice#817]
Hi, I updated from 6.1.0 to 6.3.0 (see my comment in #806 ) and I get `Search exceeds the limit of visited nodes` when calculating matrices. In the old version we used about 700 locations with `foot-walking` and `cycling-regular` without problems (we just needed to increase `maximum_routes`).

After upgrading, we have trouble getting even a 20x20 matrix with `cycling-regular` (Related to #810 ?): https://pastebin.com/M5WW5Hun

Note: There are much more locations, but the source is from 0 to 20 and the destinations from 100 to 120 -> a 20x20 matrix. I tried to subdivide the matrix to get rid of the error.

`maximum_visited_nodes` is set to 1000000000, see the [app.config](https://pastebin.com/MTwcDTeD). Before the update the default was enough ( I think it was 100000 or so).

The problems started with the pedestrian profile, but the service managed to do a 250x250 matrix; with a 300x300 one there was the same error, hence the subdividing approach. But since even a 20x20 matrix does not work and it was fine in 6.1.0, there must be an issue introduces somewhere.

**Comment by jfalameda** [comment]
Did you manage to solve this issue?

**Comment by FinnStutzenstein** [comment]
Sadly no, we are not using the matrix serivce anymore and calculate a route for each entry (which takes a while...).

**Comment by radu-jakab** [comment]
Hello, are there any updates or workarounds for this issue?
We are running into this as well. Other profiles work fine, bu cycling-regular fails with even small sets.

thanks!

**Comment by jonathananolan** [comment]
Just wanted to flag - still experiencing this issue in 2023 :) Good luck.

**Comment by aoles** [comment]
@jonathananolan: Public API or custom instance?

**Comment by jonathananolan** [comment]
Custom. Worked when I first installed then magically stopped. Still works with public API and driving so clearly not an issue with bad coords. Running on Australia PBF so quite big. Machine is windows 11 16gb. Log files/config files for local instance here:

https://drive.google.com/drive/folders/1ulHz1ko8VGPIHsFFwkLm1qSGkk-UA1_N?usp=sharing

I'm very new so likely user error! 

edit: added error - might be slightly different to this issue, I came here from here... 

https://ask.openrouteservice.org/t/6099-unable-to-compute-a-distance-duration-matrix-foot-walking/2650

and here

https://ask.openrouteservice.org/t/6099-unable-to-compute-distance-duration-matrix-foot-walk/4387/3

**Comment by aoles** [comment]
Thanks for getting back to me so quickly! :)

There have been some recent changes to ORS which might be responsible for the observed behavior, see https://github.com/GIScience/openrouteservice/pull/1428.

Please try increasing the `maximum_visited_nodes` value for matrix in your config file to e.g. `1000000`. Good luck! 🤞 

BTW: Have you already tried the [openrouteservice R package](https://github.com/GIScience/openrouteservice-r)? You might want to have a look at the [example of matrix queries](https://giscience.github.io/openrouteservice-r/articles/openrouteservice.html#matrix-1).

Cheers!

**Comment by jonathananolan** [comment]
Thanks aoles! I was really impressed by this package - very helpful. I temporarily stopped using it to exclude it as a source of error. 

re: changing maximum_visited_nodes - does stopping and starting the docker instance put the new setting into effect? If so no luck! My use case is 9 million lookups so hoping to avoid the directions API.

**Comment by aoles** [comment]
Thanks for your feedback! Not sure about docker picking up the new settings. Maybe @MichaelsJP or @takb could chime in to clarify.

**Comment by MichaelsJP** [comment]
@aoles @jonathananolan `maximum_visited_nodes` is most likely a parameter read at runtime and should be picked up on a simple restart.

**Comment by Kingshuk-Deb** [comment]
@jonathananolan were you able to build a matrix for car profile of sizes greater than 200x200?

**Comment by MichaelsJP** [comment]
@Kingshuk-Deb It's good to see you interested in the topic. You might find useful answers at our ask forum: https://ask.openrouteservice.org. You're welcome to post all your questions there.

**Comment by jonathananolan** [comment]
Just to close out this - I ended up just using the regular directions API which took a few hours longer but was fine.
