### ISSUE TITLE
Every address of small village in Germany is missing the locality field

### ISSUE THREAD

**Issue by fritzfr** [GIScience/openrouteservice#823]
#### Here's what I did
Basically, I opened an extensive issue with Pelias already, but they have confirmed the issue has been fixed on their site and it's an issue with ORS.

The issue: https://github.com/pelias/pelias/issues/893
---
#### Here's what I got
Search for "Mühlgasse 20 35510", it will return:

```json
{
"id": "way/688338717",
"gid": "openstreetmap:address:way/688338717",
"layer": "address",
"source": "openstreetmap",
"source_id": "way/688338717",
"name": "Mühlgasse 20",
"housenumber": "20",
"street": "Mühlgasse",
"postalcode": "35510",
"accuracy": "point",
"country": "Deutschland",
"country_gid": "whosonfirst:country:85633111",
"country_a": "DEU",
"region": "Hessen",
"region_gid": "whosonfirst:region:85682531",
"region_a": "HE",
"macrocounty": "Regierungsbezirk Darmstadt",
"macrocounty_gid": "whosonfirst:macrocounty:404227581",
"county": "Wetteraukreis",
"county_gid": "whosonfirst:county:102063633",
"county_a": "WT",
"continent": "Europa",
"continent_gid": "whosonfirst:continent:102191581",
"label": "Mühlgasse 20, Deutschland"
}
```

```json
{
	"geometry": {
		"type": "Point",
		"coordinates": [
			8.678653,
			50.414923
		]
	}
}
```

This street is in a village called "Nieder-Weisel" and the next bigger city (with the postal code 35510) is called "Butzbach". None of these two names is anywhere in the payload, making it rather unusable for identifying the address just from the label and **would require an additional API call to figure out what the name of the city behind the postal code is**.

In addition (or because of this issue), a search for "Mühlgasse 20 Butzbach" does not return any results, you need to provide the postal code. That is an even more inconvenient issue for the user, because it does not need to be provided when the address is within a city with it's own postal code, but if it is in a village which shares a postal code, it is required.

#### Here's what I was expecting
The locality should be included as a field and in the label. I should also be able to search with the name of the city, instead of the postal code only.

---------
As can be seen in the mentioned issue above and in [this reply](https://github.com/pelias/pelias/issues/893#issuecomment-709447564), there seems to be an issue with ORS maybe running an old Pelias build.

**Comment by koebi** [comment]
This seems to have been fixed, as the same search mentioned now returns a locality.
