### ISSUE TITLE
on the map for postalcodes with leading 0 the 0 in some places is omitted

### ISSUE THREAD

**Issue by renarena** [GIScience/openrouteservice#828]
#### Here's what I did

https://maps.openrouteservice.org/directions?n1=50.780001&n2=12.681398&n3=15&a=50.778047,12.697792,50.784451,12.665863&b=0&c=0&d=100&k1=en-US&k2=km
---
#### Here's what I got

on some locations addresses the postalcodes leading 0 is missing
---
#### Here's what I was expecting

the postalcode has 5 letters no matter if it starts with 0

**Comment by rabidllama** [comment]
This isn't an issue to do with the openrouteservice core but with the maps client. Can you please open the issue there (https://github.com/GIScience/openrouteservice-app)
