### ISSUE TITLE
Steepness not returned for driving-hgv & cycling-regular

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#843]
#### Here's what I did

`https://api.openrouteservice.org/v2/directions/driving-hgv`
```
{"coordinates":[[8.681495,49.41461],[8.686507,49.41943],[8.687872,49.420318]],"extra_info":["steepness","suitability"]}
```

#### Here's what I got

only suitability as output extra
![grafik](https://user-images.githubusercontent.com/23240110/102724733-11151a00-4312-11eb-9701-2de213602703.png)

---
---
#### Here's what I was expecting

the steepness
---

**Comment by takb** [comment]
This seems to have resolved itself, currently the instance returns steepness as expected. Most likely this was a case of elevation data not being available.
