### ISSUE TITLE
Documentation for api key and ssl

### ISSUE THREAD

**Issue by JoergSommer** [GIScience/openrouteservice#861]
Hello!

I want to use ors as a real production server.

Now I look for documentation to install ssl certificates from letsencrypt with the docker container and api keys for authentication.

Do I have to learn tomcat and others for this or are there working parameters for my docker-compose.yml.

Where can I find the documentation for this?

Best regards

**Comment by JoergSommer** [comment]
Hello!

It would help me a lot if you can tell me if there is a possibility to use certificates and api keys.

If these features are not part of the docker image until now it would be a important information for me.

If only the documentation is missing, perhaps, I can find another way to get this working.

Best regards

**Comment by nilsnolde** [comment]
Both things you’re asking for is the job of the server running ORS, don’t attempt to do that in containers. This project uses Tyk for Api key management. SSL via letsencrypt as any sane server:)
