### ISSUE TITLE
OSM changes not reflected after more than 6 weeks

### ISSUE THREAD

**Issue by ManDay** [GIScience/openrouteservice#868]
Since I haven't read anything which indicates that the usual "updates are reflected after a couple/5 days" has changed, I assume this is a bug. This is [an example](https://maps.openrouteservice.org/#/directions/1,Bulgaria/1,Bulgaria/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,38,1,152,3,160,1,128,86,1,217,8,3,128,78,27,207,54,128,88,111,210,128,104,95,204,194,159,195,80,160,194,44,234,16,13,196,76,147,58,229,240,4,99,160,191,160,182,221,122,151,236,166,165,122,52,22,80,6,207,132,39,16,16,0,58,167,129,17,54,28,161,47,64,128,12,222,0,27,116,184,66,186,138,128,22,128,2,222,0,26,201,0,28,204,196,25,221,21,221,26,29,17,12,27,207,17,50,0,22,195,41,54,29,22,26,32,11,202,3,55,1,70,128,23,220,168,0,0) of a track [way/905428025](https://www.openstreetmap.org/way/905428025) which I added which is not accounted for after 4 weeks.

**Comment by rabidllama** [comment]
Hi @ManDay 

I'm having a look into this as it might actually be an issue with the automatic processing of the OSM file we conduct every week... If the problem is there and we can figure it out tomorrow, your changes should appear in just over a weeks time

**Comment by ManDay** [comment]
@rabidllama I meant this as a honest bug report, not as a complaint or out of concern for my particular changeset. Is there already a bug which tracks the "issue" which you are referring to?

**Comment by rabidllama** [comment]
@ManDay no worries, it's good that you reported it as it was a problem with the auto importing process. I have updated the hiking profile with new graphs and now it works as expected

**Comment by ManDay** [comment]
I think this has not been solved conclusively. Once again, I've edited a way and the changes are not reflected after several weeks. Try to route across [this bridge](https://www.openstreetmap.org/way/734472571) and the adjacent footways, which were previously disconnected. ORS is still unaware of the changes made.

**Comment by ManDay** [comment]
@rabidllama can you reopen this?
