### ISSUE TITLE
asymmetric distance matrix calculation.

### ISSUE THREAD

**Issue by yurticikargoit** [GIScience/openrouteservice#873]
On documentation it's said that ,
By default a symmetric duration matrix is returned where every point in locations is paired with each other.  

is asymmetric  matrix calculation supported ? if supported then how can we test it?

**Comment by koebi** [comment]
Hey,

the documentation seems to be a bit misleading here, using the word `symmetric`.
As running [the example in the playground](https://openrouteservice.org/dev/#/api-docs/v2/matrix/{profile}/post) will show, the returned matrix is indeed asymmetric - as it should be, since a route from A to B is rarely the same as a route from B to A.

I believe the documentation should instead mention that a `quadratic` matrix is being returned by default.

**Comment by aoles** [comment]
I think the point was more about defining the set of `destinations` to be different from `sources`. There already are corresponding API parameters for doing so. Nevertheless, it still makes sense to  improve the wording as suggested by @koebi.

**Comment by yurticikargoit** [comment]
Hello again,
I tried several combination but could not succeed. I may misunderstood something. If it's asymmetric  for the following example should not I get 16 duration .

Request
`{
    "locations": [
[29.057768,40.987915],
[29.058086,40.988344],
[29.057067,40.989074],
[29.058697,40.989628]
]
}`

Response
`{
    "durations": [
        [
            0.0,
            13.31,
            46.08,
            49.18
        ],
        [
            13.31,
            0.0,
            32.77,
            35.87
        ],
        [
            46.08,
            32.77,
            0.0,
            51.16
        ],
        [
            49.18,
            35.87,
            51.16,
            0.0
        ]
    ],
    "destinations": [
        {
            "location": [
                29.057824,
                40.987998
            ],
            "snapped_distance": 10.39
        },
        {
            "location": [
                29.057975,
                40.988392
            ],
            "snapped_distance": 10.7
        },
        {
            "location": [
                29.057291,
                40.989268
            ],
            "snapped_distance": 28.64
        },
        {
            "location": [
                29.058857,
                40.989559
            ],
            "snapped_distance": 15.48
        }
    ],
    "sources": [
        {
            "location": [
                29.057824,
                40.987998
            ],
            "snapped_distance": 10.39
        },
        {
            "location": [
                29.057975,
                40.988392
            ],
            "snapped_distance": 10.7
        },
        {
            "location": [
                29.057291,
                40.989268
            ],
            "snapped_distance": 28.64
        },
        {
            "location": [
                29.058857,
                40.989559
            ],
            "snapped_distance": 15.48
        }
    ],
    "metadata": {
        "attribution": "openrouteservice.org, OpenStreetMap contributors",
        "service": "matrix",
        "timestamp": 1616520567022,
        "query": {
            "locations": [
                [
                    29.057768,
                    40.987915
                ],
                [
                    29.058086,
                    40.988344
                ],
                [
                    29.057067,
                    40.989074
                ],
                [
                    29.058697,
                    40.989628
                ]
            ],
            "profile": "driving-car",
            "responseType": "json"
        },
        "engine": {
            "version": "6.3.6",
            "build_date": "2021-03-18T05:18:04Z",
            "graph_date": "2021-03-18T05:25:49Z"
        }
    }
}`
