### ISSUE TITLE
Route calculation is not OK

### ISSUE THREAD

**Issue by Jakkajakka** [GIScience/openrouteservice#886]
Found this info: "Please note that openrouteservice uses a forked and edited version of graphhopper 0.13
The route calculation is not the same as in graphhopper 
example ORS use a highway that is not allowed to use it. 
==================== Kloosterhoek is only access destination
On: Kloosterhoek
call_missed Turn right onto Kloosterhoek
Distance: 1.0 km
access_time 1 min 47 s
======================
https://bit.ly/2Pfk05i ORS
https://tinyurl.com/6hms8k5j  graphhopper

**Comment by MichaelsJP** [comment]
@Jakkajakka Thank you for your submission. 

**Please follow the issue template** presented to you when you open a new issue. It's there for a reason. This way we make sure to be able to transfer your problems with ors properly into a technical perspective.

Thank you in advance!

**Comment by MichaelsJP** [comment]
@Jakkajakka Thank you for your issue submission.

**Please use the issue template, presented when you open a new issue.** It's there for a reason. This way we can make sure to easily transfer your problem with ORS into a technical perspective we can actually use to enhance openrouteservice.

Feel free to edit/reopen this issue properly or open a new one.
