### ISSUE TITLE
Route calculation failure, meaningless error numbers 

### ISSUE THREAD

**Issue by eliboni** [GIScience/openrouteservice#89]
Ref: https://groups.google.com/forum/#!topic/openrouteservice

https://api.openrouteservice.org/directions?api_key=<key>&coordinates=51.401380%2C35.700620%7C51.0578%2C35.848135&profile=driving-car&preference=fastest

From Ramsar: Lat,Lng (36.90387,50.68514)
To Theran  Lat,Lng (35.70062,51.40138)

fails with "random" errors 

{"error":{},"info":{"engine":{"version":"4.4.0","build_date":"2018-01-20T10:28:00Z"},"timestamp":1516786900377}}
or
{"error":{"message":"19"},"info":{"engine":{"version":"4.4.0","build_date":"2018-01-20T10:28:00Z"},"timestamp":1516786005260}}
or 
{"error":{"message":"12"},"info":{"engine":{"version":"4.4.0","build_date":"2018-01-19T16:53:44Z"},"timestamp":1517220631424}}
or also
{  "error": "Authorization field missing" }
(yes, I tried to regenrate my key).

You'll get the same error on maps.openrouteservice.org of course:
https://maps.openrouteservice.org/directions?n1=35.700619&n2=51.401376&n3=17&a=36.90387,50.68514,35.701037,51.40151&b=0&c=0&k1=en-US&k2=km

Origin and destination are reachable. 

**Narrowing down the path it seems the issues is here** 

https://maps.openrouteservice.org/directions?n1=35.806337&n2=51.013228&n3=17&a=35.806372,51.010948,35.805807,51.01082&b=0&c=0&k1=en-US&k2=km

In OSM all looks fine to me
http://www.openstreetmap.org/search?query=35.806468%2C51.010895#map=19/35.80607/51.01111
also other direction services do not have issues.

Thanks

**Comment by HendrikLeuschner** [comment]
Hi @eliboni ,

I am having a look at the issue. Will keep you updated. Thanks for narrowing it down already, helps a lot.

Hendrik

**Comment by HendrikLeuschner** [comment]
@eliboni 
The error is coming from the roundabout, specifically the problem that for some reason (that I can't tell you yet), the instruction is to leave at exit 0, which should be exit 1.
If you are consuming the API and do not need the instructions, you can try it with the added parameter "instructions=false", i.e.

https://api.openrouteservice.org/directions?api_key=&coordinates=51.401380%2C35.700620%7C51.0578%2C35.848135&profile=driving-car&preference=fastest&instructions=false

That worked for me. I am still looking at why the exit number is just 0 and not 1. It might take a bit of time though.

Hendrik

**Comment by HendrikLeuschner** [comment]
As said, this has to do with the roundabout. It looks like this is more a problem with the OSM data than with our service. The roundabout does not seem to be correctly tagged. "Normal" roundabouts with correct tags work. I will push a quick fix for this problem and it will be publicly available with the next release. Routes should then be returned as usual, though the roundabout exit number will not be returned correctly. Sorry for the inconvenience, but this bug is caused by incorrect tagging, thus not under our control.
Until then, use the API as stated above.

Hendrik

**Comment by HendrikLeuschner** [comment]
Closed by #108

**Comment by eliboni** [comment]
@HendrikLeuschner  many thanks for the feedback. Unfortunately I need "instructions=true" because that is the only way to get the distance between the intermediate waypoints (it would be nice to get that without the full instructions list). I'm looking forward for the next release.

**Comment by eliboni** [comment]
Folks, the roundabout exit issue seems solved, but the original route I was trying to calculate is still failing with 4.5!

https://maps.openrouteservice.org/directions?n1=35.700619&n2=51.401376&n3=17&a=36.90387,50.68514,35.701037,51.40151&b=0&c=0&k1=en-US&k2=km

I'm trying to narrow down, there must be another issue somewhere...

**Comment by eliboni** [comment]
I'm puzzled, I can narrow the issue down to this:

https://maps.openrouteservice.org/directions?n1=35.808069&n2=51.014081&n3=16&a=35.810853,51.012762,35.786775,51.024005&b=0&c=0&k1=en-US&k2=km

but not further, the problem then disappears...
