### ISSUE TITLE
access=no ignored for bike routing

### ISSUE THREAD

**Issue by pbnoxious** [GIScience/openrouteservice#890]
#### Here's what I did
I asked for a bike route to a place not reachable by bike: [link](https://maps.openrouteservice.org/#/directions/Forchheim%20-%20Unteres%20Wiesenttal,Germany/Walpurgiskapelle,Germany/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,70,124,3,167,192,22,1,56,3,96,3,128,86,1,153,168,9,154,211,232,1,137,128,104,42,32,118,38,165,75,183,45,67,165,124,245,68,6,228,34,86,139,9,132,199,228,169,86,143,114,252,155,180,151,223,53,118,106,135,81,5,196,4,0,14,169,224,68,77,135,40,75,208,32,3,55,128,6,221,46,112,1,60,192,121,32,3,152,2,211,67,161,4,2,184,123,35,65,152,131,59,162,187,163,134,33,131,121,227,134,64,2,219,103,162,34,195,162,195,196,1,121,67,102,224,24,2,249,85,0)

All the ways within the nature reserve are marked as forbidden for bikes, either with "access=no, foot=yes" or explicitely with "bicycle=no"

#### Here's what I got
It routes to the destination on ways marked with "access=no" (not the ones with "bicycle=no" or "vehicle=no" though)

#### Here's what I was expecting
Show error that no routing is possible (similar to when trying to calculating a route by car for the same points)

#### Here's what I think could be improved
The routing should also take "access=no" into account

**Comment by aoles** [comment]
This has been an OSM data issue caused by outdated ORS graphs. The problem has resolved itself once ORS servers have been updated.
