### ISSUE TITLE
builder only  container 

### ISSUE THREAD

**Issue by stefanocudini** [GIScience/openrouteservice#898]
I am trying to build a container that only deals with the construction of the graph
after which the service should go to stop returning a zero if the process was successful

I was thinking of modifying the docker-entrypoint.sh startup script by mounting a modified script in the cointainer

would it be the right way?

or everything is solved with some environment variable?

**Comment by rabidllama** [comment]
Hi @stefanocudini 

it would be better to put this in our ask forum (https://ask.openrouteservice.org) as it is a question rather than a feature request/bug.
