### ISSUE TITLE
no correct graph_date for routing requests

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#925]
#### Here's what I did

A request to any routing endpoint

---
#### Here's what I got

metadata graph date of `"1970-01-01T00:00:00Z"`

---
#### Here's what I was expecting

The actual date the graph was built

---
#### Here's what I think could be improved

looking at isochrones an matrix, the date should maybe be imported from 
`graphHopper.getGraphHopperStorage().getProperties().get("datareader.import.date")`
instead of `response.getHints().get("data.date", "0000-00-00T00:00:00Z")`
in 
https://github.com/GIScience/openrouteservice/blob/1b76cebdfd4d71a0018cc557239310d0fa9e23fe/openrouteservice/src/main/java/org/heigit/ors/routing/RouteResultBuilder.java#L94
and
https://github.com/GIScience/openrouteservice/blob/1b76cebdfd4d71a0018cc557239310d0fa9e23fe/openrouteservice/src/main/java/org/heigit/ors/routing/RouteResultBuilder.java#L142

refers to:
https://github.com/GIScience/openrouteservice/pull/660/commits/3425204f2efb1d08ad08f8c2898794a772ef7662
and
https://github.com/GIScience/openrouteservice/issues/648

**Comment by koebi** [comment]
This is where the date is read from the graphhopper-storage and set in the response:

https://github.com/GIScience/openrouteservice/blob/1b76cebdfd4d71a0018cc557239310d0fa9e23fe/openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/ORSGraphHopper.java#L381-L385

This is prioritising the date of the data over the date of the import.

This is where the date is read from the input data and set in the graphhopper-storage:

https://github.com/GIScience/graphhopper/blob/ee6e15f29ba52a335f2152e8c43f90d49a9e64be/core/src/main/java/com/graphhopper/GraphHopper.java#L712-L722

To me, this seems like it's a bug in the input data.

**Comment by koebi** [comment]
Since the date is returned in the `graph_date`-field, whose documentation states it is "The date that the graph data was last updated", the `datareader.import.date` should be prioritized.

Another metadata field containing the data date could be added, if the date exists.
