### ISSUE TITLE
CALT shortest preparation fails for ways tagged with `maxspeed=0`

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#940]
OSM ways tagged with `maxspeed=0` result in the following error during CALT `shortest` preparation.

```
java.lang.IllegalStateException: Speed cannot be 0 for unblocked edge, use access properties to mark edge blocked! Should only occur for shortest path calculation. See #242
```

This problem is triggered when attempting to compute travel time for a shortcut containing the offending edge.

`fastest` is not affected because such ways are discarded by https://github.com/GIScience/openrouteservice/blob/6a4cd17f5c80555b17b3f34b6eb1398909202547/openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/core/CoreNodeContractor.java#L126-L129

The problem is actually not just limited to CALT preparation, but might result in routing errors with a generic algorithm as well. As en example consider OSM way [189994021](https://www.openstreetmap.org/way/189994021). With `preference=recommended` no direct route is found https://classic-maps.openrouteservice.org/directions?n1=32.061501&n2=-102.080584&n3=16&a=32.062619,-102.085347,32.063646,-102.076737&b=0&c=0&k1=en-US&k2=km

![image](https://user-images.githubusercontent.com/6545356/117737899-1e686d80-b1fb-11eb-94ec-9f4ebe2dea5d.png)

while for `shortest` it fails with an error
https://classic-maps.openrouteservice.org/directions?n1=32.061501&n2=-102.080594&n3=16&a=32.062619,-102.085347,32.063646,-102.076737&b=0&c=1&k1=en-US&k2=km

**Comment by koebi** [comment]
According to [taginfo](https://taginfo.openstreetmap.org/tags/maxspeed=0), there's only 102 ways worldwide tagged with this.
In germany, there are 9 examples - one is a blocked street (for which this makes sense), four of them are rails, so not applicable to routing anyways, one is "access=private" and the other three were all tagged by the same user and (to me) look like typos.

All this is to say that I don't think it's a big issue in practice :)
