### ISSUE TITLE
E: Package 'tomcat8' has no installation candidate

### ISSUE THREAD

**Issue by matkoniecz** [GIScience/openrouteservice#978]
#### Here's what I did
`sudo apt-get install tomcat8` - one of steps required by nondocker install at https://github.com/GIScience/openrouteservice#installation

---
#### Here's what I got
```
mateusz@grima:~$ sudo apt-get install tomcat8
[sudo] password for mateusz: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package tomcat8 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'tomcat8' has no installation candidate
```

#### Here's what I was expecting
Working installation instructions.

---
#### Here's what I think could be improved
Updating installation instructions.

**Comment by koebi** [comment]
Installation instructions in the wiki are updated.

**Comment by matkoniecz** [comment]
in https://github.com/GIScience/openrouteservice/wiki/Building-from-Source/_compare/39e82a69ae4f49924e189b5880d5efb993ef3928...ddb4d51f8357cff4f105c99d96a53f49f861b95a
