### ISSUE TITLE
Forbidden requests from web application due to missing Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#994]
#### Here's what I did

Running a local ors instance.
Trying to use `localhost:8082/ors/v2` endpoints in a web application, which set the `Origin` header for requests.

---
#### Here's what I got

403 response: Invalid CORS request due to missing `Access-Control-Allow-Origin` Header.

---
#### Here's what I was expecting

A valid request to local instance

---
#### Here's what I think could be improved
The ors backend to include the `Access-Control-Allow-Origin` Header by default

**Comment by MichaelsJP** [comment]
Fixed by #1358 #1394
